---
sidebar: sidebar 
permalink: upgrade/task_hcc_update_management_services.html 
summary: NetApp SolidFire 스토리지 시스템 업그레이드의 일환으로 관리 서비스를 업데이트해야 합니다. 
keywords: netapp, solidfire, cluster, management services, hcc, update management services 
---
= 업데이트 관리 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
관리 노드 11.3 이상을 설치한 후 관리 서비스를 최신 번들 버전으로 업데이트할 수 있습니다.

Element 11.3 관리 노드 릴리스부터 개별 서비스를 제공하는 새로운 모듈형 아키텍처를 기반으로 관리 노드 디자인이 변경되었습니다.  이러한 모듈식 서비스는 SolidFire 올플래시 스토리지 시스템에 대한 중앙 집중식 및 확장된 관리 기능을 제공합니다.  관리 서비스에는 시스템 원격 측정, 로깅 및 업데이트 서비스, vCenter Server용 Element Plug-in을 위한 QoSSIOC 서비스, NetApp Hybrid Cloud Control 등이 포함됩니다.

.이 작업에 관하여
관리 서비스 2.27 번들에는 vCenter Server 5.5용 Element 플러그인이 포함되어 있으며, 이는 관리 노드 12.8과만 호환됩니다. 관리 서비스 2.27로 업데이트하는 경우 업그레이드 순서를 변경하고 Element 12.8로 업그레이드한 _후에_ 관리 서비스 번들을 업데이트해야 관리 노드와 관리 서비스 간의 호환성을 확보할 수 있습니다.

관리 서비스 2.21.61~2.26.40으로 업데이트하는 경우 Element 12.8로 업그레이드하기 _전에_ 관리 서비스 번들을 업데이트해야 합니다.

[NOTE]
====
* 관리 서비스 2.22.7에는 원격 플러그인이 포함된 vCenter Server 5.0용 Element 플러그인이 포함되어 있습니다. Element 플러그인을 사용하는 경우, 로컬 플러그인 지원을 중단하는 VMware 지침을 준수하려면 관리 서비스 2.22.7 이상으로 업그레이드해야 합니다. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere-sdks-tools/8-0/developing-local-plug-ins-client-sdk/about-this-book-local/deprecation-of-local-plug-in-architecture.html["자세히 알아보기"^].
* 각 서비스 번들에 대한 주요 서비스, 새로운 기능, 버그 수정 및 해결 방법을 설명하는 최신 관리 서비스 릴리스 노트를 보려면 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리스 노트"^]


====
.필요한 것
관리 서비스 2.20.69부터 NetApp Hybrid Cloud Control UI 또는 API를 사용하여 관리 서비스를 업그레이드하기 전에 최종 사용자 라이선스 계약(EULA)에 동의하고 저장해야 합니다.

. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. 스토리지 클러스터 관리자 자격 증명을 제공하여 NetApp Hybrid Cloud Control에 로그인합니다.
. 인터페이스 오른쪽 상단에 있는 *업그레이드*를 선택하세요.
. EULA가 나타납니다.  아래로 스크롤하여 *현재 및 향후 모든 업데이트에 동의합니다*를 선택하고 *저장*을 선택합니다.


.업데이트 옵션
NetApp Hybrid Cloud Control UI 또는 관리 노드 REST API를 사용하여 관리 서비스를 업데이트할 수 있습니다.

* <<Hybrid Cloud Control을 사용하여 관리 서비스 업데이트>>(추천 방법)
* <<관리 노드 API를 사용하여 관리 서비스 업데이트>>




== Hybrid Cloud Control을 사용하여 관리 서비스 업데이트

NetApp Hybrid Cloud Control을 사용하여 NetApp 관리 서비스를 업데이트할 수 있습니다.

관리 서비스 번들은 주요 릴리스 외에도 향상된 기능과 설치 수정 사항을 제공합니다.

.시작하기 전에
* 관리 노드 11.3 이상을 실행하고 있습니다.
* 관리 서비스를 버전 2.16 이상으로 업데이트하고 관리 노드 11.3~11.8을 실행 중인 경우 관리 서비스를 업데이트하기 전에 관리 노드 VM의 RAM을 늘려야 합니다.
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


* 귀하의 클러스터 버전은 NetApp Element 소프트웨어 11.3 이상을 실행하고 있습니다.
* 관리 서비스를 최소 2.1.326 버전으로 업그레이드했습니다.  NetApp Hybrid Cloud Control 업그레이드는 이전 서비스 번들에서는 제공되지 않습니다.



NOTE: 각 서비스 번들 버전에 사용 가능한 서비스 목록은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리스 노트"^] .

.단계
. 웹 브라우저에서 관리 노드의 IP 주소를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>
----
. 스토리지 클러스터 관리자 자격 증명을 제공하여 NetApp Hybrid Cloud Control에 로그인합니다.
. 인터페이스 오른쪽 상단에 있는 *업그레이드*를 선택하세요.
. 업그레이드 페이지에서 *관리 서비스* 탭을 선택합니다.
. 해당 페이지의 지침에 따라 관리 서비스 업그레이드 패키지를 다운로드하여 컴퓨터에 저장하세요.
. *찾아보기*를 선택하여 저장한 패키지를 찾아 업로드하세요.
+
패키지를 업로드하면 업그레이드가 자동으로 시작됩니다.

+
업그레이드가 시작되면 이 페이지에서 업그레이드 상태를 확인할 수 있습니다.  업그레이드하는 동안 NetApp Hybrid Cloud Control과의 연결이 끊어질 수 있으며, 업그레이드 결과를 보려면 다시 로그인해야 할 수도 있습니다.





== 관리 노드 API를 사용하여 관리 서비스 업데이트

이상적으로는 사용자는 NetApp Hybrid Cloud Control에서 관리 서비스 업데이트를 수행해야 합니다.  하지만 REST API를 사용하여 관리 노드에 관리 서비스에 대한 서비스 번들 업데이트를 수동으로 업로드, 추출 및 배포할 수 있습니다.  관리 노드의 REST API UI에서 각 명령을 실행할 수 있습니다.

.시작하기 전에
* NetApp Element 소프트웨어 관리 노드 11.3 이상을 배포했습니다.
* 관리 서비스를 버전 2.16 이상으로 업데이트하고 관리 노드 11.3~11.8을 실행 중인 경우 관리 서비스를 업데이트하기 전에 관리 노드 VM의 RAM을 늘려야 합니다.
+
.. 관리 노드 VM의 전원을 끕니다.
.. 관리 노드 VM의 RAM을 12GB에서 24GB RAM으로 변경합니다.
.. 관리 노드 VM의 전원을 켭니다.


* 귀하의 클러스터 버전은 NetApp Element 소프트웨어 11.3 이상을 실행하고 있습니다.
* 관리 서비스를 최소 2.1.326 버전으로 업그레이드했습니다.  NetApp Hybrid Cloud Control 업그레이드는 이전 서비스 번들에서는 제공되지 않습니다.
+

NOTE: 각 서비스 번들 버전에 사용 가능한 서비스 목록은 다음을 참조하세요. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["관리 서비스 릴리스 노트"^] .



.단계
. 관리 노드에서 REST API UI를 엽니다. `https://<ManagementNodeIP>/mnode`
. *승인*을 선택하고 다음을 완료하세요.
+
.. 클러스터 사용자 이름과 비밀번호를 입력하세요.
.. 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` 값이 아직 채워지지 않은 경우.
.. 세션을 시작하려면 *승인*을 선택하세요.
.. 창을 닫으세요.


. 다음 명령을 사용하여 관리 노드에 서비스 번들을 업로드하고 추출합니다. `PUT /services/upload`
. 관리 노드에 관리 서비스를 배포합니다. `PUT /services/deploy`
. 업데이트 상태를 모니터링합니다. `GET /services/update/status`
+
업데이트가 성공적으로 완료되면 다음 예와 비슷한 결과가 반환됩니다.

+
[listing]
----
{
"current_version": "2.10.29",
"details": "Updated to version 2.17.52",
"status": "success"
}
----


[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

