---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_management_node.html 
summary: NetApp SolidFire 스토리지 시스템 업그레이드의 일부로 관리 노드를 업그레이드합니다. 
keywords: netapp, cluster, management node, mNode, upgrade, 10, 11.0, 11.1, 11.3, 11.5, 11.7, 12.0, 12.2, 12.3, 12.3.1, 12.3.2, 12.3.x, 12.5, 12.7, 12.8 
---
= 관리 노드 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
버전 12.3.x 이상에서 관리 노드 12.5 이상으로 관리 노드를 업그레이드할 수 있습니다.

스토리지 클러스터에서 Element 소프트웨어를 업그레이드하기 위해 관리 노드 운영 체제를 업그레이드할 필요가 더 이상 없습니다.  NetApp Hybrid Cloud Control을 사용하여 Element 업그레이드를 수행하려면 관리 서비스를 최신 버전으로 간단히 업그레이드할 수 있습니다.  보안 개선 등의 다른 이유로 관리 노드 운영 체제를 업그레이드하려는 경우 시나리오에 맞는 관리 노드 업그레이드 절차를 따르세요.


NOTE: 관리 노드 12.2 이하 버전 업그레이드에 대한 정보가 필요한 경우 다음을 참조하세요. https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_management_node.html["Element 12.3.x 관리 노드 업그레이드 설명서"^] .



== 1단계: 관리 노드에서 VM 하드웨어 버전 업그레이드

기존 관리 노드를 Element 12.8로 인플레이스 업그레이드하는 경우 업그레이드하기 전에 환경에 따라 관리 노드의 VM 하드웨어 버전이 ESXi 6.7(VM 하드웨어 버전 14) 이상과 호환되는지 확인해야 합니다.

.단계
. vCenter 관리자로 vSphere Web Client에 로그인합니다.
. vSphere Client 메뉴에서 *VM 및 템플릿*을 선택합니다.
. 가상 머신(VM)을 마우스 오른쪽 버튼으로 클릭하고 *전원* > *게스트 OS 종료*를 선택합니다.
+
VM의 전원이 꺼질 때까지 기다리세요.

. VM을 마우스 오른쪽 버튼으로 클릭하고 *호환성* > *VM 호환성 업그레이드*를 선택합니다.
. *예*를 선택하세요.
. vSphere 환경 버전에 따라 ESXi 6.7 이상 버전을 선택하세요.
. *OK*을 선택하세요.
. 업그레이드가 완료되면 VM을 마우스 오른쪽 버튼으로 클릭하고 *전원* > *전원 켜기*를 선택합니다.
. *vSphere 클라이언트 새로 고침*을 선택하고 VM 호환성이 원하는 버전인지 확인합니다.




== 2단계: 관리 노드를 Element 12.5 이상으로 업그레이드

다음 업그레이드 옵션 중 하나를 선택하세요.

* <<버전 12.3.x 이상에서 버전 12.5 이상으로 관리 노드 업그레이드>>
* <<관리 노드 REST API를 사용하여 인증을 재구성합니다.>>
+
(1) 관리 서비스 버전과 (2) Element 스토리지 버전을 *순차적으로* 업데이트했고 기존 관리 노드를 *유지*하려는 경우 이 옵션을 선택하세요.




NOTE: Element 저장소에 이어 관리 서비스를 순차적으로 업데이트하지 않으면 이 절차를 사용하여 재인증을 재구성할 수 없습니다.  대신 적절한 업그레이드 절차를 따르세요.



=== 버전 12.3.x 이상에서 버전 12.5 이상으로 관리 노드 업그레이드

새로운 관리 노드 VM을 프로비저닝하지 않고도 버전 12.3.x 이상에서 버전 12.5 이상으로 관리 노드의 제자리 업그레이드를 수행할 수 있습니다.


NOTE: Element 12.5 이상 관리 노드는 선택적 업그레이드입니다.  기존 배포에는 필요하지 않습니다.

.시작하기 전에
* 관리 노드 VM의 RAM은 24GB입니다.
* 업그레이드하려는 관리 노드는 버전 12.0이며 IPv4 네트워킹을 사용합니다.  관리 노드 버전 12.5 이상에서는 IPv6를 지원하지 않습니다.
+

TIP: 관리 노드의 버전을 확인하려면 관리 노드에 로그인하고 로그인 배너에서 Element 버전 번호를 확인하세요.

* NetApp Hybrid Cloud Control을 사용하여 관리 서비스 번들을 최신 버전으로 업데이트했습니다.  다음 IP에서 NetApp Hybrid Cloud Control에 액세스할 수 있습니다. `\https://<ManagementNodeIP>`
* 관리 노드를 12.5 이상 버전으로 업데이트하는 경우 계속 진행하려면 관리 서비스 2.21.61 이상이 필요합니다.
* 필요한 경우 추가 네트워크 어댑터를 구성했습니다.link:../mnode/task_mnode_install_add_storage_NIC.html["추가 스토리지 NIC 구성"] .
+

NOTE: eth0을 SVIP로 라우팅할 수 없는 경우 영구 볼륨에 추가 네트워크 어댑터가 필요할 수 있습니다.  iSCSI 스토리지 네트워크에 새 네트워크 어댑터를 구성하여 영구 볼륨을 구성할 수 있습니다.

* 스토리지 노드는 Element 12.3.x 이상을 실행하고 있습니다.


.단계
. SSH 또는 콘솔 액세스를 사용하여 관리 노드 VM에 로그인합니다.
. 다운로드 https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["관리 노드 ISO"^] NetApp 지원 사이트에서 Element 소프트웨어를 관리 노드 VM으로 전송합니다.
+

NOTE: ISO의 이름은 다음과 유사합니다. `solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. 다음 예와 같이 다운로드한 파일에 md5sum을 실행하여 다운로드의 무결성을 확인하고 NetApp 지원 사이트에서 Element 소프트웨어에 대한 출력과 비교합니다.
+
`sudo md5sum -b <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso`

. 다음 명령을 사용하여 관리 노드 ISO 이미지를 마운트하고 내용을 파일 시스템에 복사합니다.
+
[listing]
----
sudo mkdir -p /upgrade
----
+
[listing]
----
sudo mount <solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso> /mnt
----
+
[listing]
----
sudo cp -r /mnt/* /upgrade
----
. 홈 디렉토리로 변경하고 ISO 파일을 마운트 해제합니다. `/mnt` :
+
[listing]
----
sudo umount /mnt
----
. 관리 노드의 공간을 절약하려면 ISO를 삭제하세요.
+
[listing]
----
sudo rm <path to iso>/solidfire-fdva-<Element release>-patchX-XX.X.X.XXXX.iso
----
. 업그레이드하는 관리 노드에서 다음 명령을 실행하여 관리 노드 OS 버전을 업그레이드합니다.  스크립트는 업그레이드 후에도 Active IQ 수집기 및 프록시 설정과 같은 모든 필수 구성 파일을 유지합니다.
+
[listing]
----
sudo /sf/rtfi/bin/sfrtfi_inplace file:///upgrade/casper/filesystem.squashfs sf_upgrade=1
----
+
업그레이드 프로세스가 완료되면 관리 노드가 새 OS로 재부팅됩니다.

+

NOTE: 이 단계에서 설명한 sudo 명령을 실행하면 SSH 세션이 종료됩니다.  지속적인 모니터링을 위해서는 콘솔 접속이 필요합니다.  업그레이드를 수행할 때 콘솔에 액세스할 수 없는 경우 SSH 로그인을 다시 시도하고 15~30분 후에 연결을 확인하세요.  로그인하면 업그레이드가 성공적으로 완료되었음을 나타내는 SSH 배너에서 새로운 OS 버전을 확인할 수 있습니다.

. 관리 노드에서 다음을 실행합니다. `redeploy-mnode` 이전 관리 서비스 구성 설정을 유지하는 스크립트:
+

NOTE: 스크립트는 사용자 설정에 따라 Active IQ 수집기 서비스, 컨트롤러(vCenter) 또는 프록시의 구성을 포함하여 이전 관리 서비스 구성을 유지합니다.

+
[listing]
----
sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>
----



IMPORTANT: 이전에 관리 노드에서 SSH 기능을 비활성화한 경우 다음을 수행해야 합니다.link:../mnode/task_mnode_ssh_management.html["SSH를 다시 비활성화하세요"] 복구된 관리 노드에서.  제공하는 SSH 기능link:../mnode/task_mnode_enable_remote_support_connections.html["NetApp 지원 원격 지원 터널(RST) 세션 액세스"] 기본적으로 관리 노드에서 활성화됩니다.



=== 관리 노드 REST API를 사용하여 인증을 재구성합니다.

(1) 관리 서비스 및 (2) Element 스토리지를 순차적으로 업그레이드한 경우 기존 관리 노드를 유지할 수 있습니다.  다른 업그레이드 순서를 따른 경우, 기존 관리 노드 업그레이드 절차를 참조하세요.

.시작하기 전에
* 관리 서비스를 2.20.69 버전 이상으로 업데이트했습니다.
* 스토리지 클러스터에서 Element 12.3 이상이 실행 중입니다.
* Element 스토리지를 업그레이드한 후 관리 서비스를 순차적으로 업데이트했습니다.  설명된 순서대로 업그레이드를 완료하지 않은 경우 이 절차를 사용하여 인증을 재구성할 수 없습니다.


.단계
. 관리 노드에서 관리 노드 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. *승인*을 선택하고 다음을 완료하세요.
+
.. 클러스터 사용자 이름과 비밀번호를 입력하세요.
.. 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` 값이 아직 채워지지 않은 경우.
.. 세션을 시작하려면 *승인*을 선택하세요.


. REST API UI에서 *POST /services/reconfigure-auth*를 선택합니다.
. *시도해보기*를 선택하세요.
. *load_images* 매개변수에 대해 다음을 선택하세요. `true` .
. *실행*을 선택하세요.
+
응답 본문은 재구성이 성공적이었음을 나타냅니다.





== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

