---
sidebar: sidebar 
permalink: mnode/task_mnode_install_add_storage_NIC.html 
summary: 저장소용으로 추가 NIC를 사용하는 경우 태그가 지정되지 않은 네트워크 인터페이스나 태그가 지정된 네트워크 인터페이스를 설정해야 합니다. 
keywords: netapp, element, management node, mnode, network, nic, storage nic 
---
= 스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
스토리지용으로 추가 NIC를 사용하는 경우 관리 노드에 SSH를 통해 접속하거나 vCenter 콘솔을 사용하여 curl 명령을 실행하여 태그가 지정되거나 지정되지 않은 네트워크 인터페이스를 설정할 수 있습니다.

.시작하기 전에
* eth0 IP 주소를 알고 계시죠.
* 귀하의 클러스터 버전은 NetApp Element 소프트웨어 11.3 이상을 실행하고 있습니다.
* 관리 노드 11.3 이상을 배포했습니다.


.구성 옵션
귀하의 환경에 적합한 옵션을 선택하세요.

* <<태그가 지정되지 않은 네트워크 인터페이스에 대한 스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성>>
* <<태그가 지정된 네트워크 인터페이스에 대한 스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성>>




== 태그가 지정되지 않은 네트워크 인터페이스에 대한 스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성

.단계
. SSH 또는 vCenter 콘솔을 엽니다.
. 다음 명령 템플릿의 값을 바꾸고 명령을 실행합니다.
+

NOTE: 값은 다음으로 표현됩니다. `$` 새로운 스토리지 네트워크 인터페이스에 필요한 각 매개변수에 대해.  그만큼 `cluster` 다음 템플릿의 객체는 필수이며 관리 노드 호스트 이름 변경에 사용할 수 있습니다. `--insecure` 또는 `-k` 옵션은 프로덕션 환경에서 사용하면 안 됩니다.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name"
                         }
             },
    "method": "SetConfig"
}
'
----




== 태그가 지정된 네트워크 인터페이스에 대한 스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성

.단계
. SSH 또는 vCenter 콘솔을 엽니다.
. 다음 명령 템플릿의 값을 바꾸고 명령을 실행합니다.
+

NOTE: 값은 다음으로 표현됩니다. `$` 새로운 스토리지 네트워크 인터페이스에 필요한 각 매개변수에 대해.  그만큼 `cluster` 다음 템플릿의 객체는 필수이며 관리 노드 호스트 이름 변경에 사용할 수 있습니다. `--insecure` 또는 `-k` 옵션은 프로덕션 환경에서 사용하면 안 됩니다.

+
[listing]
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up",
                                   "virtualNetworkTag" : "$vlan_id"
                                   }
                          },
               "cluster": {
                         "name": "$mnode_host_name",
                         "cipi": "$eth1.$vlan_id",
                         "sipi": "$eth1.$vlan_id"
                         }
             },
    "method": "SetConfig"
}
'
----


[discrete]
== 더 많은 정보를 찾아보세요

* link:task_mnode_add_assets.html["관리 노드에 컨트롤러 자산 추가"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]

