---
sidebar: sidebar 
permalink: mnode/task_mnode_api_find_mgmt_svcs_version.html 
summary: REST API를 사용하여 관리 노드에서 사용되는 관리 노드 OS 및 관리 서비스 버전을 찾을 수 있습니다. 
keywords: netapp, Element, management node, management services, version, bundle version, what is 
---
= 관리 노드 OS 및 서비스 버전 확인
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
관리 노드의 REST API를 사용하여 관리 노드 OS, 관리 서비스 번들 및 관리 노드에서 실행되는 개별 서비스의 버전 번호를 확인할 수 있습니다.

.필요한 것
* 클러스터에서 NetApp Element 소프트웨어 11.3 이상이 실행되고 있습니다.
* 버전 11.3 이상을 실행하는 관리 노드를 배포했습니다.


.옵션
* <<API 명령>>
* <<REST API UI 단계>>




== API 명령

* 관리 노드에서 실행 중인 관리 노드 OS, 관리 서비스 번들 및 관리 노드 API(mnode-api) 서비스에 대한 버전 정보를 가져옵니다.
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/about" -H  "accept: application/json"
----
* 관리 노드에서 실행 중인 개별 서비스에 대한 버전 정보를 가져옵니다.
+
[listing]
----
curl -X GET "https://<ManagementNodeIP>/mnode/services?status=running" -H  "accept: */*" -H  "Authorization: ${TOKEN}"
----
+

NOTE: 당신은 운반자를 찾을 수 있습니다 `${TOKEN}` API 명령에서 사용됨link:task_mnode_api_get_authorizationtouse.html["허가하다"] .  운반자 `${TOKEN}` curl 응답에 있습니다.





== REST API UI 단계

. 관리 노드 IP 주소를 입력한 다음 다음을 입력하여 서비스에 대한 REST API UI에 액세스합니다. `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. 다음 중 하나를 수행하세요.
+
** 관리 노드에서 실행 중인 관리 노드 OS, 관리 서비스 번들 및 관리 노드 API(mnode-api) 서비스에 대한 버전 정보를 가져옵니다.
+
... *GET /about*을 선택하세요.
... *시도해보기*를 선택하세요.
... *실행*을 선택하세요.
+
관리 서비스 번들 버전(`"mnode_bundle_version"` ), 관리 노드 OS 버전(`"os_version"` ), 및 관리 노드 API 버전(`"version"` )는 응답 본문에 표시됩니다.



** 관리 노드에서 실행 중인 개별 서비스에 대한 버전 정보를 가져옵니다.
+
... *GET /services*를 선택하세요.
... *시도해보기*를 선택하세요.
... 상태를 *실행 중*으로 선택하세요.
... *실행*을 선택하세요.
+
관리 노드에서 실행 중인 서비스는 응답 본문에 표시됩니다.







[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]

