---
sidebar: sidebar 
permalink: mnode/task_mnode_run_system_utilities.html 
summary: 클러스터 지원 번들을 생성하거나 삭제하고, 노드 구성 설정을 재설정하거나 네트워킹을 다시 시작할 수 있습니다. 
keywords: netapp, Element, management node ui, mnode ui, system utilities 
---
= 관리 노드에서 시스템 유틸리티 실행
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
관리 노드의 노드별 UI를 사용하여 클러스터 지원 번들을 생성하거나 삭제하고, 노드 구성 설정을 재설정하거나 네트워킹을 다시 시작할 수 있습니다.

.단계
. 관리 노드 관리자 자격 증명을 사용하여 노드별 관리 노드 UI를 엽니다.
. *시스템 유틸리티*를 선택하세요.
. 실행하려는 유틸리티의 버튼을 선택하세요.
+
.. *전원 제어*: 노드를 재부팅, 전원 주기 또는 종료합니다.  다음 옵션 중 하나를 지정하세요.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어집니다.

+
*** *작업*: 옵션은 다음과 같습니다. `Restart` 그리고 `Halt` (전원 끄기).
*** *웨이크업 지연*: 노드가 다시 온라인 상태가 되기 전까지의 추가 시간입니다.


.. *클러스터 지원 번들 생성*: 클러스터의 하나 이상의 노드에 대한 NetApp 지원 진단 평가를 지원하기 위해 클러스터 지원 번들을 생성합니다.  다음 옵션을 지정하세요.
+
*** *번들 이름*: 생성된 각 지원 번들에 대한 고유한 이름입니다.  이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
*** *Mvip*: 클러스터의 MVIP입니다.  번들은 클러스터의 모든 노드에서 수집됩니다.  Nodes 매개변수가 지정되지 않은 경우 이 매개변수가 필요합니다.
*** *노드*: 번들을 수집할 노드의 IP 주소입니다.  번들을 수집할 노드를 지정하려면 Nodes 또는 Mvip 중 하나만 사용하지만, 둘 다 사용하지는 마세요.  Mvip가 지정되지 않은 경우 이 매개변수가 필요합니다.
*** *사용자 이름*: 클러스터 관리자 사용자 이름입니다.
*** *비밀번호*: 클러스터 관리자 비밀번호입니다.
*** *미완료 허용*: 하나 이상의 노드에서 번들을 수집할 수 없는 경우 스크립트가 계속 실행되도록 허용합니다.
*** *추가 인수*: 이 매개변수는 다음에 공급됩니다. `sf_make_support_bundle` 스크립트.  이 매개변수는 NetApp 지원팀의 요청에 의해서만 사용되어야 합니다.


.. *모든 지원 번들 삭제*: 관리 노드에 있는 현재 지원 번들을 모두 삭제합니다.
.. *노드 재설정*: 관리 노드를 새 설치 이미지로 재설정합니다.  이렇게 하면 네트워크 구성을 제외한 모든 설정이 기본 상태로 변경됩니다.  다음 옵션을 지정하세요.
+
*** *빌드*: 노드가 재설정될 원격 Element 소프트웨어 이미지의 URL입니다.
*** *옵션*: 재설정 작업을 실행하기 위한 사양입니다.  자세한 내용은 필요한 경우 NetApp 지원팀에서 제공해 드립니다.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어집니다.



.. *네트워킹 재시작*: 관리 노드에서 모든 네트워크 서비스를 재시작합니다.
+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어집니다.





[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]

