---
sidebar: sidebar 
permalink: mnode/task_mnode_install.html 
summary: NetApp Element 소프트웨어를 실행하는 클러스터에 대한 관리 노드를 설치할 수 있습니다. 
keywords: netapp, element, management node, mnode, storage, install 
---
= 관리 노드 설치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
구성에 적합한 이미지를 사용하여 NetApp Element 소프트웨어를 실행하는 클러스터에 대한 관리 노드를 수동으로 설치할 수 있습니다.

이 수동 프로세스는 관리 노드 설치에 NetApp 배포 엔진을 사용하지 않는 SolidFire 올플래시 스토리지 관리자를 대상으로 합니다.

.시작하기 전에
* 귀하의 클러스터 버전은 NetApp Element 소프트웨어 11.3 이상을 실행하고 있습니다.
* 귀하의 설치는 IPv4를 사용합니다.  관리 노드 11.3은 IPv6를 지원하지 않습니다.
+

NOTE: IPv6 지원이 필요한 경우 관리 노드 11.1을 사용할 수 있습니다.

* NetApp 지원 사이트에서 소프트웨어를 다운로드할 수 있는 권한이 있습니다.
* 플랫폼에 맞는 관리 노드 이미지 유형을 식별했습니다.
+
[cols="30,30"]
|===
| 플랫폼 | 설치 이미지 유형 


| 마이크로소프트 하이퍼-V | .iso 


| 케이비엠 | .iso 


| VMware vSphere | .iso, .ova 


| 시트릭스 젠서버 | .iso 


| 오픈스택 | .iso 
|===
* (프록시 서버가 있는 관리 노드 12.0 이상) 프록시 서버를 구성하기 전에 NetApp Hybrid Cloud Control을 관리 서비스 버전 2.16으로 업데이트했습니다.


.이 작업에 관하여
Element 12.2 관리 노드는 선택적 업그레이드입니다.  기존 배포에는 필요하지 않습니다.

이 절차를 따르기 전에 다음 사항을 이해해야 합니다.link:../concepts/concept_solidfire_concepts_volumes.html#persistent-volumes["영구 볼륨"] 그리고 그것을 사용할 것인지의 여부.  영구 볼륨은 선택 사항이지만 가상 머신(VM) 손실 시 관리 노드 구성 데이터 복구에 권장됩니다.



== 1단계: ISO 또는 OVA를 다운로드하고 VM을 배포합니다.

NetApp 지원 사이트에서 적절한 ISO 또는 OVA를 다운로드하여 VM을 설치합니다.

.단계
. 설치를 위해 OVA 또는 ISO를 다운로드하세요.link:https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["엘리먼트 소프트웨어"^] NetApp 지원 사이트의 페이지입니다.
+
.. *최신 릴리스 다운로드*를 선택하고 EULA에 동의하세요.
.. 다운로드할 관리 노드 이미지를 선택하세요.


. OVA를 다운로드한 경우 다음 단계를 따르세요.
+
.. OVA를 배포합니다.
.. 스토리지 클러스터가 관리 노드(eth0)와 별도의 서브넷에 있고 영구 볼륨을 사용하려는 경우 스토리지 서브넷(예: eth1)의 VM에 두 번째 네트워크 인터페이스 컨트롤러(NIC)를 추가하거나 관리 네트워크가 스토리지 네트워크로 라우팅될 수 있는지 확인하세요.


. ISO를 다운로드한 경우 다음 단계를 따르세요.
+
.. 다음 구성을 사용하여 하이퍼바이저에서 새 64비트 VM을 만듭니다.
+
*** 6개의 가상 CPU
*** 24GB 램
*** 저장 어댑터 유형이 LSI Logic Parallel로 설정됨
+

IMPORTANT: 관리 노드의 기본값은 LSI Logic SAS일 수 있습니다.  *새 가상 머신* 창에서 *하드웨어 사용자 지정* > *가상 하드웨어*를 선택하여 스토리지 어댑터 구성을 확인합니다.  필요한 경우 LSI Logic SAS를 *LSI Logic Parallel*로 변경합니다.

*** 400GB 가상 디스크, 씬 프로비저닝
*** 인터넷 접속과 스토리지 MVIP 접속이 가능한 하나의 가상 네트워크 인터페이스.
*** (선택 사항) 스토리지 클러스터에 대한 관리 네트워크 액세스가 가능한 하나의 가상 네트워크 인터페이스.  스토리지 클러스터가 관리 노드(eth0)와 별도의 서브넷에 있고 영구 볼륨을 사용하려는 경우 스토리지 서브넷(eth1)의 VM에 두 번째 네트워크 인터페이스 컨트롤러(NIC)를 추가하거나 관리 네트워크가 스토리지 네트워크로 라우팅될 수 있는지 확인하세요.
+

IMPORTANT: 이 절차의 뒷부분에서 지시하는 단계 이전에는 VM의 전원을 켜지 마십시오.



.. ISO를 VM에 연결하고 .iso 설치 이미지로 부팅합니다.
+

NOTE: 이미지를 사용하여 관리 노드를 설치하면 시작 화면이 나타나기 전에 30초의 지연이 발생할 수 있습니다.



. 설치가 완료되면 관리 노드의 VM 전원을 켭니다.




== 2단계: 관리 노드 관리자를 생성하고 네트워크를 구성합니다.

VM 설치가 완료되면 관리 노드 관리자 사용자를 만들고 관리 노드 네트워크를 구성합니다.

.단계
. 터미널 사용자 인터페이스(TUI)를 사용하여 관리 노드 관리자 사용자를 만듭니다.
+

TIP: 메뉴 옵션 사이를 이동하려면 위쪽 또는 아래쪽 화살표 키를 누르세요.  버튼 사이를 이동하려면 Tab 키를 누르세요.  버튼에서 필드로 이동하려면 Tab 키를 누르세요.  필드 사이를 이동하려면 위쪽 또는 아래쪽 화살표 키를 누르세요.

. 네트워크에 최대 전송 단위(MTU)가 1500바이트 미만인 IP를 할당하는 DHCP(동적 호스트 구성 프로토콜) 서버가 있는 경우 다음 단계를 수행해야 합니다.
+
.. DHCP가 없는 vSphere 네트워크(예: iSCSI)에 관리 노드를 임시로 배치합니다.
.. VM을 재부팅하거나 VM 네트워크를 다시 시작합니다.
.. TUI를 사용하여 관리 네트워크에서 1500바이트 이상의 MTU로 올바른 IP를 구성합니다.
.. VM에 올바른 VM 네트워크를 다시 할당합니다.


+

NOTE: MTU가 1500바이트 미만인 IP를 할당하는 DHCP로 인해 관리 노드 네트워크를 구성하거나 관리 노드 UI를 사용할 수 없습니다.

. 관리 노드 네트워크(eth0)를 구성합니다.
+

NOTE: 스토리지 트래픽을 분리하기 위해 추가 NIC가 필요한 경우 다른 NIC 구성에 대한 지침을 참조하세요.link:task_mnode_install_add_storage_NIC.html["스토리지 네트워크 인터페이스 컨트롤러(NIC) 구성"] .





== 3단계: 시간 동기화 구성

관리 노드를 설정하기 전에 관리 노드와 스토리지 클러스터 간의 시간을 동기화하세요.

.단계
. NTP를 사용하여 관리 노드와 스토리지 클러스터 간의 시간이 동기화되었는지 확인하세요.



NOTE: 요소 12.3.1부터 하위 단계 (a)부터 (e)까지는 자동으로 수행됩니다.  관리 노드 12.3.1의 경우 다음으로 진행하세요.<<substep_f_install_config_time_sync,하위 단계 (f)>> 시간 동기화 구성을 완료합니다.

. SSH나 하이퍼바이저가 제공하는 콘솔을 사용하여 관리 노드에 로그인합니다.
. NTPD 중지:
+
[listing]
----
sudo service ntpd stop
----
. NTP 구성 파일 편집 `/etc/ntp.conf` :
+
.. 기본 서버를 주석 처리합니다.(`server 0.gentoo.pool.ntp.org` )을 추가하여 `#` 각각의 앞에.
.. 추가하려는 각 기본 시간 서버에 대해 새 줄을 추가합니다. 기본 시간 서버는 스토리지 클러스터에서 사용되는 NTP 서버와 동일해야 합니다. <<set-up-the-management-node,나중 단계>>.
+
[listing]
----
vi /etc/ntp.conf

#server 0.gentoo.pool.ntp.org
#server 1.gentoo.pool.ntp.org
#server 2.gentoo.pool.ntp.org
#server 3.gentoo.pool.ntp.org
server <insert the hostname or IP address of the default time server>
----
.. 완료되면 구성 파일을 저장합니다.


. 새로 추가된 서버와 NTP 동기화를 강제로 실행합니다.
+
[listing]
----
sudo ntpd -gq
----
. NTPD를 다시 시작합니다.
+
[listing]
----
sudo service ntpd start
----
. [[substep_f_install_config_time_sync]]하이퍼바이저를 통해 호스트와의 시간 동기화를 비활성화합니다(다음은 VMware 예시입니다):
+

NOTE: 예를 들어 Openstack 환경의 .iso 이미지에서와 같이 VMware가 아닌 다른 하이퍼바이저 환경에 mNode를 배포하는 경우 해당 명령에 대한 하이퍼바이저 설명서를 참조하세요.

+
.. 주기적 시간 동기화 비활성화:
+
[listing]
----
vmware-toolbox-cmd timesync disable
----
.. 서비스의 현재 상태를 표시하고 확인합니다.
+
[listing]
----
vmware-toolbox-cmd timesync status
----
.. vSphere에서 다음을 확인하십시오. `Synchronize guest time with host` VM 옵션에서 상자가 선택 취소되어 있습니다.
+

NOTE: 나중에 VM을 변경하는 경우 이 옵션을 활성화하지 마세요.






NOTE: 시간 동기화 구성을 완료한 후에는 NTP를 편집하지 마십시오. 편집하면 NTP가 실행될 때 영향을 받습니다. <<set-up-the-management-node,설치 명령>> 관리 노드에서.



== 4단계: 관리 노드 설정

다음을 사용하여 관리 노드를 구성합니다. `setup-mnode` 명령.

.단계
. 관리 노드 설정 명령을 구성하고 실행합니다.
+

NOTE: 보안 프롬프트에서 비밀번호를 입력하라는 메시지가 표시됩니다.  클러스터가 프록시 서버 뒤에 있는 경우 공용 네트워크에 접속할 수 있도록 프록시 설정을 구성해야 합니다.

+
[listing]
----
sudo /sf/packages/mnode/setup-mnode --mnode_admin_user [username] --storage_mvip [mvip] --storage_username [username] --telemetry_active [true]
----
+
.. 다음 필수 매개변수 각각에 대해 [ ] 괄호(괄호 포함) 안의 값을 바꾸세요.
+

NOTE: 명령어 이름의 약어는 괄호( )로 표시되며, 전체 이름으로 대체될 수 있습니다.

+
*** *--mnode_admin_user (-mu) [사용자 이름]*: 관리 노드 관리자 계정의 사용자 이름입니다.  이는 관리 노드에 로그인하는 데 사용한 사용자 계정의 사용자 이름일 가능성이 높습니다.
*** *--storage_mvip (-sm) [MVIP 주소]*: Element 소프트웨어를 실행하는 스토리지 클러스터의 관리 가상 IP 주소(MVIP)입니다. 이전에 사용했던 것과 동일한 스토리지 클러스터로 관리 노드를 구성합니다. <<configure-time-sync,NTP 서버 구성>>.
*** *--storage_username (-su) [사용자 이름]*: 지정된 클러스터에 대한 스토리지 클러스터 관리자 사용자 이름 `--storage_mvip` 매개변수.
*** *--telemetry_active (-t) [true]*: Active IQ 에서 분석을 위한 데이터 수집을 활성화하는 true 값을 유지합니다.


.. (선택 사항): 명령에 Active IQ 엔드포인트 매개변수를 추가합니다.
+
*** *--remote_host (-rh) [AIQ_endpoint]*: Active IQ 원격 측정 데이터가 처리되도록 전송되는 엔드포인트입니다.  매개변수가 포함되지 않으면 기본 엔드포인트가 사용됩니다.


.. (권장): 다음 영구 볼륨 매개변수를 추가합니다.  영구 볼륨 기능을 위해 생성된 계정 및 볼륨을 수정하거나 삭제하지 마십시오. 그렇지 않으면 관리 기능이 손실됩니다.
+
*** *--use_persistent_volumes (-pv) [true/false, 기본값: false]*: 영구 볼륨을 활성화하거나 비활성화합니다.  영구 볼륨 기능을 활성화하려면 true 값을 입력하세요.
*** *--persistent_volumes_account (-pva) [계정_이름]*: 만약 `--use_persistent_volumes` true로 설정된 경우 이 매개변수를 사용하고 영구 볼륨에 사용될 스토리지 계정 이름을 입력합니다.
+

NOTE: 클러스터의 기존 계정 이름과 다른, 영구 볼륨에 고유한 계정 이름을 사용합니다.  영구 볼륨 계정을 나머지 환경과 분리해 두는 것이 매우 중요합니다.

*** *--persistent_volumes_mvip (-pvm) [mvip]*: 영구 볼륨과 함께 사용될 Element 소프트웨어를 실행하는 스토리지 클러스터의 관리 가상 IP 주소(MVIP)를 입력합니다.  이는 관리 노드에서 여러 스토리지 클러스터를 관리하는 경우에만 필요합니다.  여러 클러스터를 관리하지 않으면 기본 클러스터 MVIP가 사용됩니다.


.. 프록시 서버를 구성하세요:
+
*** *--use_proxy (-up) [true/false, 기본값: false]*: 프록시 사용을 활성화하거나 비활성화합니다.  이 매개변수는 프록시 서버를 구성하는 데 필요합니다.
*** *--proxy_hostname_or_ip (-pi) [호스트]*: 프록시 호스트 이름 또는 IP.  프록시를 사용하려면 이 작업이 필요합니다.  이것을 지정하면 입력하라는 메시지가 표시됩니다. `--proxy_port` .
*** *--proxy_username (-pu) [사용자 이름]*: 프록시 사용자 이름.  이 매개변수는 선택 사항입니다.
*** *--proxy_password (-pp) [비밀번호]*: 프록시 비밀번호.  이 매개변수는 선택 사항입니다.
*** *--proxy_port (-pq) [포트, 기본값: 0]*: 프록시 포트.  이것을 지정하면 프록시 호스트 이름이나 IP를 입력하라는 메시지가 표시됩니다.(`--proxy_hostname_or_ip` ).
*** *--proxy_ssh_port (-ps) [포트, 기본값: 443]*: SSH 프록시 포트.  기본적으로 포트는 443입니다.


.. (선택 사항) 각 매개변수에 대한 추가 정보가 필요한 경우 매개변수 도움말을 사용하세요.
+
*** *--help (-h)*: 각 매개변수에 대한 정보를 반환합니다.  매개변수는 초기 배포에 따라 필수 또는 선택 사항으로 정의됩니다.  업그레이드 및 재배포 매개변수 요구 사항은 다를 수 있습니다.


.. 실행하다 `setup-mnode` 명령.






== 5단계: 컨트롤러 자산 구성

설치 ID를 찾아 vCenter 컨트롤러 자산을 추가합니다.

.단계
. 설치 ID를 찾으세요.
+
.. 브라우저에서 관리 노드 REST API UI에 로그인합니다.
.. 저장소 MVIP로 이동하여 로그인합니다. 이렇게 하면 다음 단계에서 인증서가 승인됩니다.
.. 관리 노드에서 인벤토리 서비스 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. *승인*을 선택하고 다음을 완료하세요.
+
... 클러스터 사용자 이름과 비밀번호를 입력하세요.
... 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` .
... 세션을 시작하려면 *승인*을 선택하세요.


.. REST API UI에서 *GET ​/installations*를 선택합니다.
.. *시도해보기*를 선택하세요.
.. *실행*을 선택하세요.
.. 코드 200 응답 본문에서 복사하여 저장하세요. `id` 이후 단계에서 사용하기 위한 설치용입니다.
+
설치에는 설치 또는 업그레이드 중에 생성된 기본 자산 구성이 있습니다.



. NetApp Hybrid Cloud Control에 대한 vCenter 컨트롤러 자산을 관리 노드 알려진 자산에 추가합니다.
+
.. 관리 노드에서 관리 노드 IP 주소를 입력한 다음 mnode 서비스 API UI에 액세스합니다. `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. *승인* 또는 잠금 아이콘을 선택하고 다음을 완료하세요.
+
... 클러스터 사용자 이름과 비밀번호를 입력하세요.
... 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` .
... 세션을 시작하려면 *승인*을 선택하세요.
... 창을 닫으세요.


.. 컨트롤러 하위 자산을 추가하려면 *POST /assets/{asset_id}/controllers*를 선택하세요.
+

NOTE: 컨트롤러 하위 자산을 추가하려면 vCenter에서 새로운 NetApp HCC 역할을 만들어야 합니다.  이 새로운 NetApp HCC 역할은 관리 노드 서비스 보기를 NetApp 자산으로만 제한합니다. 보다link:task_mnode_create_netapp_hcc_role_vcenter.html["vCenter에서 NetApp HCC 역할 생성"] .

.. *시도해보기*를 선택하세요.
.. 클립보드에 복사한 부모 기반 자산 ID를 *asset_id* 필드에 입력합니다.
.. 필요한 페이로드 값을 유형으로 입력하세요. `vCenter` 및 vCenter 자격 증명.
.. *실행*을 선택하세요.






== 더 많은 정보를 찾아보세요

* link:../concepts/concept_solidfire_concepts_volumes.html#persistent-volumes["영구 볼륨"]
* link:task_mnode_add_assets.html["관리 노드에 컨트롤러 자산 추가"]
* link:task_mnode_install_add_storage_NIC.html["스토리지 NIC 구성"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]

