---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: '관리 노드(mNode)를 사용하여 SolidFire 올플래시 스토리지에 대해 Active IQ 활성화할 수 있습니다.' 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Active IQ 및 NetApp 모니터링 활성화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
설치 또는 업그레이드 중에 Active IQ 스토리지 모니터링을 아직 활성화하지 않았다면 이제 활성화할 수 있습니다.  SolidFire 올플래시 스토리지 시스템을 설치하는 동안 SolidFire Active IQ 설정하지 않은 경우 이 절차를 사용해야 할 수도 있습니다.

Active IQ 수집기 서비스는 구성 데이터와 Element 소프트웨어 기반 클러스터 성능 측정 항목을 SolidFire Active IQ 로 전달하여 과거 보고 및 실시간에 가까운 성능 모니터링을 수행합니다.  NetApp 모니터링 서비스를 사용하면 스토리지 클러스터 오류를 vCenter로 전달하여 경고 알림을 받을 수 있습니다.

.시작하기 전에
* 예를 들어 Active IQ 의 일부 기능(서비스 품질(QoS))을 사용하려면 Element 11.3 이상이 필요합니다.  모든 Active IQ 기능을 사용할 수 있는 능력이 있는지 확인하기 위해 NetApp 다음을 권장합니다.
+
** 스토리지 클러스터에서 NetApp Element 소프트웨어 11.3 이상이 실행되고 있습니다.
** 버전 11.3 이상을 실행하는 관리 노드를 배포했습니다.


* 인터넷에 접속할 수 있습니다.  Active IQ 수집기 서비스는 외부 연결이 없는 다크 사이트에서는 사용할 수 없습니다.


.단계
. 설치에 대한 기본 자산 ID를 가져옵니다.
+
.. 관리 노드에서 인벤토리 서비스 REST API UI를 엽니다.
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. *승인*을 선택하고 다음을 완료하세요.
+
... 클러스터 사용자 이름과 비밀번호를 입력하세요.
... 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` .
... 세션을 시작하려면 *승인*을 선택하세요.
... 창을 닫으세요.


.. REST API UI에서 *GET ​/installations*를 선택합니다.
.. *시도해보기*를 선택하세요.
.. *실행*을 선택하세요.
.. 코드 200 응답 본문에서 다음을 복사합니다. `id` 설치를 위해서.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: 설치에는 설치 또는 업그레이드 중에 생성된 기본 자산 구성이 있습니다.



. 원격 측정 활성화:
+
.. 관리 노드에서 관리 노드 IP 주소를 입력한 다음 mnode 서비스 API UI에 액세스합니다. `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. *승인* 또는 잠금 아이콘을 선택하고 다음을 완료하세요.
+
... 클러스터 사용자 이름과 비밀번호를 입력하세요.
... 클라이언트 ID를 다음과 같이 입력하세요. `mnode-client` .
... 세션을 시작하려면 *승인*을 선택하세요.
... 창을 닫으세요.


.. 기본 자산을 구성합니다.
+
... *PUT /assets/{asset_id}*를 선택하세요.
... *시도해보기*를 선택하세요.
... JSON 페이로드에 다음을 입력하세요.
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... 이전 단계의 기본 ID를 *asset_ID*에 입력합니다.
... *실행*을 선택하세요.
+
Active IQ 서비스는 자산이 변경될 때마다 자동으로 다시 시작됩니다.  자산을 수정하면 설정이 적용되기 전에 약간의 지연이 발생합니다.





. 아직 수행하지 않았다면 NetApp Hybrid Cloud Control에 대한 vCenter 컨트롤러 자산을 관리 노드 알려진 자산에 추가합니다.
+

NOTE: NetApp 모니터링 서비스에는 컨트롤러 자산이 필요합니다.

+
.. 컨트롤러 하위 자산을 추가하려면 *POST /assets/{asset_id}/controllers*를 선택하세요.
.. *시도해보기*를 선택하세요.
.. 클립보드에 복사한 부모 기반 자산 ID를 *asset_id* 필드에 입력합니다.
.. 필요한 페이로드 값을 입력하세요. `type` ~처럼 `vCenter` 및 vCenter 자격 증명.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip`vCenter IP 주소입니다.

.. *실행*을 선택하세요.




[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]

