---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_node_troubleshooting_sessions.html 
summary: Element 12.5부터 NetApp 지원팀의 도움 없이 관리 노드에서 sfreadonly 사용자 계정을 활성화하여 시스템 구성 요소의 문제를 해결할 수 있습니다.  고급 문제 해결을 위해 NetApp 지원에 대한 원격 지원 터널 액세스를 활성화하고 열 수도 있습니다. 
keywords: netapp, sfreadonly, connect to support, support tunnel, rst, mnode, management node 
---
= 기본 문제 해결을 위해 SSH를 사용하여 스토리지 노드에 액세스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Element 12.5부터 기본적인 문제 해결을 위해 스토리지 노드에서 sfreadonly 시스템 계정을 사용할 수 있습니다.  고급 문제 해결을 위해 NetApp 지원에 대한 원격 지원 터널 액세스를 활성화하고 열 수도 있습니다.

sfreadonly 시스템 계정을 사용하면 다음을 포함한 기본 Linux 시스템 및 네트워크 문제 해결 명령을 실행할 수 있습니다. `ping` .


WARNING: NetApp 지원팀의 별도 안내 없이 이 시스템을 변경하는 것은 지원되지 않으며, 지원 계약이 무효화되고 데이터 불안정이나 접근 불가 현상이 발생할 수 있습니다.

.시작하기 전에
* *쓰기 권한*: 현재 작업 디렉토리에 대한 쓰기 권한이 있는지 확인하세요.
* *(선택 사항) 나만의 키 쌍을 생성하세요*: 실행 `ssh-keygen` Windows 10, MacOS 또는 Linux 배포판에서.  이는 사용자 키 쌍을 생성하는 일회성 작업이며 향후 문제 해결 세션에 재사용할 수 있습니다.  직원 계정과 연결된 인증서를 사용하면 이 모델에서도 효과적일 수 있습니다.
* *관리 노드에서 SSH 기능 활성화*: 관리 모드에서 원격 액세스 기능을 활성화하려면 다음을 참조하세요.link:task_mnode_ssh_management.html["이 주제"] .  관리 서비스 2.18 이상의 경우, 관리 노드에서 원격 액세스 기능은 기본적으로 비활성화됩니다.
* *저장소 클러스터에서 SSH 기능 활성화*: 저장소 클러스터 노드에서 원격 액세스 기능을 활성화하려면 다음을 참조하세요.link:https://docs.netapp.com/us-en/element-software/storage/task_system_manage_cluster_enable_and_disable_support_access.html["이 주제"] .
* *방화벽 구성*: 관리 노드가 프록시 서버 뒤에 있는 경우 sshd.config 파일에 다음 TCP 포트가 필요합니다.
+
[cols="15,25,60"]
|===
| TCP 포트 | 설명 | 연결 방향 


| 443 | 웹 UI에 대한 개방형 지원 터널을 통한 역방향 포트 포워딩을 위한 API 호출/HTTPS | 관리 노드에서 저장 노드로 


| 22 | SSH 로그인 접근 | 관리 노드에서 스토리지 노드로 또는 스토리지 노드에서 관리 노드로 
|===


.문제 해결 옵션
* <<클러스터 노드 문제 해결>>
* <<NetApp 지원을 통해 클러스터 노드 문제 해결>>
* <<클러스터에 속하지 않는 노드 문제 해결>>




== 클러스터 노드 문제 해결

sfreadonly 시스템 계정을 사용하여 기본적인 문제 해결을 수행할 수 있습니다.

.단계
. 관리 노드 VM을 설치할 때 선택한 계정 로그인 자격 증명을 사용하여 관리 노드에 SSH를 실행합니다.
. 관리 노드에서 다음으로 이동하세요. `/sf/bin` .
. 시스템에 적합한 스크립트를 찾으세요.
+
** SignSshKeys.ps1
** SignSshKeys.py
** SignSshKeys.sh
+
[NOTE]
====
SignSshKeys.ps1은 PowerShell 7 이상에 종속되고 SignSshKeys.py는 Python 3.6.0 이상에 종속됩니다. https://docs.python-requests.org/["요청 모듈"^] .

그만큼 `SignSshKeys` 대본을 쓰다 `user` , `user.pub` , 그리고 `user-cert.pub` 현재 작업 디렉토리에 파일을 저장하면 나중에 다음에서 사용됩니다. `ssh` 명령.  그러나 스크립트에 공개 키 파일이 제공되는 경우에는 `<public_key>` 파일(와 함께 `<public_key>` 스크립트에 전달된 공개 키 파일의 접두사로 대체된 내용이 디렉토리에 기록됩니다.

====


. 관리 노드에서 스크립트를 실행하여 SSH 키체인을 생성합니다.  이 스크립트는 클러스터의 모든 노드에서 sfreadonly 시스템 계정을 사용하여 SSH 액세스를 활성화합니다.
+
[listing]
----
SignSshKeys --ip [ip address] --user [username] --duration [hours] --publickey [public key path]
----
+
.. 다음 각 매개변수에 대해 [ ] 괄호(괄호 포함) 안의 값을 바꾸세요.
+

NOTE: 약어 또는 전체 형식 매개변수를 사용할 수 있습니다.

+
*** *--ip | -i [ip 주소]*: API를 실행할 대상 노드의 IP 주소입니다.
*** *--user | -u [사용자 이름]*: API 호출을 실행하는 데 사용되는 클러스터 사용자입니다.
*** *(선택 사항) --duration | -d [시간]*: 서명된 키가 유효한 상태로 유지되는 기간을 정수로 시간 단위로 지정합니다.  기본값은 24시간입니다.
*** *(선택 사항) --publickey | -k [공개 키 경로]*: 사용자가 공개 키를 제공하기로 선택한 경우 공개 키 경로입니다.


.. 다음 샘플 명령과 입력 내용을 비교해 보세요.  이 예에서, `10.116.139.195` 저장 노드의 IP입니다. `admin` 클러스터 사용자 이름이고 키 유효 기간은 2시간입니다.
+
[listing]
----
sh /sf/bin/SignSshKeys.sh --ip 10.116.139.195 --user admin --duration 2
----
.. 명령을 실행합니다.


. 노드 IP에 SSH를 실행합니다.
+
[listing]
----
ssh -i user sfreadonly@[node_ip]
----
+
다음과 같은 기본 Linux 시스템 및 네트워크 문제 해결 명령을 실행할 수 있습니다. `ping` 및 기타 읽기 전용 명령.

. (선택 사항) 비활성화link:task_mnode_ssh_management.html["원격 액세스 기능"] 문제 해결이 완료된 후에 다시 시도하세요.
+

NOTE: SSH를 비활성화하지 않으면 관리 노드에서 SSH가 활성화된 상태로 유지됩니다.  SSH가 활성화된 구성은 수동으로 비활성화할 때까지 업데이트 및 업그레이드를 통해 관리 노드에 유지됩니다.





== NetApp 지원을 통해 클러스터 노드 문제 해결

NetApp 지원팀은 기술자가 Element에 대한 심층적인 진단을 실행할 수 있도록 하는 시스템 계정을 사용하여 고급 문제 해결을 수행할 수 있습니다.

.단계
. 관리 노드 VM을 설치할 때 선택한 계정 로그인 자격 증명을 사용하여 관리 노드에 SSH를 실행합니다.
. NetApp 지원팀에서 보낸 포트 번호로 첫 번째 명령을 실행하여 지원 터널을 엽니다.
+
`rst -r  sfsupport.solidfire.com -u element -p <port_number>`

+
NetApp 지원팀은 지원 터널을 사용하여 관리 노드에 로그인합니다.

. 관리 노드에서 다음으로 이동하세요. `/sf/bin` .
. 시스템에 적합한 스크립트를 찾으세요.
+
** SignSshKeys.ps1
** SignSshKeys.py
** SignSshKeys.sh
+
[NOTE]
====
SignSshKeys.ps1은 PowerShell 7 이상에 종속되고 SignSshKeys.py는 Python 3.6.0 이상에 종속됩니다. https://docs.python-requests.org/["요청 모듈"^] .

그만큼 `SignSshKeys` 대본을 쓰다 `user` , `user.pub` , 그리고 `user-cert.pub` 현재 작업 디렉토리에 파일을 저장하면 나중에 다음에서 사용됩니다. `ssh` 명령.  그러나 스크립트에 공개 키 파일이 제공되는 경우에는 `<public_key>` 파일(와 함께 `<public_key>` 스크립트에 전달된 공개 키 파일의 접두사로 대체된 내용이 디렉토리에 기록됩니다.

====


. SSH 키체인을 생성하려면 스크립트를 실행하세요. `--sfadmin` 깃발.  이 스크립트는 모든 노드에서 SSH를 활성화합니다.
+
[listing]
----
SignSshKeys --ip [ip address] --user [username] --duration [hours] --sfadmin
----
+
[NOTE]
====
SSH로 `--sfadmin` 클러스터된 노드에 SSH 키체인을 생성하려면 다음을 사용해야 합니다. `--user` ~와 함께 `supportAdmin` 클러스터에 대한 액세스.

구성하려면 `supportAdmin` 클러스터 관리자 계정에 대한 액세스를 위해 Element UI 또는 API를 사용할 수 있습니다.

** link:../storage/concept_system_manage_manage_cluster_administrator_users.html#view-cluster-admin-details["Element UI를 사용하여 "supportAdmin" 액세스 구성"]
** 구성 `supportAdmin` API를 사용하여 액세스하고 추가 `"supportAdmin"` 로서 `"access"` API 요청을 입력하세요:
+
*** link:../api/reference_element_api_addclusteradmin.html["새 계정에 대한 "supportAdmin" 액세스 구성"]
*** link:../api/reference_element_api_modifyclusteradmin.html["기존 계정에 대한 "supportAdmin" 액세스 구성"]
+
을 얻으려면 `clusterAdminID` , 당신은 사용할 수 있습니다link:../api/reference_element_api_listclusteradmins.html["클러스터 관리자 목록"] API.





추가하려면 `supportAdmin` 접근하려면 클러스터 관리자 또는 관리자 권한이 있어야 합니다.

====
+
.. 다음 각 매개변수에 대해 [ ] 괄호(괄호 포함) 안의 값을 바꾸세요.
+

NOTE: 약어 또는 전체 형식 매개변수를 사용할 수 있습니다.

+
*** *--ip | -i [ip 주소]*: API를 실행할 대상 노드의 IP 주소입니다.
*** *--user | -u [사용자 이름]*: API 호출을 실행하는 데 사용되는 클러스터 사용자입니다.
*** *(선택 사항) --duration | -d [시간]*: 서명된 키가 유효한 상태로 유지되는 기간을 정수로 시간 단위로 지정합니다.  기본값은 24시간입니다.


.. 다음 샘플 명령과 입력 내용을 비교해 보세요.  이 예에서, `192.168.0.1` 저장 노드의 IP입니다. `admin` 클러스터 사용자 이름이고 키 유효 기간은 2시간입니다. `--sfadmin` 문제 해결을 위해 NetApp 지원 노드에 액세스할 수 있습니다.
+
[listing]
----
sh /sf/bin/SignSshKeys.sh --ip 192.168.0.1 --user admin --duration 2 --sfadmin
----
.. 명령을 실행합니다.


. 노드 IP에 SSH를 실행합니다.
+
[listing]
----
ssh -i user sfadmin@[node_ip]
----
. 원격 지원 터널을 닫으려면 다음을 입력하세요.
+
`rst --killall`

. (선택 사항) 비활성화link:task_mnode_ssh_management.html["원격 액세스 기능"] 문제 해결이 완료된 후에 다시 시도하세요.
+

NOTE: SSH를 비활성화하지 않으면 관리 노드에서 SSH가 활성화된 상태로 유지됩니다.  SSH가 활성화된 구성은 수동으로 비활성화할 때까지 업데이트 및 업그레이드를 통해 관리 노드에 유지됩니다.





== 클러스터에 속하지 않는 노드 문제 해결

아직 클러스터에 추가되지 않은 노드의 기본적인 문제 해결을 수행할 수 있습니다.  NetApp 지원팀의 도움 여부와 관계없이 sfreadonly 시스템 계정을 이 목적으로 사용할 수 있습니다.  관리 노드가 설정되어 있으면 이를 SSH에 사용하고 이 작업을 위해 제공된 스크립트를 실행할 수 있습니다.

. SSH 클라이언트가 설치된 Windows, Linux 또는 Mac 컴퓨터에서 NetApp 지원팀에서 제공한 시스템에 적합한 스크립트를 실행합니다.
. 노드 IP에 SSH를 실행합니다.
+
[listing]
----
ssh -i user sfreadonly@[node_ip]
----
. (선택 사항) 비활성화link:task_mnode_ssh_management.html["원격 액세스 기능"] 문제 해결이 완료된 후에 다시 시도하세요.
+

NOTE: SSH를 비활성화하지 않으면 관리 노드에서 SSH가 활성화된 상태로 유지됩니다.  SSH가 활성화된 구성은 수동으로 비활성화할 때까지 업데이트 및 업그레이드를 통해 관리 노드에 유지됩니다.



[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]
* https://docs.netapp.com/us-en/hci/index.html["NetApp HCI 문서"^]

