---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: 시스템의 저장 리소스를 관리하고 액세스를 제공하려면 시스템 리소스에 대한 계정을 설정해야 합니다. 
---
= 계정 및 권한
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템의 저장 리소스를 관리하고 액세스를 제공하려면 시스템 리소스에 대한 계정을 설정해야 합니다.

Element 저장소를 사용하면 다음 유형의 계정을 만들고 관리할 수 있습니다.

* <<스토리지 클러스터 관리자 계정,스토리지 클러스터의 관리자 사용자 계정>>
* <<사용자 계정,저장소 볼륨 액세스를 위한 사용자 계정>>
* <<권한 있는 클러스터 사용자 계정,NetApp Hybrid Cloud Control에 대한 권한 있는 클러스터 사용자 계정>>




== 스토리지 클러스터 관리자 계정

NetApp Element 소프트웨어를 실행하는 스토리지 클러스터에는 두 가지 유형의 관리자 계정이 있을 수 있습니다.

* *기본 클러스터 관리자 계정*: 이 관리자 계정은 클러스터가 생성될 때 생성됩니다.  이 계정은 클러스터에 대한 가장 높은 수준의 액세스 권한을 가진 기본 관리 계정입니다.  이 계정은 Linux 시스템의 루트 사용자와 유사합니다.  이 관리자 계정의 비밀번호를 변경할 수 있습니다.
* *클러스터 관리자 계정*: 클러스터 관리자 계정에 클러스터 내에서 특정 작업을 수행하기 위한 제한된 범위의 관리 액세스 권한을 부여할 수 있습니다.  각 클러스터 관리자 계정에 할당된 자격 증명은 스토리지 시스템 내에서 API 및 Element UI 요청을 인증하는 데 사용됩니다.



NOTE: 노드별 UI를 통해 클러스터의 활성 노드에 액세스하려면 로컬(비 LDAP) 클러스터 관리자 계정이 필요합니다.  아직 클러스터에 속하지 않은 노드에 액세스하는 데는 계정 자격 증명이 필요하지 않습니다.

당신은 할 수 있습니다link:../storage/concept_system_manage_manage_cluster_administrator_users.html["클러스터 관리자 계정 관리"] 클러스터 관리자 계정을 생성, 삭제, 편집하고, 클러스터 관리자 비밀번호를 변경하고, LDAP 설정을 구성하여 사용자의 시스템 액세스를 관리합니다.



== 사용자 계정

사용자 계정은 NetApp Element 소프트웨어 기반 네트워크의 스토리지 리소스에 대한 액세스를 제어하는 ​​데 사용됩니다.  볼륨을 생성하려면 최소한 하나의 사용자 계정이 필요합니다.

볼륨을 생성하면 볼륨이 계정에 할당됩니다.  가상 볼륨을 생성한 경우 해당 계정이 스토리지 컨테이너입니다.

다음은 몇 가지 추가 고려 사항입니다.

* 계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP 인증이 포함되어 있습니다.
* 한 계정에는 최대 2000개의 볼륨을 할당할 수 있지만, 볼륨은 한 계정에만 속할 수 있습니다.
* 사용자 계정은 NetApp Element Management 확장 지점에서 관리할 수 있습니다.




== 권한 있는 클러스터 사용자 계정

권한 있는 클러스터 사용자 계정은 NetApp Hybrid Cloud Control 노드 및 클러스터 인스턴스와 연결된 모든 스토리지 자산에 대해 인증할 수 있습니다.  이 계정을 사용하면 모든 클러스터에서 볼륨, 계정, 액세스 그룹 등을 관리할 수 있습니다.

권한이 있는 사용자 계정은 NetApp Hybrid Cloud Control의 오른쪽 상단 메뉴인 사용자 관리 옵션에서 관리됩니다.

그만큼link:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["권한 있는 스토리지 클러스터"] NetApp Hybrid Cloud Control이 사용자를 인증하는 데 사용하는 스토리지 클러스터입니다.

권한 있는 스토리지 클러스터에서 생성된 모든 사용자는 NetApp Hybrid Cloud Control에 로그인할 수 있습니다.  다른 스토리지 클러스터에서 생성된 사용자는 Hybrid Cloud Control에 로그인할 수 없습니다.

* 관리 노드에 스토리지 클러스터가 하나만 있는 경우 해당 클러스터가 권한 클러스터입니다.
* 관리 노드에 두 개 이상의 스토리지 클러스터가 있는 경우 해당 클러스터 중 하나가 권한 있는 클러스터로 지정되고 해당 클러스터의 사용자만 NetApp Hybrid Cloud Control에 로그인할 수 있습니다.


많은 NetApp Hybrid Cloud Control 기능이 여러 스토리지 클러스터에서 작동하지만 인증 및 권한 부여에는 불가피한 제한이 있습니다.  인증 및 권한 부여와 관련된 제한은 권한이 있는 클러스터의 사용자가 다른 스토리지 클러스터의 사용자가 아니더라도 NetApp Hybrid Cloud Control에 연결된 다른 클러스터에서 작업을 실행할 수 있다는 것입니다.  여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다.  NetApp Hybrid Cloud Control에서 사용자를 관리할 수 있습니다.



== 볼륨 계정

볼륨별 계정은 해당 계정이 생성된 스토리지 클러스터에만 적용됩니다.  이러한 계정을 사용하면 네트워크 전반의 특정 볼륨에 대한 권한을 설정할 수 있지만 해당 볼륨 외부에는 아무런 영향도 미치지 않습니다.

볼륨 계정은 NetApp Hybrid Cloud Control Volumes 테이블 내에서 관리됩니다.
