---
permalink: concepts/concept_solidfire_concepts_security.html 
sidebar: sidebar 
keywords: solidfire security, element security, encryption at rest, software encryption at rest, external key management, fips 140-2, mfa 
summary: NetApp Element 소프트웨어를 사용하면 업계 표준 보안 프로토콜을 통해 데이터가 보호됩니다. 
---
= 보안
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 올플래시 스토리지 시스템을 사용하면 데이터는 업계 표준 보안 프로토콜로 보호됩니다.



== 휴면 암호화(하드웨어)

저장 노드의 모든 드라이브는 드라이브 수준에서 AES 256비트 암호화를 활용하여 암호화할 수 있습니다.  각 드라이브에는 고유한 암호화 키가 있으며, 이 키는 드라이브가 처음 초기화될 때 생성됩니다.  암호화 기능을 활성화하면 클러스터 전체 암호가 생성되고 암호 일부가 클러스터의 모든 노드에 배포됩니다.  어떤 단일 노드도 전체 비밀번호를 저장하지 않습니다.  이 비밀번호는 드라이브에 대한 모든 액세스를 비밀번호로 보호하는 데 사용됩니다.  비밀번호는 드라이브 잠금을 해제하는 데 필요하며, 드라이브의 전원을 끄거나 드라이브가 잠겨 있지 않는 한 필요하지 않습니다.

link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["휴면 상태의 하드웨어 암호화 기능 활성화"^]클러스터의 성능이나 효율성에 영향을 미치지 않습니다.  Element API 또는 Element UI를 사용하여 암호화가 활성화된 드라이브나 노드를 클러스터 구성에서 제거하면 해당 드라이브에서 저장 데이터 암호화가 비활성화됩니다.  드라이브를 제거한 후에는 다음을 사용하여 드라이브를 안전하게 지울 수 있습니다. `SecureEraseDrives` API 방식.  물리적 드라이브나 노드가 강제로 제거된 경우에도 데이터는 클러스터 전체 암호와 드라이브의 개별 암호화 키로 보호됩니다.



== 휴면 암호화(소프트웨어)

저장 중 암호화의 또 다른 유형인 소프트웨어 저장 중 암호화를 사용하면 스토리지 클러스터의 SSD에 기록된 모든 데이터를 암호화할 수 있습니다. link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["활성화 시"^] 소프트웨어에서 자동으로 작성된 모든 데이터를 암호화하고, 읽은 모든 데이터를 복호화합니다.  휴면 상태의 소프트웨어 암호화는 하드웨어에서 SED(자체 암호화 드라이브) 구현을 반영하여 SED가 없는 경우에도 데이터 보안을 제공합니다.


WARNING: SolidFire 올플래시 스토리지 클러스터의 경우, 클러스터 생성 중에 소프트웨어 암호화를 활성화해야 하며 클러스터가 생성된 후에는 비활성화할 수 없습니다.

소프트웨어 기반 암호화와 하드웨어 기반 암호화는 독립적으로 또는 서로 결합하여 사용할 수 있습니다.



== 외부 키 관리

Element 소프트웨어를 구성하여 타사 KMIP 호환 키 관리 서비스(KMS)를 사용하여 스토리지 클러스터 암호화 키를 관리할 수 있습니다.  이 기능을 활성화하면 스토리지 클러스터의 클러스터 전체 드라이브 액세스 암호 암호화 키가 사용자가 지정한 KMS에서 관리됩니다.

Element는 다음과 같은 키 관리 서비스를 사용할 수 있습니다.

* Gemalto SafeNet KeySecure
* 세이프넷 AT 키시큐어
* 하이트러스트 키컨트롤
* Vormetric 데이터 보안 관리자
* IBM 보안 키 라이프사이클 관리자


외부 키 관리 구성에 대한 자세한 내용은 다음을 참조하세요.link:../storage/concept_system_manage_key_get_started_with_external_key_management.html["외부 키 관리 시작하기"] 선적 서류 비치.



== 다중 요소 인증

다중 요소 인증(MFA)을 사용하면 사용자가 로그인할 때 NetApp Element 웹 UI 또는 스토리지 노드 UI에서 인증을 받기 위해 여러 유형의 증거를 제시하도록 요구할 수 있습니다.  기존 사용자 관리 시스템 및 ID 공급자와 통합하여 Element를 구성하여 로그인에 대해 다중 요소 인증만 허용할 수 있습니다.  Element를 기존 SAML 2.0 ID 공급자와 통합하도록 구성하면 비밀번호와 문자 메시지, 비밀번호와 이메일 메시지 또는 기타 방법과 같은 여러 인증 체계를 적용할 수 있습니다.

Microsoft Active Directory Federation Services(ADFS) 및 Shibboleth와 같은 일반적인 SAML 2.0 호환 ID 공급자(IdP)와 다중 요소 인증을 함께 사용할 수 있습니다.

MFA를 구성하려면 다음을 참조하세요. link:../storage/task_system_manage_mfa_set_up_multi_factor_authentication.html["다중 요소 인증을 활성화합니다"] 선적 서류 비치.



== HTTPS 및 저장 데이터 암호화를 위한 FIPS 140-2

NetApp SolidFire 스토리지 클러스터는 암호화 모듈에 대한 FIPS(연방 정보 처리 표준) 140-2 요구 사항을 준수하는 암호화를 지원합니다.  SolidFire 클러스터에서 HTTPS 통신과 드라이브 암호화 모두에 대해 FIPS 140-2 규정 준수를 활성화할 수 있습니다.

클러스터에서 FIPS 140-2 운영 모드를 활성화하면 클러스터에서 NetApp 암호화 보안 모듈(NCSM)이 활성화되고 HTTPS를 통해 NetApp Element UI 및 API에 대한 모든 통신에 FIPS 140-2 레벨 1 인증 암호화가 활용됩니다.  당신은 사용합니다 `EnableFeature` Element API를 사용하여 `fips` FIPS 140-2 HTTPS 암호화를 활성화하는 매개변수입니다.  FIPS 호환 하드웨어가 있는 스토리지 클러스터에서는 다음을 사용하여 저장 중인 데이터에 대한 FIPS 드라이브 암호화를 활성화할 수도 있습니다. `EnableFeature` Element API를 사용하여 `FipsDrives` 매개변수.

FIPS 140-2 암호화를 위한 새 스토리지 클러스터 준비에 대한 자세한 내용은 다음을 참조하세요.link:../storage/task_system_manage_fips_create_a_cluster_supporting_fips_drives.html["FIPS 드라이브를 지원하는 클러스터 만들기"] .

기존의 준비된 클러스터에서 FIPS 140-2를 활성화하는 방법에 대한 자세한 내용은 다음을 참조하세요.link:../api/reference_element_api_enablefeature.html["EnableFeature 요소 API"] .



== 더 많은 정보를 원하시면

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

