---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: 데이터 보호 기능에는 원격 복제, 볼륨 스냅샷, 볼륨 복제, 보호 도메인, 이중 나선 기술을 통한 고가용성 등이 포함됩니다. 
---
= 데이터 보호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 기능에는 원격 복제, 볼륨 스냅샷, 볼륨 복제, 보호 도메인, 이중 나선 기술을 통한 고가용성 등이 포함됩니다.

요소 저장 데이터 보호에는 다음과 같은 개념이 포함됩니다.

* <<원격 복제 유형>>
* <<데이터 보호를 위한 볼륨 스냅샷>>
* <<볼륨 클론>>
* <<Element 저장소에 대한 백업 및 복원 프로세스 개요>>
* <<보호 도메인>>
* <<custom_pd,사용자 정의 보호 도메인>>
* <<Double Helix 고가용성>>




== 원격 복제 유형

데이터의 원격 복제는 다음과 같은 형태를 취할 수 있습니다.

* <<클러스터 간 동기 및 비동기 복제>>
* <<스냅샷 전용 복제>>
* <<SnapMirror 사용한 Element와 ONTAP 클러스터 간 복제>>


자세한 내용은 다음을 참조하세요. https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741: NetApp Element 소프트웨어 원격 복제"^] .



=== 클러스터 간 동기 및 비동기 복제

NetApp Element 소프트웨어를 실행하는 클러스터의 경우 실시간 복제를 통해 볼륨 데이터의 원격 복사본을 빠르게 생성할 수 있습니다.

최대 4개의 다른 스토리지 클러스터와 스토리지 클러스터를 페어링할 수 있습니다.  장애 조치 및 장애 복구 시나리오를 위해 클러스터 쌍의 어느 클러스터에서든 동기식 또는 비동기식으로 볼륨 데이터를 복제할 수 있습니다.



==== 동기 복제

동기 복제는 소스 클러스터에서 대상 클러스터로 데이터를 지속적으로 복제하며 지연 시간, 패킷 손실, 지터, 대역폭의 영향을 받습니다.

동기 복제는 다음과 같은 상황에 적합합니다.

* 짧은 거리에 걸쳐 여러 시스템 복제
* 출처와 지리적으로 가까운 재해 복구 사이트
* 시간에 민감한 애플리케이션 및 데이터베이스 보호
* 기본 사이트가 다운되었을 때 보조 사이트가 기본 사이트 역할을 해야 하는 비즈니스 연속성 애플리케이션




==== 비동기 복제

비동기 복제는 대상 클러스터의 확인을 기다리지 않고 소스 클러스터에서 대상 클러스터로 데이터를 지속적으로 복제합니다.  비동기 복제 중에 쓰기는 소스 클러스터에서 커밋된 후 클라이언트(애플리케이션)에 확인됩니다.

비동기 복제는 다음과 같은 상황에 적합합니다.

* 재해 복구 사이트가 소스와 멀리 떨어져 있으며, 애플리케이션이 네트워크로 인해 발생하는 지연을 허용하지 않습니다.
* 소스 클러스터와 대상 클러스터를 연결하는 네트워크에는 대역폭 제한이 있습니다.




=== 스냅샷 전용 복제

스냅샷 전용 데이터 보호는 특정 시점에 변경된 데이터를 원격 클러스터에 복제합니다.  소스 클러스터에서 생성된 스냅샷만 복제됩니다.  소스 볼륨의 활성 쓰기는 그렇지 않습니다.

스냅샷 복제 빈도를 설정할 수 있습니다.

스냅샷 복제는 비동기 또는 동기 복제에 영향을 미치지 않습니다.



=== SnapMirror 사용한 Element와 ONTAP 클러스터 간 복제

NetApp SnapMirror 기술을 사용하면 NetApp Element 소프트웨어를 사용하여 촬영한 스냅샷을 재해 복구 목적으로 ONTAP 에 복제할 수 있습니다.  SnapMirror 관계에서 Element는 한 엔드포인트이고 ONTAP 다른 엔드포인트입니다.

SnapMirror 는 재해 복구를 용이하게 하는 NetApp 스냅샷 복제 기술로, 지리적으로 멀리 떨어진 사이트의 기본 스토리지에서 보조 스토리지로 장애 조치를 수행하도록 설계되었습니다.  SnapMirror 기술은 기본 사이트에 장애가 발생하더라도 보조 저장소에 작업 데이터의 복제본 또는 미러를 생성하여 이를 통해 데이터를 계속 제공할 수 있습니다.  데이터는 볼륨 수준에서 미러링됩니다.

기본 저장소의 소스 볼륨과 보조 저장소의 대상 볼륨 간의 관계를 데이터 보호 관계라고 합니다.  클러스터는 볼륨이 상주하는 엔드포인트라고 하며 복제된 데이터가 포함된 볼륨은 피어링되어야 합니다.  피어 관계를 통해 클러스터와 볼륨이 안전하게 데이터를 교환할 수 있습니다.

SnapMirror NetApp ONTAP 컨트롤러에서 기본적으로 실행되며 NetApp HCI 및 SolidFire 클러스터에서 실행되는 Element에 통합되어 있습니다.  SnapMirror 제어하는 ​​논리는 ONTAP 소프트웨어에 있습니다. 따라서 모든 SnapMirror 관계에는 조정 작업을 수행하기 위해 최소한 하나의 ONTAP 시스템이 포함되어야 합니다.  사용자는 주로 Element UI를 통해 Element와 ONTAP 클러스터 간의 관계를 관리합니다. 하지만 일부 관리 작업은 NetApp ONTAP System Manager에 있습니다.  사용자는 ONTAP 과 Element에서 모두 사용 가능한 CLI와 API를 통해 SnapMirror 관리할 수도 있습니다.

보다 https://fieldportal.netapp.com/content/616239["TR-4651: NetApp SolidFire SnapMirror 아키텍처 및 구성"^] (로그인 필요)

Element 소프트웨어를 사용하여 클러스터 수준에서 SnapMirror 기능을 수동으로 활성화해야 합니다.  SnapMirror 기능은 기본적으로 비활성화되어 있으며, 새로 설치하거나 업그레이드해도 자동으로 활성화되지 않습니다.

SnapMirror 활성화한 후 Element 소프트웨어의 데이터 보호 탭에서 SnapMirror 관계를 만들 수 있습니다.

NetApp Element 소프트웨어 10.1 이상은 ONTAP 시스템에서 스냅샷을 복사하고 복원하는 SnapMirror 기능을 지원합니다.

Element 10.1 이상을 실행하는 시스템에는 9.3 이상을 실행하는 ONTAP 시스템의 SnapMirror 와 직접 통신할 수 있는 코드가 포함되어 있습니다.  Element API는 클러스터, 볼륨 및 스냅샷에서 SnapMirror 기능을 활성화하는 방법을 제공합니다.  또한 Element UI에는 Element 소프트웨어와 ONTAP 시스템 간의 SnapMirror 관계를 관리하는 기능이 포함되어 있습니다.

Element 10.3 및 ONTAP 9.4 시스템부터 제한된 기능으로 특정 사용 사례에서 ONTAP 생성된 볼륨을 Element 볼륨으로 복제할 수 있습니다.

자세한 내용은 다음을 참조하세요. link:../storage/element-replication-index.html["NetApp Element 소프트웨어와 ONTAP 간 복제(ONTAP CLI)"].



== 데이터 보호를 위한 볼륨 스냅샷

볼륨 스냅샷은 나중에 볼륨을 특정 시간으로 복원하는 데 사용할 수 있는 볼륨의 특정 시점 복사본입니다.

스냅샷은 볼륨 복제본과 유사하지만, 볼륨 메타데이터의 복제본일 뿐이므로 마운트하거나 쓸 수 없습니다.  볼륨 스냅샷을 만드는 데는 시스템 리소스와 공간도 적게 사용되므로 복제보다 스냅샷을 만드는 속도가 더 빠릅니다.

스냅샷을 원격 클러스터에 복제하여 볼륨의 백업 사본으로 사용할 수 있습니다.  이를 통해 복제된 스냅샷을 사용하여 볼륨을 특정 시점으로 롤백할 수 있습니다. 또한 복제된 스냅샷에서 볼륨의 복제본을 생성할 수도 있습니다.

Element 클러스터의 스냅샷을 외부 개체 저장소나 다른 Element 클러스터로 백업할 수 있습니다.  스냅샷을 외부 개체 저장소에 백업하는 경우 읽기/쓰기 작업을 허용하는 개체 저장소에 대한 연결이 있어야 합니다.

개별 볼륨이나 여러 볼륨의 스냅샷을 찍어서 데이터를 보호할 수 있습니다.



== 볼륨 클론

단일 볼륨 또는 여러 볼륨의 복제본은 데이터의 특정 시점 복사본입니다.  볼륨을 복제하면 시스템은 볼륨의 스냅샷을 만든 다음 스냅샷에서 참조하는 데이터의 복사본을 만듭니다.

이는 비동기 프로세스이며, 프로세스에 필요한 시간은 복제하는 볼륨의 크기와 현재 클러스터 부하에 따라 달라집니다.

클러스터는 볼륨당 동시에 최대 2개의 실행 중인 복제 요청을 지원하고, 동시에 최대 8개의 활성 볼륨 복제 작업을 지원합니다.  이러한 제한을 초과하는 요청은 나중에 처리하기 위해 대기합니다.



== Element 저장소에 대한 백업 및 복원 프로세스 개요

Amazon S3 또는 OpenStack Swift와 호환되는 보조 객체 저장소뿐만 아니라 다른 SolidFire 스토리지에도 볼륨을 백업하고 복원할 수 있습니다.

다음 위치에 볼륨을 백업할 수 있습니다.

* SolidFire 스토리지 클러스터
* Amazon S3 객체 저장소
* OpenStack Swift 객체 저장소


OpenStack Swift 또는 Amazon S3에서 볼륨을 복원하는 경우 원래 백업 프로세스의 매니페스트 정보가 필요합니다.  SolidFire 스토리지 시스템에 백업된 볼륨을 복원하는 경우 매니페스트 정보가 필요하지 않습니다.



== 보호 도메인

보호 도메인은 일부 또는 전체가 실패하더라도 데이터 가용성을 유지할 수 있도록 그룹화된 노드 또는 노드 집합입니다.  보호 도메인을 사용하면 스토리지 클러스터가 섀시(섀시 친화성) 또는 전체 도메인(섀시 그룹) 손실로부터 자동으로 복구될 수 있습니다.

vCenter Server용 NetApp Element 플러그인의 NetApp Element 구성 확장 지점을 사용하여 보호 도메인 모니터링을 수동으로 활성화할 수 있습니다.  노드 또는 섀시 도메인을 기반으로 보호 도메인 임계값을 선택할 수 있습니다.  Element API나 웹 UI를 사용하여 보호 도메인 모니터링을 활성화할 수도 있습니다.

보호 도메인 레이아웃은 각 노드를 특정 보호 도메인에 할당합니다.

보호 도메인 수준이라고 하는 두 가지 보호 도메인 레이아웃이 지원됩니다.

* 노드 수준에서 각 노드는 자체 보호 도메인에 있습니다.
* 섀시 수준에서는 섀시를 공유하는 노드만 동일한 보호 도메인에 있습니다.
+
** 노드가 클러스터에 추가되면 섀시 수준 레이아웃이 하드웨어에서 자동으로 결정됩니다.
** 각 노드가 별도의 섀시에 있는 클러스터에서는 이 두 수준이 기능적으로 동일합니다.




새 클러스터를 생성할 때 공유 섀시에 있는 스토리지 노드를 사용하는 경우 보호 도메인 기능을 사용하여 섀시 수준 장애 보호를 설계하는 것이 좋습니다.



== [[custom_pd]]사용자 정의 보호 도메인

사용자의 특정 섀시 및 노드 레이아웃에 맞는 사용자 정의 보호 도메인 레이아웃을 정의할 수 있으며, 각 노드는 단 하나의 사용자 정의 보호 도메인에만 연결됩니다.  기본적으로 각 노드는 동일한 기본 사용자 지정 보호 도메인에 할당됩니다.

사용자 지정 보호 도메인이 할당되지 않은 경우:

* 클러스터 작동에는 영향을 미치지 않습니다.
* 사용자 정의 수준은 관용적이지도 않고 회복력도 없습니다.


클러스터에 대한 사용자 지정 보호 도메인을 구성하는 경우 Element 웹 UI 대시보드에서 확인할 수 있는 세 가지 보호 수준이 있습니다.

* 보호되지 않음: 스토리지 클러스터가 사용자 지정 보호 도메인 중 하나의 장애로부터 보호되지 않습니다.  이 문제를 해결하려면 클러스터에 추가 저장 용량을 추가하거나 클러스터의 사용자 지정 보호 도메인을 재구성하여 클러스터를 잠재적인 데이터 손실로부터 보호하세요.
* 장애 허용: 스토리지 클러스터에는 사용자 지정 보호 도메인 중 하나에 장애가 발생한 후에도 데이터 손실을 방지할 수 있을 만큼 충분한 여유 용량이 있습니다.
* 장애 복구력: 스토리지 클러스터는 사용자 지정 보호 도메인 중 하나에 장애가 발생한 후에도 자체 복구를 수행할 수 있는 충분한 여유 용량을 확보합니다.  치료 과정이 완료되면 추가 도메인에 장애가 발생하더라도 클러스터는 데이터 손실로부터 보호됩니다.


두 개 이상의 사용자 정의 보호 도메인이 할당된 경우 각 하위 시스템은 중복된 보호 도메인을 별도의 사용자 정의 보호 도메인에 할당합니다.  이것이 가능하지 않으면 중복된 항목을 별도의 노드에 할당하게 됩니다.  각 하위 시스템(예: 빈, 슬라이스, 프로토콜 엔드포인트 공급자, 앙상블)은 이를 독립적으로 수행합니다.

Element UI를 사용하여 다음을 수행할 수 있습니다.link:../storage/task_data_protection_configure_custom_protection_domains.html["사용자 정의 보호 도메인 구성"] 또는 다음 API 메서드를 사용할 수 있습니다.

* link:../api/reference_element_api_getprotectiondomainlayout.html["보호 도메인 레이아웃 가져오기"]- 각 노드가 속한 섀시와 사용자 정의 보호 도메인을 표시합니다.
* link:../api/reference_element_api_setprotectiondomainlayout.html["보호 도메인 레이아웃 설정"]- 각 노드에 사용자 정의 보호 도메인을 할당할 수 있습니다.




== Double Helix 고가용성

Double Helix 데이터 보호는 시스템 내의 모든 드라이브에 최소 두 개의 중복된 데이터 사본을 분산시키는 복제 방법입니다.  "RAID-less" 방식을 사용하면 시스템이 스토리지 시스템의 모든 수준에서 동시에 발생하는 여러 가지 오류를 흡수하고 신속하게 복구할 수 있습니다.
