---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 클러스터는 SolidFire 스토리지 시스템의 허브이며 여러 노드로 구성됩니다.  SolidFire 스토리지 효율성을 실현하려면 클러스터에 최소 4개의 노드가 있어야 합니다.  클러스터는 네트워크에 단일 논리적 그룹으로 나타나며 블록 스토리지로 액세스할 수 있습니다. 
---
= 클러스터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터는 SolidFire 스토리지 시스템의 허브이며 여러 노드로 구성됩니다.  SolidFire 스토리지 효율성을 실현하려면 클러스터에 최소 4개의 노드가 있어야 합니다.  클러스터는 네트워크에 단일 논리적 그룹으로 나타나며 블록 스토리지로 액세스할 수 있습니다.

새로운 클러스터를 생성하면 클러스터의 통신 소유자로 노드가 초기화되고 클러스터의 각 노드에 대한 네트워크 통신이 설정됩니다.  이 프로세스는 새로운 클러스터마다 한 번씩만 수행됩니다.  Element UI나 API를 사용하여 클러스터를 만들 수 있습니다.

추가 노드를 추가하여 클러스터를 확장할 수 있습니다.  새로운 노드를 추가하면 서비스가 중단되지 않으며 클러스터는 자동으로 새 노드의 성능과 용량을 사용합니다.

관리자와 호스트는 가상 IP 주소를 사용하여 클러스터에 액세스할 수 있습니다.  클러스터의 모든 노드는 가상 IP 주소를 호스팅할 수 있습니다.  관리 가상 IP(MVIP)는 1GbE 연결을 통해 클러스터 관리를 가능하게 하고, 스토리지 가상 IP(SVIP)는 10GbE 연결을 통해 호스트가 스토리지에 액세스할 수 있도록 합니다.  이러한 가상 IP 주소를 사용하면 SolidFire 클러스터의 크기나 구성에 관계없이 일관된 연결이 가능합니다.  가상 IP 주소를 호스팅하는 노드에 장애가 발생하면 클러스터의 다른 노드가 가상 IP 주소를 호스팅하기 시작합니다.


NOTE: Element 버전 11.0부터 노드는 관리 네트워크에 IPv4, IPv6 또는 두 주소 모두를 사용하여 구성할 수 있습니다.  이는 IPv6를 지원하지 않는 관리 노드 11.3 이상을 제외하고 저장 노드와 관리 노드 모두에 적용됩니다.  클러스터를 생성할 때 MVIP에는 단일 IPv4 또는 IPv6 주소만 사용할 수 있으며 모든 노드에서 해당 주소 유형을 구성해야 합니다.

.클러스터에 대한 추가 정보
* <<권한 있는 스토리지 클러스터>>
* <<삼분법>>
* <<좌초 용량>>
* <<스토리지 효율성>>
* <<스토리지 클러스터 쿼럼>>




== 권한 있는 스토리지 클러스터

권한 있는 스토리지 클러스터는 NetApp Hybrid Cloud Control이 사용자를 인증하는 데 사용하는 스토리지 클러스터입니다.

관리 노드에 스토리지 클러스터가 하나만 있는 경우 해당 클러스터가 권한 클러스터입니다.  관리 노드에 두 개 이상의 스토리지 클러스터가 있는 경우 해당 클러스터 중 하나가 권한 있는 클러스터로 지정되고 해당 클러스터의 사용자만 NetApp Hybrid Cloud Control에 로그인할 수 있습니다.  어떤 클러스터가 권위 있는 클러스터인지 알아내려면 다음을 사용할 수 있습니다. `GET /mnode/about` API.  응답에서 IP 주소는 `token_url` 필드는 권한 있는 스토리지 클러스터의 관리 가상 IP 주소(MVIP)입니다.  권한이 있는 클러스터에 없는 사용자로 NetApp Hybrid Cloud Control에 로그인을 시도하면 로그인 시도가 실패합니다.

NetApp Hybrid Cloud Control 기능 중 다수는 여러 스토리지 클러스터에서 작동하도록 설계되었지만 인증 및 권한 부여에는 제한이 있습니다.  인증 및 권한 부여와 관련된 제한은 권한이 있는 클러스터의 사용자가 다른 스토리지 클러스터의 사용자가 아니더라도 NetApp Hybrid Cloud Control에 연결된 다른 클러스터에서 작업을 실행할 수 있다는 것입니다.

여러 스토리지 클러스터를 관리하기 전에 권한 있는 클러스터에 정의된 사용자가 동일한 권한을 가진 다른 모든 스토리지 클러스터에 정의되어 있는지 확인해야 합니다.  사용자를 관리할 수 있습니다.link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element 소프트웨어 사용자 인터페이스"] .

보다link:../mnode/task_mnode_manage_storage_cluster_assets.html["스토리지 클러스터 자산을 생성하고 관리합니다."] 관리 노드 스토리지 클러스터 자산 작업에 대한 자세한 내용은 다음을 참조하세요.



== 삼분법

NetApp SolidFire 스토리지 클러스터에서 스토리지 노드 유형을 혼합하는 경우 단일 스토리지 노드는 전체 스토리지 클러스터 용량의 33% 이상을 포함할 수 없습니다.



== 좌초 용량

새로 추가된 노드가 전체 클러스터 용량의 50% 이상을 차지하는 경우, 해당 노드의 일부 용량은 사용할 수 없게 됩니다("고착"). 이는 용량 규칙을 준수하기 위한 조치입니다.  더 많은 저장 용량이 추가될 때까지 이는 그대로 유지됩니다.  용량 규칙을 위반하는 매우 큰 노드가 추가되면 이전에 고립되었던 노드는 더 이상 고립되지 않지만 새로 추가된 노드는 고립됩니다.  이런 일이 발생하지 않도록 용량은 항상 쌍으로 추가해야 합니다.  노드가 고립되면 적절한 클러스터 오류가 발생합니다.



== 스토리지 효율성

Netapp SolidFire 스토리지 클러스터는 중복 제거, 압축 및 씬 프로비저닝을 활용하여 볼륨을 저장하는 데 필요한 물리적 스토리지 양을 줄입니다.

* *압축*
+
압축은 데이터 블록을 압축 그룹으로 결합하여 볼륨에 필요한 물리적 저장 공간의 양을 줄입니다. 각 압축 그룹은 단일 블록으로 저장됩니다.

* *중복 제거*
+
중복 제거는 중복된 데이터 블록을 삭제하여 볼륨에 필요한 물리적 저장 공간의 양을 줄입니다.

* *씬 프로비저닝*
+
씬 프로비저닝 볼륨 또는 LUN은 저장소가 사전에 예약되지 않은 볼륨입니다.  대신, 저장소는 필요에 따라 동적으로 할당됩니다.  볼륨 또는 LUN의 데이터가 삭제되면 여유 공간이 스토리지 시스템으로 다시 해제됩니다.





== 스토리지 클러스터 쿼럼

Element 소프트웨어는 선택된 노드에서 스토리지 클러스터를 생성하고, 이를 통해 클러스터 구성의 복제된 데이터베이스를 유지 관리합니다.  클러스터 복원력을 위한 쿼럼을 유지하려면 클러스터 앙상블에 참여해야 하며 최소 3개의 노드가 필요합니다.
