---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: '메타데이터 드라이브 하나 또는 둘 다 실패한 경우 클러스터에 다시 추가하여 메타데이터 드라이브(또는 슬라이스 드라이브)를 복구할 수 있습니다.  노드에서 MDSS 기능이 이미 활성화된 경우 NetApp Element UI에서 복구 작업을 수행할 수 있습니다.' 
---
= 기본 MDSS 드라이브 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
하나 또는 두 개의 메타데이터 드라이브가 모두 실패한 경우 클러스터에 다시 추가하여 메타데이터(또는 슬라이스) 드라이브를 복구할 수 있습니다.  노드에서 MDSS 기능이 이미 활성화된 경우 NetApp Element UI에서 복구 작업을 수행할 수 있습니다.

노드의 메타데이터 드라이브 중 하나 또는 둘 다에 장애가 발생하면 슬라이스 서비스가 종료되고 두 드라이브의 데이터가 노드의 다른 드라이브에 백업됩니다.

다음 시나리오에서는 가능한 실패 시나리오를 간략하게 설명하고 문제를 해결하기 위한 기본적인 권장 사항을 제공합니다.



== 시스템 슬라이스 드라이브가 실패했습니다

* 이 시나리오에서는 슬롯 2가 검증되어 사용 가능한 상태로 돌아갑니다.
* 슬라이스 서비스를 다시 온라인으로 전환하려면 먼저 시스템 슬라이스 드라이브를 다시 채워야 합니다.
* 시스템 슬라이스 드라이브를 교체해야 합니다. 시스템 슬라이스 드라이브를 사용할 수 있게 되면 드라이브와 슬롯 2 드라이브를 동시에 추가하세요.



NOTE: 슬롯 2에 드라이브 자체를 메타데이터 드라이브로 추가할 수 없습니다.  두 드라이브를 동시에 노드에 다시 추가해야 합니다.



== 슬롯 2가 실패합니다

* 이 시나리오에서는 시스템 슬라이스 드라이브가 검증되고 사용 가능한 상태로 돌아갑니다.
* 슬롯 2를 예비 드라이브로 교체하고, 슬롯 2가 사용 가능해지면 시스템 슬라이스 드라이브와 슬롯 2 드라이브를 동시에 추가하세요.




== 시스템 슬라이스 드라이브와 슬롯 2가 실패했습니다.

* 시스템 슬라이스 드라이브와 슬롯 2를 모두 예비 드라이브로 교체해야 합니다.  두 드라이브를 모두 사용할 수 있게 되면 시스템 슬라이스 드라이브와 슬롯 2 드라이브를 동시에 추가합니다.




== 작업 순서

* 고장난 하드웨어 드라이브를 예비 드라이브로 교체합니다(두 드라이브 모두 고장난 경우 두 드라이브를 모두 교체합니다).
* 드라이브가 다시 채워지고 사용 가능한 상태가 되면 클러스터에 다시 추가합니다.




== 작업 확인

* 슬롯 0(또는 내부)과 슬롯 2의 드라이브가 활성 드라이브 목록에서 메타데이터 드라이브로 식별되는지 확인하세요.
* 모든 슬라이스 밸런싱이 완료되었는지 확인합니다(최소 30분 동안 이벤트 로그에 슬라이스 이동 메시지가 더 이상 표시되지 않음).




== 더 많은 정보를 원하시면

xref:task_troubleshoot_add_mdss_drives.adoc[MDSS 드라이브 추가]
