---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: SolidFire 스토리지 시스템의 클러스터 관리자 계정을 관리할 수 있습니다.  사용 가능한 클러스터 관리자 관리 기능에는 클러스터 관리자 계정 생성, 삭제, 편집, 클러스터 관리자 비밀번호 변경, 사용자의 시스템 액세스를 관리하기 위한 LDAP 설정 구성 등이 있습니다. 
---
= 클러스터 관리자 사용자 계정 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 관리자 계정을 생성, 삭제, 편집하고, 클러스터 관리자 비밀번호를 변경하고, 사용자의 시스템 액세스를 관리하기 위한 LDAP 설정을 구성하여 SolidFire 스토리지 시스템의 클러스터 관리자 계정을 관리할 수 있습니다.



== 스토리지 클러스터 관리자 계정 유형

NetApp Element 소프트웨어를 실행하는 스토리지 클러스터에는 두 가지 유형의 관리자 계정이 있습니다. 기본 클러스터 관리자 계정과 클러스터 관리자 계정입니다.

* *기본 클러스터 관리자 계정*
+
이 관리자 계정은 클러스터가 생성될 때 생성됩니다.  이 계정은 클러스터에 대한 가장 높은 수준의 액세스 권한을 가진 기본 관리 계정입니다.  이 계정은 Linux 시스템의 루트 사용자와 유사합니다.  이 관리자 계정의 비밀번호를 변경할 수 있습니다.

* *클러스터 관리자 계정*
+
클러스터 관리자 계정에 클러스터 내에서 특정 작업을 수행하기 위한 제한된 범위의 관리 액세스 권한을 부여할 수 있습니다.  각 클러스터 관리자 계정에 할당된 자격 증명은 스토리지 시스템 내에서 API 및 Element UI 요청을 인증하는 데 사용됩니다.




NOTE: 노드별 UI를 통해 클러스터의 활성 노드에 액세스하려면 로컬(비 LDAP) 클러스터 관리자 계정이 필요합니다.  아직 클러스터에 속하지 않은 노드에 액세스하는 데는 계정 자격 증명이 필요하지 않습니다.



== 클러스터 관리자 세부 정보 보기

. 클러스터 전체(비 LDAP) 클러스터 관리자 계정을 만들려면 다음 작업을 수행하세요.
+
.. *사용자* > *클러스터 관리자*를 클릭합니다.


. 사용자 탭의 클러스터 관리자 페이지에서 다음 정보를 볼 수 있습니다.
+
** *ID*: 클러스터 관리자 계정에 할당된 순차 번호입니다.
** *사용자 이름*: 클러스터 관리자 계정이 생성될 때 지정된 이름입니다.
** *액세스*: 사용자 계정에 할당된 사용자 권한입니다. 가능한 값:
+
*** 읽다
*** 보고
*** 노드
*** 드라이브
*** 볼륨
*** 계정
*** 클러스터 관리자
*** 관리자
*** 지원 관리자




+
[NOTE]
====
모든 권한은 관리자 액세스 유형에만 제공됩니다.

Element UI에서는 사용할 수 없는 API를 통해 사용 가능한 액세스 유형이 있습니다.

====
+
** *유형*: 클러스터 관리자의 유형입니다. 가능한 값:
+
*** 무리
*** LDAP


** *속성*: 클러스터 관리자 계정이 Element API를 사용하여 생성된 경우 이 열에는 해당 방법을 사용하여 설정된 모든 이름-값 쌍이 표시됩니다.
+
보다link:../api/concept_element_api_about_the_api.html["NetApp Element 소프트웨어 API 참조"] .







== 클러스터 관리자 계정 만들기

스토리지 시스템의 특정 영역에 대한 액세스를 허용하거나 제한하는 권한이 있는 새로운 클러스터 관리자 계정을 만들 수 있습니다.  클러스터 관리자 계정 권한을 설정하면 시스템은 클러스터 관리자에게 할당하지 않은 모든 권한에 대해 읽기 전용 권한을 부여합니다.

LDAP 클러스터 관리자 계정을 만들려면 시작하기 전에 클러스터에 LDAP가 구성되어 있는지 확인하세요.

link:concept_system_manage_manage_ldap.html["Element 사용자 인터페이스를 사용하여 LDAP 인증 활성화"]

나중에 보고, 노드, 드라이브, 볼륨, 계정 및 클러스터 수준 액세스에 대한 클러스터 관리자 계정 권한을 변경할 수 있습니다.  권한을 활성화하면 시스템은 해당 수준에 대한 쓰기 액세스 권한을 할당합니다.  시스템은 선택하지 않은 수준에 대해서는 관리자 사용자에게 읽기 전용 액세스 권한을 부여합니다.

나중에 시스템 관리자가 만든 클러스터 관리자 사용자 계정을 제거할 수도 있습니다.  클러스터가 생성될 때 생성된 기본 클러스터 관리자 계정은 제거할 수 없습니다.

. 클러스터 전체(비 LDAP) 클러스터 관리자 계정을 만들려면 다음 작업을 수행하세요.
+
.. *사용자* > *클러스터 관리자*를 클릭합니다.
.. *클러스터 관리자 만들기*를 클릭합니다.
.. *클러스터* 사용자 유형을 선택하세요.
.. 계정의 사용자 이름과 비밀번호를 입력하고 비밀번호를 확인하세요.
.. 계정에 적용할 사용자 권한을 선택합니다.
.. 최종 사용자 라이선스 계약에 동의하려면 확인란을 선택하세요.
.. *클러스터 관리자 만들기*를 클릭합니다.


. LDAP 디렉토리에 클러스터 관리자 계정을 만들려면 다음 작업을 수행하세요.
+
.. *클러스터* > *LDAP*를 클릭합니다.
.. LDAP 인증이 활성화되어 있는지 확인하세요.
.. *사용자 인증 테스트*를 클릭하고 사용자 또는 사용자가 구성원인 그룹 중 하나에 표시되는 고유 이름을 복사하여 나중에 붙여넣을 수 있습니다.
.. *사용자* > *클러스터 관리자*를 클릭합니다.
.. *클러스터 관리자 만들기*를 클릭합니다.
.. LDAP 사용자 유형을 선택하세요.
.. 고유 이름 필드에서 텍스트 상자의 예를 따라 사용자 또는 그룹의 전체 고유 이름을 입력합니다.  또는, 앞서 복사한 고유 이름을 붙여넣으세요.
+
고유 이름이 그룹의 일부인 경우 LDAP 서버에서 해당 그룹의 멤버인 모든 사용자는 이 관리자 계정의 권한을 갖습니다.

+
LDAP 클러스터 관리자 사용자 또는 그룹을 추가하려면 사용자 이름의 일반적인 형식은 "`LDAP:<전체 고유 이름>`"입니다.

.. 계정에 적용할 사용자 권한을 선택합니다.
.. 최종 사용자 라이선스 계약에 동의하려면 확인란을 선택하세요.
.. *클러스터 관리자 만들기*를 클릭합니다.






== 클러스터 관리자 권한 편집

보고, 노드, 드라이브, 볼륨, 계정 및 클러스터 수준 액세스에 대한 클러스터 관리자 계정 권한을 변경할 수 있습니다.  권한을 활성화하면 시스템은 해당 수준에 대한 쓰기 액세스 권한을 할당합니다.  시스템은 선택하지 않은 수준에 대해서는 관리자 사용자에게 읽기 전용 액세스 권한을 부여합니다.

. *사용자* > *클러스터 관리자*를 클릭합니다.
. 편집하려는 클러스터 관리자에 대한 작업 아이콘을 클릭합니다.
. *편집*을 클릭하세요.
. 계정에 적용할 사용자 권한을 선택합니다.
. *변경 사항 저장*을 클릭하세요.




== 클러스터 관리자 계정의 비밀번호 변경

Element UI를 사용하여 클러스터 관리자 비밀번호를 변경할 수 있습니다.

. *사용자* > *클러스터 관리자*를 클릭합니다.
. 편집하려는 클러스터 관리자에 대한 작업 아이콘을 클릭합니다.
. *편집*을 클릭하세요.
. 비밀번호 변경 필드에 새 비밀번호를 입력하고 확인하세요.
. *변경 사항 저장*을 클릭하세요.


.관련 정보
* link:../api/reference_element_api_app_b_access_control.html["Element API에 사용 가능한 액세스 유형에 대해 알아보세요."]
* link:concept_system_manage_manage_ldap.html["Element 사용자 인터페이스를 사용하여 LDAP 인증 활성화"]
* link:concept_system_manage_manage_ldap.html["LDAP 비활성화"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

