---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: 스토리지 컨테이너는 Element 소프트웨어를 실행하는 클러스터에서 생성된 vSphere 데이터스토어 표현입니다. 
---
= 저장 용기 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 컨테이너는 Element 소프트웨어를 실행하는 클러스터에서 생성된 vSphere 데이터스토어 표현입니다.

스토리지 컨테이너는 NetApp Element 계정에 생성되어 연결됩니다.  Element 스토리지에 생성된 스토리지 컨테이너는 vCenter 및 ESXi에서 vSphere 데이터스토어로 표시됩니다.  저장 컨테이너는 Element 저장소에 어떠한 공간도 할당하지 않습니다.  이는 단순히 가상 볼륨을 논리적으로 연결하는 데 사용됩니다.

클러스터당 최대 4개의 저장 컨테이너가 지원됩니다.  VVols 기능을 사용하려면 최소 하나의 저장 컨테이너가 필요합니다.



== 저장 용기를 만드세요

Element UI에서 스토리지 컨테이너를 만들고 vCenter에서 검색할 수 있습니다.  VVol 지원 가상 머신 프로비저닝을 시작하려면 최소한 하나의 스토리지 컨테이너를 만들어야 합니다.

시작하기 전에 클러스터의 Element UI에서 VVols 기능을 활성화하세요.

.단계
. *VVols* > *저장 컨테이너*를 선택합니다.
. *저장 컨테이너 만들기* 버튼을 클릭합니다.
. *새 보관 컨테이너 만들기* 대화 상자에 보관 컨테이너 정보를 입력하세요.
+
.. 저장 컨테이너의 이름을 입력하세요.
.. CHAP에 대한 개시자 및 대상 비밀을 구성합니다.
+

TIP: CHAP 설정 필드를 비워 두면 자동으로 비밀이 생성됩니다.

.. *저장 컨테이너 만들기* 버튼을 클릭하세요.


. 새 저장 컨테이너가 *저장 컨테이너* 하위 탭의 목록에 나타나는지 확인하세요.
+

NOTE: NetApp Element 계정 ID는 자동으로 생성되어 스토리지 컨테이너에 할당되므로 수동으로 계정을 만들 필요가 없습니다.





== 저장 컨테이너 세부 정보 보기

VVols 탭의 스토리지 컨테이너 페이지에서 클러스터의 모든 활성 스토리지 컨테이너에 대한 정보를 볼 수 있습니다.

* *계정 ID*: 스토리지 컨테이너와 연결된 NetApp Element 계정의 ID입니다.
* *이름*: 보관 용기의 이름입니다.
* *상태*: 저장 컨테이너의 상태입니다. 가능한 값:
+
** 활성: 저장 컨테이너가 사용 중입니다.
** 잠김: 보관 용기가 잠겨 있습니다.


* *PE 유형*: 프로토콜 엔드포인트 유형(SCSI는 Element 소프트웨어에서 사용 가능한 유일한 프로토콜입니다).
* *저장 컨테이너 ID*: 가상 볼륨 저장 컨테이너의 UUID입니다.
* *활성 가상 볼륨*: 스토리지 컨테이너와 연결된 활성 가상 볼륨의 수입니다.




== 개별 보관 컨테이너 세부 정보 보기

VVols 탭의 스토리지 컨테이너 페이지에서 개별 스토리지 컨테이너를 선택하면 해당 스토리지 컨테이너에 대한 정보를 볼 수 있습니다.

* *계정 ID*: 스토리지 컨테이너와 연결된 NetApp Element 계정의 ID입니다.
* *이름*: 보관 용기의 이름입니다.
* *상태*: 저장 컨테이너의 상태입니다. 가능한 값:
+
** 활성: 저장 컨테이너가 사용 중입니다.
** 잠김: 보관 용기가 잠겨 있습니다.


* *챕 개시자 비밀*: 개시자를 위한 고유한 CHAP 비밀입니다.
* *Chap Target Secret*: 타겟에 대한 고유한 CHAP 비밀번호입니다.
* *저장 컨테이너 ID*: 가상 볼륨 저장 컨테이너의 UUID입니다.
* *프로토콜 엔드포인트 유형*: 프로토콜 엔드포인트 유형을 나타냅니다(SCSI는 유일하게 사용 가능한 프로토콜입니다).




== 저장 컨테이너 편집

Element UI에서 스토리지 컨테이너 CHAP 인증을 수정할 수 있습니다.

. *VVols* > *저장 컨테이너*를 선택합니다.
. 편집하려는 저장 컨테이너의 *작업* 아이콘을 클릭합니다.
. 나타나는 메뉴에서 *편집*을 선택합니다.
. CHAP 설정에서 인증에 사용되는 개시자 비밀번호와 대상 비밀번호 자격 증명을 편집합니다.
+

TIP: CHAP 설정 자격 증명을 변경하지 않으면 동일하게 유지됩니다.  자격 증명 필드를 비워 두면 시스템이 자동으로 새로운 비밀번호를 생성합니다.

. *변경 사항 저장*을 클릭하세요.




== 저장 컨테이너 삭제

Element UI에서 저장 컨테이너를 삭제할 수 있습니다.

.필요한 것
모든 가상 머신이 VVol 데이터 저장소에서 제거되었는지 확인하세요.

.단계
. *VVols* > *저장 컨테이너*를 선택합니다.
. 삭제하려는 저장 컨테이너의 *작업* 아이콘을 클릭합니다.
. 나타나는 메뉴에서 *삭제*를 선택합니다.
. 작업을 확인합니다.
. *저장 컨테이너* 하위 탭에서 저장 컨테이너 목록을 새로 고쳐 저장 컨테이너가 제거되었는지 확인하세요.

