---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: Element 소프트웨어를 실행하는 클러스터는 클러스터 용량이 부족해질 때 스토리지 관리자에게 경고하기 위해 클러스터 오류를 생성합니다.  클러스터 충만도에는 경고, 오류, 위험의 세 가지 수준이 있으며, 이는 모두 NetApp Element UI에 표시됩니다. 
---
= 클러스터 충만도 수준 이해
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 소프트웨어를 실행하는 클러스터는 클러스터 용량이 부족해질 때 스토리지 관리자에게 경고하기 위해 클러스터 오류를 생성합니다.  클러스터 충만도에는 경고, 오류, 위험의 세 가지 수준이 있으며, 이는 모두 NetApp Element UI에 표시됩니다.

시스템은 BlockClusterFull 오류 코드를 사용하여 클러스터 블록 저장소가 가득 찼음을 경고합니다.  Element UI의 알림 탭에서 클러스터 충만도 심각도 수준을 볼 수 있습니다.

다음 목록에는 BlockClusterFull 심각도 수준에 대한 정보가 포함되어 있습니다.

* *경고*
+
이는 클러스터의 블록 용량이 오류 심각도 수준에 접근하면 나타나는 고객이 구성 가능한 경고입니다.  기본적으로 이 수준은 오류 수준보다 3% 낮게 설정되며 Element UI 및 API를 통해 조정할 수 있습니다.  가능한 한 빨리 용량을 추가하거나, 용량을 확보해야 합니다.

* *오류*
+
클러스터가 이 상태에 있을 때 노드가 손실되면 클러스터에 Double Helix 데이터 보호를 재구축할 수 있는 충분한 용량이 없게 됩니다.  클러스터가 이 상태에 있는 동안에는 새로운 볼륨 생성, 복제 및 스냅샷이 모두 차단됩니다.  이는 어떤 클러스터에도 안전하지 않고 권장되지 않는 상태입니다. 용량을 추가하거나 즉시 용량을 확보해야 합니다.

* *비판적인*
+
이 심각한 오류는 클러스터가 100% 소모되었기 때문에 발생했습니다.  읽기 전용 상태이므로 클러스터에 새로운 iSCSI 연결을 만들 수 없습니다.  이 단계에 도달하면 즉시 용량을 확보하거나 추가해야 합니다.



시스템은 MetadataClusterFull 오류 코드를 사용하여 클러스터 메타데이터 저장소가 가득 찼음을 경고합니다.  Element UI의 보고 탭에 있는 개요 페이지의 클러스터 용량 섹션에서 클러스터 메타데이터 저장소의 가득 참 상태를 볼 수 있습니다.

다음 목록에는 MetadataClusterFull 심각도 수준에 대한 정보가 포함되어 있습니다.

* *경고*
+
이는 클러스터의 메타데이터 용량이 오류 심각도 수준에 접근하면 나타나는 고객이 구성 가능한 경고입니다.  기본적으로 이 수준은 오류 수준보다 3% 낮게 설정되며 Element API를 통해 조정할 수 있습니다.  가능한 한 빨리 용량을 추가하거나, 용량을 확보해야 합니다.

* *오류*
+
클러스터가 이 상태에 있을 때 노드가 손실되면 클러스터에 Double Helix 데이터 보호를 재구축할 수 있는 충분한 용량이 없게 됩니다.  클러스터가 이 상태에 있는 동안에는 새로운 볼륨 생성, 복제 및 스냅샷이 모두 차단됩니다.  이는 어떤 클러스터에도 안전하지 않고 권장되지 않는 상태입니다. 용량을 추가하거나 즉시 용량을 확보해야 합니다.

* *비판적인*
+
이 심각한 오류는 클러스터가 100% 소모되었기 때문에 발생했습니다.  읽기 전용 상태이므로 클러스터에 새로운 iSCSI 연결을 만들 수 없습니다.  이 단계에 도달하면 즉시 용량을 확보하거나 추가해야 합니다.




NOTE: 다음은 2노드 클러스터 임계값에 적용됩니다.

* 메타데이터 완전성 오류는 위험 수준보다 20% 낮습니다.
* 블록 충만도 오류는 임계 용량보다 1개 블록 드라이브(고정 용량 포함)가 낮다는 의미입니다. 즉, 임계 용량보다 2개 블록 드라이브의 용량이 낮다는 의미입니다.

