---
permalink: storage/concept-element-replication-create-custom-replication-policy.html 
sidebar: sidebar 
keywords: ontap, cli, create, custom, replication, policy, relationship, 
summary: 관계에 대한 기본 정책이 적합하지 않은 경우 사용자 지정 복제 정책을 만들 수 있습니다. 
---
= 사용자 정의 복제 정책 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
복제 관계를 생성할 때 기본 정책이나 사용자 지정 정책을 사용할 수 있습니다.  사용자 정의 통합 복제 정책의 경우 초기화 및 업데이트 중에 어떤 스냅샷 복사본이 전송되는지 결정하는 하나 이상의 _규칙_을 정의해야 합니다.

관계에 대한 기본 정책이 적합하지 않은 경우 사용자 지정 복제 정책을 만들 수 있습니다.  예를 들어, 네트워크 전송 시 데이터를 압축하거나 SnapMirror 스냅샷 복사본을 전송하는 시도 횟수를 수정할 수 있습니다.

.이 작업에 관하여
복제 정책의 _정책 유형_은 지원하는 관계 유형을 결정합니다.  아래 표는 사용 가능한 정책 유형을 보여줍니다.

[cols="2*"]
|===


| 정책 유형 | 관계 유형 


 a| 
비동기 미러
 a| 
SnapMirror DR



 a| 
거울 금고
 a| 
통합 복제

|===
.단계
. 사용자 정의 복제 정책을 만듭니다.
+
`snapmirror policy create -vserver _SVM_ -policy policy -type async-mirror|mirror-vault -comment _comment_ -tries _transfer_tries_ -transfer-priority low|normal -is-network-compression-enabled true|false`

+
전체 명령 구문은 매뉴얼 페이지를 참조하세요.

+
ONTAP 9.5부터 SnapMirror 동기 관계에 대한 공통 스냅샷 복사 일정을 생성하기 위한 일정을 다음을 사용하여 지정할 수 있습니다. `-common-snapshot-schedule` 매개변수.  기본적으로 SnapMirror 동기 관계에 대한 일반적인 스냅샷 복사 일정은 1시간입니다.  SnapMirror 동기 관계에 대한 스냅샷 복사 일정에 대해 30분에서 2시간까지의 값을 지정할 수 있습니다.

+
다음 예제에서는 데이터 전송을 위한 네트워크 압축을 활성화하는 SnapMirror DR에 대한 사용자 지정 복제 정책을 만듭니다.

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
다음 예제에서는 통합 복제를 위한 사용자 지정 복제 정책을 만듭니다.

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


.당신이 완료한 후
"`mirror-vault`" 정책 유형의 경우 초기화 및 업데이트 중에 어떤 스냅샷 복사본이 전송되는지 결정하는 규칙을 정의해야 합니다.

사용하다 `snapmirror policy show` SnapMirror 정책이 생성되었는지 확인하는 명령입니다.  전체 명령 구문은 매뉴얼 페이지를 참조하세요.
