---
permalink: storage/concept_system_manage_drives_managing_drives.html 
sidebar: sidebar 
keywords: drives, manage, cluster, element ui, remove drives 
summary: 각 노드에는 클러스터의 데이터 일부를 저장하는 데 사용되는 하나 이상의 물리적 드라이브가 포함되어 있습니다.  클러스터는 드라이브가 클러스터에 성공적으로 추가된 후 드라이브의 용량과 성능을 활용합니다.  Element UI를 사용하여 드라이브를 관리할 수 있습니다. 
---
= 드라이브 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 노드에는 클러스터의 데이터 일부를 저장하는 데 사용되는 하나 이상의 물리적 드라이브가 포함되어 있습니다.  클러스터는 드라이브가 클러스터에 성공적으로 추가된 후 드라이브의 용량과 성능을 활용합니다.  Element UI를 사용하여 드라이브를 관리할 수 있습니다.



== 드라이브 세부 정보

클러스터 탭의 드라이브 페이지는 클러스터의 활성 드라이브 목록을 제공합니다.  활성, 사용 가능, 제거 중, 삭제 중, 실패 탭을 선택하여 페이지를 필터링할 수 있습니다.

클러스터를 처음 초기화하면 활성 드라이브 목록이 비어 있습니다.  새 SolidFire 클러스터가 생성된 후 클러스터에 할당되지 않고 사용 가능 탭에 나열된 드라이브를 추가할 수 있습니다.

활성 드라이브 목록에는 다음 요소가 나타납니다.

* *드라이브 ID*
+
드라이브에 할당된 순차 번호입니다.

* *노드 ID*
+
클러스터에 노드가 추가될 때 할당되는 노드 번호입니다.

* *노드 이름*
+
드라이브를 수용하는 노드의 이름입니다.

* *슬롯*
+
드라이브가 물리적으로 위치한 슬롯 번호입니다.

* *용량*
+
드라이브의 크기(GB)입니다.

* *연속물*
+
드라이브의 일련번호.

* *남은 마모량*
+
마모 수준 표시기.

+
저장 시스템은 각 솔리드 스테이트 드라이브(SSD)에서 데이터 쓰기 및 지우기에 사용할 수 있는 대략적인 마모량을 보고합니다.  설계된 쓰기 및 지우기 주기의 5%를 소모한 드라이브는 95%의 마모가 남아 있다고 보고합니다.  시스템은 드라이브 마모 정보를 자동으로 새로 고치지 않습니다. 새로 고치거나 페이지를 닫았다가 다시 로드하여 정보를 새로 고칠 수 있습니다.

* *유형*
+
드라이브의 유형.  유형은 블록이나 메타데이터가 될 수 있습니다.





== 더 많은 정보를 원하시면

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

