---
permalink: storage/concept_troubleshoot_drives.html 
sidebar: sidebar 
keywords: troubleshoot, drives, ssd, swappable, solid-state drives 
summary: '고장난 솔리드 스테이트 드라이브(SSD)를 교체용 드라이브로 교체할 수 있습니다.  SolidFire 스토리지 노드용 SSD는 핫스왑이 가능합니다.  SSD에 오류가 발생한 것으로 의심되는 경우 NetApp 지원팀에 문의하여 오류를 확인하고 적절한 해결 절차를 안내받으세요.  NetApp 지원팀은 귀하의 서비스 수준 계약에 따라 교체 드라이브를 구하는 데 도움을 드립니다.' 
---
= 드라이브 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
고장난 SSD(솔리드 스테이트 드라이브)를 교체용 드라이브로 교체할 수 있습니다.  SolidFire 스토리지 노드용 SSD는 핫스왑이 가능합니다.  SSD에 오류가 발생한 것으로 의심되는 경우 NetApp 지원팀에 문의하여 오류를 확인하고 적절한 해결 절차를 안내받으세요.  NetApp 지원팀은 귀하의 서비스 수준 계약에 따라 교체 드라이브를 구하는 데 도움을 드립니다.

이 경우 교체 가능성은 활성 노드에서 오류가 발생한 드라이브를 제거하고 NetApp 에서 새 SSD 드라이브로 교체할 수 있음을 의미합니다.  활성 클러스터에서 오류가 발생하지 않은 드라이브를 제거하는 것은 권장되지 않습니다.

드라이브에 오류가 발생할 경우 즉시 교체할 수 있도록 NetApp 지원팀에서 제안한 현장 예비 드라이브를 유지 관리해야 합니다.


NOTE: 테스트 목적으로, 노드에서 드라이브를 꺼내 드라이브 오류를 시뮬레이션하는 경우 드라이브를 드라이브 슬롯에 다시 삽입하기 전에 30초 동안 기다려야 합니다.

드라이브에 오류가 발생하면 Double Helix는 드라이브의 데이터를 클러스터에 남아 있는 노드에 재분산합니다.  Element 소프트웨어는 동일한 노드에 있는 두 개의 데이터 사본으로부터 데이터를 보호하므로 동일한 노드에서 여러 드라이브에 오류가 발생해도 문제가 되지 않습니다.  드라이브에 오류가 발생하면 다음과 같은 이벤트가 발생합니다.

* 데이터가 드라이브에서 마이그레이션됩니다.
* 전체 클러스터 용량은 드라이브 용량만큼 감소합니다.
* Double Helix 데이터 보호는 데이터의 유효한 사본이 두 개 존재하도록 보장합니다.



IMPORTANT: SolidFire 스토리지 시스템은 데이터를 마이그레이션할 저장 공간이 부족할 경우 드라이브 제거를 지원하지 않습니다.



== 더 많은 정보를 원하시면

* xref:task_troubleshoot_remove_failed_drives.adoc[클러스터에서 실패한 드라이브 제거]
* xref:concept_troubleshoot_basic_mdss_drive_troubleshooting.adoc[기본 MDSS 드라이브 문제 해결]
* xref:task_troubleshoot_remove_mdss_drives.adoc[MDSS 드라이브 제거]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2844771["SolidFire 스토리지 노드용 드라이브 교체"]
* https://library.netapp.com/ecm/ecm_download_file/ECMLP2846859["H600S 시리즈 스토리지 노드용 드라이브 교체"]
* link:../hardware/task_h410s_h610s_install.html["H410S 및 H610S 하드웨어 정보"]
* link:../hardware/task_sfseries_chassisrepl.html["SF 시리즈 하드웨어 정보"]

