---
permalink: storage/element-replication-index.html 
sidebar: sidebar 
keywords: ontap, cli, replication, element, software, ontap, business continuity, snapmirror, replicate, snapshot, copies, volume 
summary: SnapMirror 사용하여 Element 볼륨의 스냅샷 복사본을 ONTAP 대상에 복제하면 Element 시스템에서 비즈니스 연속성을 보장할 수 있습니다. 
---
= NetApp Element 소프트웨어와 ONTAP 간 복제 개요(ONTAP CLI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror 사용하여 Element 볼륨의 스냅샷 복사본을 ONTAP 대상에 복제하면 Element 시스템에서 비즈니스 연속성을 보장할 수 있습니다.  Element 사이트에서 재해가 발생하는 경우 ONTAP 시스템에서 클라이언트에게 데이터를 제공한 다음 서비스가 복구되면 Element 시스템을 다시 활성화할 수 있습니다.

ONTAP 9.4부터 ONTAP 노드에서 생성된 LUN의 스냅샷 복사본을 Element 시스템으로 다시 복제할 수 있습니다.  Element 사이트에서 정전이 발생한 동안 LUN을 생성했을 수도 있고, ONTAP 에서 Element 소프트웨어로 데이터를 마이그레이션하기 위해 LUN을 사용했을 수도 있습니다.

다음 사항이 적용되는 경우 Element to ONTAP 백업을 사용해야 합니다.

* 모든 가능한 옵션을 탐색하기보다는 모범 사례를 활용하세요.
* System Manager나 자동화 스크립팅 도구가 아닌 ONTAP 명령줄 인터페이스(CLI)를 사용하려고 합니다.
* iSCSI를 사용하여 클라이언트에 데이터를 제공하고 있습니다.


추가 SnapMirror 구성이나 개념 정보가 필요한 경우 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["데이터 보호 개요"^] .



== Element와 ONTAP 간 복제에 관하여

ONTAP 9.3부터 SnapMirror 사용하여 Element 볼륨의 스냅샷 복사본을 ONTAP 대상에 복제할 수 있습니다.  Element 사이트에서 재해가 발생하는 경우 ONTAP 시스템에서 클라이언트에 데이터를 제공한 다음 서비스가 복구되면 Element 소스 볼륨을 다시 활성화할 수 있습니다.

ONTAP 9.4부터 ONTAP 노드에서 생성된 LUN의 스냅샷 복사본을 Element 시스템으로 다시 복제할 수 있습니다.  Element 사이트에서 정전이 발생한 동안 LUN을 생성했을 수도 있고, ONTAP 에서 Element 소프트웨어로 데이터를 마이그레이션하기 위해 LUN을 사용했을 수도 있습니다.



=== 데이터 보호 관계 유형

SnapMirror 두 가지 유형의 데이터 보호 관계를 제공합니다.  각 유형에 대해 SnapMirror 관계를 초기화하거나 업데이트하기 전에 Element 소스 볼륨의 스냅샷 복사본을 만듭니다.

* _재해 복구(DR)_ 데이터 보호 관계에서 대상 볼륨에는 SnapMirror 에서 생성된 스냅샷 복사본만 포함되며, 이를 통해 기본 사이트에서 재해가 발생하는 경우에도 계속해서 데이터를 제공할 수 있습니다.
* _장기 보존_ 데이터 보호 관계에서 대상 볼륨에는 Element 소프트웨어에서 생성된 시점 스냅샷 복사본과 SnapMirror 에서 생성된 스냅샷 복사본이 포함됩니다.  예를 들어, 20년 동안 생성된 월별 스냅샷 사본을 보관하고 싶을 수도 있습니다.




=== 기본 정책

SnapMirror 처음 호출하면 소스 볼륨에서 대상 볼륨으로 _기준 전송_이 수행됩니다.  _SnapMirror 정책_은 기준선의 내용과 모든 업데이트를 정의합니다.

데이터 보호 관계를 생성할 때 기본 정책이나 사용자 지정 정책을 사용할 수 있습니다.  _정책 유형_은 포함할 스냅샷 복사본과 보관할 복사본 수를 결정합니다.

아래 표는 기본 정책을 보여줍니다.  사용하다 `MirrorLatest` 전통적인 DR 관계를 만드는 정책입니다.  사용하다 `MirrorAndVault` 또는 `Unified7year` DR과 장기 보존이 동일한 대상 볼륨에 구성되는 통합 복제 관계를 만드는 정책입니다.

[cols="25,25,50"]
|===


| 정책 | 정책 유형 | 업데이트 동작 


 a| 
미러최신
 a| 
비동기 미러
 a| 
SnapMirror 에서 생성된 스냅샷 복사본을 전송합니다.



 a| 
미러앤볼트
 a| 
거울 금고
 a| 
SnapMirror 에서 생성된 스냅샷 복사본과 마지막 업데이트 이후에 생성된 스냅샷 복사본 중 "매일" 또는 "매주"라는 SnapMirror 레이블이 있는 경우 해당 복사본을 전송합니다.



 a| 
Unified7year
 a| 
거울 금고
 a| 
SnapMirror 에서 생성된 스냅샷 복사본과 마지막 업데이트 이후에 생성된 스냅샷 복사본 중 "매일", "매주" 또는 "매월"이라는 SnapMirror 레이블이 있는 경우 해당 복사본을 전송합니다.

|===
[NOTE]
====
SnapMirror 정책에 대한 전체 배경 정보(사용할 정책에 대한 지침 포함)는 다음을 참조하세요.link:https://docs.netapp.com/us-en/ontap/data-protection-disaster-recovery/index.html["데이터 보호 개요"^] .

====


=== SnapMirror 레이블 이해

"`mirror-vault`" 정책 유형이 있는 모든 정책에는 복제할 스냅샷 복사본을 지정하는 규칙이 있어야 합니다.  예를 들어, "매일" 규칙은 SnapMirror 레이블 "매일"이 할당된 스냅샷 복사본만 복제해야 함을 나타냅니다.  Element 스냅샷 복사본을 구성할 때 SnapMirror 레이블을 할당합니다.



=== Element 소스 클러스터에서 ONTAP 대상 클러스터로 복제

SnapMirror 사용하면 Element 볼륨의 스냅샷 복사본을 ONTAP 대상 시스템에 복제할 수 있습니다.  Element 사이트에서 재해가 발생하는 경우 ONTAP 시스템에서 클라이언트에 데이터를 제공한 다음 서비스가 복구되면 Element 소스 볼륨을 다시 활성화할 수 있습니다.

Element 볼륨은 ONTAP LUN과 거의 동일합니다.  Element 소프트웨어와 ONTAP 간의 데이터 보호 관계가 초기화되면 SnapMirror Element 볼륨의 이름으로 LUN을 생성합니다.  LUN이 Element to ONTAP 복제에 대한 요구 사항을 충족하는 경우 SnapMirror 기존 LUN에 데이터를 복제합니다.

복제 규칙은 다음과 같습니다.

* ONTAP 볼륨에는 하나의 Element 볼륨의 데이터만 포함될 수 있습니다.
* ONTAP 볼륨에서 여러 Element 볼륨으로 데이터를 복제할 수 없습니다.




=== ONTAP 소스 클러스터에서 Element 대상 클러스터로 복제

ONTAP 9.4부터 ONTAP 시스템에서 생성된 LUN의 스냅샷 복사본을 Element 볼륨으로 다시 복제할 수 있습니다.

* Element 소스와 ONTAP 대상 사이에 SnapMirror 관계가 이미 존재하는 경우 대상에서 데이터를 제공하는 동안 생성된 LUN은 소스가 다시 활성화될 때 자동으로 복제됩니다.
* 그렇지 않은 경우 ONTAP 소스 클러스터와 Element 대상 클러스터 간에 SnapMirror 관계를 만들고 초기화해야 합니다.


복제 규칙은 다음과 같습니다.

* 복제 관계에는 "async-mirror" 유형의 정책이 있어야 합니다.
+
"`mirror-vault`" 유형의 정책은 지원되지 않습니다.

* iSCSI LUN만 지원됩니다.
* ONTAP 볼륨에서 Element 볼륨으로 두 개 이상의 LUN을 복제할 수 없습니다.
* ONTAP 볼륨에서 여러 Element 볼륨으로 LUN을 복제할 수 없습니다.




=== 필수 조건

Element와 ONTAP 간의 데이터 보호 관계를 구성하기 전에 다음 작업을 완료해야 합니다.

* Element 클러스터는 NetApp Element 소프트웨어 버전 10.1 이상을 실행해야 합니다.
* ONTAP 클러스터는 ONTAP 9.3 이상을 실행해야 합니다.
* SnapMirror ONTAP 클러스터에서 라이센스를 받아야 합니다.
* 예상되는 데이터 전송을 처리할 수 있을 만큼 충분히 큰 Element 및 ONTAP 클러스터에 볼륨을 구성해야 합니다.
* "`mirror-vault`" 정책 유형을 사용하는 경우 Element 스냅샷 복사본을 복제하려면 SnapMirror 레이블이 구성되어 있어야 합니다.
+
[NOTE]
====
이 작업은 다음에서만 수행할 수 있습니다.link:concept_snapmirror_labels.html["Element 소프트웨어 웹 UI"] 또는 사용link:../api/concept_element_api_snapshots_overview.html["API 메서드"] .

====
* 포트 5010을 사용할 수 있는지 확인해야 합니다.
* 대상 볼륨을 이동해야 할 것으로 예상되는 경우 소스와 대상 사이에 풀 메시 연결이 있는지 확인해야 합니다.  Element 소스 클러스터의 모든 노드는 ONTAP 대상 클러스터의 모든 노드와 통신할 수 있어야 합니다.




=== 지원 세부 정보

다음 표는 Element to ONTAP 백업에 대한 지원 세부 정보를 보여줍니다.

[cols="25,75"]
|===


| 리소스 또는 기능 | 지원 세부 정보 


 a| 
SnapMirror
 a| 
* SnapMirror 복원 기능은 지원되지 않습니다.
* 그만큼 `MirrorAllSnapshots` 그리고 `XDPDefault` 정책이 지원되지 않습니다.
* "`vault`" 정책 유형은 지원되지 않습니다.
* 시스템 정의 규칙 "`all_source_snapshots`"는 지원되지 않습니다.
* "`mirror-vault`" 정책 유형은 Element 소프트웨어에서 ONTAP 으로의 복제에만 지원됩니다.  ONTAP 에서 Element 소프트웨어로 복제하려면 "`async-mirror`"를 사용합니다.
* 그만큼 `-schedule` 그리고 `-prefix` 옵션 `snapmirror policy add-rule` 지원되지 않습니다.
* 그만큼 `-preserve` 그리고 `-quick-resync` 옵션 `snapmirror resync` 지원되지 않습니다.
* 저장 효율성이 유지되지 않습니다.
* 팬아웃 및 캐스케이드 데이터 보호 배포는 지원되지 않습니다.




 a| 
ONTAP
 a| 
* ONTAP Select 는 ONTAP 9.4 및 Element 10.3부터 지원됩니다.
* Cloud Volumes ONTAP 은 ONTAP 9.5 및 Element 11.0부터 지원됩니다.




 a| 
요소
 a| 
* 볼륨 크기 제한은 8TiB입니다.
* 볼륨 블록 크기는 512바이트여야 합니다.  4K 바이트 블록 크기는 지원되지 않습니다.
* 볼륨 크기는 1MiB의 배수여야 합니다.
* 볼륨 속성은 보존되지 않습니다.
* 복제할 수 있는 스냅샷 복사본의 최대 수는 30개입니다.




 a| 
회로망
 a| 
* 전송당 하나의 TCP 연결이 허용됩니다.
* Element 노드는 IP 주소로 지정되어야 합니다.  DNS 호스트 이름 조회가 지원되지 않습니다.
* IPspace는 지원되지 않습니다.




 a| 
SnapLock
 a| 
SnapLock 볼륨은 지원되지 않습니다.



 a| 
FlexGroup
 a| 
FlexGroup 볼륨은 지원되지 않습니다.



 a| 
SVM DR
 a| 
SVM DR 구성의 ONTAP 볼륨은 지원되지 않습니다.



 a| 
MetroCluster
 a| 
MetroCluster 구성의 ONTAP 볼륨은 지원되지 않습니다.

|===