---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 시스템은 여러 유형의 이벤트를 보고합니다. 각 이벤트는 시스템이 완료한 작업입니다.  이벤트는 일상적이고 일반적인 이벤트이거나 관리자의 주의가 필요한 이벤트일 수 있습니다.  이벤트 로그 페이지의 이벤트 유형 열은 이벤트가 시스템의 어느 부분에서 발생했는지 나타냅니다. 
---
= 이벤트 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템은 여러 유형의 이벤트를 보고합니다. 각 이벤트는 시스템이 완료한 작업입니다.  이벤트는 일상적이고 일반적인 이벤트이거나 관리자의 주의가 필요한 이벤트일 수 있습니다.  이벤트 로그 페이지의 이벤트 유형 열은 이벤트가 시스템의 어느 부분에서 발생했는지 나타냅니다.


NOTE: 시스템은 이벤트 로그에 읽기 전용 API 명령을 기록하지 않습니다.

다음 목록은 이벤트 로그에 나타나는 이벤트 유형을 설명합니다.

* *api이벤트*
+
API나 웹 UI를 통해 사용자가 시작하여 설정을 수정하는 이벤트입니다.

* *binAssignmentsEvent*
+
데이터 빈 할당과 관련된 이벤트입니다.  빈은 기본적으로 데이터를 보관하는 컨테이너이며 클러스터 전체에 매핑됩니다.

* *binSync이벤트*
+
블록 서비스 간 데이터 재할당과 관련된 시스템 이벤트입니다.

* *bsCheckEvent*
+
블록 서비스 검사와 관련된 시스템 이벤트입니다.

* *bs킬이벤트*
+
블록 서비스 종료와 관련된 시스템 이벤트입니다.

* *대량운영이벤트*
+
백업, 복원, 스냅샷 또는 복제와 같이 전체 볼륨에서 수행되는 작업과 관련된 이벤트입니다.

* *클론이벤트*
+
볼륨 클로닝과 관련된 이벤트.

* *클러스터마스터이벤트*
+
클러스터 초기화 시 또는 노드 추가나 제거와 같은 클러스터 구성 변경 시 나타나는 이벤트입니다.

* [[csum_event]]*cSumEvent*
+
엔드투엔드 체크섬 검증 중 체크섬 불일치 감지와 관련된 이벤트입니다.

+
체크섬 불일치를 감지한 서비스는 이 이벤트가 생성된 후 자동으로 중지되고 다시 시작되지 않습니다.

* *데이터이벤트*
+
데이터 읽기 및 쓰기와 관련된 이벤트입니다.

* *db이벤트*
+
클러스터의 앙상블 노드가 유지 관리하는 글로벌 데이터베이스와 관련된 이벤트입니다.

* *드라이브이벤트*
+
운전 작업과 관련된 이벤트.

* *휴지중 암호화 이벤트*
+
클러스터의 암호화 프로세스와 관련된 이벤트입니다.

* *앙상블이벤트*
+
앙상블에서 노드 수를 늘리거나 줄이는 것과 관련된 이벤트입니다.

* *파이버채널이벤트*
+
노드의 구성 및 연결과 관련된 이벤트입니다.

* *gc이벤트*
+
프로세스와 관련된 이벤트는 블록 드라이브의 저장 공간을 회수하기 위해 60분마다 실행됩니다.  이 과정은 가비지 컬렉션이라고도 불립니다.

* *ie이벤트*
+
내부 시스템 오류입니다.

* *설치이벤트*
+
자동 소프트웨어 설치 이벤트.  보류 중인 노드에 소프트웨어가 자동으로 설치되고 있습니다.

* *iSCSI이벤트*
+
시스템의 iSCSI 문제와 관련된 이벤트입니다.

* *이벤트 제한*
+
계정이나 클러스터의 볼륨 또는 가상 볼륨 수가 허용된 최대값에 가까워지는 것과 관련된 이벤트입니다.

* *유지관리모드이벤트*
+
노드 비활성화 등 노드 유지 관리 모드와 관련된 이벤트입니다.

* [[네트워크_이벤트]]*네트워크이벤트*
+
각 물리적 네트워크 인터페이스 카드(NIC) 인터페이스에 대한 네트워크 오류 보고와 관련된 이벤트입니다.

+
이러한 이벤트는 10분 모니터링 간격 동안 인터페이스의 오류 수가 기본 임계값인 1000을 초과할 때 발생합니다.  이러한 이벤트는 수신 미스, 순환 중복 검사(CRC) 오류, 길이 오류, 오버런 오류, 프레임 오류와 같은 네트워크 오류에 적용됩니다.

* *플랫폼하드웨어이벤트*
+
하드웨어 장치에서 감지된 문제와 관련된 이벤트입니다.

* *원격클러스터이벤트*
+
원격 클러스터 페어링과 관련된 이벤트입니다.

* *스케줄러이벤트*
+
예약된 스냅샷과 관련된 이벤트입니다.

* *서비스이벤트*
+
시스템 서비스 상태와 관련된 이벤트입니다.

* *슬라이스이벤트*
+
메타데이터 드라이브나 볼륨을 제거하는 등 Slice Server와 관련된 이벤트입니다.

+
볼륨이 할당된 서비스에 대한 정보를 포함하는 세 가지 유형의 슬라이스 재할당 이벤트가 있습니다.

+
** 플리핑: 기본 서비스를 새로운 기본 서비스로 변경
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 이동: 보조 서비스를 새로운 보조 서비스로 변경
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 가지치기: 서비스 세트에서 볼륨 제거
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* *snmp트랩이벤트*
+
SNMP 트랩과 관련된 이벤트.

* *상태이벤트*
+
시스템 통계와 관련된 이벤트.

* *ts이벤트*
+
시스템 전송 서비스와 관련된 이벤트입니다.

* *예기치 않은 예외*
+
예상치 못한 시스템 예외와 관련된 이벤트입니다.

* *ureEvent*
+
저장 장치에서 읽는 동안 발생하는 복구할 수 없는 읽기 오류와 관련된 이벤트입니다.

* *vasaProviderEvent*
+
VASA(vSphere APIs for Storage Awareness) 공급자와 관련된 이벤트입니다.


