---
permalink: storage/reference_post_deploy_change_default_ssl_certificate.html 
sidebar: sidebar 
keywords: ssl certificate, SSL, private key, self-signed, cluster, nodes, user-defined certificate, API, change default certificate, certificate, Element API 
summary: NetApp Element API를 사용하여 클러스터의 스토리지 노드의 기본 SSL 인증서와 개인 키를 변경할 수 있습니다. 
---
= Element 소프트웨어 기본 SSL 인증서 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element API를 사용하여 클러스터의 스토리지 노드의 기본 SSL 인증서와 개인 키를 변경할 수 있습니다.

NetApp Element 소프트웨어 클러스터가 생성되면 클러스터는 Element UI, 노드별 UI 또는 API를 통한 모든 HTTPS 통신에 사용되는 고유한 자체 서명된 SSL(Secure Sockets Layer) 인증서와 개인 키를 생성합니다.  Element 소프트웨어는 자체 서명 인증서는 물론 신뢰할 수 있는 인증 기관(CA)에서 발급하고 검증한 인증서도 지원합니다.

다음 API 메서드를 사용하면 기본 SSL 인증서에 대한 자세한 정보를 얻고 변경할 수 있습니다.

* *SSL인증서 받기*
+
당신은 사용할 수 있습니다link:../api/reference_element_api_getsslcertificate.html["GetSSLCertificate 메서드"] 모든 인증서 세부 정보를 포함하여 현재 설치된 SSL 인증서에 대한 정보를 검색합니다.

* *SSL인증서 설정*
+
당신은 사용할 수 있습니다link:../api/reference_element_api_setsslcertificate.html["SetSSLCertificate 메서드"] 클러스터 및 노드별 SSL 인증서를 사용자가 제공한 인증서와 개인 키로 설정합니다.  시스템은 잘못된 인증서가 적용되는 것을 방지하기 위해 인증서와 개인 키를 검증합니다.

* *SSL인증서 제거*
+
그만큼link:../api/reference_element_api_removesslcertificate.html["RemoveSSLCertificate 메서드"] 현재 설치된 SSL 인증서와 개인 키를 제거합니다.  그러면 클러스터는 새로운 자체 서명 인증서와 개인 키를 생성합니다.




NOTE: 클러스터 SSL 인증서는 클러스터에 추가된 모든 새 노드에 자동으로 적용됩니다.  클러스터에서 제거된 모든 노드는 자체 서명 인증서로 되돌아가고 모든 사용자 정의 인증서와 키 정보는 노드에서 제거됩니다.



== 더 많은 정보를 찾아보세요

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["관리 노드 기본 SSL 인증서 변경"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Element Software에서 사용자 정의 SSL 인증서를 설정하는 데 필요한 요구 사항은 무엇입니까?"^]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

