---
permalink: storage/reference_per_node_network_settings_details.html 
sidebar: sidebar 
keywords: network settings, per-node UI, storage node, ui 
summary: 스토리지 노드 네트워크 설정을 변경하여 노드에 새로운 네트워크 속성 세트를 제공할 수 있습니다. 
---
= 노드별 UI의 네트워크 설정 세부 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드 네트워크 설정을 변경하여 노드에 새로운 네트워크 속성 세트를 제공할 수 있습니다.

노드에 로그인하면 *네트워크 설정* 페이지에서 스토리지 노드의 네트워크 설정을 볼 수 있습니다. (`https://<node_IP>:442/hcc/node/network-settings`). *Bond1G* (관리) 또는 *Bond10G* (저장) 설정을 선택할 수 있습니다. 다음 목록은 스토리지 노드가 사용 가능, 보류 중 또는 활성 상태일 때 수정할 수 있는 설정을 설명합니다.

* *방법*
+
인터페이스를 구성하는 데 사용되는 방법입니다.  가능한 방법:

+
** 루프백: IPv4 루프백 인터페이스를 정의하는 데 사용됩니다.
** manual: 기본적으로 구성이 수행되지 않는 인터페이스를 정의하는 데 사용됩니다.
** dhcp: DHCP를 통해 IP 주소를 얻는 데 사용됩니다.
** 정적: 정적으로 할당된 IPv4 주소로 이더넷 인터페이스를 정의하는 데 사용됩니다.


* *링크 속도*
+
가상 NIC가 협상하는 속도입니다.

* *IPv4 주소*
+
eth0 네트워크의 IPv4 주소입니다.

* *IPv4 서브넷 마스크*
+
IPv4 네트워크의 하위 구분을 나타냅니다.

* *IPv4 게이트웨이 주소*
+
로컬 네트워크에서 패킷을 전송하기 위한 라우터 네트워크 주소입니다.

* *IPv6 주소*
+
eth0 네트워크의 IPv6 주소입니다.

* *IPv6 게이트웨이 주소*
+
로컬 네트워크에서 패킷을 전송하기 위한 라우터 네트워크 주소입니다.

* *MTU*
+
네트워크 프로토콜이 전송할 수 있는 가장 큰 패킷 크기.  1500 이상이어야 합니다.  두 번째 스토리지 NIC를 추가하는 경우 값은 9000이어야 합니다.

* *DNS 서버*
+
클러스터 통신에 사용되는 네트워크 인터페이스입니다.

* *도메인 검색*
+
시스템에서 사용 가능한 추가 MAC 주소를 검색합니다.

* *본드 모드*
+
다음 모드 중 하나일 수 있습니다.

+
** ActivePassive(기본값)
** 장백의
** LACP


* *상태*
+
가능한 값:

+
** 업앤러닝
** 아래에
** 위로


* *가상 네트워크 태그*
+
가상 네트워크가 생성될 때 할당된 태그입니다.

* *경로*
+
연결된 인터페이스를 통해 특정 호스트나 네트워크에 대한 정적 경로를 구성하여 사용합니다.


