---
permalink: storage/reference_copyright.html 
sidebar: sidebar 
keywords:  
summary:  
---
= 저작권
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Copyright © 2021 NetApp, Inc. All rights reserved. 미국에서 인쇄됨

저작권으로 보호되는 이 문서의 어떠한 부분도 저작권 소유자의 사전 서면 허가 없이는 어떠한 형태나 수단(복사, 녹음, 녹음 또는 전자 검색 시스템에 저장하는 것을 포함한 그래픽, 전자 또는 기계적 수단 포함)으로 복제할 수 없습니다.

NetApp이 저작권을 가진 자료에 있는 소프트웨어에는 아래의 라이센스와 고지 사항이 적용됩니다.

본 소프트웨어는 NETAPP에서 "있는 그대로" 제공되며 상품성 및 특정 목적에의 적합성에 대한 묵시적 보증을 포함하되 이에 국한되지 않는 명시적 또는 묵시적 보증 없이 제공됩니다. 본 계약에 따라 이러한 보증은 부인됩니다. NetApp은 대체품 또는 대체 서비스의 조달, 사용 불능, 데이터 손실, 이익 손실, 영업 중단을 포함하고 이에 국한되지 않으며, 이 소프트웨어의 사용으로 인해 발생하는 모든 직접 및 간접 손해, 우발적 손해, 특별 손해, 징벌적 손해, 결과적 손해의 발생에 대하여 그 발생 이유, 책임론, 계약 여부, 엄격한 책임, 불법 행위(과실 또는 그렇지 않은 경우)에 관계없이 어떠한 책임도 지지 않으며, 이와 같은 손실의 발생 가능성이 통지되었다 하더라도 마찬가지입니다.

NetApp은 본 문서에 설명된 제품을 언제든지 예고 없이 변경할 권리를 보유합니다. NetApp은 NetApp의 명시적인 서면 동의를 받은 경우를 제외하고 본 문서에 설명된 제품을 사용하여 발생하는 어떠한 문제에도 책임을 지지 않습니다. 본 제품의 사용 또는 구입의 경우 NetApp에서는 어떠한 특허권, 상표권 또는 기타 지적 재산권이 적용되는 라이센스도 제공하지 않습니다.

본 매뉴얼에 설명된 제품은 하나 이상의 미국 특허, 기타 국가의 특허 또는 출원 중인 특허에 의해 보호될 수 있습니다.

여기에 포함된 데이터는 상업용 품목(FAR 2.101에 정의됨)과 관련이 있으며 NetApp, Inc.의 독점 자산입니다. 미국 정부는 미국 정부와의 계약과 관련하여 데이터를 사용하고 지원하기 위해서만 데이터를 사용할 수 있는 비독점적, 양도 불가능, 하위 라이선스 불가능, 전 세계적, 제한적, 취소 불가능 라이선스를 보유하고 있습니다.  여기에 규정된 경우를 제외하고, NetApp, Inc.의 사전 서면 승인 없이는 데이터를 사용, 공개, 복제, 수정, 수행 또는 표시할 수 없습니다. 국방부에 대한 미국 정부 라이선스 권리는 DFARS 조항 252.227-7015(b)에 명시된 권리로 제한됩니다.
