---
permalink: storage/reference_snapmirror_relationship_actions.html 
sidebar: sidebar 
keywords: element, ui, relationships, snapmirror, actions, configure 
summary: 데이터 보호 탭의 SnapMirror 관계 페이지에서 관계를 구성할 수 있습니다.  동작 아이콘의 옵션은 다음과 같습니다. 
---
= SnapMirror 관계 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 탭의 SnapMirror 관계 페이지에서 관계를 구성할 수 있습니다.  동작 아이콘의 옵션은 다음과 같습니다.

* *편집*: 관계에 사용된 정책이나 일정을 편집합니다.
* *삭제*: SnapMirror 관계를 삭제합니다.  이 기능은 대상 볼륨을 삭제하지 않습니다.
* *초기화*: 새로운 관계를 설정하기 위해 데이터의 첫 번째 초기 기준 전송을 수행합니다.
* *업데이트*: 관계에 대한 주문형 업데이트를 수행하고 마지막 업데이트 이후에 포함된 모든 새 데이터와 스냅샷 사본을 대상에 복제합니다.
* *정지*: 관계에 대한 추가 업데이트를 방지합니다.
* *다시 시작*: 중단된 관계를 다시 시작합니다.
* *중단*: 대상 볼륨을 읽기/쓰기로 만들고 현재 및 미래의 모든 전송을 중지합니다.  역방향 재동기화 작업으로 인해 원본 소스 볼륨이 읽기 전용이 되므로 클라이언트가 원본 소스 볼륨을 사용하지 않는지 확인합니다.
* *재동기화*: 관계가 끊어지기 전과 같은 방향으로 끊어진 관계를 다시 설정합니다.
* *역방향 재동기화*: 반대 방향으로 새로운 관계를 만들고 초기화하는 데 필요한 단계를 자동화합니다.  이는 기존 관계가 깨진 경우에만 가능합니다.  이 작업을 수행해도 현재 관계는 삭제되지 않습니다.  원본 소스 볼륨은 가장 최근의 공통 스냅샷 복사본으로 되돌아가고 대상과 다시 동기화됩니다.  마지막으로 SnapMirror 성공적으로 업데이트한 이후 원본 소스 볼륨에 적용된 모든 변경 사항은 손실됩니다.  현재 대상 볼륨에 적용된 모든 변경 사항이나 현재 대상 볼륨에 작성된 모든 새 데이터는 원래 소스 볼륨으로 다시 전송됩니다.
* *중단*: 진행 중인 전송을 취소합니다.  중단된 관계에 대해 SnapMirror 업데이트가 발행되면 관계는 중단이 발생하기 전에 생성된 마지막 재시작 체크포인트의 마지막 전송으로 계속됩니다.

