---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: SSL 암호는 호스트가 안전한 통신을 구축하는 데 사용하는 암호화 알고리즘입니다.  Element 소프트웨어가 지원하는 표준 암호와 FIPS 140-2 모드가 활성화된 경우 지원하는 비표준 암호가 있습니다. 
---
= SSL 암호
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSL 암호는 호스트가 안전한 통신을 구축하는 데 사용하는 암호화 알고리즘입니다.  Element 소프트웨어가 지원하는 표준 암호와 FIPS 140-2 모드가 활성화된 경우 지원하는 비표준 암호가 있습니다.

다음 목록은 Element 소프트웨어에서 지원하는 표준 SSL(Secure Socket Layer) 암호와 FIPS 140-2 모드가 활성화된 경우 지원되는 SSL 암호를 제공합니다.

* *FIPS 140-2 비활성화*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(secp256r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA(rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384(rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5(rsa 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA(rsa 2048) - C

+
TLS_RSA_WITH_SEED_CBC_SHA(rsa 2048) - A

* *FIPS 140-2 지원*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(섹션 571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(sect571r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA(rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256(rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384(rsa 2048) - A





== 더 많은 정보를 찾아보세요

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[클러스터에서 HTTPS에 대해 FIPS 140-2를 활성화합니다.]
