---
permalink: storage/reference_replication_volume_pairing_warnings.html 
sidebar: sidebar 
keywords: volume warnings, messages, replication, data protection 
summary: '데이터 보호 탭의 볼륨 쌍 페이지에서는 볼륨을 페어링한 후 다음 메시지가 표시됩니다.  이러한 메시지는 복제 볼륨 목록 보기에서 쌍의 소스 및 대상 양쪽에 표시될 수 있습니다(별도로 표시되지 않는 한).' 
---
= 볼륨 페어링 경고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 탭의 볼륨 쌍 페이지에서는 볼륨을 페어링한 후 다음과 같은 메시지가 표시됩니다.  이러한 메시지는 복제 볼륨 목록 보기에서 쌍의 소스 및 대상 양쪽에 표시될 수 있습니다(달리 표시되지 않는 한).

* *일시 중지된 클러스터 가득 참*
+
대상 클러스터가 가득 차서 소스 복제 및 대량 데이터 전송을 진행할 수 없습니다.  해당 메시지는 쌍의 소스 쪽에만 표시됩니다.

* *일시 중지됨최대 스냅샷 수 초과*
+
대상 볼륨에는 이미 최대 개수의 스냅샷이 있으며 추가 스냅샷을 복제할 수 없습니다.

* *일시 중지된 수동*
+
로컬 볼륨이 수동으로 일시 중지되었습니다.  복제를 재개하기 전에 일시 중지를 해제해야 합니다.

* *수동 원격 일시 중지*
+
원격 볼륨이 수동 일시 정지 모드에 있습니다.  복제를 재개하기 전에 원격 볼륨의 일시 중지를 해제하려면 수동 개입이 필요합니다.

* *일시 중지됨잘못 구성됨*
+
활성화된 소스와 타겟을 기다리고 있습니다.  복제를 재개하려면 수동 개입이 필요합니다.

* *일시 중지된 QoS*
+
대상 QoS가 들어오는 IO를 유지할 수 없습니다.  복제가 자동으로 재개됩니다.  해당 메시지는 쌍의 소스 쪽에만 표시됩니다.

* *일시 중지된 느린 링크*
+
느린 링크가 감지되어 복제가 중단되었습니다.  복제가 자동으로 재개됩니다.  해당 메시지는 쌍의 소스 쪽에만 표시됩니다.

* *일시 중지된 볼륨 크기 불일치*
+
대상 볼륨의 크기가 소스 볼륨의 크기와 같지 않습니다.

* *일시 중지X복사*
+
SCSI XCOPY 명령이 소스 볼륨에 발행되고 있습니다.  복제를 재개하려면 명령을 완료해야 합니다.  해당 메시지는 쌍의 소스 쪽에만 표시됩니다.

* *중지됨잘못 구성됨*
+
영구적인 구성 오류가 감지되었습니다.  원격 볼륨이 제거되었거나 페어링이 해제되었습니다.  시정 조치는 불가능합니다. 새로운 페어링을 설정해야 합니다.


