---
permalink: storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html 
sidebar: sidebar 
keywords: enable, disable, encryption at rest, cluster, sed, hardware-based, encryption settings, software-based 
summary: SolidFire 클러스터를 사용하면 소프트웨어 또는 하드웨어 기반 암호화를 사용하여 클러스터에 저장된 모든 데이터를 암호화할 수 있습니다. 
---
= 클러스터에 대한 휴면 암호화 활성화 및 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 클러스터를 사용하면 클러스터 드라이브에 저장된 모든 저장 데이터를 암호화할 수 있습니다.  다음 중 하나를 사용하여 클러스터 전체에서 자체 암호화 드라이브(SED) 보호를 활성화할 수 있습니다.link:../concepts/concept_solidfire_concepts_security.html["하드웨어 또는 소프트웨어 기반 암호화"] .

Element UI나 API를 사용하여 하드웨어 암호화를 활성화할 수 있습니다.  휴면 상태의 하드웨어 암호화 기능을 활성화해도 클러스터의 성능이나 효율성에는 영향을 미치지 않습니다.  Element API를 사용해서만 소프트웨어 암호화를 활성화할 수 있습니다.

클러스터 생성 중에는 하드웨어 기반 암호화가 기본적으로 활성화되지 않으며 Element UI에서 활성화 및 비활성화할 수 있습니다.


WARNING: SolidFire 올플래시 스토리지 클러스터의 경우, 클러스터 생성 중에 소프트웨어 암호화를 활성화해야 하며 클러스터가 생성된 후에는 비활성화할 수 없습니다.

.필요한 것
* 암호화 설정을 활성화하거나 변경하려면 클러스터 관리자 권한이 있어야 합니다.
* 하드웨어 기반 암호화의 경우 암호화 설정을 변경하기 전에 클러스터가 정상 상태인지 확인해야 합니다.
* 암호화를 비활성화하는 경우 드라이브의 암호화를 비활성화하는 키에 액세스하려면 두 개의 노드가 클러스터에 참여해야 합니다.




== 휴면 상태에서 암호화 확인

클러스터에서 암호화의 현재 상태 및/또는 소프트웨어 암호화의 현재 상태를 보려면 다음을 사용하십시오.link:../api/reference_element_api_getclusterinfo.html["클러스터 정보 가져오기"^] 방법.  당신은 사용할 수 있습니다link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["GetSoftwareEncryptionAtRestInfo"^] 클러스터가 저장 중인 데이터를 암호화하는 데 사용하는 정보를 가져오는 방법입니다.


NOTE: Element 소프트웨어 UI 대시보드 `https://<MVIP>/` 현재는 하드웨어 기반 암호화의 경우 암호화가 정지된 상태만 표시합니다.

.옵션
* <<하드웨어 기반 암호화를 휴면 상태로 활성화>>
* <<휴면 상태에서 소프트웨어 기반 암호화 활성화>>
* <<휴면 상태에서 하드웨어 기반 암호화 비활성화>>




== 하드웨어 기반 암호화를 휴면 상태로 활성화


NOTE: 외부 키 관리 구성을 사용하여 휴면 암호화를 활성화하려면 다음을 통해 휴면 암호화를 활성화해야 합니다.link:../api/reference_element_api_enableencryptionatrest.html["API"] .  기존 Element UI 버튼을 사용하도록 설정하면 내부적으로 생성된 키를 사용하게 됩니다.

. Element UI에서 *클러스터* > *설정*을 선택합니다.
. *저장 시 암호화 사용*을 선택합니다.




== 휴면 상태에서 소프트웨어 기반 암호화 활성화


NOTE: 클러스터에서 소프트웨어 암호화를 활성화한 후에는 비활성화할 수 없습니다.

. 클러스터 생성 중에 다음을 실행합니다.link:../api/reference_element_api_createcluster.html["클러스터 생성 방법"] ~와 함께 `enableSoftwareEncryptionAtRest` 로 설정 `true` .




== 휴면 상태에서 하드웨어 기반 암호화 비활성화

. Element UI에서 *클러스터* > *설정*을 선택합니다.
. *저장 시 암호화 비활성화*를 선택합니다.


[discrete]
== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

