---
permalink: storage/task_snapmirror_perform_failback_when_source_volume_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source volume, snapmirror 
summary: NetApp Element UI를 사용하여 원본 소스 볼륨을 다시 동기화하고 장애 복구할 수 있습니다.  이 절차는 원래 소스 볼륨이 여전히 존재하는 시나리오에 적용됩니다. 
---
= 소스 볼륨이 여전히 존재하는 경우 장애 복구를 수행합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UI를 사용하여 원본 소스 볼륨을 다시 동기화하고 장애 복구할 수 있습니다.  이 절차는 원래 소스 볼륨이 여전히 존재하는 시나리오에 적용됩니다.

. Element UI에서 장애 조치를 수행하기 위해 중단한 관계를 찾습니다.
. 작업 아이콘을 클릭하고 *역방향 재동기화*를 클릭합니다.
. 작업을 확인합니다.
+

NOTE: 역방향 재동기화 작업은 원본 볼륨과 대상 볼륨의 역할이 반전되는 새로운 관계를 생성합니다(원래 관계가 지속되므로 두 개의 관계가 생성됩니다).  원래 대상 볼륨의 모든 새 데이터는 역방향 재동기화 작업의 일부로 원래 소스 볼륨으로 전송됩니다.  대상 측에서 활성 볼륨에 계속 액세스하고 데이터를 쓸 수 있지만, 원본 볼륨에 대한 모든 호스트의 연결을 끊고 원래 기본 볼륨으로 리디렉션하기 전에 SnapMirror 업데이트를 수행해야 합니다.

. 방금 만든 역관계의 작업 아이콘을 클릭하고 *업데이트*를 클릭합니다.
+
이제 역방향 재동기화를 완료하고 대상 측 볼륨에 연결된 활성 세션이 없으며 최신 데이터가 원래 기본 볼륨에 있는지 확인했으므로 다음 단계를 수행하여 장애 복구를 완료하고 원래 기본 볼륨을 다시 활성화할 수 있습니다.

. 역관계의 동작 아이콘을 클릭하고 *해제*를 클릭합니다.
. 원래 관계의 작업 아이콘을 클릭하고 *재동기화*를 클릭합니다.
+

NOTE: 이제 원래의 기본 볼륨을 마운트하여 원래의 기본 볼륨에서 프로덕션 워크로드를 재개할 수 있습니다.  원래 SnapMirror 복제는 관계에 대해 구성된 정책 및 일정에 따라 재개됩니다.

. 원래 관계 상태가 "`snapmirrored`"인지 확인한 후, 역관계의 작업 아이콘을 클릭하고 *삭제*를 클릭합니다.




== 더 많은 정보를 찾아보세요

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror 장애 복구 시나리오]
