---
permalink: storage/task-element-replication-initialize-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, initialize, replication, relationship 
summary: 모든 관계 유형에 대해 초기화는 기준선 전송을 수행합니다. 즉, 소스 볼륨의 스냅샷 복사본을 만든 다음 해당 복사본과 참조하는 모든 데이터 블록을 대상 볼륨으로 전송합니다. 
---
= 복제 관계 초기화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 관계 유형에 대해 초기화는 _기준선 전송_을 수행합니다. 즉, 소스 볼륨의 스냅샷 복사본을 만든 다음 해당 복사본과 참조하는 모든 데이터 블록을 대상 볼륨으로 전송합니다.

.시작하기 전에
* 복제할 볼륨이 포함된 Element 노드는 ONTAP 에서 액세스할 수 있어야 합니다.
* SnapMirror 복제를 위해 Element 볼륨이 활성화되어 있어야 합니다.
* "`mirror-vault`" 정책 유형을 사용하는 경우 Element 스냅샷 복사본을 복제하려면 SnapMirror 레이블이 구성되어 있어야 합니다.
+
[NOTE]
====
이 작업은 다음에서만 수행할 수 있습니다.link:concept_snapmirror_labels.html["Element 소프트웨어 웹 UI"] 또는 사용link:../api/concept_element_api_snapshots_overview.html["API 메서드"] .

====


.이 작업에 관하여
양식에서 Element 소스 경로를 지정해야 합니다. `<hostip:>/lun/<name>` 여기서 "`lun`"은 실제 문자열 "`lun`"이고 `_name_` Element 볼륨의 이름입니다.

초기화에는 시간이 많이 걸릴 수 있습니다.  비수요 시간대에 기준 전송을 실행하는 것이 좋습니다.

[NOTE]
====
ONTAP 소스에서 Element 대상으로의 관계 초기화가 어떤 이유로든 실패하면 문제를 해결한 후에도(예: 잘못된 LUN 이름) 계속 실패합니다.  해결 방법은 다음과 같습니다.

. 관계를 삭제합니다.
. Element 대상 볼륨을 삭제합니다.
. 새로운 Element 대상 볼륨을 생성합니다.
. ONTAP 소스에서 Element 대상 볼륨으로 새로운 관계를 만들고 초기화합니다.


====
.단계
. 복제 관계를 초기화합니다.
+
`snapmirror initialize -source-path <hostip:>/lun/<name> -destination-path <SVM:volume|cluster://SVM/volume>`

+
전체 명령 구문은 매뉴얼 페이지를 참조하세요.

+
다음 예제에서는 소스 볼륨 간의 관계를 초기화합니다. `0005` IP 주소 10.0.0.11 및 대상 볼륨 `volA_dst` ~에 `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

