---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 스토리지 노드의 노드별 UI를 사용하여 지원 번들을 생성하거나 삭제하고, 드라이브의 구성 설정을 재설정하고, 네트워크 또는 클러스터 서비스를 다시 시작할 수 있습니다. 
---
= 노드별 UI를 사용하여 시스템 유틸리티 실행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 노드의 노드별 UI를 사용하여 지원 번들을 생성하거나 삭제하고, 드라이브의 구성 설정을 재설정하고, 네트워크 또는 클러스터 서비스를 다시 시작할 수 있습니다.

스토리지 노드의 노드별 UI에 로그인했습니다.

. *시스템 유틸리티*를 클릭하세요.
. 실행하려는 시스템 유틸리티의 버튼을 클릭하세요.
+
** *제어력*
+
노드를 재부팅하거나, 전원을 껐다가 켜거나, 종료합니다.

+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어집니다.

+
다음 매개변수를 지정하세요.

+
*** 작업: 옵션으로는 재시작 및 중지(전원 끄기)가 있습니다.
*** 웨이크업 지연: 노드가 다시 온라인 상태가 되기 전까지의 추가 시간입니다.


** *노드 로그 수집*
+
노드의 /tmp/bundles 디렉토리에 지원 번들을 생성합니다.

+
다음 매개변수를 지정하세요.

+
*** 번들 이름: 생성된 각 지원 번들에 대한 고유한 이름입니다.  이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
*** 추가 인수: 이 매개변수는 sf_make_support_bundle 스크립트에 전달됩니다.  이 매개변수는 NetApp 지원팀의 요청에 의해서만 사용되어야 합니다.
*** 시간 초과 초: 각 개별 ping 응답을 기다리는 시간(초)을 지정합니다.


** *노드 로그 삭제*
+
*클러스터 지원 번들 생성* 또는 CreateSupportBundle API 메서드를 사용하여 생성된 노드의 현재 지원 번들을 삭제합니다.

** *드라이브 재설정*
+
드라이브를 초기화하고 현재 드라이브에 있는 모든 데이터를 제거합니다.  기존 노드나 업그레이드된 노드에서 드라이브를 재사용할 수 있습니다.

+
다음 매개변수를 지정하세요:

+
*** 드라이브: 재설정할 장치 이름 목록(드라이브 ID 아님)


** *네트워크 구성 재설정*
+
개별 노드의 네트워크 구성 문제를 해결하고 개별 노드의 네트워크 구성을 공장 기본 설정으로 재설정합니다.

** *노드 재설정*
+
노드를 공장 설정으로 재설정합니다.  이 작업 동안 모든 데이터는 제거되지만 노드의 네트워크 설정은 보존됩니다.  노드는 클러스터에 할당되지 않고 사용 가능 상태인 경우에만 재설정할 수 있습니다.

+

IMPORTANT: 이 옵션을 사용하면 모든 데이터, 패키지(소프트웨어 업그레이드), 구성 및 로그 파일이 노드에서 삭제됩니다.

** *네트워킹 재시작*
+
노드의 모든 네트워크 서비스를 다시 시작합니다.

+

IMPORTANT: 이 작업으로 인해 네트워크 연결이 일시적으로 끊어질 수 있습니다.

** *서비스 재시작*
+
노드에서 Element 소프트웨어 서비스를 다시 시작합니다.

+

IMPORTANT: 이 작업으로 인해 노드 서비스가 일시적으로 중단될 수 있습니다.  이 작업은 NetApp 지원팀의 지시에 따라서만 수행해야 합니다.

+
다음 매개변수를 지정하세요.

+
*** 서비스: 다시 시작할 서비스 이름입니다.
*** 작업: 서비스에서 수행할 작업입니다.  옵션에는 시작, 중지, 다시 시작이 있습니다.





