---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 클러스터의 복원력을 향상시키기 위해 사용자 정의 보호 도메인을 구성할 수 있습니다. 
---
= 사용자 정의 보호 도메인 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
두 개 이상의 스토리지 노드가 포함된 Element 클러스터의 경우 각 노드에 대해 사용자 정의 보호 도메인을 구성할 수 있습니다.  사용자 지정 보호 도메인을 구성할 때 클러스터의 모든 노드를 도메인에 할당해야 합니다.


TIP: 보호 도메인을 할당하면 노드 간 데이터 동기화가 시작되고, 데이터 동기화가 완료될 때까지 일부 클러스터 작업을 사용할 수 없습니다.  클러스터에 대해 사용자 지정 보호 도메인을 구성한 후 새 스토리지 노드를 추가하면 노드에 대한 보호 도메인을 할당하고 데이터 동기화가 완료될 때까지 새 노드에 드라이브를 추가할 수 없습니다.  방문하세요link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["보호 도메인 문서"] 보호 도메인에 대해 자세히 알아보세요.


NOTE: 사용자 정의 보호 도메인 체계가 클러스터에 유용하려면 각 섀시 내의 모든 스토리지 노드를 동일한 사용자 정의 보호 도메인에 할당해야 합니다.  이를 위해서는 필요한 만큼의 사용자 정의 보호 도메인을 만들어야 합니다(가능한 가장 작은 사용자 정의 보호 도메인 구성표는 3개의 도메인입니다).  가장 좋은 방법은 도메인당 동일한 수의 노드를 구성하고 특정 도메인에 할당된 각 노드가 동일한 유형인지 확인하는 것입니다.

.단계
. *클러스터* > *노드*를 클릭합니다.
. *보호 도메인 구성*을 클릭합니다.
+
*사용자 정의 보호 도메인 구성* 창에서는 현재 구성된 보호 도메인(있는 경우)과 개별 노드에 대한 보호 도메인 할당을 볼 수 있습니다.

. 새로운 사용자 지정 보호 도메인의 이름을 입력하고 *만들기*를 클릭합니다.
+
새로 만들어야 하는 모든 보호 도메인에 대해 이 단계를 반복합니다.

. *노드 할당* 목록의 각 노드에 대해 *보호 도메인* 열의 드롭다운을 클릭하고 해당 노드에 할당할 보호 도메인을 선택합니다.
+

CAUTION: 변경 사항을 적용하기 전에 노드 및 섀시 레이아웃, 구성한 사용자 지정 보호 도메인 구성표, 데이터 보호에 대한 구성표의 영향을 이해했는지 확인하세요.  보호 도메인 체계를 적용하고 즉시 변경해야 하는 경우 구성이 적용된 후 발생하는 데이터 동기화로 인해 변경 작업을 완료하는 데 시간이 걸릴 수 있습니다.

. *보호 도메인 구성*을 클릭합니다.


.결과
클러스터 크기에 따라 도메인 간 데이터 동기화에 시간이 걸릴 수 있습니다.  데이터 동기화가 완료되면 *클러스터* > *노드* 페이지에서 사용자 지정 보호 도메인 할당을 볼 수 있으며, Element 웹 UI 대시보드의 *사용자 지정 보호 도메인 상태* 창에 클러스터의 보호 상태가 표시됩니다.

.가능한 오류
사용자 지정 보호 도메인 구성을 적용한 후 발생할 수 있는 오류는 다음과 같습니다.

|===


| 오류 | 설명 | 해결 


| SetProtectionDomainLayout 실패: ProtectionDomainLayout으로 인해 NodeID {9}를 사용할 수 없게 됩니다.  기본 이름과 기본이 아닌 이름을 함께 사용할 수 없습니다. | 노드에 보호 도메인이 할당되지 않았습니다. | 노드에 보호 도메인을 할당합니다. 


| SetProtectionDomainLayout 실패: 보호 도메인 유형 'custom'이 보호 도메인 유형 'chassis'를 분할합니다. | 다중 노드 섀시의 노드에는 섀시의 다른 노드와 다른 보호 도메인이 할당됩니다. | 섀시의 모든 노드에 동일한 보호 도메인이 할당되었는지 확인하세요. 
|===


== 더 많은 정보를 찾아보세요

* link:../concepts/concept_solidfire_concepts_data_protection.html#custom_pd["사용자 정의 보호 도메인"^]
* link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"^]

