---
permalink: storage/task_system_manage_cluster_ntp_configure.html 
sidebar: sidebar 
keywords: ntp, cluster, query, fqdn, dns server 
summary: '클러스터의 각 노드에 네트워크 시간 프로토콜(NTP) 서버에 업데이트를 쿼리하도록 지시할 수 있습니다.  클러스터는 구성된 서버에만 접속하여 해당 서버에서 NTP 정보를 요청합니다.' 
---
= 클러스터가 쿼리할 수 있도록 네트워크 시간 프로토콜 서버를 구성합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 각 노드에 NTP(네트워크 시간 프로토콜) 서버에 업데이트를 쿼리하도록 지시할 수 있습니다.  클러스터는 구성된 서버에만 접속하여 해당 서버에서 NTP 정보를 요청합니다.

NTP는 네트워크 상에서 시계를 동기화하는 데 사용됩니다.  내부 또는 외부 NTP 서버에 대한 연결은 초기 클러스터 설정의 일부여야 합니다.

클러스터에서 NTP를 구성하여 로컬 NTP 서버를 가리키도록 합니다.  IP 주소나 FQDN 호스트 이름을 사용할 수 있습니다.  클러스터 생성 시 기본 NTP 서버는 us.pool.ntp.org로 설정됩니다. 그러나 SolidFire 클러스터의 물리적 위치에 따라 이 사이트에 대한 연결이 항상 이루어지지 않을 수 있습니다.

FQDN을 사용할지는 개별 스토리지 노드의 DNS 설정이 제대로 작동하고 있는지 여부에 따라 달라집니다.  이를 위해 모든 스토리지 노드에서 DNS 서버를 구성하고 네트워크 포트 요구 사항 페이지를 검토하여 포트가 열려 있는지 확인하세요.

최대 5개의 다른 NTP 서버를 입력할 수 있습니다.


NOTE: IPv4와 IPv6 주소를 모두 사용할 수 있습니다.

.필요한 것
이 설정을 구성하려면 클러스터 관리자 권한이 있어야 합니다.

.단계
. 서버 설정에서 IP 및/또는 FQDN 목록을 구성합니다.
. 노드에 DNS가 올바르게 설정되었는지 확인하세요.
. *클러스터* > *설정*을 클릭합니다.
. 네트워크 시간 프로토콜 설정에서 *아니요*를 선택하면 표준 NTP 구성이 사용됩니다.
. *변경 사항 저장*을 클릭하세요.




== 더 많은 정보를 찾아보세요

* link:../storage/task_system_manage_cluster_ntp_configure_to_listen_for_ntp_broadcasts.html["NTP 브로드캐스트를 수신하도록 클러스터를 구성합니다."]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

