---
permalink: storage/task_data_manage_vol_access_group_create_an_initiator.html 
sidebar: sidebar 
keywords: initiator, create, fc, iscsi, aliases, chap 
summary: iSCSI 또는 파이버 채널 이니시에이터를 생성하고 선택적으로 별칭을 할당할 수 있습니다. 
---
= 개시자를 생성하세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
iSCSI 또는 파이버 채널 이니시에이터를 생성하고 선택적으로 별칭을 할당할 수 있습니다.

API 호출을 사용하여 이니시에이터 기반 CHAP 속성을 할당할 수도 있습니다.  이니시에이터당 CHAP 계정 이름과 자격 증명을 추가하려면 다음을 사용해야 합니다. `CreateInitiator` CHAP 액세스 및 속성을 제거하고 추가하는 API 호출입니다.  하나 이상의 virtualNetworkID를 지정하여 하나 이상의 VLAN으로 개시자 액세스를 제한할 수 있습니다. `CreateInitiators` 그리고 `ModifyInitiators` API 호출.  가상 네트워크가 지정되지 않으면 개시자는 모든 네트워크에 액세스할 수 있습니다.

자세한 내용은 API 참조 정보를 확인하세요. link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"]

.단계
. *관리* > *개시자*를 클릭합니다.
. *이니시에이터 만들기*를 클릭하세요.
. 단일 개시자 또는 여러 개시자를 생성하려면 다음 단계를 수행합니다.
+
[cols="25,75"]
|===
| 옵션 | 단계 


 a| 
단일 개시자 생성
 a| 
.. *단일 개시자 만들기*를 클릭합니다.
.. *IQN/WWPN* 필드에 개시자의 IQN 또는 WWPN을 입력합니다.
.. *별칭* 필드에 개시자의 친근한 이름을 입력하세요.
.. *이니시에이터 만들기*를 클릭하세요.




 a| 
여러 개의 개시자를 생성합니다
 a| 
.. *대량으로 개시자 생성*을 클릭하세요.
.. 텍스트 상자에 IQN 또는 WWPN 목록을 입력합니다.
.. *이니시에이터 추가*를 클릭합니다.
.. 결과 목록에서 개시자를 선택하고 *별칭* 열에서 해당 추가 아이콘을 클릭하여 개시자에 대한 별칭을 추가합니다.
.. 새 별칭을 확인하려면 확인 표시를 클릭하세요.
.. *이니시에이터 만들기*를 클릭하세요.


|===

