---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire 시스템은 볼륨을 사용하여 스토리지를 프로비저닝합니다.  볼륨은 iSCSI 또는 파이버 채널 클라이언트가 네트워크를 통해 액세스하는 블록 장치입니다. 
---
= 볼륨 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 시스템은 볼륨을 사용하여 스토리지를 프로비저닝합니다.  볼륨은 iSCSI 또는 파이버 채널 클라이언트가 네트워크를 통해 액세스하는 블록 장치입니다.

관리 탭의 볼륨 페이지에서 노드의 볼륨을 생성, 수정, 복제 및 삭제할 수 있습니다.



== 볼륨을 생성합니다

볼륨을 생성하고 해당 볼륨을 지정된 계정과 연결할 수 있습니다.  모든 볼륨은 계정과 연결되어야 합니다.  이 연결을 통해 계정은 CHAP 자격 증명을 사용하여 iSCSI 이니시에이터를 통해 볼륨에 액세스할 수 있습니다.

볼륨을 생성하는 동안 볼륨에 대한 QoS 설정을 지정할 수 있습니다.

. *관리* > *볼륨*을 선택합니다.
. *볼륨 생성*을 클릭합니다.
. *새 볼륨 만들기* 대화 상자에서 *볼륨 이름*을 입력합니다.
. 볼륨의 총 크기를 입력하세요.
+

NOTE: 기본 볼륨 크기 선택 단위는 GB입니다.  GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
** 1GB = 1,000,000,000바이트
** 1GiB = 1,073,741,824바이트


. 볼륨에 대한 *블록 크기*를 선택합니다.
. *계정* 드롭다운 목록을 클릭하고 볼륨에 액세스할 수 있는 계정을 선택합니다.
+
계정이 없으면 *계정 만들기* 링크를 클릭하고 새 계정 이름을 입력한 후 *만들기*를 클릭하세요.  계정이 생성되어 새 볼륨과 연결됩니다.

+

NOTE: 계정이 50개가 넘으면 목록이 나타나지 않습니다.  입력을 시작하면 자동완성 기능이 선택할 수 있는 가능한 값을 표시합니다.

. *서비스 품질*을 설정하려면 다음 중 하나를 수행하세요.
+
.. *정책*에서 기존 QoS 정책이 있는 경우 이를 선택할 수 있습니다.
.. *사용자 정의 설정*에서 IOPS에 대한 사용자 정의 최소값, 최대값 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+
최대 또는 버스트 IOPS 값이 20,000 IOPS보다 큰 볼륨에는 단일 볼륨에서 이 수준의 IOPS를 달성하려면 높은 대기열 깊이 또는 여러 세션이 필요할 수 있습니다.



. *볼륨 생성*을 클릭합니다.




== 볼륨 세부 정보 보기

. *관리* > *볼륨*을 선택합니다.
. 자세한 내용을 검토하세요.
+
** *ID*: 볼륨에 대한 시스템 생성 ID입니다.
** *이름*: 볼륨이 생성될 때 지정된 이름입니다.
** *계정*: 볼륨에 할당된 계정의 이름입니다.
** *액세스 그룹*: 볼륨이 속한 볼륨 액세스 그룹의 이름입니다.
** *액세스*: 볼륨이 생성될 때 할당된 액세스 유형입니다. 가능한 값:
+
*** 읽기/쓰기: 모든 읽기와 쓰기가 허용됩니다.
*** 읽기 전용: 모든 읽기 활동이 허용됩니다. 쓰기는 허용되지 않습니다.
*** 잠금: 관리자 접근만 허용됩니다.
*** 복제 대상: 복제된 볼륨 쌍의 대상 볼륨으로 지정됩니다.


** *사용됨*: 볼륨에서 사용된 공간의 백분율입니다.
** *크기*: 볼륨의 총 크기(GB)입니다.
** *기본 노드 ID*: 이 볼륨의 기본 노드입니다.
** *보조 노드 ID*: 이 볼륨의 보조 노드 목록입니다.  2차 노드의 변경과 같은 일시적인 상태에서는 여러 값이 될 수 있지만 일반적으로는 단일 값을 갖습니다.
** *QoS 제한*: 기본 스토리지 노드의 부하가 높아 볼륨이 제한되는지 여부를 식별합니다.
** *QoS 정책*: 사용자 정의 QoS 정책의 이름과 링크입니다.
** *최소 IOPS*: 볼륨에 대해 보장되는 최소 IOPS 수입니다.
** *최대 IOPS*: 볼륨에 허용되는 최대 IOPS 수입니다.
** *버스트 IOPS*: 볼륨에 대해 짧은 시간 동안 허용되는 최대 IOPS 수입니다.  기본값 = 15,000.
** *스냅샷*: 볼륨에 대해 생성된 스냅샷의 수입니다.
** *속성*: API 메서드를 통해 키/값 쌍으로 볼륨에 할당된 속성입니다.
** *512e*: 볼륨에서 512e가 활성화되어 있는지 여부를 나타냅니다. 가능한 값:
+
*** 예
*** 아니요


** *생성일*: 볼륨이 생성된 날짜와 시간입니다.






== 개별 볼륨 세부 정보 보기

개별 볼륨에 대한 성능 통계를 볼 수 있습니다.

. *보고* > *볼륨 성능*을 선택합니다.
. 볼륨 목록에서 볼륨의 작업 아이콘을 클릭합니다.
. *자세히 보기*를 클릭하세요.
+
페이지 하단에 볼륨에 대한 일반 정보가 담긴 트레이가 나타납니다.

. 해당 권에 대한 자세한 정보를 보려면 *자세히 보기*를 클릭하세요.
+
이 시스템은 볼륨에 대한 자세한 정보와 성능 그래프를 표시합니다.





== 활성 볼륨 편집

QoS 값, 볼륨 크기, 바이트 값이 계산되는 측정 단위 등의 볼륨 속성을 수정할 수 있습니다.  복제 사용을 위해 계정 액세스를 수정하거나 볼륨에 대한 액세스를 제한할 수도 있습니다.

다음 조건에서 클러스터에 충분한 공간이 있으면 볼륨 크기를 조정할 수 있습니다.

* 정상적인 작동 조건.
* 볼륨 오류나 오류가 보고되었습니다.
* 볼륨을 복제하고 있습니다.
* 볼륨이 다시 동기화되고 있습니다.


.단계
. *관리* > *볼륨*을 선택합니다.
. *활성* 창에서 편집하려는 볼륨의 작업 아이콘을 클릭합니다.
. *편집*을 클릭하세요.
. *선택 사항:* 볼륨의 전체 크기를 변경합니다.
+
** 볼륨의 크기를 늘릴 수는 있지만 줄일 수는 없습니다.  한 번의 크기 조정 작업에서는 볼륨 하나만 크기를 조정할 수 있습니다.  가비지 수집 작업과 소프트웨어 업그레이드는 크기 조정 작업을 방해하지 않습니다.
** 복제를 위해 볼륨 크기를 조정하는 경우 먼저 복제 대상으로 지정된 볼륨의 크기를 늘려야 합니다.  그런 다음 소스 볼륨의 크기를 조정할 수 있습니다.  대상 볼륨은 소스 볼륨보다 크거나 같을 수 있지만, 더 작을 수는 없습니다.


+
기본 볼륨 크기 선택 단위는 GB입니다.  GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
** 1GB = 1,000,000,000바이트
** 1GiB = 1,073,741,824바이트


. *선택 사항:* 다음 중 다른 계정 액세스 수준을 선택하세요.
+
** 읽기 전용
** 읽기/쓰기
** 잠김
** 복제 대상


. *선택 사항:* 볼륨에 액세스할 수 있는 계정을 선택하세요.
+
계정이 존재하지 않으면 *계정 만들기* 링크를 클릭하고 새 계정 이름을 입력한 후 *만들기*를 클릭하세요.  계정이 생성되어 볼륨과 연결됩니다.

+

NOTE: 계정이 50개가 넘으면 목록이 나타나지 않습니다.  입력을 시작하면 자동완성 기능이 선택할 수 있는 가능한 값을 표시합니다.

. *선택 사항:* *서비스 품질*에서 선택 사항을 변경하려면 다음 중 하나를 수행하세요.
+
.. *정책*에서 기존 QoS 정책이 있는 경우 이를 선택할 수 있습니다.
.. *사용자 정의 설정*에서 IOPS에 대한 사용자 정의 최소값, 최대값 및 버스트 값을 설정하거나 기본 QoS 값을 사용합니다.
+

NOTE: 볼륨에서 QoS 정책을 사용하는 경우 사용자 지정 QoS를 설정하여 볼륨과의 QoS 정책 제휴를 제거할 수 있습니다.  사용자 지정 QoS는 볼륨 QoS 설정에 대한 QoS 정책 값을 재정의하고 조정합니다.

+

TIP: IOPS 값을 변경할 때는 수십 또는 수백 단위로 증가시켜야 합니다.  입력 값에는 유효한 정수가 필요합니다.

+

TIP: 매우 높은 버스트 값으로 볼륨을 구성합니다.  이를 통해 시스템은 볼륨의 지속형 IOPS를 제한하면서도 가끔씩 발생하는 대규모 블록 순차적 작업 부하를 더 빠르게 처리할 수 있습니다.



. *변경 사항 저장*을 클릭하세요.




== 볼륨 삭제

Element 스토리지 클러스터에서 하나 이상의 볼륨을 삭제할 수 있습니다.

시스템은 삭제된 볼륨을 즉시 삭제하지 않습니다. 볼륨은 약 8시간 동안 사용 가능한 상태로 유지됩니다.  시스템에서 볼륨을 삭제하기 전에 볼륨을 복원하면 볼륨이 다시 온라인 상태가 되고 iSCSI 연결이 복원됩니다.

스냅샷을 만드는 데 사용된 볼륨이 삭제되면 연관된 스냅샷도 비활성화됩니다.  삭제된 소스 볼륨이 정리되면 연관된 비활성 스냅샷도 시스템에서 제거됩니다.


IMPORTANT: 관리 서비스와 연관된 영구 볼륨은 설치 또는 업그레이드 중에 생성되어 새 계정에 할당됩니다.  영구 볼륨을 사용하는 경우 볼륨이나 연결된 계정을 수정하거나 삭제하지 마세요.

.단계
. *관리* > *볼륨*을 선택합니다.
. 단일 볼륨을 삭제하려면 다음 단계를 수행하세요.
+
.. 삭제하려는 볼륨의 작업 아이콘을 클릭합니다.
.. 결과 메뉴에서 *삭제*를 클릭합니다.
.. 작업을 확인합니다.


+
시스템은 해당 볼륨을 *볼륨* 페이지의 *삭제됨* 영역으로 이동합니다.

. 여러 볼륨을 삭제하려면 다음 단계를 수행하세요.
+
.. 볼륨 목록에서 삭제하려는 볼륨 옆에 있는 상자를 선택합니다.
.. *대량 작업*을 클릭하세요.
.. 결과 메뉴에서 *삭제*를 클릭합니다.
.. 작업을 확인합니다.
+
시스템은 볼륨을 *볼륨* 페이지의 *삭제됨* 영역으로 이동합니다.







== 삭제된 볼륨 복원

볼륨이 삭제되었지만 아직 정리되지 않은 경우 시스템에서 볼륨을 복원할 수 있습니다.  시스템은 볼륨이 삭제된 후 약 8시간 후에 자동으로 볼륨을 정리합니다.  시스템에서 볼륨을 제거한 경우 복원할 수 없습니다.

. *관리* > *볼륨*을 선택합니다.
. 삭제된 볼륨 목록을 보려면 *삭제됨* 탭을 클릭하세요.
. 복원하려는 볼륨의 작업 아이콘을 클릭합니다.
. 결과 메뉴에서 *복원*을 클릭합니다.
. 작업을 확인합니다.
+
볼륨이 *활성* 볼륨 목록에 배치되고 볼륨에 대한 iSCSI 연결이 복원됩니다.





== 볼륨 제거

볼륨이 제거되면 시스템에서 영구적으로 제거됩니다.  볼륨의 모든 데이터가 손실됩니다.

시스템은 삭제된 볼륨을 삭제한 후 8시간이 지나면 자동으로 삭제합니다.  하지만 예약된 시간 전에 볼륨을 정리하려는 경우에는 그렇게 할 수 있습니다.

. *관리* > *볼륨*을 선택합니다.
. *삭제됨* 버튼을 클릭하세요.
. 단일 볼륨이나 여러 볼륨을 정리하는 단계를 수행합니다.
+
[cols="25,75"]
|===
| 옵션 | 단계 


 a| 
단일 볼륨을 제거합니다
 a| 
.. 삭제할 볼륨의 작업 아이콘을 클릭합니다.
.. *삭제*를 클릭하세요.
.. 작업을 확인합니다.




 a| 
여러 볼륨을 제거합니다
 a| 
.. 제거할 볼륨을 선택하세요.
.. *대량 작업*을 클릭하세요.
.. 나타나는 메뉴에서 *제거*를 선택합니다.
.. 작업을 확인합니다.


|===




== 볼륨 복제

단일 볼륨이나 여러 볼륨의 복제본을 만들어서 데이터의 특정 시점 복사본을 만들 수 있습니다.  볼륨을 복제하면 시스템은 볼륨의 스냅샷을 만든 다음 스냅샷에서 참조하는 데이터의 복사본을 만듭니다.  이는 비동기 프로세스이며, 프로세스에 필요한 시간은 복제하는 볼륨의 크기와 현재 클러스터 부하에 따라 달라집니다.

클러스터는 볼륨당 동시에 최대 2개의 실행 중인 복제 요청을 지원하고, 동시에 최대 8개의 활성 볼륨 복제 작업을 지원합니다.  이러한 제한을 초과하는 요청은 나중에 처리하기 위해 대기합니다.


NOTE: 운영 체제마다 복제된 볼륨을 처리하는 방식이 다릅니다.  VMware ESXi는 복제된 볼륨을 볼륨 복사본이나 스냅샷 볼륨으로 처리합니다.  볼륨은 새로운 데이터 저장소를 만드는 데 사용할 수 있는 장치입니다.  클론 볼륨 마운트 및 스냅샷 LUN 처리에 대한 자세한 내용은 VMware 설명서를 참조하세요. https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["VMFS 데이터 저장소 복사본 마운트"] 그리고 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["중복된 VMFS 데이터 저장소 관리"] .


IMPORTANT: 더 작은 크기로 복제하여 복제된 볼륨을 잘라내기 전에 해당 파티션이 더 작은 볼륨에 맞도록 준비해야 합니다.

.단계
. *관리* > *볼륨*을 선택합니다.
. 단일 볼륨을 복제하려면 다음 단계를 수행하세요.
+
.. *활성* 페이지의 볼륨 목록에서 복제하려는 볼륨의 작업 아이콘을 클릭합니다.
.. 결과 메뉴에서 *복제*를 클릭합니다.
.. *볼륨 복제* 창에서 새로 복제된 볼륨의 볼륨 이름을 입력합니다.
.. *볼륨 크기* 스핀 상자와 목록을 사용하여 볼륨의 크기와 치수를 선택합니다.
+

NOTE: 기본 볼륨 크기 선택 단위는 GB입니다.  GB 또는 GiB 단위로 측정된 크기를 사용하여 볼륨을 생성할 수 있습니다.

+
*** 1GB = 1,000,000,000바이트
*** 1GiB = 1,073,741,824바이트


.. 새로 복제된 볼륨에 대한 액세스 유형을 선택합니다.
.. *계정* 목록에서 새로 복제된 볼륨과 연결할 계정을 선택합니다.
+

NOTE: 이 단계에서 *계정 만들기* 링크를 클릭하고, 계정 이름을 입력한 다음 *만들기*를 클릭하면 계정을 만들 수 있습니다.  계정을 생성하면 시스템이 자동으로 해당 계정을 *계정* 목록에 추가합니다.



. 여러 볼륨을 복제하려면 다음 단계를 수행하세요.
+
.. *활성* 페이지의 볼륨 목록에서 복제하려는 볼륨 옆에 있는 상자를 선택합니다.
.. *대량 작업*을 클릭하세요.
.. 결과 메뉴에서 *복제*를 선택합니다.
.. *여러 볼륨 복제* 대화 상자에서 *새 볼륨 이름 접두사* 필드에 복제된 볼륨의 접두사를 입력합니다.
.. *계정* 목록에서 복제된 볼륨과 연결할 계정을 선택합니다.
.. 복제된 볼륨에 대한 액세스 유형을 선택합니다.


. *복제 시작*을 클릭합니다.
+

NOTE: 클론의 볼륨 크기를 늘리면 볼륨 끝에 추가 여유 공간이 있는 새 볼륨이 생성됩니다.  볼륨을 어떻게 사용하는지에 따라, 볼륨을 활용하기 위해 파티션을 확장하거나 여유 공간에 새 파티션을 만들어야 할 수도 있습니다.





== 더 많은 정보를 원하시면

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

