---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: 원격 클러스터에 대한 클러스터 관리자 자격 증명이 있는 경우 원격 클러스터의 다른 볼륨과 볼륨을 페어링할 수 있습니다. 
---
= 볼륨 ID를 사용하여 볼륨 페어링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 페어링할 두 클러스터 모두에 대한 클러스터 관리자 액세스 권한이 있는 경우 원격 클러스터의 다른 볼륨과 볼륨을 페어링할 수 있습니다. 이 방법은 원격 클러스터의 볼륨 ID를 사용하여 연결을 시작합니다.

.필요한 것
* 볼륨이 포함된 클러스터가 쌍을 이루고 있는지 확인하세요.
* 원격 클러스터에 새 볼륨을 생성합니다.
+

NOTE: 페어링 프로세스가 끝나면 복제 소스와 대상을 할당할 수 있습니다.  복제 소스 또는 대상은 볼륨 쌍의 볼륨일 수 있습니다.  데이터가 포함되지 않고 크기, 볼륨의 블록 크기 설정(512e 또는 4k), QoS 구성 등 소스 볼륨의 정확한 특성을 갖춘 대상 볼륨을 만들어야 합니다.  기존 볼륨을 복제 대상으로 할당하면 해당 볼륨의 데이터가 덮어쓰여집니다.  대상 볼륨은 소스 볼륨보다 크거나 같을 수 있지만, 더 작을 수는 없습니다.

* 대상 볼륨 ID를 알아보세요.


.단계
. *관리* > *볼륨*을 선택합니다.
. 페어링하려는 볼륨의 *작업* 아이콘을 클릭합니다.
. *페어링*을 클릭하세요.
. *볼륨 페어링* 대화 상자에서 *페어링 시작*을 선택합니다.
. 원격 클러스터에 액세스할 수 있음을 나타내려면 *동의*를 선택하세요.
. 목록에서 *복제 모드*를 선택하세요:
+
** *실시간(비동기)*: 쓰기는 소스 클러스터에서 커밋된 후 클라이언트에 확인됩니다.
** *실시간(동기식)*: 쓰기는 소스 및 대상 클러스터 모두에서 커밋된 후 클라이언트에 확인됩니다.
** *스냅샷만*: 소스 클러스터에서 생성된 스냅샷만 복제됩니다.  소스 볼륨의 활성 쓰기는 복제되지 않습니다.


. 목록에서 원격 클러스터를 선택하세요.
. 원격 볼륨 ID를 선택하세요.
. *페어링 시작*을 클릭하세요.
+
시스템은 원격 클러스터의 Element UI에 연결되는 웹 브라우저 탭을 엽니다.  클러스터 관리자 자격 증명을 사용하여 원격 클러스터에 로그인해야 할 수도 있습니다.

. 원격 클러스터의 Element UI에서 *페어링 완료*를 선택합니다.
. *볼륨 페어링 확인*에서 세부 정보를 확인하세요.
. *페어링 완료*를 클릭하세요.
+
페어링을 확인한 후 두 클러스터는 페어링을 위해 볼륨을 연결하는 프로세스를 시작합니다.  페어링 과정 중에 *볼륨 쌍* 창의 *볼륨 상태* 열에서 메시지를 볼 수 있습니다.  볼륨 쌍이 표시됩니다 `PausedMisconfigured` 볼륨 쌍 소스와 대상이 할당될 때까지.

+
페어링을 성공적으로 완료한 후에는 볼륨 표를 새로 고쳐 페어링된 볼륨의 *작업* 목록에서 *페어* 옵션을 제거하는 것이 좋습니다.  표를 새로 고치지 않으면 *쌍* 옵션은 선택 가능한 상태로 유지됩니다.  *페어* 옵션을 다시 선택하면 새 탭이 열리고 볼륨이 이미 페어링되어 있으므로 시스템에서 보고합니다. `StartVolumePairing Failed: xVolumeAlreadyPaired` Element UI 페이지의 *볼륨 쌍* 창에 오류 메시지가 표시됩니다.





== 더 많은 정보를 찾아보세요

* xref:reference_replication_volume_pairing_messages.adoc[볼륨 페어링 메시지]
* xref:reference_replication_volume_pairing_warnings.adoc[볼륨 페어링 경고]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[페어링된 볼륨에 복제 소스 및 대상 지정]

