---
permalink: storage/task_snapmirror_create_an_endpoint.html 
sidebar: sidebar 
keywords: element, endpoints, create, snapmirror, ui 
summary: 관계를 생성하려면 먼저 NetApp Element UI에서 SnapMirror 엔드포인트를 만들어야 합니다. 
---
= SnapMirror 엔드포인트 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관계를 생성하려면 먼저 NetApp Element UI에서 SnapMirror 엔드포인트를 만들어야 합니다.

SnapMirror 엔드포인트는 Element 소프트웨어를 실행하는 클러스터의 복제 대상 역할을 하는 ONTAP 클러스터입니다.  SnapMirror 관계를 생성하기 전에 먼저 SnapMirror 엔드포인트를 생성해야 합니다.

Element 소프트웨어를 실행하는 스토리지 클러스터에서 최대 4개의 SnapMirror 엔드포인트를 만들고 관리할 수 있습니다.


NOTE: 원래 API를 사용하여 기존 엔드포인트를 생성했고 자격 증명이 저장되지 않은 경우 Element UI에서 엔드포인트를 보고 해당 엔드포인트의 존재 여부를 확인할 수 있지만 Element UI를 사용하여 관리할 수는 없습니다.  이 엔드포인트는 Element API를 사용해서만 관리할 수 있습니다.

API 메소드에 대한 자세한 내용은 다음을 참조하세요. link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"].

.필요한 것
* 스토리지 클러스터의 Element UI에서 SnapMirror 활성화했어야 합니다.
* 엔드포인트에 대한 ONTAP 자격 증명을 알고 있습니다.


.단계
. *데이터 보호* > * SnapMirror 엔드포인트*를 클릭합니다.
. *엔드포인트 생성*을 클릭합니다.
. *새 엔드포인트 만들기* 대화 상자에서 ONTAP 시스템의 클러스터 관리 IP 주소를 입력합니다.
. 엔드포인트와 연결된 ONTAP 관리자 자격 증명을 입력합니다.
. 추가 세부 정보를 검토하세요:
+
** LIF: Element와 통신하는 데 사용되는 ONTAP 클러스터 간 논리 인터페이스를 나열합니다.
** 상태: SnapMirror 엔드포인트의 현재 상태를 보여줍니다.  가능한 값은 연결됨, 연결 해제됨, 관리되지 않음입니다.


. *엔드포인트 생성*을 클릭합니다.

