---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 더 많은 저장 공간이 필요하거나 클러스터를 생성한 후에 클러스터에 노드를 추가할 수 있습니다.  노드는 처음 전원을 켤 때 초기 구성이 필요합니다.  노드가 구성된 후에는 보류 중인 노드 목록에 나타나고 클러스터에 추가할 수 있습니다. 
---
= 클러스터에 노드 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
더 많은 저장 공간이 필요하거나 클러스터를 생성한 후에 클러스터에 노드를 추가할 수 있습니다.  노드는 처음 전원을 켤 때 초기 구성이 필요합니다.  노드가 구성된 후에는 보류 중인 노드 목록에 나타나고 클러스터에 추가할 수 있습니다.

클러스터의 각 노드에 있는 소프트웨어 버전은 호환되어야 합니다.  클러스터에 노드를 추가하면 클러스터는 필요에 따라 새 노드에 NetApp Element 소프트웨어의 클러스터 버전을 설치합니다.

기존 클러스터에 더 작거나 더 큰 용량의 노드를 추가할 수 있습니다.  클러스터에 더 큰 노드 용량을 추가하여 용량 증가를 허용할 수 있습니다.  작은 노드가 있는 클러스터에 큰 노드를 추가하려면 쌍으로 추가해야 합니다.  이를 통해 큰 노드 중 하나에 장애가 발생하더라도 Double Helix가 데이터를 이동할 수 있는 충분한 공간이 확보됩니다.  성능을 향상시키려면 더 큰 노드 클러스터에 더 작은 노드 용량을 추가할 수 있습니다.


NOTE: 새로 추가된 노드가 전체 클러스터 용량의 50% 이상을 차지하는 경우, 해당 노드의 일부 용량은 사용할 수 없게 됩니다("고착"). 이는 용량 규칙을 준수하기 위한 조치입니다.  더 많은 저장 공간이 추가될 때까지 이는 그대로 유지됩니다.  용량 규칙을 위반하는 매우 큰 노드가 추가되면 이전에 고립되었던 노드는 더 이상 고립되지 않지만 새로 추가된 노드는 고립됩니다.  이런 일이 일어나지 않도록 용량은 항상 쌍으로 추가해야 합니다.  노드가 고립되면 strandedCapacity 클러스터 오류가 발생합니다.

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp 비디오: 원하는 조건으로 확장: SolidFire 클러스터 확장"^]

NetApp HCI 어플라이언스에 노드를 추가할 수 있습니다.

.단계
. *클러스터* > *노드*를 선택합니다.
. 보류 중인 노드 목록을 보려면 *보류*를 클릭하세요.
+
노드 추가 프로세스가 완료되면 활성 노드 목록에 해당 노드가 나타납니다.  그때까지 보류 중인 노드는 보류 중인 활성 목록에 나타납니다.

+
SolidFire 클러스터에 노드를 추가하면 해당 노드에 클러스터의 Element 소프트웨어 버전을 설치합니다. 몇 분 정도 걸릴 수 있습니다.

. 다음 중 하나를 수행하세요.
+
** 개별 노드를 추가하려면 추가하려는 노드의 *작업* 아이콘을 클릭합니다.
** 여러 노드를 추가하려면 추가할 노드의 확인란을 선택한 다음 *대량 작업*을 선택합니다.  *참고:* 추가하는 노드에 클러스터에서 실행되는 Element 소프트웨어 버전과 다른 버전이 있는 경우, 클러스터는 노드를 클러스터 마스터에서 실행되는 Element 소프트웨어 버전으로 비동기적으로 업데이트합니다.  노드가 업데이트되면 자동으로 클러스터에 추가됩니다.  이 비동기 프로세스 동안 노드는 pendingActive 상태가 됩니다.


. *추가*를 클릭하세요.
+
노드가 활성 노드 목록에 나타납니다.





== 더 많은 정보를 찾아보세요

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[노드 버전 관리 및 호환성]
