---
permalink: storage/task_system_manage_rekey_software_ear_master_key.html 
sidebar: sidebar 
keywords: element, rekey, encryption at rest, rekey master, replace key 
summary: Element API를 사용하면 기존 키를 다시 키로 사용할 수 있습니다.  이 프로세스는 외부 키 관리 서버에 대한 새로운 대체 마스터 키를 생성합니다. 
---
= 휴면 마스터 키에서 소프트웨어 암호화 재키
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element API를 사용하면 기존 키를 다시 키로 사용할 수 있습니다.  이 프로세스는 외부 키 관리 서버에 대한 새로운 대체 마스터 키를 생성합니다.  마스터 키는 항상 새로운 마스터 키로 교체되며, 복제되거나 덮어쓰여지지 않습니다.

다음 절차 중 하나로 키를 다시 입력해야 할 수도 있습니다.

* 내부 키 관리에서 외부 키 관리로 변경하는 일환으로 새 키를 만듭니다.
* 보안 관련 이벤트에 대한 대응이나 보호 수단으로 새로운 키를 생성합니다.



NOTE: 이 프로세스는 비동기적으로 진행되며 재키 작업이 완료되기 전에 응답을 반환합니다.  당신은 사용할 수 있습니다link:../api/reference_element_api_getasyncresult.html["비동기 결과 가져오기"] 프로세스가 완료되었는지 확인하기 위해 시스템을 폴링하는 방법입니다.

.필요한 것
* 다음을 사용하여 휴면 상태의 소프트웨어 암호화를 활성화했습니다.link:../api/reference_element_api_createcluster.html["클러스터 생성"] 볼륨이 없고 I/O가 없는 새 클러스터에 대한 방법입니다.  링크 사용:../api/reference_element_api_getsoftwareencryptionatrestinfo.html[`GetSoftwareEncryptionatRestInfo` ] 상태가 확인됨 `enabled` 계속하기 전에.
* 당신은 가지고있다link:../storage/task_system_manage_key_set_up_external_key_management.html["신뢰 관계를 구축했다"] SolidFire 클러스터와 외부 키 서버(EKS) 사이.  실행하다link:../api/reference_element_api_testkeyserverkmip.html["테스트키공급자Kmip"] 키 공급자와의 연결이 설정되었는지 확인하는 방법입니다.


.단계
. 실행하다link:../api/reference_element_api_listkeyserverskmip.html["ListKeyProvidersKmip"] 명령을 입력하고 키 공급자 ID를 복사합니다.(`keyProviderID` ).
. 실행하다link:../api/reference_element_api_rekeysoftwareencryptionatrestmasterkey.html["RekeySoftwareEncryptionAtRestMasterKey"] 와 함께 `keyManagementType` 매개변수로 `external` 그리고 `keyProviderID` 이전 단계의 키 공급자 ID 번호와 같습니다.
+
[listing]
----
{
 "method": "rekeysoftwareencryptionatrestmasterkey",
 "params": {
   "keyManagementType": "external",
   "keyProviderID": "<ID number>"
 }
}
----
. 복사하다 `asyncHandle` 에서 가치 `RekeySoftwareEncryptionAtRestMasterKey` 명령 응답.
. 실행하다link:../api/reference_element_api_getasyncresult.html["비동기 결과 가져오기"] 명령으로 `asyncHandle` 이전 단계의 값을 사용하여 구성의 변경 사항을 확인합니다.  명령 응답을 통해 이전 마스터 키 구성이 새로운 키 정보로 업데이트되었음을 확인할 수 있습니다.  이후 단계에서 사용할 새 키 공급자 ID를 복사합니다.
+
[listing]
----
{
   "id": null,
   "result": {
     "createTime": "2021-01-01T22:29:18Z",
     "lastUpdateTime": "2021-01-01T22:45:51Z",
     "result": {
       "keyToDecommission": {
         "keyID": "<value>",
         "keyManagementType": "internal"
     },
     "newKey": {
       "keyID": "<value>",
       "keyManagementType": "external",
       "keyProviderID": <value>
     },
     "operation": "Rekeying Master Key. Master Key management being transferred from Internal Key Management to External Key Management with keyProviderID=<value>",
     "state": "Ready"
   },
   "resultType": "RekeySoftwareEncryptionAtRestMasterKey",
   "status": "complete"
}
----
. 실행하다 `GetSoftwareEncryptionatRestInfo` 새로운 키 세부 정보를 포함하여 확인하는 명령 `keyProviderID` , 업데이트되었습니다.
+
[listing]
----
{
   "id": null,
   "result": {
     "masterKeyInfo": {
       "keyCreatedTime": "2021-01-01T22:29:18Z",
       "keyID": "<updated value>",
       "keyManagementType": "external",
       "keyProviderID": <value>
     },
     "rekeyMasterKeyAsyncResultID": <value>
     "status": "enabled",
     "version": 1
   },
}
----


[discrete]
== 더 많은 정보를 찾아보세요

* link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

