---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 네트워크 구성에 변경 사항을 적용한 후 네트워크 설정의 변경 사항을 테스트할 수 있습니다.  테스트를 실행하여 스토리지 노드가 안정적이며 아무런 문제 없이 온라인으로 전환될 수 있는지 확인할 수 있습니다. 
---
= 노드별 UI를 사용하여 시스템 테스트 실행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크 구성에 변경 사항을 적용한 후 네트워크 설정의 변경 사항을 테스트할 수 있습니다.  테스트를 실행하여 스토리지 노드가 안정적이며 아무런 문제 없이 온라인으로 전환될 수 있는지 확인할 수 있습니다.

스토리지 노드의 노드별 UI에 로그인했습니다.

. *시스템 테스트*를 클릭하세요.
. 실행하려는 테스트 옆에 있는 *테스트 실행*을 클릭하거나 *모든 테스트 실행*을 선택합니다.
+

NOTE: 모든 테스트 작업을 실행하는 데는 시간이 많이 소요될 수 있으므로 NetApp 지원팀의 지시에 따라서만 수행해야 합니다.

+
** *연결된 앙상블 테스트*
+
데이터베이스 앙상블에 대한 연결성을 테스트하고 검증합니다.  기본적으로 테스트에서는 노드가 연결된 클러스터의 앙상블을 사용합니다.  혹은 연결성을 테스트하기 위해 다른 앙상블을 제공할 수도 있습니다.

** *테스트 커넥트 Mvip*
+
지정된 관리 가상 IP(MVIP) 주소에 ping을 보낸 다음 MVIP에 대한 간단한 API 호출을 실행하여 연결을 확인합니다.  기본적으로 테스트에서는 노드가 연결된 클러스터의 MVIP를 사용합니다.

** *테스트 커넥트 Svip*
+
네트워크 어댑터에 설정된 최대 전송 단위(MTU) 크기와 일치하는 인터넷 제어 메시지 프로토콜(ICMP) 패킷을 사용하여 지정된 스토리지 가상 IP(SVIP) 주소에 ping을 보냅니다.  그런 다음 iSCSI 초기자로 SVIP에 연결합니다.  기본적으로 테스트에서는 노드가 연결된 클러스터의 SVIP를 사용합니다.

** *하드웨어 구성 테스트*
+
모든 하드웨어 구성이 올바른지 테스트하고, 펌웨어 버전이 올바른지 검증하며, 모든 드라이브가 제대로 설치되어 실행되고 있는지 확인합니다.  이는 공장 테스트와 동일합니다.

+

NOTE: 이 테스트는 리소스를 많이 소모하므로 NetApp 지원팀에서 요청한 경우에만 실행해야 합니다.

** *로컬 연결 테스트*
+
각 노드에서 클러스터 IP(CIP)를 ping하여 클러스터의 다른 모든 노드에 대한 연결성을 테스트합니다.  이 테스트는 노드가 활성 클러스터의 일부인 경우에만 노드에 표시됩니다.

** *클러스터 찾기 테스트*
+
노드가 클러스터 구성에 지정된 클러스터를 찾을 수 있는지 확인합니다.

** *네트워크 구성 테스트*
+
구성된 네트워크 설정이 시스템에서 사용 중인 네트워크 설정과 일치하는지 확인합니다.  이 테스트는 노드가 클러스터에 적극적으로 참여할 때 하드웨어 오류를 감지하기 위한 것이 아닙니다.

** *테스트 핑*
+
지정된 호스트 목록에 ping을 보내거나, 아무것도 지정되지 않은 경우 클러스터에 등록된 모든 노드 목록을 동적으로 구축하고 간단한 연결을 위해 각 노드에 ping을 보냅니다.

** *원격 연결 테스트*
+
각 노드에서 클러스터 IP(CIP)를 ping하여 원격으로 연결된 클러스터의 모든 노드에 대한 연결성을 테스트합니다.  이 테스트는 노드가 활성 클러스터의 일부인 경우에만 노드에 표시됩니다.




