---
permalink: storage/task_monitor_system_alerts.html 
sidebar: sidebar 
keywords: system alerts, view, cluster faults, system errors 
summary: 시스템의 클러스터 오류나 오류에 대한 정보에 대한 알림을 볼 수 있습니다.  알림은 정보, 경고 또는 오류일 수 있으며 클러스터가 얼마나 잘 실행되고 있는지를 나타내는 좋은 지표입니다.  대부분의 오류는 자동으로 해결됩니다. 
---
= 시스템 알림 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템의 클러스터 오류나 오류에 대한 정보에 대한 알림을 볼 수 있습니다.  알림은 정보, 경고 또는 오류일 수 있으며 클러스터가 얼마나 잘 실행되고 있는지를 나타내는 좋은 지표입니다.  대부분의 오류는 자동으로 해결됩니다.

ListClusterFaults API 메서드를 사용하면 알림 모니터링을 자동화할 수 있습니다.  이를 통해 발생하는 모든 경고에 대한 알림을 받을 수 있습니다.

. Element UI에서 *보고* > *알림*을 선택합니다.
+
시스템은 30초마다 페이지의 알림을 새로 고칩니다.

+
모든 이벤트에 대해 다음 정보를 볼 수 있습니다.

+
|===


| 목 | 설명 


 a| 
ID
 a| 
클러스터 알림과 관련된 고유 ID입니다.



 a| 
심각성
 a| 
경고의 중요도. 가능한 값:

** 경고: 곧 주의가 필요할 수 있는 사소한 문제입니다.  시스템 업그레이드는 계속 허용됩니다.
** 오류: 성능 저하나 고가용성(HA) 손실을 초래할 수 있는 장애입니다.  일반적으로 오류는 서비스에 영향을 미치지 않습니다.
** 중대한: 서비스에 영향을 미치는 심각한 실패.  시스템에서 API 또는 클라이언트 I/O 요청을 처리할 수 없습니다.  이 상태에서 작업하면 잠재적으로 데이터가 손실될 수 있습니다.
** bestPractice: 권장되는 시스템 구성 모범 사례가 사용되지 않습니다.




 a| 
유형
 a| 
오류가 영향을 미치는 구성 요소입니다.  노드, 드라이브, 클러스터, 서비스 또는 볼륨이 될 수 있습니다.



 a| 
마디
 a| 
이 오류가 참조하는 노드의 노드 ID입니다.  노드 및 드라이브 오류에 포함되며, 그렇지 않은 경우 - (대시)로 설정됩니다.



 a| 
드라이브 ID
 a| 
이 오류가 참조하는 드라이브의 드라이브 ID입니다.  드라이브 오류에 포함되고, 그렇지 않은 경우 - (대시)로 설정됩니다.



 a| 
오류 코드
 a| 
오류의 원인을 나타내는 설명 코드입니다.



 a| 
세부
 a| 
추가 세부 정보가 포함된 오류 설명입니다.



 a| 
날짜
 a| 
오류가 기록된 날짜와 시간입니다.

|===
. 개별 알림에 대한 정보를 보려면 *세부 정보 표시*를 클릭하세요.
. 페이지의 모든 알림에 대한 세부 정보를 보려면 세부 정보 열을 클릭하세요.
+
시스템에서 경고가 해결되면 경고가 해결된 날짜를 포함한 경고에 대한 모든 정보가 해결됨 영역으로 이동됩니다.





== 더 많은 정보를 찾아보세요

* xref:reference_monitor_cluster_fault_codes.adoc[클러스터 오류 코드]
* link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"]

