---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 보안 액세스를 위해 볼륨 컬렉션에 이니시에이터를 매핑하여 볼륨 액세스 그룹을 만들 수 있습니다.  그런 다음 계정 CHAP 초기자 비밀번호와 대상 비밀번호를 사용하여 그룹의 볼륨에 대한 액세스 권한을 부여할 수 있습니다. 
---
= 볼륨 액세스 그룹 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 액세스를 위해 볼륨 컬렉션에 이니시에이터를 매핑하여 볼륨 액세스 그룹을 만들 수 있습니다.  그런 다음 계정 CHAP 초기자 비밀번호와 대상 비밀번호를 사용하여 그룹의 볼륨에 대한 액세스 권한을 부여할 수 있습니다.

초기자 기반 CHAP를 사용하는 경우 볼륨 액세스 그룹의 단일 초기자에 대한 CHAP 자격 증명을 추가하여 보안을 강화할 수 있습니다.  이를 통해 이미 존재하는 볼륨 액세스 그룹에 이 옵션을 적용할 수 있습니다.

.단계
. *관리* > *그룹 액세스*를 클릭합니다.
. *액세스 그룹 만들기*를 클릭합니다.
. *이름* 필드에 볼륨 액세스 그룹의 이름을 입력합니다.
. 다음 방법 중 하나로 볼륨 액세스 그룹에 개시자를 추가합니다.
+
[cols="25,75"]
|===
| 옵션 | 설명 


 a| 
파이버 채널 이니시에이터 추가
 a| 
.. '이니시에이터 추가'에서 '바인딩되지 않은 파이버 채널 이니시에이터' 목록에서 기존 파이버 채널 이니시에이터를 선택합니다.
.. *FC 초기자 추가*를 클릭합니다.
+

NOTE: 이 단계에서 *이니시에이터 생성* 링크를 클릭하고, 이니시에이터 이름을 입력한 다음 *생성*을 클릭하면 이니시에이터를 생성할 수 있습니다.  사용자가 개시자를 생성하면 시스템이 자동으로 개시자 목록에 개시자를 추가합니다.



형식 샘플은 다음과 같습니다.

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
iSCSI 이니시에이터 추가
 a| 
'이니시에이터 추가'에서 '이니시에이터' 목록에서 기존 이니시에이터를 선택합니다.  *참고:* 이 단계에서 *이니시에이터 생성* 링크를 클릭하고, 이니시에이터 이름을 입력한 다음 *생성*을 클릭하면 이니시에이터를 생성할 수 있습니다.  사용자가 개시자를 생성하면 시스템이 자동으로 개시자 목록에 개시자를 추가합니다.

형식 샘플은 다음과 같습니다.

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 볼륨의 작업 메뉴에서 *관리* > *볼륨* > *활성* 목록의 *세부 정보 보기*를 선택하면 각 볼륨의 개시자 IQN을 찾을 수 있습니다.

초기자를 수정할 때 requiredCHAP 속성을 True로 전환하여 대상 초기자 비밀번호를 설정할 수 있습니다.  자세한 내용은 ModifyInitiator API 메서드에 대한 API 정보를 참조하세요.

link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"]

|===
. *선택 사항:* 필요에 따라 더 많은 개시자를 추가합니다.
. 볼륨 추가에서 *볼륨* 목록에서 볼륨을 선택합니다.
+
해당 볼륨이 *첨부된 볼륨* 목록에 나타납니다.

. *선택 사항:* 필요에 따라 볼륨을 더 추가하세요.
. *액세스 그룹 만들기*를 클릭합니다.




== 더 많은 정보를 찾아보세요

xref:task_data_manage_vol_access_group_add_volumes.adoc[액세스 그룹에 볼륨 추가]
