---
permalink: storage/task_system_manage_fips_enable_fips_140_2_for_https.html 
sidebar: sidebar 
keywords: FIPS 140-2, enable fips, federal information processing standards, ncsm 
summary: EnableFeature API 메서드를 사용하면 HTTPS 통신에 대해 FIPS 140-2 운영 모드를 활성화할 수 있습니다. 
---
= 클러스터에서 HTTPS에 대해 FIPS 140-2를 활성화합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EnableFeature API 메서드를 사용하면 HTTPS 통신에 대해 FIPS 140-2 운영 모드를 활성화할 수 있습니다.

NetApp Element 소프트웨어를 사용하면 클러스터에서 FIPS(연방 정보 처리 표준) 140-2 운영 모드를 활성화할 수 있습니다.  이 모드를 활성화하면 NetApp 암호화 보안 모듈(NCSM)이 활성화되고 HTTPS를 통한 NetApp Element UI 및 API와의 모든 통신에 FIPS 140-2 레벨 1 인증 암호화가 활용됩니다.


IMPORTANT: FIPS 140-2 모드를 활성화한 후에는 비활성화할 수 없습니다.  FIPS 140-2 모드가 활성화되면 클러스터의 각 노드가 재부팅되고 자체 테스트를 통해 NCSM이 올바르게 활성화되어 있고 FIPS 140-2 인증 모드에서 작동하는지 확인합니다.  이로 인해 클러스터의 관리 및 스토리지 연결이 모두 중단됩니다.  신중하게 계획하고 해당 환경에서 암호화 메커니즘이 필요한 경우에만 이 모드를 활성화해야 합니다.

자세한 내용은 Element API 정보를 참조하세요.

다음은 FIPS를 활성화하기 위한 API 요청의 예입니다.

[listing]
----
{
  "method": "EnableFeature",
    "params": {
        "feature" : "fips"
    },
    "id": 1
}
----
이 작동 모드가 활성화되면 모든 HTTPS 통신은 FIPS 140-2 승인 암호를 사용합니다.



== 더 많은 정보를 찾아보세요

* xref:reference_system_manage_fips_ssl_cipher_changes.adoc[SSL 암호]
* link:../api/concept_element_api_about_the_api.html["Element API로 저장소 관리"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

