---
permalink: storage/task_replication_plan_cluster_and_volume_pairing.html 
sidebar: sidebar 
keywords: cluster, volume pairing, plan for, real-time replication 
summary: 실시간 원격 복제를 위해서는 Element 소프트웨어를 실행하는 두 개의 스토리지 클러스터를 페어링하고, 각 클러스터의 볼륨을 페어링하고, 복제를 검증해야 합니다.  복제가 완료되면 볼륨 관계를 삭제해야 합니다. 
---
= 실시간 복제를 위한 클러스터 및 볼륨 페어링 계획
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실시간 원격 복제를 위해서는 Element 소프트웨어를 실행하는 두 개의 스토리지 클러스터를 페어링하고, 각 클러스터의 볼륨을 페어링하고, 복제를 검증해야 합니다.  복제가 완료되면 볼륨 관계를 삭제해야 합니다.

.필요한 것
* 페어링할 클러스터 중 하나 또는 둘 다에 대한 클러스터 관리자 권한이 있어야 합니다.
* 페어링된 클러스터의 관리 네트워크와 스토리지 네트워크 모두에 있는 모든 노드 IP 주소는 서로 라우팅됩니다.
* 모든 페어링된 노드의 MTU는 동일해야 하며 클러스터 간에 엔드투엔드로 지원되어야 합니다.
* 두 스토리지 클러스터 모두 고유한 클러스터 이름, MVIP, SVIP 및 모든 노드 IP 주소를 가져야 합니다.
* 클러스터의 Element 소프트웨어 버전 차이는 주요 버전 하나보다 크지 않습니다.  차이가 더 크면 클러스터 중 하나를 업그레이드하여 데이터 복제를 수행해야 합니다.



NOTE: WAN 가속기 어플라이언스는 NetApp 에서 데이터 복제 시 사용하기에 적합한 것으로 인증되지 않았습니다.  이러한 어플라이언스는 데이터를 복제하는 두 클러스터 사이에 배포되는 경우 압축 및 중복 제거를 방해할 수 있습니다.  WAN 가속기 어플라이언스를 프로덕션 환경에 배포하기 전에 해당 어플라이언스의 효과를 완전히 검증해야 합니다.



== 더 많은 정보를 찾아보세요

* xref:task_replication_pair_clusters.adoc[복제를 위한 쌍 클러스터]
* xref:task_replication_pair_volumes.adoc[쌍 볼륨]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[페어링된 볼륨에 복제 소스 및 대상 지정]

