---
permalink: storage/task_replication_pair_cluster_using_pairing_key.html 
sidebar: sidebar 
keywords: remote replication, pairing key, pairing clusters 
summary: 로컬 클러스터에는 클러스터 관리자 액세스 권한이 있지만 원격 클러스터에는 액세스 권한이 없는 경우 페어링 키를 사용하여 클러스터를 페어링할 수 있습니다.  로컬 클러스터에서 페어링 키가 생성된 다음 원격 사이트의 클러스터 관리자에게 안전하게 전송되어 연결을 설정하고 실시간 복제를 위한 클러스터 페어링을 완료합니다. 
---
= 페어링 키를 사용하여 클러스터 페어링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
로컬 클러스터에는 클러스터 관리자 액세스 권한이 있지만 원격 클러스터에는 액세스 권한이 없는 경우 페어링 키를 사용하여 클러스터를 페어링할 수 있습니다.  로컬 클러스터에서 페어링 키가 생성된 다음 원격 사이트의 클러스터 관리자에게 안전하게 전송되어 연결을 설정하고 실시간 복제를 위한 클러스터 페어링을 완료합니다.

. 로컬 클러스터에서 *데이터 보호* > *클러스터 쌍*을 선택합니다.
. *클러스터 페어링*을 클릭합니다.
. *페어링 시작*을 클릭하고 원격 클러스터에 액세스할 수 없음을 나타내려면 *아니요*를 클릭합니다.
. *키 생성*을 클릭하세요.
+

NOTE: 이 작업을 수행하면 페어링을 위한 텍스트 키가 생성되고 로컬 클러스터에 구성되지 않은 클러스터 쌍이 생성됩니다.  절차를 완료하지 않으면 클러스터 쌍을 수동으로 삭제해야 합니다.

. 클러스터 페어링 키를 클립보드에 복사합니다.
. 원격 클러스터 사이트의 클러스터 관리자가 페어링 키에 액세스할 수 있도록 합니다.
+

NOTE: 클러스터 페어링 키에는 원격 복제를 위한 볼륨 연결을 허용하는 MVIP 버전, 사용자 이름, 비밀번호 및 데이터베이스 정보가 포함되어 있습니다.  이 키는 안전한 방식으로 처리되어야 하며, 사용자 이름이나 비밀번호에 대한 우발적 또는 보안되지 않은 액세스를 허용하는 방식으로 저장되어서는 안 됩니다.

+

IMPORTANT: 페어링 키의 문자를 수정하지 마세요.  키가 수정되면 무효화됩니다.

. 원격 클러스터에서 *데이터 보호* > *클러스터 쌍*을 선택합니다.
. *클러스터 페어링*을 클릭합니다.
. *페어링 완료*를 클릭하고 *페어링 키* 필드에 페어링 키를 입력합니다(붙여넣기가 권장되는 방법입니다).
. *페어링 완료*를 클릭하세요.




== 더 많은 정보를 찾아보세요

* xref:task_replication_pair_cluster_using_mvip.adoc[MVIP를 사용하여 클러스터 쌍 만들기]
* https://www.youtube.com/watch?v=1ljHAd1byC8&feature=youtu.be["클러스터 페어링 키를 사용하여 클러스터 페어링(비디오)"]

