---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 기존 볼륨 액세스 그룹에 개시자를 추가할 수 있습니다. 
---
= 볼륨 액세스 그룹에 단일 이니시에이터 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기존 볼륨 액세스 그룹에 개시자를 추가할 수 있습니다.

볼륨 액세스 그룹에 초기자를 추가하면 초기자는 해당 볼륨 액세스 그룹의 모든 볼륨에 액세스할 수 있습니다.


TIP: 각 볼륨의 개시자를 찾으려면 작업 아이콘을 클릭한 다음 활성 볼륨 목록에서 볼륨에 대한 *세부 정보 보기*를 선택합니다.

초기자 기반 CHAP를 사용하는 경우 볼륨 액세스 그룹의 단일 초기자에 대한 CHAP 자격 증명을 추가하여 보안을 강화할 수 있습니다.  이를 통해 이미 존재하는 볼륨 액세스 그룹에 이 옵션을 적용할 수 있습니다.

.단계
. *관리* > *그룹 액세스*를 클릭합니다.
. 편집하려는 액세스 그룹의 *작업* 아이콘을 클릭합니다.
. *편집*을 클릭하세요.
. 볼륨 액세스 그룹에 파이버 채널 초기자를 추가하려면 다음 단계를 수행하세요.
+
.. '이니시에이터 추가'에서 *바인딩되지 않은 파이버 채널 이니시에이터* 목록에서 기존 파이버 채널 이니시에이터를 선택합니다.
.. *FC 초기자 추가*를 클릭합니다.
+

NOTE: 이 단계에서 *이니시에이터 생성* 링크를 클릭하고, 이니시에이터 이름을 입력한 다음 *생성*을 클릭하면 이니시에이터를 생성할 수 있습니다.  사용자가 개시자를 생성하면 시스템이 자동으로 개시자를 *개시자* 목록에 추가합니다.

+
형식 샘플은 다음과 같습니다.



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. 볼륨 액세스 그룹에 iSCSI 이니시에이터를 추가하려면 이니시에이터 추가에서 *이니시에이터* 목록에서 기존 이니시에이터를 선택합니다.
+

NOTE: 이 단계에서 *이니시에이터 생성* 링크를 클릭하고, 이니시에이터 이름을 입력한 다음 *생성*을 클릭하면 이니시에이터를 생성할 수 있습니다.  사용자가 개시자를 생성하면 시스템이 자동으로 개시자를 *개시자* 목록에 추가합니다.

+
허용되는 개시자 IQN 형식은 다음과 같습니다. iqn.yyyy-mm, 여기서 y와 m은 숫자이고, 뒤에 숫자, 소문자 알파벳, 마침표(.), 콜론(:) 또는 대시(-)만 포함하는 텍스트가 옵니다.

+
형식 샘플은 다음과 같습니다.

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: 각 볼륨의 개시자 IQN을 찾으려면 *관리* > *볼륨* 활성 볼륨 페이지에서 작업 아이콘을 클릭한 다음 볼륨에 대한 *세부 정보 보기*를 선택합니다.

. *변경 사항 저장*을 클릭하세요.

