---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: '노드에 원격 IPMI 액세스 권한이 생기면 기본 IPMI(Intelligent Platform Management Interface) 관리자 비밀번호를 변경할 수 있습니다.  설치 업데이트가 있는 경우 이 작업을 수행하는 것이 좋습니다.' 
---
= 노드의 기본 IPMI 비밀번호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드에 원격 IPMI 액세스 권한이 생기면 기본 IPMI(Intelligent Platform Management Interface) 관리자 비밀번호를 변경할 수 있습니다.  설치 업데이트가 있는 경우 이 작업을 수행하는 것이 좋습니다.

노드에 대한 IPM 액세스 구성에 대한 자세한 내용은 다음을 참조하세요.link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["각 노드에 대한 IPMI 구성"^] .

다음 노드의 IPM 비밀번호를 변경할 수 있습니다.

* H410S 노드
* H610S 노드




== H410S 노드의 기본 IPMI 비밀번호 변경

IPMI 네트워크 포트를 구성하자마자 각 스토리지 노드의 IPMI 관리자 계정에 대한 기본 비밀번호를 변경해야 합니다.

.필요한 것
각 스토리지 노드에 대해 IPMI IP 주소를 구성했어야 합니다.

.단계
. IPMI 네트워크에 접속할 수 있는 컴퓨터에서 웹 브라우저를 열고 노드의 IPMI IP 주소로 이동합니다.
. 사용자 이름을 입력하세요 `ADMIN` 그리고 비밀번호 `ADMIN` 로그인 프롬프트에서.
. 로그인 후 *구성* 탭을 클릭하세요.
. *사용자*를 클릭합니다.
. 선택하세요 `ADMIN` 사용자를 클릭하고 *사용자 수정*을 클릭합니다.
. *비밀번호 변경* 확인란을 선택하세요.
. *비밀번호*와 *비밀번호 확인* 필드에 새 비밀번호를 입력하세요.
. *수정*을 클릭한 다음 *확인*을 클릭합니다.
. 기본 IPMI 암호가 있는 다른 H410S 노드에 대해서도 이 절차를 반복합니다.




== H610S 노드의 기본 IPMI 비밀번호 변경

IPMI 네트워크 포트를 구성하자마자 각 스토리지 노드의 IPMI 관리자 계정에 대한 기본 비밀번호를 변경해야 합니다.

.필요한 것
각 스토리지 노드에 대해 IPMI IP 주소를 구성했어야 합니다.

.단계
. IPMI 네트워크에 접속할 수 있는 컴퓨터에서 웹 브라우저를 열고 노드의 IPMI IP 주소로 이동합니다.
. 사용자 이름을 입력하세요 `root` 그리고 비밀번호 `calvin` 로그인 프롬프트에서.
. 로그인 후 페이지 왼쪽 상단에 있는 메뉴 탐색 아이콘을 클릭하여 사이드바 서랍을 엽니다.
. *설정*을 클릭하세요.
. *사용자 관리*를 클릭하세요.
. 목록에서 *관리자* 사용자를 선택합니다.
. *비밀번호 변경* 확인란을 활성화합니다.
. *비밀번호* 및 *비밀번호 확인* 필드에 새롭고 강력한 비밀번호를 입력하세요.
. 페이지 하단의 *저장*을 클릭하세요.
. 기본 IPMI 암호가 있는 다른 H610S 노드에 대해 이 절차를 반복합니다.




== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

