---
permalink: storage/task-element-replication-create-replication-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, element, source, destination 
summary: SnapMirror 사용하면 Element 볼륨의 스냅샷 복사본을 ONTAP 대상 시스템에 복제할 수 있습니다.  Element 사이트에서 재해가 발생하는 경우 ONTAP 시스템에서 클라이언트에 데이터를 제공한 다음 서비스가 복구되면 Element 소스 볼륨을 다시 활성화할 수 있습니다. 
---
= Element 소스에서 ONTAP 대상까지의 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 저장소의 소스 볼륨과 보조 저장소의 대상 볼륨 간의 관계를 _데이터 보호 관계_라고 합니다.  당신은 사용할 수 있습니다 `snapmirror create` Element 소스에서 ONTAP 대상으로, 또는 ONTAP 소스에서 Element 대상으로 데이터 보호 관계를 생성하는 명령입니다.

SnapMirror 사용하면 Element 볼륨의 스냅샷 복사본을 ONTAP 대상 시스템에 복제할 수 있습니다.  Element 사이트에서 재해가 발생하는 경우 ONTAP 시스템에서 클라이언트에 데이터를 제공한 다음 서비스가 복구되면 Element 소스 볼륨을 다시 활성화할 수 있습니다.

.시작하기 전에
* 복제할 볼륨이 포함된 Element 노드는 ONTAP 에서 액세스할 수 있어야 합니다.
* SnapMirror 복제를 위해 Element 볼륨이 활성화되어 있어야 합니다.
* "`mirror-vault`" 정책 유형을 사용하는 경우 Element 스냅샷 복사본을 복제하려면 SnapMirror 레이블이 구성되어 있어야 합니다.
+
[NOTE]
====
이 작업은 다음에서만 수행할 수 있습니다.link:concept_snapmirror_labels.html["Element 소프트웨어 웹 UI"] 또는 사용link:../api/concept_element_api_snapshots_overview.html["API 메서드"] .

====


.이 작업에 관하여
양식에서 Element 소스 경로를 지정해야 합니다. `<hostip:>/lun/<name>` 여기서 "`lun`"은 실제 문자열 "`lun`"이고 `name` Element 볼륨의 이름입니다.

Element 볼륨은 ONTAP LUN과 거의 동일합니다.  Element 소프트웨어와 ONTAP 간의 데이터 보호 관계가 초기화되면 SnapMirror Element 볼륨의 이름으로 LUN을 생성합니다.  LUN이 Element 소프트웨어에서 ONTAP 으로 복제하는 데 필요한 요구 사항을 충족하는 경우 SnapMirror 기존 LUN에 데이터를 복제합니다.

복제 규칙은 다음과 같습니다.

* ONTAP 볼륨에는 하나의 Element 볼륨의 데이터만 포함될 수 있습니다.
* ONTAP 볼륨에서 여러 Element 볼륨으로 데이터를 복제할 수 없습니다.


ONTAP 9.3 이하 버전에서는 대상 볼륨에 최대 251개의 스냅샷 복사본이 포함될 수 있습니다.  ONTAP 9.4 이상에서는 대상 볼륨에 최대 1019개의 스냅샷 복사본을 포함할 수 있습니다.

.단계
. 대상 클러스터에서 Element 소스에서 ONTAP 대상으로 복제 관계를 만듭니다.
+
`snapmirror create -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -schedule schedule -policy <policy>`

+
전체 명령 구문은 매뉴얼 페이지를 참조하세요.

+
다음 예제에서는 기본을 사용하여 SnapMirror DR 관계를 만듭니다. `MirrorLatest` 정책:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
다음 예제에서는 기본값을 사용하여 통합 복제 관계를 만듭니다. `MirrorAndVault` 정책:

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
다음 예제에서는 다음을 사용하여 통합 복제 관계를 만듭니다. `Unified7year` 정책:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
다음 예제에서는 사용자 정의를 사용하여 통합 복제 관계를 만듭니다. `my_unified` 정책:

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


.당신이 완료한 후
사용하다 `snapmirror show` SnapMirror 관계가 생성되었는지 확인하는 명령입니다.  전체 명령 구문은 매뉴얼 페이지를 참조하세요.
