---
permalink: storage/task-element-replication-create-relationship-element-destination.html 
sidebar: sidebar 
keywords: ontap, cli, create, relationship, replication, snapmirror 
summary: ONTAP 9.4부터 SnapMirror 사용하여 ONTAP 소스에서 생성된 LUN의 스냅샷 복사본을 Element 대상으로 다시 복제할 수 있습니다.  ONTAP 에서 Element 소프트웨어로 데이터를 마이그레이션하기 위해 LUN을 사용하고 있을 수 있습니다. 
---
= ONTAP 소스에서 Element 대상까지의 관계 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.4부터 SnapMirror 사용하여 ONTAP 소스에서 생성된 LUN의 스냅샷 복사본을 Element 대상으로 다시 복제할 수 있습니다.  ONTAP 에서 Element 소프트웨어로 데이터를 마이그레이션하기 위해 LUN을 사용하고 있을 수 있습니다.

.시작하기 전에
* Element 대상 노드는 ONTAP 에서 접근 가능해야 합니다.
* SnapMirror 복제를 위해 Element 볼륨이 활성화되어 있어야 합니다.


.이 작업에 관하여
양식에서 Element 대상 경로를 지정해야 합니다. `<hostip:>/lun/<name>` 여기서 "`lun`"은 실제 문자열 "`lun`"이고 `name` Element 볼륨의 이름입니다.

복제 규칙은 다음과 같습니다.

* 복제 관계에는 "async-mirror" 유형의 정책이 있어야 합니다.
+
기본 정책이나 사용자 지정 정책을 사용할 수 있습니다.

* iSCSI LUN만 지원됩니다.
* ONTAP 볼륨에서 Element 볼륨으로 두 개 이상의 LUN을 복제할 수 없습니다.
* ONTAP 볼륨에서 여러 Element 볼륨으로 LUN을 복제할 수 없습니다.


.단계
. ONTAP 소스에서 Element 대상으로 복제 관계를 만듭니다.
+
`snapmirror create -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -type XDP -schedule schedule -policy <policy>`

+
전체 명령 구문은 매뉴얼 페이지를 참조하세요.

+
다음 예제에서는 기본을 사용하여 SnapMirror DR 관계를 만듭니다. `MirrorLatest` 정책:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
다음 예제에서는 사용자 정의를 사용하여 SnapMirror DR 관계를 만듭니다. `my_mirror` 정책:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


.당신이 완료한 후
사용하다 `snapmirror show` SnapMirror 관계가 생성되었는지 확인하는 명령입니다.  전체 명령 구문은 매뉴얼 페이지를 참조하세요.
