---
permalink: storage/task_replication_pair_clusters.html 
sidebar: sidebar 
keywords: pair clusters, replication, connect clusters, data protection 
summary: '실시간 복제 기능을 사용하려면 첫 단계로 두 개의 클러스터를 페어링해야 합니다.  두 개의 클러스터를 페어링하고 연결한 후에는 한 클러스터의 활성 볼륨을 두 번째 클러스터로 지속적으로 복제하도록 구성하여 지속적인 데이터 보호(CDP)를 제공할 수 있습니다.' 
---
= 복제를 위한 쌍 클러스터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
실시간 복제 기능을 사용하려면 첫 단계로 두 개의 클러스터를 페어링해야 합니다.  두 개의 클러스터를 페어링하고 연결한 후에는 한 클러스터의 활성 볼륨을 두 번째 클러스터로 지속적으로 복제하도록 구성하여 지속적인 데이터 보호(CDP)를 제공할 수 있습니다.

.필요한 것
* 페어링할 클러스터 중 하나 또는 둘 다에 대한 클러스터 관리자 권한이 있어야 합니다.
* 모든 노드 MIP와 SIP는 서로 라우팅됩니다.
* 클러스터 간 왕복 지연 시간은 2000ms 미만입니다.
* 두 스토리지 클러스터 모두 고유한 클러스터 이름, MVIP, SVIP 및 모든 노드 IP 주소를 가져야 합니다.
* 클러스터의 Element 소프트웨어 버전 차이는 주요 버전 하나보다 크지 않습니다.  차이가 더 크면 클러스터 중 하나를 업그레이드하여 데이터 복제를 수행해야 합니다.



NOTE: 클러스터 페어링에는 관리 네트워크의 노드 간에 완전한 연결이 필요합니다.  복제에는 스토리지 클러스터 네트워크의 개별 노드 간 연결이 필요합니다.

최대 4개의 다른 클러스터와 하나의 클러스터를 페어링하여 볼륨을 복제할 수 있습니다.  클러스터 그룹 내의 클러스터를 서로 페어링할 수도 있습니다.



== MVIP 또는 페어링 키를 사용하여 클러스터 페어링

두 클러스터 모두에 클러스터 관리자 액세스 권한이 있는 경우 대상 클러스터의 MVIP를 사용하여 소스 및 대상 클러스터를 페어링할 수 있습니다.  클러스터 쌍의 한 클러스터에서만 클러스터 관리자 액세스가 가능한 경우 대상 클러스터에서 페어링 키를 사용하여 클러스터 페어링을 완료할 수 있습니다.

. 다음 방법 중 하나를 선택하여 클러스터를 페어링합니다.
+
** link:task_replication_pair_cluster_using_mvip.html["MVIP를 사용하여 클러스터 쌍 만들기"]: 두 클러스터 모두에 클러스터 관리자 액세스 권한이 있는 경우 이 방법을 사용합니다. 이 방법은 원격 클러스터의 MVIP를 사용하여 두 클러스터를 페어링합니다.
** link:task_replication_pair_cluster_using_pairing_key.html["페어링 키를 사용하여 클러스터 페어링"]: 클러스터 관리자가 클러스터 중 하나에만 액세스할 수 있는 경우 이 방법을 사용합니다. 이 방법은 대상 클러스터에서 클러스터 페어링을 완료하는 데 사용할 수 있는 페어링 키를 생성합니다.






== 더 많은 정보를 찾아보세요

xref:reference_prereq_network_port_requirements.adoc[네트워크 포트 요구 사항]
