---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: 지정된 간격으로 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다. 
---
= 스냅샷 일정 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지정된 간격으로 볼륨의 스냅샷이 자동으로 발생하도록 예약할 수 있습니다.

스냅샷 일정을 구성할 때 요일이나 월별 날짜를 기준으로 시간 간격을 선택할 수 있습니다.  반복 일정을 만들고 다음 스냅샷이 발생하기 전 날짜, 시간, 분을 지정할 수도 있습니다.

5분으로 나누어 떨어지지 않는 기간에 스냅샷을 실행하도록 예약하면, 스냅샷은 5분으로 나누어 떨어지는 다음 기간에 실행됩니다.  예를 들어, 스냅샷을 12:42:00 UTC에 실행되도록 예약하면 12:45:00 UTC에 실행됩니다.  5분 미만의 간격으로 스냅샷을 실행하도록 예약할 수 없습니다.

Element 12.5부터 UI에서 직렬 생성을 활성화하고 스냅샷을 FIFO(선입선출) 방식으로 보관하도록 선택할 수 있습니다.

* *직렬 생성 사용* 옵션은 한 번에 하나의 스냅샷만 복제되도록 지정합니다.  이전 스냅샷 복제가 진행 중일 때는 새 스냅샷을 만드는 데 실패합니다.  체크박스를 선택하지 않으면 다른 스냅샷 복제가 진행 중일 때에도 스냅샷 생성이 허용됩니다.
* *FIFO* 옵션은 일관된 수의 최신 스냅샷을 보관하는 기능을 추가합니다.  확인란을 선택하면 스냅샷이 FIFO 기반으로 보관됩니다.  FIFO 스냅샷 대기열이 최대 깊이에 도달하면 새로운 FIFO 스냅샷이 삽입될 때 가장 오래된 FIFO 스냅샷이 삭제됩니다.


.단계
. *데이터 보호* > *일정*을 선택하세요.
. *일정 만들기*를 선택하세요.
. *볼륨 ID CSV* 필드에 스냅샷 작업에 포함할 단일 볼륨 ID 또는 쉼표로 구분된 볼륨 ID 목록을 입력합니다.
. 새로운 일정 이름을 입력하세요.
. 일정 유형을 선택하고 제공된 옵션에서 일정을 설정하세요.
. *선택 사항:* 스냅샷 일정을 무기한 반복하려면 *반복 일정*을 선택하세요.
. *선택 사항:* *새 스냅샷 이름* 필드에 새 스냅샷의 이름을 입력합니다.
+
필드를 비워두면 시스템은 스냅샷이 생성된 시간과 날짜를 이름으로 사용합니다.

. *선택 사항:* 부모 볼륨이 페어링될 때 복제에서 스냅샷이 캡처되도록 하려면 *페어링 시 복제에 스냅샷 포함* 확인란을 선택합니다.
. *선택 사항:* 한 번에 하나의 스냅샷만 복제되도록 하려면 *직렬 생성 사용* 확인란을 선택합니다.
. 스냅샷의 보존 기간을 설정하려면 다음 옵션 중에서 선택하세요.
+
** *선택 사항:* 최신 스냅샷의 일관된 수를 유지하려면 *FIFO(선입선출)* 확인란을 선택합니다.
** *영구 보관*을 선택하면 스냅샷이 시스템에 무기한 보관됩니다.
** *보존 기간 설정*을 선택하고 날짜 스핀 상자를 사용하여 시스템이 스냅샷을 보관할 기간을 선택합니다.


. *일정 만들기*를 선택하세요.

