---
permalink: storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html 
sidebar: sidebar 
keywords: volume pairings, paired volumes, replication source, assign 
summary: 볼륨을 페어링한 후에는 소스 볼륨과 복제 대상 볼륨을 할당해야 합니다.  복제 소스 또는 대상은 볼륨 쌍의 볼륨일 수 있습니다.  소스 볼륨을 사용할 수 없게 되면 소스 볼륨으로 전송된 데이터를 원격 대상 볼륨으로 리디렉션하는 데도 이 절차를 사용할 수 있습니다. 
---
= 페어링된 볼륨에 복제 소스 및 대상 지정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 페어링한 후에는 소스 볼륨과 복제 대상 볼륨을 할당해야 합니다.  복제 소스 또는 대상은 볼륨 쌍의 볼륨일 수 있습니다.  소스 볼륨을 사용할 수 없게 되면 소스 볼륨으로 전송된 데이터를 원격 대상 볼륨으로 리디렉션하는 데도 이 절차를 사용할 수 있습니다.

.필요한 것
소스 및 대상 볼륨이 포함된 클러스터에 액세스할 수 있습니다.

.단계
. 소스 볼륨을 준비합니다.
+
.. 소스로 지정하려는 볼륨이 포함된 클러스터에서 *관리* > *볼륨*을 선택합니다.
.. 소스로 지정하려는 볼륨의 *작업* 아이콘을 클릭하고 *편집*을 클릭합니다.
.. *액세스* 드롭다운 목록에서 *읽기/쓰기*를 선택합니다.
+

IMPORTANT: 소스 및 대상 할당을 되돌리는 경우 이 작업을 수행하면 새 복제 대상이 할당될 때까지 볼륨 쌍에 다음 메시지가 표시됩니다. `PausedMisconfigured`

+
액세스를 변경하면 볼륨 복제가 일시 중지되고 데이터 전송이 중단됩니다.  두 사이트 모두에서 이러한 변경 사항을 조정했는지 확인하세요.

.. *변경 사항 저장*을 클릭하세요.


. 대상 볼륨을 준비하세요:
+
.. 대상으로 지정하려는 볼륨이 포함된 클러스터에서 *관리* > *볼륨*을 선택합니다.
.. 대상으로 지정하려는 볼륨에 대한 작업 아이콘을 클릭하고 *편집*을 클릭합니다.
.. *액세스* 드롭다운 목록에서 *복제 대상*을 선택합니다.
+

IMPORTANT: 기존 볼륨을 복제 대상으로 할당하면 해당 볼륨의 데이터가 덮어쓰여집니다.  데이터가 없고 크기, 512e 설정, QoS 구성 등 소스 볼륨의 정확한 특성을 갖춘 새로운 대상 볼륨을 사용해야 합니다.  대상 볼륨은 소스 볼륨보다 크거나 같을 수 있지만, 더 작을 수는 없습니다.

.. *변경 사항 저장*을 클릭하세요.






== 더 많은 정보를 찾아보세요

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[볼륨 ID를 사용하여 볼륨 페어링]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[페어링 키를 사용하여 볼륨 페어링]

