---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: NetApp Element UI를 사용하여 원본 소스 볼륨을 다시 동기화하고 장애 복구할 수 있습니다.  이 섹션은 원본 볼륨이 손실되었지만 원본 클러스터가 여전히 손상되지 않은 시나리오에 적용됩니다.  새 클러스터로 복원하는 방법에 대한 지침은 NetApp 지원 사이트의 설명서를 참조하세요. 
---
= 소스 볼륨이 더 이상 존재하지 않을 때 장애 복구를 수행합니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Element UI를 사용하여 원본 소스 볼륨을 다시 동기화하고 장애 복구할 수 있습니다.  이 섹션은 원본 볼륨이 손실되었지만 원본 클러스터가 여전히 손상되지 않은 시나리오에 적용됩니다.  새 클러스터로 복원하는 방법에 대한 지침은 NetApp 지원 사이트의 설명서를 참조하세요.

.필요한 것
* Element와 ONTAP 볼륨 사이에 복제 관계가 끊어졌습니다.
* Element 볼륨은 회복 불가능하게 손실되었습니다.
* 원래 볼륨 이름이 '찾을 수 없음'으로 표시됩니다.


.단계
. Element UI에서 장애 조치를 수행하기 위해 중단한 관계를 찾습니다.
+
*모범 사례:* SnapMirror 정책을 기록하고 원래 중단된 관계의 세부 정보를 일정에 추가하세요.  이 정보는 관계를 다시 만들 때 필요합니다.

. *작업* 아이콘을 클릭하고 *역방향 재동기화*를 클릭합니다.
. 작업을 확인합니다.
+

NOTE: 역방향 재동기화 작업은 원본 볼륨과 대상 볼륨의 역할이 반전되는 새로운 관계를 생성합니다(원래 관계가 지속되므로 두 개의 관계가 생성됩니다).  원래 볼륨이 더 이상 존재하지 않으므로 시스템은 원래 소스 볼륨과 동일한 볼륨 이름과 볼륨 크기를 가진 새로운 Element 볼륨을 생성합니다.  새 볼륨에는 sm-recovery라는 기본 QoS 정책이 할당되고 sm-recovery라는 기본 계정과 연결됩니다.  SnapMirror 에서 생성된 모든 볼륨의 계정 및 QoS 정책을 수동으로 편집하여 파괴된 원본 볼륨을 대체해야 합니다.

+
최신 스냅샷의 데이터는 역방향 재동기화 작업의 일부로 새 볼륨으로 전송됩니다.  대상 측에서 활성 볼륨에 계속 액세스하고 데이터를 쓸 수 있지만, 이후 단계에서 원래 기본 관계를 복구하기 전에 활성 볼륨에 대한 모든 호스트의 연결을 끊고 SnapMirror 업데이트를 수행해야 합니다.  역방향 재동기화를 완료하고 대상 측 볼륨에 연결된 활성 세션이 없고 최신 데이터가 원래 기본 볼륨에 있는지 확인한 후 다음 단계를 계속 진행하여 장애 복구를 완료하고 원래 기본 볼륨을 다시 활성화합니다.

. 역방향 재동기화 작업 중에 생성된 역관계의 *작업* 아이콘을 클릭하고 *중단*을 클릭합니다.
. 소스 볼륨이 존재하지 않는 원래 관계의 *작업* 아이콘을 클릭하고 *삭제*를 클릭합니다.
. 4단계에서 끊은 역관계의 *작업* 아이콘을 클릭하고 *역방향 재동기화*를 클릭합니다.
. 이렇게 하면 소스와 대상이 바뀌고 원래 관계와 동일한 볼륨 소스 및 볼륨 대상이 있는 관계가 생성됩니다.
. *작업* 아이콘을 클릭하고 *편집*을 클릭하여 원래 QoS 정책 및 일정 설정으로 이 관계를 업데이트합니다.
. 이제 6단계에서 역동기화한 역관계를 안전하게 삭제할 수 있습니다.




== 더 많은 정보를 찾아보세요

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror 장애 복구 시나리오]
