---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: SolidFire 스토리지 시스템에서 테넌트는 계정을 사용하여 클라이언트가 노드의 볼륨에 연결하도록 할 수 있습니다.  계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP 인증이 포함되어 있습니다.  볼륨을 생성하면 특정 계정에 할당됩니다. 
---
= CHAP를 사용하여 계정 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire 스토리지 시스템에서 테넌트는 계정을 사용하여 클라이언트가 클러스터의 볼륨에 연결하도록 할 수 있습니다.  계정에는 할당된 볼륨에 액세스하는 데 필요한 CHAP(Challenge-Handshake 인증 프로토콜) 인증이 포함되어 있습니다.  볼륨을 생성하면 특정 계정에 할당됩니다.

한 계정에는 최대 2,000개의 볼륨이 할당될 수 있지만, 볼륨은 한 계정에만 속할 수 있습니다.



== CHAP 알고리즘

Element 12.7부터 보안 FIPS 호환 CHAP 알고리즘 SHA1, SHA-256, SHA3-256이 지원됩니다.  호스트 iSCSI 이니시에이터가 Element iSCSI 대상과 iSCSI 세션을 생성할 때 사용할 CHAP 알고리즘 목록을 요청합니다.  Element iSCSI 대상은 호스트 iSCSI 초기자가 요청한 목록에서 지원하는 첫 번째 알고리즘을 선택합니다.  Element iSCSI 대상이 가장 안전한 알고리즘을 선택하는지 확인하려면 호스트 iSCSI 초기자가 가장 안전한 알고리즘(예: SHA3-256)부터 가장 안전하지 않은 알고리즘(예: SHA1 또는 MD5) 순으로 정렬된 알고리즘 목록을 보내도록 구성해야 합니다.  호스트 iSCSI 초기자가 SHA 알고리즘을 요청하지 않으면 Element iSCSI 대상은 호스트의 제안된 알고리즘 목록에 MD5가 포함되어 있다고 가정하고 MD5를 선택합니다.  보안 알고리즘에 대한 지원을 활성화하려면 호스트 iSCSI 초기자 구성을 업데이트해야 할 수도 있습니다.

Element 12.7 이상 업그레이드 중에 SHA 알고리즘을 포함하는 목록으로 세션 요청을 보내도록 호스트 iSCSI 초기자 구성을 이미 업데이트한 경우, 스토리지 노드가 재부팅되면 새로운 보안 알고리즘이 활성화되고 가장 안전한 프로토콜을 사용하여 새 iSCSI 세션이나 다시 연결된 iSCSI 세션이 설정됩니다.  업그레이드하는 동안 모든 기존 iSCSI 세션은 MD5에서 SHA로 전환됩니다.  호스트 iSCSI 이니시에이터 구성을 SHA 요청으로 업데이트하지 않으면 기존 iSCSI 세션은 계속해서 MD5를 사용합니다.  나중에 호스트 iSCSI 이니시에이터 CHAP 알고리즘을 업데이트한 후에는 iSCSI 세션이 iSCSI 세션 재연결을 초래하는 유지 관리 활동을 기반으로 시간이 지남에 따라 MD5에서 SHA로 점진적으로 전환되어야 합니다.

예를 들어, Red Hat Enterprise Linux(RHEL) 8.3의 기본 호스트 iSCSI 초기자에는 다음이 있습니다. `node.session.auth.chap_algs = SHA3-256,SHA256,SHA1,MD5` 설정이 주석 처리되어 iSCSI 초기자가 MD5만 사용하게 됩니다.  호스트에서 이 설정의 주석 처리를 해제하고 iSCSI 초기자를 다시 시작하면 해당 호스트의 iSCSI 세션이 SHA3-256을 사용하기 시작합니다.

필요한 경우 다음을 사용할 수 있습니다. https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["ListISCSISessions"] 각 세션에 사용되는 CHAP 알고리즘을 확인하는 API 방법입니다.



== 계정을 생성하세요

볼륨에 대한 액세스를 허용하려면 계정을 만들 수 있습니다.

시스템의 각 계정 이름은 고유해야 합니다.

. *관리* > *계정*을 선택하세요.
. *계정 만들기*를 클릭하세요.
. *사용자 이름*을 입력하세요.
. *CHAP 설정* 섹션에 다음 정보를 입력하세요.
+

NOTE: 비밀번호가 자동으로 생성되도록 하려면 자격 증명 필드를 비워 두세요.

+
** CHAP 노드 세션 인증을 위한 *개시자 비밀*
** CHAP 노드 세션 인증을 위한 *대상 비밀*입니다.


. *계정 만들기*를 클릭하세요.




== 계정 세부 정보 보기

개별 계정의 성과 활동을 그래픽 형식으로 볼 수 있습니다.

그래프 정보는 해당 계정의 I/O 및 처리량 정보를 제공합니다.  평균 및 최대 활동 수준은 10초 보고 기간 단위로 표시됩니다.  이러한 통계에는 계정에 할당된 모든 볼륨에 대한 활동이 포함됩니다.

. *관리* > *계정*을 선택하세요.
. 계정의 작업 아이콘을 클릭합니다.
. *자세히 보기*를 클릭하세요.


자세한 내용은 다음과 같습니다.

* *상태*: 계정의 상태입니다. 가능한 값:
+
** 활성: 활성 계정.
** 잠김: 잠긴 계정.
** 제거됨: 삭제 및 정리된 계정입니다.


* *활성 볼륨*: 계정에 할당된 활성 볼륨의 수입니다.
* *압축*: 계정에 할당된 볼륨에 대한 압축 효율성 점수입니다.
* *중복 제거*: 계정에 할당된 볼륨에 대한 중복 제거 효율성 점수입니다.
* *씬 프로비저닝*: 계정에 할당된 볼륨에 대한 씬 프로비저닝 효율성 점수입니다.
* *전반적인 효율성*: 계정에 할당된 볼륨에 대한 전반적인 효율성 점수입니다.




== 계정 편집

계정을 편집하여 상태를 변경하고, CHAP 비밀번호를 변경하거나, 계정 이름을 수정할 수 있습니다.

계정에서 CHAP 설정을 수정하거나 액세스 그룹에서 이니시에이터 또는 볼륨을 제거하면 이니시에이터가 예기치 않게 볼륨에 액세스할 수 없게 될 수 있습니다.  볼륨 액세스가 예기치 않게 손실되지 않도록 하려면 계정이나 액세스 그룹 변경의 영향을 받는 iSCSI 세션에서 항상 로그아웃하고, 이니시에이터 설정과 클러스터 설정에 대한 변경이 완료된 후 이니시에이터가 볼륨에 다시 연결할 수 있는지 확인하세요.


IMPORTANT: 관리 서비스와 연관된 영구 볼륨은 설치 또는 업그레이드 중에 생성된 새 계정에 할당됩니다.  영구 볼륨을 사용하는 경우 연결된 계정을 수정하거나 삭제하지 마세요.

. *관리* > *계정*을 선택하세요.
. 계정의 작업 아이콘을 클릭합니다.
. 나타나는 메뉴에서 *편집*을 선택합니다.
. *선택 사항:* *사용자 이름*을 편집하세요.
. *선택 사항:* *상태* 드롭다운 목록을 클릭하고 다른 상태를 선택합니다.
+

IMPORTANT: 상태를 *잠김*으로 변경하면 해당 계정에 대한 모든 iSCSI 연결이 종료되고, 더 이상 계정에 액세스할 수 없습니다.  계정과 연결된 볼륨은 유지되지만 볼륨은 iSCSI에서 검색할 수 없습니다.

. *선택 사항:* *CHAP 설정*에서 노드 세션 인증에 사용되는 *개시자 비밀* 및 *대상 비밀* 자격 증명을 편집합니다.
+

NOTE: *CHAP 설정* 자격 증명을 변경하지 않으면 동일하게 유지됩니다.  자격 증명 필드를 비워 두면 시스템이 새로운 비밀번호를 생성합니다.

. *변경 사항 저장*을 클릭하세요.




== 계정 삭제

더 이상 필요하지 않은 계정은 삭제할 수 있습니다.

계정을 삭제하기 전에 해당 계정과 연관된 모든 볼륨을 삭제하고 정리하세요.


IMPORTANT: 관리 서비스와 연관된 영구 볼륨은 설치 또는 업그레이드 중에 생성된 새 계정에 할당됩니다.  영구 볼륨을 사용하는 경우 연결된 계정을 수정하거나 삭제하지 마세요.

. *관리* > *계정*을 선택하세요.
. 삭제하려는 계정의 작업 아이콘을 클릭합니다.
. 나타나는 메뉴에서 *삭제*를 선택합니다.
. 작업을 확인합니다.




== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

