---
permalink: storage/task-element-replication-define-rule-policy.html 
sidebar: sidebar 
keywords: ontap, cli, define, rule, policy 
summary: '"미러 볼트" 정책 유형이 있는 사용자 지정 정책의 경우 초기화 및 업데이트 중에 어떤 스냅샷 복사본이 전송되는지 결정하는 규칙을 하나 이상 정의해야 합니다.  "미러 볼트" 정책 유형을 사용하여 기본 정책에 대한 규칙을 정의할 수도 있습니다.' 
---
= 정책에 대한 규칙 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"`mirror-vault`" 정책 유형이 있는 사용자 지정 정책의 경우 초기화 및 업데이트 중에 어떤 스냅샷 복사본이 전송되는지 결정하는 규칙을 하나 이상 정의해야 합니다.  "`mirror-vault`" 정책 유형을 사용하여 기본 정책에 대한 규칙을 정의할 수도 있습니다.

.이 작업에 관하여
"`mirror-vault`" 정책 유형이 있는 모든 정책에는 복제할 스냅샷 복사본을 지정하는 규칙이 있어야 합니다.  예를 들어, "2개월마다" 규칙은 SnapMirror 레이블 "2개월마다"가 할당된 스냅샷 복사본만 복제해야 함을 나타냅니다.  Element 스냅샷 복사본을 구성할 때 SnapMirror 레이블을 할당합니다.

각 정책 유형은 하나 이상의 시스템 정의 규칙과 연결됩니다.  이러한 규칙은 정책 유형을 지정하면 자동으로 정책에 할당됩니다.  아래 표는 시스템에서 정의한 규칙을 보여줍니다.

|===


| 시스템 정의 규칙 | 정책 유형에 사용됨 | 결과 


 a| 
sm_created
 a| 
비동기 미러, 미러 볼트
 a| 
SnapMirror 에서 생성된 스냅샷 사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
일일
 a| 
거울 금고
 a| 
SnapMirror 레이블이 "`daily`"인 소스의 새로운 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
주간
 a| 
거울 금고
 a| 
SnapMirror 레이블이 "`주간`"인 소스의 새로운 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.



 a| 
월간 간행물
 a| 
거울 금고
 a| 
SnapMirror 레이블이 "`monthly`"인 소스의 새로운 스냅샷 복사본은 초기화 및 업데이트 시 전송됩니다.

|===
필요에 따라 기본 정책이나 사용자 지정 정책에 대한 추가 규칙을 지정할 수 있습니다. 예를 들어:

* 기본값의 경우 `MirrorAndVault` 정책을 사용하면 "`2개월마다`"라는 규칙을 만들어 소스의 스냅샷 복사본을 "2개월마다`" SnapMirror 레이블과 일치시킬 수 있습니다.
* "`mirror-vault`" 정책 유형이 있는 사용자 지정 정책의 경우, 소스의 스냅샷 복사본을 "`bi-weekly`" SnapMirror 레이블과 일치시키기 위해 "`bi-weekly`"라는 규칙을 만들 수 있습니다.


.단계
. 정책에 대한 규칙을 정의합니다.
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
전체 명령 구문은 매뉴얼 페이지를 참조하세요.

+
다음 예제에서는 SnapMirror 레이블이 있는 규칙을 추가합니다. `bi-monthly` 기본값으로 `MirrorAndVault` 정책:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
다음 예제에서는 SnapMirror 레이블이 있는 규칙을 추가합니다. `bi-weekly` 관습에 따라 `my_snapvault` 정책:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
다음 예제에서는 SnapMirror 레이블이 있는 규칙을 추가합니다. `app_consistent` 관습에 따라 `Sync` 정책:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
그런 다음 이 SnapMirror 레이블과 일치하는 소스 클러스터에서 스냅샷 복사본을 복제할 수 있습니다.

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

