---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 클러스터에 노드를 추가하려면 먼저 개별 노드를 구성해야 합니다.  랙 유닛에 노드를 설치하고 케이블을 연결한 후 전원을 켜면 노드별 UI나 노드 터미널 사용자 인터페이스를 사용하여 노드 네트워크 설정을 구성할 수 있습니다. 
---
= 스토리지 노드 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터에 노드를 추가하려면 먼저 개별 노드를 구성해야 합니다.  랙 유닛에 노드를 설치하고 케이블을 연결한 후 전원을 켜면 노드별 UI나 노드 터미널 사용자 인터페이스(TUI)를 사용하여 노드 네트워크 설정을 구성할 수 있습니다.  계속 진행하기 전에 노드에 필요한 네트워크 구성 정보가 있는지 확인하세요.

저장 노드를 구성하는 데는 두 가지 옵션이 있습니다.

* <<노드별 UI를 사용하여 스토리지 노드 구성,노드별 UI>>: 노드별 UI 사용 (`https://<node_management_IP>:442`) 노드 네트워크 설정을 구성합니다.
* <<TUI를 사용하여 스토리지 노드 구성,투이>>: 노드 터미널 사용자 인터페이스(TUI)를 사용하여 노드를 구성합니다.


DHCP가 할당된 IP 주소가 있는 노드를 클러스터에 추가할 수 없습니다.  DHCP IP 주소를 사용하여 노드별 UI, TUI 또는 API에서 노드를 처음 구성할 수 있습니다.  이 초기 구성 중에 정적 IP 주소 정보를 추가하여 노드를 클러스터에 추가할 수 있습니다.

초기 구성 후 노드의 관리 IP 주소를 사용하여 노드에 액세스할 수 있습니다.  그런 다음 노드 설정을 변경하고, 클러스터에 추가하거나, 노드를 사용하여 클러스터를 만들 수 있습니다.  Element 소프트웨어 API 메서드를 사용하여 새로운 노드를 구성할 수도 있습니다.


NOTE: Element 버전 11.0부터 노드는 관리 네트워크에 IPv4, IPv6 또는 두 주소 모두를 사용하여 구성할 수 있습니다.  이는 IPv6를 지원하지 않는 관리 노드 11.3 이상을 제외하고 저장 노드와 관리 노드 모두에 적용됩니다.  클러스터를 생성할 때 MVIP에는 단일 IPv4 또는 IPv6 주소만 사용할 수 있으며 모든 노드에서 해당 주소 유형을 구성해야 합니다.



== 노드별 UI를 사용하여 스토리지 노드 구성

노드별 사용자 인터페이스를 사용하여 노드를 구성할 수 있습니다.

.이 작업에 관하여
* 노드에 IPv4 또는 IPv6 주소를 설정할 수 있습니다.
* 노드에 액세스하려면 TUI에 표시된 DHCP 주소가 필요합니다.  DHCP 주소를 사용하여 클러스터에 노드를 추가할 수 없습니다.
+

IMPORTANT: 관리(Bond1G) 및 스토리지(Bond10G) 인터페이스는 별도의 서브넷에 대해 구성해야 합니다.  동일한 서브넷에 구성된 Bond1G 및 Bond10G 인터페이스는 Bond1G 인터페이스를 통해 스토리지 트래픽을 전송할 때 라우팅 문제를 일으킵니다.  관리 및 스토리지 트래픽에 동일한 서브넷을 사용해야 하는 경우 Bond10G 인터페이스를 사용하도록 관리 트래픽을 수동으로 구성하세요.  노드별 UI의 *클러스터 설정* 페이지를 사용하여 각 노드에 대해 이 작업을 수행할 수 있습니다.



.단계
. 브라우저 창에 노드의 DHCP IP 주소를 입력합니다.
+
확장자를 추가해야 합니다 `:442` 노드에 접근하려면 예를 들어, `https://172.25.103.6:442`.

+
*네트워크 설정* 탭이 *Bond1G* 섹션과 함께 열립니다.

. 1G 관리 네트워크 설정을 입력하세요.
. *변경 사항 적용*을 클릭하세요.
. *Bond10G*를 클릭하면 10G 저장 네트워크 설정이 표시됩니다.
. 10G 저장 네트워크 설정을 입력하세요.
. *변경 사항 적용*을 클릭하세요.
. *클러스터 설정*을 클릭합니다.
. 10G 네트워크의 호스트 이름을 입력하세요.
. 클러스터 이름을 입력하세요.
+

IMPORTANT: 클러스터를 생성하려면 먼저 모든 노드의 구성에 이 이름을 추가해야 합니다.  클러스터의 모든 노드는 동일한 클러스터 이름을 가져야 합니다.  클러스터 이름은 대소문자를 구분합니다.

. *변경 사항 적용*을 클릭하세요.




== TUI를 사용하여 스토리지 노드 구성

터미널 사용자 인터페이스(TUI)를 사용하여 새 노드에 대한 초기 구성을 수행할 수 있습니다.

Bond1G(관리) 및 Bond10G(저장) 인터페이스는 별도의 서브넷에 대해 구성해야 합니다.  동일한 서브넷에 대해 구성된 Bond1G 및 Bond10G 인터페이스는 Bond1G 인터페이스를 통해 스토리지 트래픽을 전송할 때 라우팅 문제를 일으킵니다.  관리 및 스토리지 트래픽에 동일한 서브넷을 사용해야 하는 경우 Bond10G 인터페이스를 사용하도록 관리 트래픽을 수동으로 구성하세요.  Element UI의 *클러스터* > *노드* 페이지를 사용하여 각 노드에 대해 이 작업을 수행할 수 있습니다.

.단계
. 노드에 키보드와 모니터를 연결한 다음 노드의 전원을 켭니다.
+
TUI의 NetApp Storage Main 메뉴는 tty1 터미널에 나타납니다.

+

NOTE: 노드가 구성 서버에 접속할 수 없는 경우 TUI는 오류 메시지를 표시합니다.  오류를 해결하려면 구성 서버 연결이나 네트워크 연결을 확인하세요.

. *네트워크* > *네트워크 구성*을 선택합니다.
+

TIP: 메뉴를 탐색하려면 위쪽 또는 아래쪽 화살표 키를 누르세요.  다른 버튼이나 버튼에서 필드로 이동하려면 *Tab*을 누르세요.  필드 사이를 이동하려면 위쪽 또는 아래쪽 화살표 키를 사용하세요.

. 노드의 1G 및 10G 네트워크 설정을 구성하려면 *Bond1G(관리)* 또는 *Bond10G(저장소)*를 선택합니다.
. 채권 모드와 상태 필드의 경우, *Tab* 키를 눌러 도움말 버튼을 선택하고 사용 가능한 옵션을 확인하세요.
+
클러스터의 모든 노드는 동일한 클러스터 이름을 가져야 합니다.  클러스터 이름은 대소문자를 구분합니다.  사용 가능한 IP 주소가 있는 네트워크에서 DHCP 서버가 실행 중인 경우 1GbE 주소가 주소 필드에 나타납니다.

. *Tab*을 눌러 *확인* 버튼을 선택하고 변경 사항을 저장합니다.
+
노드는 보류 상태가 되며 기존 클러스터나 새 클러스터에 추가될 수 있습니다.





== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

