---
permalink: setup/task_setup_create_a_storage_cluster.html 
sidebar: sidebar 
keywords:  
summary: 모든 개별 노드를 구성한 후에 스토리지 클러스터를 만들 수 있습니다.  클러스터를 생성하면 클러스터 관리자 사용자 계정이 자동으로 생성됩니다.  클러스터 관리자는 모든 클러스터 속성을 관리할 수 있는 권한이 있으며 다른 클러스터 관리자 계정을 만들 수 있습니다. 
---
= 스토리지 클러스터 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 개별 노드를 구성한 후에 스토리지 클러스터를 만들 수 있습니다.  클러스터를 생성하면 클러스터 관리자 사용자 계정이 자동으로 생성됩니다.  클러스터 관리자는 모든 클러스터 속성을 관리할 수 있는 권한이 있으며 다른 클러스터 관리자 계정을 만들 수 있습니다.

.필요한 것
* 관리 노드를 설치했습니다.
* 모든 개별 노드를 구성했습니다.


.이 작업에 관하여
새로운 노드 구성 중에 각 노드에 1G 또는 10G 관리 IP(MIP) 주소가 할당됩니다.  새 클러스터 만들기 페이지를 열려면 구성 중에 생성된 노드 IP 주소 중 하나를 사용해야 합니다.  사용하는 IP 주소는 클러스터 관리를 위해 선택한 네트워크에 따라 달라집니다.

[IMPORTANT]
====
클러스터 전체에서 활성화하려면link:../concepts/concept_solidfire_concepts_security.html#encryption-at-rest-software["휴면 상태의 소프트웨어 암호화"] SolidFire 올플래시 스토리지 클러스터의 경우 클러스터 생성 중에 이 작업을 수행해야 합니다.  Element 12.5부터 클러스터를 생성하는 동안 클러스터 생성 UI에서 소프트웨어 암호화를 활성화해야 합니다.  Element 12.3.x 및 이전 버전의 경우 다음을 사용하여 클러스터를 생성해야 합니다.link:../api/reference_element_api_createcluster.html["클러스터 생성"] API 메서드 및 enableSoftwareEncryptionAtRest 매개변수를 다음으로 변경합니다. `true` .  클러스터에서 휴면 상태의 소프트웨어 암호화가 활성화되면 비활성화할 수 없습니다.  당신은 할 수 있습니다link:../storage/task_system_manage_cluster_enable_and_disable_encryption_for_a_cluster.html["활성화 및 비활성화"] 클러스터 생성 후 하드웨어 기반 암호화를 실행합니다.

====
[NOTE]
====
새로운 클러스터를 만들 때 다음 사항을 고려하세요.

* 공유 섀시에 있는 스토리지 노드를 사용하는 경우 보호 도메인 기능을 사용하여 섀시 수준 장애 보호를 설계하는 것이 좋습니다.
* 공유 섀시를 사용하지 않는 경우 사용자 정의 보호 도메인 레이아웃을 정의할 수 있습니다.


====
.단계
. 브라우저 창에서 다음을 입력하세요. `\https://MIP:443` 여기서 MIP는 관리 노드 IP 주소입니다.
. 새 클러스터 만들기에서 다음 정보를 입력합니다.
+
** 관리 VIP: 네트워크 관리 작업을 위해 1GbE 또는 10GbE 네트워크에서 라우팅 가능한 가상 IP입니다.
+

NOTE: IPv4 또는 IPv6 주소를 사용하여 새 클러스터를 만들 수 있습니다.

** iSCSI(스토리지) VIP: 스토리지 및 iSCSI 검색을 위한 10GbE 네트워크의 가상 IP입니다.
+

NOTE: 클러스터를 생성한 후에는 MVIP, SVIP 또는 클러스터 이름을 변경할 수 없습니다.

** 사용자 이름: 클러스터에 대한 인증된 액세스를 위한 기본 클러스터 관리자 사용자 이름입니다.  나중에 참조할 수 있도록 사용자 이름을 저장해야 합니다.
+

NOTE: 사용자 이름과 비밀번호에는 대문자, 소문자, 특수문자, 숫자를 사용할 수 있습니다.

** 비밀번호: 클러스터에 대한 인증된 액세스를 위한 비밀번호입니다.  나중에 참조할 수 있도록 비밀번호를 저장해야 합니다.  기본적으로 양방향 데이터 보호가 활성화되어 있습니다.  이 설정은 변경할 수 없습니다.


. 최종 사용자 라이선스 계약을 읽고 *동의합니다*를 선택하세요.
. *선택 사항*: 노드 목록에서 클러스터에 포함되지 않아야 하는 노드의 확인란이 선택되어 있지 않은지 확인합니다.
. *클러스터 만들기*를 선택합니다.
+
클러스터의 노드 수에 따라 클러스터를 생성하는 데 몇 분이 걸릴 수 있습니다.  적절하게 구성된 네트워크에서는 5개의 노드로 구성된 소규모 클러스터가 1분도 걸리지 않습니다.  클러스터가 생성된 후 새 클러스터 생성 창이 클러스터의 MVIP URL 주소로 리디렉션되고 Element UI가 표시됩니다.





== 더 많은 정보를 원하시면

* link:../api/concept_element_api_about_the_api.html["Element API를 사용한 저장소 관리"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

