---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: 개별 파이버 채널 노드를 구성한 후 새 클러스터를 만들 수 있습니다.  클러스터를 생성하면 클러스터 관리자 사용자 계정이 자동으로 생성됩니다.  클러스터 관리자는 모든 클러스터 속성을 관리할 수 있는 권한이 있으며 다른 클러스터 관리자 계정을 만들 수 있습니다. 
---
= 파이버 채널 노드가 있는 새 클러스터를 만듭니다.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
개별 파이버 채널 노드를 구성한 후 새 클러스터를 만들 수 있습니다.  클러스터를 생성하면 클러스터 관리자 사용자 계정이 자동으로 생성됩니다.  클러스터 관리자는 모든 클러스터 속성을 관리할 수 있는 권한이 있으며 다른 클러스터 관리자 계정을 만들 수 있습니다.

새로운 노드 구성 중에 각 노드에 1G 또는 10G 관리 IP(MIP) 주소가 할당됩니다.  새 클러스터 만들기 페이지를 열려면 구성 중에 생성된 노드 IP 주소 중 하나를 사용해야 합니다.  사용하는 IP 주소는 클러스터 관리를 위해 선택한 네트워크에 따라 달라집니다.

.필요한 것
개별 파이버 채널 노드를 구성했습니다.

.단계
. 브라우저 창에 노드 MIP 주소를 입력합니다.
. 새 클러스터 만들기에서 다음 정보를 입력합니다.
+
** 관리 VIP: 네트워크 관리 작업을 위해 1GbE 또는 10GbE 네트워크에서 라우팅 가능한 가상 IP입니다.
** iSCSI(스토리지) VIP: 스토리지 및 iSCSI 검색을 위한 10GbE 네트워크의 가상 IP입니다.
+

NOTE: 클러스터를 생성한 후에는 SVIP를 변경할 수 없습니다.

** 사용자 이름: 클러스터에 대한 인증된 액세스를 위한 기본 클러스터 관리자 사용자 이름입니다.  나중에 참조할 수 있도록 사용자 이름을 저장해야 합니다.
+

NOTE: 사용자 이름에는 대문자, 소문자, 특수문자, 숫자를 사용할 수 있습니다.

** 비밀번호: 클러스터에 대한 인증된 액세스를 위한 비밀번호입니다.  나중에 참조할 수 있도록 사용자 이름을 저장해야 합니다.  기본적으로 양방향 데이터 보호가 활성화되어 있습니다.  이 설정은 변경할 수 없습니다.


. 최종 사용자 라이선스 계약을 읽고 *동의합니다*를 클릭하세요.
. *선택 사항*: 노드 목록에서 클러스터에 포함되지 않아야 하는 노드의 확인란이 선택되어 있지 않은지 확인합니다.
. *클러스터 만들기*를 클릭합니다.
+
클러스터의 노드 수에 따라 클러스터를 생성하는 데 몇 분이 걸릴 수 있습니다.  적절하게 구성된 네트워크에서는 5개의 노드로 구성된 소규모 클러스터가 1분도 걸리지 않습니다.  클러스터가 생성된 후 새 클러스터 생성 창이 클러스터의 MVIP URL 주소로 리디렉션되고 웹 UI가 표시됩니다.





== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/us-en/vcp/index.html["vCenter Server용 NetApp Element 플러그인"^]

