---
permalink: api/concept_element_api_asynchronous_methods.html 
sidebar: sidebar 
keywords: async,asynchronous,methods,API 
summary: 일부 API 메서드는 비동기적입니다. 즉, 메서드가 반환될 때 수행하는 작업이 완료되지 않을 수 있습니다.  비동기 메서드는 작업 상태를 확인하기 위해 쿼리할 수 있는 핸들을 반환합니다. 일부 작업의 상태 정보에는 완료율이 포함될 수 있습니다. 
---
= 비동기 메서드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 API 메서드는 비동기적입니다. 즉, 메서드가 반환될 때 수행하는 작업이 완료되지 않을 수 있습니다.  비동기 메서드는 작업 상태를 확인하기 위해 쿼리할 수 있는 핸들을 반환합니다. 일부 작업의 상태 정보에는 완료율이 포함될 수 있습니다.

비동기 작업을 쿼리하면 결과는 다음 유형 중 하나일 수 있습니다.

* `DriveAdd`: 시스템이 클러스터에 드라이브를 추가하고 있습니다.
* `BulkVolume`: 시스템은 백업이나 복원과 같은 볼륨 간 복사 작업을 수행하고 있습니다.
* `Clone`: 시스템이 볼륨을 복제하고 있습니다.
* `DriveRemoval`: 시스템은 클러스터에서 드라이브를 제거하기 위해 드라이브에서 데이터를 복사하고 있습니다.
* `RtfiPendingNode`: 시스템은 클러스터에 노드를 추가하기 전에 해당 노드에 호환 소프트웨어를 설치합니다.


비동기 메서드를 사용하거나 실행 중인 비동기 작업의 상태를 가져올 때 다음 사항에 유의하세요.

* 비동기 메서드는 개별 메서드 설명서에 표시됩니다.
* 비동기 메서드는 API 메서드에서 알려진 핸들인 "asyncHandle"을 반환합니다.  핸들을 사용하여 비동기 작업의 상태나 결과를 폴링할 수 있습니다.
* GetAsyncResult 메서드를 사용하면 개별 비동기 메서드의 결과를 얻을 수 있습니다.  GetAsyncResult를 사용하여 완료된 작업을 쿼리하면 시스템에서 결과를 반환하고 시스템에서 자동으로 결과를 제거합니다.  GetAsyncResult를 사용하여 완료되지 않은 작업을 쿼리하는 경우 시스템은 결과를 반환하지만 삭제하지는 않습니다.
* ListAsyncResults 메서드를 사용하면 실행 중이거나 완료된 모든 비동기 메서드의 상태와 결과를 얻을 수 있습니다.  이 경우 시스템은 완료된 작업에 대한 결과를 삭제하지 않습니다.




== 더 많은 정보를 찾아보세요

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

