---
permalink: api/reference_element_api_enableldapauthentication.html 
sidebar: sidebar 
keywords: LDAP,auth,authentication,enable,enabling,EnableLdapAuthentication 
summary: EnableLdapAuthentication 메서드를 사용하면 클러스터에 대한 LDAP 인증을 위해 LDAP 디렉터리 연결을 구성할 수 있습니다.  LDAP 디렉토리의 멤버인 사용자는 LDAP 자격 증명을 사용하여 스토리지 시스템에 로그인할 수 있습니다. 
---
= LDAP 인증 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `EnableLdapAuthentication` 클러스터에 대한 LDAP 인증을 위해 LDAP 디렉토리 연결을 구성하는 방법입니다.  LDAP 디렉토리의 멤버인 사용자는 LDAP 자격 증명을 사용하여 스토리지 시스템에 로그인할 수 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
인증 유형
 a| 
사용할 사용자 인증 방법을 식별합니다. 가능한 값:

* `DirectBind`
* `SearchAndBind`

 a| 
끈
 a| 
검색 및 바인딩
 a| 
아니요



 a| 
그룹검색기반DN
 a| 
그룹 하위 트리 검색을 시작할 트리의 기본 DN입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
그룹검색유형
 a| 
사용되는 기본 그룹 검색 필터를 제어합니다. 가능한 값:

* NoGroups: 그룹 지원이 없습니다.
* ActiveDirectory: 사용자의 모든 Active Directory 그룹에 대한 중첩된 멤버십입니다.
* MemberDN: MemberDN 스타일 그룹(단일 레벨).

 a| 
끈
 a| 
액티브 디렉토리
 a| 
아니요



 a| 
서버 URI
 a| 
LDAP 또는 LDAPS 서버 URI를 쉼표로 구분한 목록입니다.  콜론 뒤에 포트 번호를 사용하여 LDAP 또는 LDAPS URI 끝에 사용자 지정 포트를 추가할 수 있습니다.  예를 들어, URI "ldap://1.2.3.4"는 기본 포트를 사용하고 URI "ldaps://1.2.3.4:123"은 사용자 지정 포트 123을 사용합니다.
 a| 
문자열 배열
 a| 
None
 a| 
예



 a| 
사용자 검색 기반 DN
 a| 
하위 트리 검색을 시작할 트리의 기본 DN입니다.  SearchAndBind의 authType을 사용할 때 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
검색BindDN
 a| 
사용자에 대한 LDAP 검색을 수행하기 위해 로그인하는 데 필요한 완전한 DN입니다.  DN에는 LDAP 디렉토리에 대한 읽기 액세스 권한이 필요합니다.  SearchAndBind의 authType을 사용할 때 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
검색바인드패스워드
 a| 
검색에 사용되는 searchBindDN 계정의 비밀번호입니다.  SearchAndBind의 authType을 사용할 때 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
사용자 검색 필터
 a| 
LDAP 서버에 쿼리를 보낼 때 사용할 LDAP 검색 필터입니다.  문자열에는 인증하는 사용자의 사용자 이름으로 대체되는 플레이스홀더 텍스트 "%USERNAME%"이 있어야 합니다.  예를 들어, (&(objectClass=person)(sAMAccountName=%USERNAME%))는 Active Directory의 sAMAccountName 필드를 사용하여 클러스터 로그인 시 입력된 사용자 이름과 일치시킵니다.  SearchAndBind의 authType을 사용할 때 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
사용자 DNTemplate
 a| 
전체 사용자 고유 이름(DN)을 구성하기 위한 패턴을 정의하는 데 사용되는 문자열 템플릿입니다.  문자열에는 인증하는 사용자의 사용자 이름으로 대체되는 플레이스홀더 텍스트 "%USERNAME%"이 있어야 합니다.  DirectBind의 authType을 사용할 때 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
그룹검색커스텀필터
 a| 
CustomFilter 검색 유형과 함께 사용하여 사용자 그룹의 DN을 반환하는 데 사용할 LDAP 필터입니다.  문자열에는 %USERNAME%과 %USERDN%의 플레이스홀더 텍스트가 포함될 수 있으며, 필요에 따라 이를 사용자 이름과 전체 사용자 DN으로 바꿀 수 있습니다.
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "EnableLdapAuthentication",
  "params": {
     "authType": "SearchAndBind",
     "groupSearchBaseDN": "dc=prodtest,dc=solidfire,dc=net",
     "groupSearchType": "ActiveDirectory",
     "searchBindDN": "SFReadOnly@prodtest.solidfire.net",
     "searchBindPassword": "zsw@#edcASD12",
     "sslCert": "",
     "userSearchBaseDN": "dc=prodtest,dc=solidfire,dc=net",
     "userSearchFilter": "(&(objectClass=person)(sAMAccountName=%USERNAME%))",
     "serverURIs":[
           "ldaps://111.22.333.444",
           "ldap://555.66.777.888"
           ]
       },
  "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
"id": 1,
"result": {
  }
}
----


== 버전 이후 새로운

9.6
