---
permalink: api/reference_element_api_createvolume.html 
sidebar: sidebar 
keywords: create,volume,volumes,creating,CreateVolume 
summary: CreateVolume 메서드를 사용하면 클러스터에 새 빈 볼륨을 만들 수 있습니다.  볼륨 생성이 완료되면 iSCSI를 통해 볼륨을 연결할 수 있습니다. 
---
= 볼륨 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `CreateVolume` 클러스터에 새 빈 볼륨을 생성하는 방법입니다.  볼륨이 생성되면 iSCSI를 통해 볼륨을 연결할 수 있습니다.

QoS 값을 지정하지 않고 생성된 볼륨은 기본값을 사용합니다.  다음을 사용하여 볼륨의 기본값을 볼 수 있습니다. `GetDefaultQoS` 방법.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


| `access` | 볼륨에 대한 액세스 모드입니다.  이 매개변수가 포함된 경우 지원되는 유일한 값은 다음과 같습니다. `snapMirrorTarget` . | 끈 | None | 아니요 


| `accountID` | 이 볼륨을 소유한 계정의 ID입니다. | 정수 | None | 예 


| `associateWithQoSPolicy`  a| 
볼륨을 지정된 QoS 정책과 연결합니다. 가능한 값:

* `true`: QoSPolicyID 매개변수에 지정된 QoS 정책과 볼륨을 연결합니다.
* `false`: QoSPolicyID 매개변수에 지정된 QoS 정책과 볼륨을 연관시키지 마세요.  거짓인 경우 QoSPolicy 매개변수에서 QoS 정책을 지정했는지 여부에 관계없이 기존 정책 연결이 모두 제거됩니다.

| 부울 | true | 아니요 


| `attributes` | JSON 객체 형식의 이름-값 쌍 목록입니다.  JSON 형식 문자를 포함하여 전체 속성 크기는 1000B 또는 1KB 미만이어야 합니다. | JSON 객체 | None | 아니요 


| `dontMoveforIopsRebalance`  a| 
실제 IOPS로 부하를 분산할 때 볼륨이 이동하지 않도록 방지합니다.  이 설정은 Element 12.8부터 사용할 수 있으며 다음 경우에만 유효합니다.link:reference_element_api_enablefeature.html["실제 IOPS에 대한 볼륨 로드 밸런스"] 활성화되어 있습니다. 가능한 값:

* `true`: 볼륨은 실제 IOPS를 기준으로 부하를 분산하지 않습니다.
* `false`: 볼륨은 실제 IOPS를 기준으로 부하를 분산합니다.


*참고*: 고가용성(노드 장애)을 위한 밸런싱은 다음보다 우선합니다. `VolumeLoadBalanceOnActualIOPS` 그리고 `dontMoveforIopsRebalance` .
| 부울 | 거짓 | 아니요 


| `enable512e`  a| 
512바이트 섹터 에뮬레이션을 활성화합니다. 가능한 값:

* `true`: 이 볼륨은 512바이트 섹터 에뮬레이션을 제공합니다.
* `false`: 512e 에뮬레이션이 활성화되어 있지 않습니다.

| 부울 | None | 예 


| `enableSnapMirrorReplication`  a| 
SnapMirror 엔드포인트를 사용하여 볼륨을 복제하는 데 사용할 수 있는지 여부를 결정합니다. 가능한 값:

* `true`
* `false`

| 부울 | 거짓 | 아니요 


| `fifoSize` | 볼륨에서 지원하는 FIFO(선입선출) 스냅샷의 최대 수를 지정합니다.  FIFO 및 비 FIFO 스냅샷은 모두 볼륨에서 사용 가능한 스냅샷 슬롯의 동일한 풀을 사용합니다.  이 옵션을 사용하면 사용 가능한 스냅샷 슬롯의 FIFO 스냅샷 소비를 제한할 수 있습니다.  생략하면 기본값은 24입니다. | 정수 | 24 | 아니요 


| `minFifoSize` | 볼륨에서 예약된 FIFO(선입선출) 스냅샷 슬롯의 최소 수를 지정합니다.  이를 통해 볼륨에서 FIFO 스냅샷과 비 FIFO 스냅샷을 모두 사용하는 경우 비 FIFO 스냅샷이 의도치 않게 너무 많은 FIFO 슬롯을 사용하지 않도록 보장할 수 있습니다.  또한 이를 통해 최소한 이 수의 FIFO 스냅샷을 항상 사용할 수 있습니다.  FIFO 및 비 FIFO 스냅샷은 동일한 풀을 공유하므로 `minFifoSize` 가능한 비 FIFO 스냅샷의 총 개수를 동일한 양만큼 줄입니다.  생략하면 값은 기본적으로 0이 됩니다. | 정수 | 0 | 아니요 


| `name` | 볼륨 액세스 그룹의 이름(사용자가 지정할 수 있음).  고유할 필요는 없지만 권장됩니다.  길이는 1~64자여야 합니다. | 끈 | None | 예 


| `qos`  a| 
이 볼륨에 대한 초기 서비스 품질 설정입니다.  아무것도 지정하지 않으면 기본값이 사용됩니다. 가능한 값:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

| QoS 객체 | None | 아니요 


| `qosPolicyID` | 지정된 볼륨에 QoS 설정을 적용해야 하는 정책의 ID입니다.  이 매개변수는 다음과 상호 배타적입니다. `qos` 매개변수. | 정수 | None | 아니요 


| `totalSize` | 볼륨의 총 크기(바이트)입니다.  크기는 가장 가까운 메가바이트로 반올림됩니다. | 정수 | None | 예 
|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
용량
 a| 
새로 생성된 볼륨에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_volume.adoc[용량]



 a| 
볼륨ID
 a| 
새로 생성된 볼륨의 볼륨ID입니다.
 a| 
정수



 a| 
곡선
 a| 
곡선은 키-값 쌍의 집합입니다.  키는 바이트 단위의 I/O 크기입니다.  값은 특정 I/O 크기에서 IOP를 수행하는 데 드는 비용을 나타냅니다.  곡선은 100 IOPS로 설정된 4096바이트 작업을 기준으로 계산됩니다.
 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "CreateVolume",
   "params": {
      "name": "testit",
      "accountID": 22,
      "dontMoveForIopsRebalance": true,
      "totalSize": 100000000000,
      "enable512e": false,
      "attributes": {},
      "qos": {
         "minIOPS": 500,
         "maxIOPS": 27000,
         "burstIOPS": 27000,
         "burstTime": 60
      }
   },
   "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
    "id": 1,
    "result": {
        "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
        },
        "volume": {
            "access": "readWrite",
            "accountID": 22,
            "attributes": {},
            "blockSize": 4096,
            "createTime": "2024-04-02T13:03:02Z",
            "currentProtectionScheme": "doubleHelix",
            "deleteTime": "",
            "dontMoveForIopsRebalance": true,
            "enable512e": false,
            "enableSnapMirrorReplication": false,
            "fifoSize": 24,
            "iqn": "iqn.2010-01.com.solidfire:mysqldata.677",
            "lastAccessTime": null,
            "lastAccessTimeIO": null,
            "minFifoSize": 0,
            "name": "testit",
            "previousProtectionScheme": null,
            "purgeTime": "",
            "qos": {
                "burstIOPS": 27000,
                "burstTime": 60,
                "curve": {
                    "1048576": 15000,
                    "131072": 1950,
                    "16384": 270,
                    "262144": 3900,
                    "32768": 500,
                    "4096": 100,
                    "524288": 7600,
                    "65536": 1000,
                    "8192": 160
                },
                "maxIOPS": 27000,
                "minIOPS": 500
            },
            "qosPolicyID": null,
            "scsiEUIDeviceID": "3365657500000140f47acc0100000000",
            "scsiNAADeviceID": "6f47acc1000000003365657500000140",
            "sliceCount": 0,
            "status": "active",
            "totalSize": 1000000716800,
            "virtualVolumeID": null,
            "volumeAccessGroups": [],
            "volumeConsistencyGroupUUID": "8ed68e57-13ee-47df-8381-29b125142718",
            "volumeID": 320,
            "volumePairs": [],
            "volumeUUID": "e0e2c938-4ecd-4de9-a1be-f6b17c93ce5d"
        },
        "volumeID": 320
    }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_getdefaultqos.adoc[기본 QoS 가져오기]
