---
permalink: api/reference_element_api_initiator.html 
sidebar: sidebar 
keywords: object,objects,initiator 
summary: 이니시에이터 개체에는 iSCSI 또는 파이버 채널 이니시에이터에 대한 정보가 포함되어 있습니다.  개시자 객체에는 IQN 또는 WWPN 식별자가 포함될 수 있습니다.  ListInitiators 메서드를 사용하면 시스템에 알려진 모든 시작자 목록을 가져올 수 있습니다.  볼륨 액세스 그룹을 통해 볼륨 세트에 대한 SCSI 개시자 액세스를 구성하려면 개시자 개체를 사용합니다.  개시자는 한 번에 하나의 볼륨 액세스 그룹에만 속할 수 있습니다.  CreateInitiators 및 ModifyInitiators 메서드를 사용하여 하나 이상의 virtualNetworkID를 지정하여 하나 이상의 VLAN에 대한 개시자 액세스를 제한할 수 있습니다.  가상 네트워크를 지정하지 않으면 개시자는 모든 네트워크에 액세스할 수 있습니다. 
---
= 창시자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이니시에이터 개체에는 iSCSI 또는 파이버 채널 이니시에이터에 대한 정보가 포함되어 있습니다.  개시자 객체에는 IQN 또는 WWPN 식별자가 포함될 수 있습니다.  당신은 사용할 수 있습니다 `ListInitiators` 시스템에 알려진 모든 개시자 목록을 가져오는 방법입니다.  볼륨 액세스 그룹을 통해 볼륨 세트에 대한 SCSI 개시자 액세스를 구성하려면 개시자 개체를 사용합니다.  개시자는 한 번에 하나의 볼륨 액세스 그룹에만 속할 수 있습니다.  하나 이상의 virtualNetworkID를 지정하여 하나 이상의 VLAN에 대한 개시자 액세스를 제한할 수 있습니다. `CreateInitiators` 그리고 `ModifyInitiators` 행동 양식.  가상 네트워크를 지정하지 않으면 개시자는 모든 네트워크에 액세스할 수 있습니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
별명
 a| 
개시자에게 할당된 친근한 이름(있는 경우)입니다.
 a| 
끈



 a| 
속성
 a| 
이 시작자에게 할당된 JSON 속성 집합입니다.  속성이 할당되지 않으면 비어 있습니다.
 a| 
JSON 객체



 a| 
chapUsername
 a| 
이 개시자에 대한 고유한 CHAP 사용자 이름입니다.
 a| 
끈



 a| 
개시자ID
 a| 
개시자의 숫자 식별자입니다.
 a| 
정수



 a| 
개시자 이름
 a| 
IQN 또는 WWPN 형식의 개시자 이름입니다.
 a| 
끈



 a| 
개시자 비밀
 a| 
개시자를 인증하는 데 사용되는 CHAP 비밀번호입니다.
 a| 
끈



 a| 
요구 사항
 a| 
이 이니시에이터에 CHAP가 필요한 경우 True입니다.
 a| 
부울



 a| 
대상 비밀
 a| 
대상을 인증하는 데 사용되는 CHAP 비밀번호입니다(상호 CHAP 인증을 사용하는 경우).
 a| 
끈



 a| 
가상 네트워크 ID
 a| 
이 개시자와 연관된 가상 네트워크 식별자 목록입니다.  하나 이상이 정의된 경우, 이 개시자는 지정된 가상 네트워크에만 로그인할 수 있습니다.  가상 네트워크가 정의되지 않은 경우 이 개시자는 모든 네트워크에 로그인할 수 있습니다.
 a| 
정수



 a| 
볼륨액세스그룹
 a| 
이 개시자가 속한 볼륨 액세스 그룹 ID 목록입니다.
 a| 
정수 배열

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listinitiators.adoc[리스트이니시에이터]
