---
permalink: api/reference_element_api_volume.html 
sidebar: sidebar 
keywords: object,objects,volume 
summary: 볼륨 개체에는 페어링되지 않은 볼륨이나 페어링된 볼륨에 대한 구성 정보가 포함되어 있습니다.  여기에는 런타임이나 사용 정보가 포함되지 않으며, 가상 볼륨에 대한 정보도 포함되지 않습니다. 
---
= 용량
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 개체에는 페어링되지 않은 볼륨이나 페어링된 볼륨에 대한 구성 정보가 포함되어 있습니다.  여기에는 런타임이나 사용 정보가 포함되지 않으며, 가상 볼륨에 대한 정보도 포함되지 않습니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
입장
 a| 
볼륨에 허용된 액세스 유형입니다. 가능한 값:

* `readOnly`: 읽기 작업만 허용됩니다.
* `readWrite`: 읽기와 쓰기가 허용됩니다.
* `locked`: 읽기나 쓰기가 허용되지 않습니다.
* `replicationTarget`: 복제된 볼륨 쌍의 대상 볼륨으로 지정됨.

 a| 
끈



 a| 
계정ID
 a| 
볼륨이 포함된 계정의 accountID입니다.
 a| 
정수



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체



 a| 
블록 크기
 a| 
볼륨의 블록 크기.
 a| 
정수



 a| 
생성시간
 a| 
볼륨이 생성된 UTC+0 형식 시간입니다.
 a| 
ISO 8601 문자열



 a| 
현재 보호 계획
 a| 
이 권에 사용된 보호 체계입니다.  볼륨이 한 보호 체계에서 다른 보호 체계로 변환되는 경우, 이 멤버는 볼륨이 변환되는 보호 체계를 반영합니다.
 a| 
끈



 a| 
삭제시간
 a| 
볼륨이 삭제된 UTC+0 형식 시간입니다.
 a| 
ISO 8601 문자열



 a| 
enable512e
 a| 
true로 설정하면 볼륨은 512바이트 섹터 에뮬레이션을 제공합니다.
 a| 
부울



 a| 
enableSnapMirrorReplication
 a| 
볼륨을 SnapMirror 엔드포인트와 함께 복제에 사용할 수 있는지 여부입니다.
 a| 
부울



| fifoSize | FIFO(선입선출) 스냅샷 보존 모드를 사용하는 경우 볼륨의 스냅샷을 동시에 유지할 최대 개수를 지정합니다. | 정수 


 a| 
아이큐엔
 a| 
볼륨의 iSCSI 정규화된 이름입니다.
 a| 
끈



 a| 
마지막 접근 시간
 a| 
볼륨에 대한 마지막 액세스(I/O 포함) 시간(UTC+0으로 포맷됨).  마지막 액세스 시간을 알 수 없는 경우 이 값은 null입니다.
 a| 
ISO 8601 문자열



 a| 
마지막 액세스 시간IO
 a| 
볼륨에 대한 마지막 I/O가 발생한 시간(UTC+0으로 형식 지정).  마지막 액세스 시간을 알 수 없는 경우 이 값은 null입니다.
 a| 
ISO 8601 문자열



| 최소FifoSize | 볼륨에서 FIFO(선입선출) 스냅샷 보존 모드를 사용하는 경우 동시에 예약되는 FIFO(선입선출) 스냅샷 슬롯의 최소 수를 지정합니다. | 정수 


 a| 
이름
 a| 
생성 시 제공된 볼륨의 이름입니다.
 a| 
끈



 a| 
이전보호계획
 a| 
볼륨이 한 보호 체계에서 다른 보호 체계로 변환되는 경우, 이 멤버는 볼륨이 변환되는 보호 체계를 반영합니다.  이 멤버는 변환이 시작될 때까지 변경되지 않습니다.  볼륨이 변환된 적이 없으면 이 멤버는 null입니다.
 a| 
끈



 a| 
퍼지시간
 a| 
볼륨이 시스템에서 제거된 UTC+0 형식 시간입니다.
 a| 
ISO 8601 문자열



 a| 
qos
 a| 
이 볼륨에 대한 서비스 품질 설정입니다.
 a| 
xref:reference_element_api_qos.adoc[서비스 품질]



 a| 
qos정책ID
 a| 
볼륨과 연결된 QoS 정책 ID입니다.  볼륨이 정책과 연결되지 않은 경우 값은 null입니다.
 a| 
정수



 a| 
scsiEUIDeviceID
 a| 
EUI-64 기반 16바이트 형식의 볼륨에 대한 전역적으로 고유한 SCSI 장치 식별자입니다.
 a| 
끈



 a| 
scsiNAADeviceID
 a| 
NAA IEEE 등록 확장 형식의 볼륨에 대한 전역적으로 고유한 SCSI 장치 식별자입니다.
 a| 
끈



 a| 
슬라이스 개수
 a| 
볼륨의 슬라이스 수입니다.  이 값은 항상 "1"입니다.
 a| 
정수



 a| 
상태
 a| 
볼륨의 현재 상태입니다. 가능한 값:

* init: 초기화 중이며 연결할 준비가 되지 않은 볼륨입니다.
* 활성: 연결을 위해 준비된 활성 볼륨입니다.
* 삭제됨: 삭제 표시가 되어 있지만 아직 정리되지 않은 볼륨입니다.

 a| 
끈



 a| 
총 크기
 a| 
프로비저닝된 용량의 총 바이트입니다.
 a| 
정수



 a| 
가상볼륨ID
 a| 
볼륨과 연관된 고유한 가상 볼륨 ID(있는 경우)입니다.
 a| 
UUID



 a| 
볼륨액세스그룹
 a| 
볼륨이 속한 볼륨 액세스 그룹의 ID 목록입니다.  볼륨이 어떤 볼륨 액세스 그룹에도 속하지 않으면 이 값은 빈 목록입니다.
 a| 
정수 배열



 a| 
볼륨 일관성 그룹 UUID
 a| 
볼륨이 구성원인 볼륨 일관성 그룹의 범용 고유 ID입니다.
 a| 
UUID



 a| 
볼륨ID
 a| 
볼륨의 고유한 볼륨 ID입니다.
 a| 
정수



 a| 
볼륨 쌍
 a| 
쌍으로 된 볼륨에 대한 정보입니다.  볼륨이 페어링된 경우에만 표시됩니다.  볼륨이 페어링되지 않은 경우 이 값은 빈 목록입니다.
 a| 
xref:reference_element_api_volumepair.adoc[볼륨페어]정렬



 a| 
볼륨UUID
 a| 
볼륨의 범용 고유 ID입니다.
 a| 
UUID

|===


== 더 많은 정보를 찾아보세요

* xref:reference_element_api_listactivevolumes.adoc[ListActiveVolumes]
* xref:reference_element_api_listdeletedvolumes.adoc[삭제된 볼륨 목록]
* xref:reference_element_api_listvolumes.adoc[볼륨 목록]
* xref:reference_element_api_listvolumesforaccount.adoc[계정 볼륨 목록]
* xref:reference_element_api_qos.adoc[서비스 품질]

