---
permalink: api/reference_element_api_updatebulkvolumestatus.html 
sidebar: sidebar 
keywords: updatebulkvolumestatus,update,updating,bulk,volume,status,job 
summary: StartBulkVolumeRead 또는 StartBulkVolumeWrite 메서드로 시작한 대량 볼륨 작업의 상태를 업데이트하려면 UpdateBulkVolumeStatus 메서드를 사용할 수 있습니다. 
---
= 대량 볼륨 상태 업데이트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `UpdateBulkVolumeStatus` 시작한 대량 볼륨 작업의 상태를 업데이트하는 방법 `StartBulkVolumeRead` 또는 `StartBulkVolumeWrite` 행동 양식.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
열쇠
 a| 
초기화 중에 할당된 키xref:reference_element_api_startbulkvolumeread.adoc[대량 볼륨 읽기 시작] 또는xref:reference_element_api_startbulkvolumewrite.adoc[시작대량볼륨쓰기] 세션.
 a| 
끈
 a| 
None
 a| 
예



 a| 
상태
 a| 
시스템은 주어진 대량 볼륨 작업의 상태를 설정합니다. 가능한 값:

* 실행 중: 여전히 활성화된 작업입니다.
* 완료: 완료된 작업.
* 실패: 실패한 작업.

 a| 
끈
 a| 
None
 a| 
예



 a| 
완료율
 a| 
대량 작업의 완료 진행률을 백분율로 나타낸 것입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
메시지
 a| 
작업이 완료되면 대량 볼륨 작업의 상태를 반환합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
속성
 a| 
JSON 속성; 대량 볼륨 작업에 있는 내용을 업데이트합니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
상태
 a| 
요청된 세션의 상태입니다.  반환된 상태:

* 준비 중
* 활동적인
* 완료
* 실패한

 a| 
끈



 a| 
속성
 a| 
메서드 호출에서 지정된 속성을 반환합니다.  값은 변경 여부에 관계없이 반환됩니다.
 a| 
끈



 a| 
URL
 a| 
노드의 웹 서버에 접속하기 위한 URL입니다. 세션이 활성 상태인 경우에만 제공됩니다.
 a| 
끈

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "UpdateBulkVolumeStatus",
   "params": {
          "key": "0b2f532123225febda2625f55dcb0448",
	      "status": "running"
      },
   "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result": {
	  "status" : "running",
	  "url" : "https://10.10.23.47:8443/"
    }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_startbulkvolumeread.adoc[대량 볼륨 읽기 시작]
* xref:reference_element_api_startbulkvolumewrite.adoc[시작대량볼륨쓰기]

