---
permalink: api/reference_element_api_createschedule.html 
sidebar: sidebar 
keywords: CreateSchedule,create,creating,schedule,schedules,snapshot,snapshots,scheduling,automatic,volume,volumes 
summary: CreateSchedule을 사용하면 정의된 간격으로 볼륨의 자동 스냅샷을 예약할 수 있습니다. 
---
= 일정 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `CreateSchedule` 정의된 간격으로 볼륨의 자동 스냅샷을 예약합니다.

생성된 스냅샷을 나중에 백업이나 롤백으로 사용하여 스냅샷이 생성된 시점에 볼륨이나 볼륨 그룹의 데이터가 일관성을 유지하도록 할 수 있습니다.  5분으로 나누어 떨어지지 않는 기간에 스냅샷을 실행하도록 예약하면, 스냅샷은 5분으로 나누어 떨어지는 다음 기간에 실행됩니다.  예를 들어, 스냅샷을 12:42:00 UTC에 실행되도록 예약하면 12:45:00 UTC에 실행됩니다.  5분 미만의 간격으로 스냅샷을 실행하도록 예약할 수 없습니다.


NOTE: 클러스터 충만도가 1, 2 또는 3단계에 있는 경우 스냅샷을 만들 수 있습니다.  클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
`attributes`
 a| 
스냅샷의 빈도를 나타내려면 "`frequency`" 문자열을 사용합니다. 가능한 값:

* `Days of Week`
* `Days of Month`
* `Time Interval`

 a| 
JSON 객체
 a| 
None
 a| 
아니요



| `hasError` | *설명에 도움이 필요합니다* | 부울 | `false` | 아니요 


 a| 
`hours`
 a| 
주중 또는 월중 모드에서 반복되는 스냅샷 사이의 시간 수 또는 스냅샷이 발생하는 GMT 시간입니다. 유효한 값은 0~23입니다.
 a| 
정수
 a| 
None
 a| 
아니요



| `lastRunStatus` | 마지막으로 예약된 스냅샷 생성의 결과 또는 상태입니다. | 끈 | None | 아니요 


 a| 
`name`
 a| 
스냅샷의 이름입니다.  이름을 입력하지 않으면 그룹 스냅샷이 촬영된 날짜와 시간이 사용됩니다.  허용되는 최대 이름 길이는 244자입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`minutes`
 a| 
주중 또는 월중 모드에서 반복되는 스냅샷 사이의 분 수 또는 스냅샷이 발생하는 GMT 시간의 분입니다. 유효한 값은 5~59입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
`paused`
 a| 
일정을 일시 중지할지 여부를 나타냅니다.  유효한 값:

* `true`
* `false`

 a| 
부울
 a| 
None
 a| 
아니요



 a| 
`recurring`
 a| 
일정이 반복되는지 여부를 나타냅니다.  유효한 값은 다음과 같습니다.

* `true`
* `false`

 a| 
부울
 a| 
None
 a| 
아니요



| `runNextInterval`  a| 
스케줄러가 다음에 활성화될 때 스냅샷을 실행할지 여부를 지정합니다.  true로 설정하면 스케줄러가 다음에 활성화될 때 예약된 스냅샷이 실행되고 false로 재설정됩니다.  유효한 값은 다음과 같습니다.

* `true`
* `false`

| 부울 | `false` | 아니요 


 a| 
`scheduleName`
 a| 
일정에 대한 고유한 이름입니다.  허용되는 일정 이름의 최대 길이는 244자입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
`scheduleType`
 a| 
생성할 일정의 유형을 나타냅니다.  유효한 값은 스냅샷입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
`scheduleInfo`
 a| 
일정에 지정된 고유한 이름, 생성된 스냅샷의 보존 기간, 스냅샷이 생성된 볼륨의 볼륨 ID입니다.  유효한 값:

* `volumeID`: 스냅샷에 포함될 볼륨의 ID입니다.  (정수)
* `volumes`: 그룹 스냅샷에 포함될 볼륨 ID 목록입니다.  (정수 배열)
* `name`: 사용할 스냅샷 이름입니다.  (끈)
* `enableRemoteReplication`: 스냅샷을 원격 복제에 포함할지 여부를 나타냅니다.  (부울)
* `retention`: 스냅샷이 HH:mm:ss 형식으로 보관되는 시간입니다.  비어 있으면 스냅샷은 영구적으로 보관됩니다.  (끈)
* `fifo`: 스냅샷은 FIFO(선입선출) 방식으로 보관됩니다.  (끈)
* `ensureSerialCreation`: 이전 스냅샷 복제가 진행 중인 경우 새 스냅샷 생성을 허용할지 여부를 지정합니다.  (부울)

 a| 
JSON 객체
 a| 
None
 a| 
예



 a| 
`snapMirrorLabel`
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트의 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`startingDate`
 a| 
일정이 실행될 시간입니다.  설정하지 않으면 일정이 즉시 시작됩니다.  UTC 시간으로 포맷되었습니다.
 a| 
ISO 8601 날짜 문자열
 a| 
None
 a| 
아니요



| `toBeDeleted` | 스냅샷 생성이 완료된 후 이 스냅샷 일정을 삭제하도록 지정합니다. | 부울 | `false` | 아니요 


 a| 
`monthdays`
 a| 
스냅샷을 찍을 날짜입니다. 유효한 값은 1~31입니다.
 a| 
정수 배열
 a| 
None
 a| 
예(해당 월의 특정 날짜에 대한 일정을 예약하는 경우)



 a| 
`weekdays`
 a| 
스냅샷을 만들 요일입니다.  필수 값(사용되는 경우):

* `Day`: 0~6(일요일~토요일)
* `Offset`: 한 달의 각 주에 대해 1~6까지(1보다 큰 경우 주의 N-1번째 요일에만 일치함).  예를 들어, offset:3을 일요일에 적용하면 그 달의 세 번째 일요일을 의미하고, offset:4를 수요일에 적용하면 그 달의 네 번째 수요일을 의미합니다.  오프셋:0은 아무런 조치도 취하지 않음을 의미합니다.  오프셋: 1(기본값)은 스냅샷이 해당 요일에 생성됨을 의미하며, 이는 해당 요일이 해당 월에 어디에 있는지와 무관합니다.

 a| 
JSON 객체 배열
 a| 
None
 a| 
예 (요일별로 예약하는 경우)

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
스케줄ID
 a| 
생성된 일정의 ID입니다.
 a| 
정수



 a| 
일정
 a| 
새로 생성된 일정에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_schedule.adoc[일정]

|===


== 요청 예제 1

다음 예시 일정에는 다음과 같은 매개변수가 있습니다.

* 시작 시간이나 분이 지정되지 않았으므로 일정은 자정(00:00:00Z)에 최대한 가깝게 시작됩니다.
* 반복되지 않습니다(한 번만 실행됩니다).
* 2015년 6월 1일 UTC 19:17:15Z 이후 첫 번째 일요일 또는 수요일에 한 번 실행됩니다(먼저 도달하는 날짜).
* 여기에는 볼륨이 하나만 포함됩니다(volumeID = 1).


[listing]
----
{
  "method":"CreateSchedule",
  "params":{
    "hours":0,
    "minutes":0,
    "paused":false,
    "recurring":false,
    "scheduleName":"MCAsnapshot1",
    "scheduleType":"snapshot",
    "attributes":{
      "frequency":"Days Of Week"
    },
    "scheduleInfo":{
      "volumeID":"1",
      "name":"MCA1"
    },
    "monthdays":[],
    "weekdays":[
      {
        "day":0,
        "offset":1
      },
      {
        "day":3,
        "offset":1
      }
    ],
    "startingDate":"2015-06-01T19:17:54Z"
  },
   "id":1
}
}
}
----


== 응답 예시 1

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Week"
      },
      "hasError": false,
      "hours": 0,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 0,
      "monthdays": [],
      "paused": false,
      "recurring": false,
      "runNextInterval": false,
      "scheduleID": 4,
      "scheduleInfo": {
        "name": "MCA1",
        "volumeID": "1"
      },
      "scheduleName": "MCAsnapshot1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-06-01T19:17:54Z",
      "toBeDeleted": false,
      "weekdays": [
        {
          "day": 0,
          "offset": 1
        },
        {
          "day": 3,
          "offset": 1
        }
      ]
    },
    "scheduleID": 4
  }
}
----


== 요청 예제 2

다음 예시 일정에는 다음과 같은 매개변수가 있습니다.

* 반복됩니다(매달 정해진 시간에 예약된 간격으로 실행됨).
* 시작일 이후 매월 1일, 10일, 15일, 30일에 진행됩니다.
* 이 행사는 매일 오후 12시 15분에 진행됩니다.
* 여기에는 볼륨이 하나만 포함됩니다(volumeID = 1).


[listing]
----
{
  "method":"CreateSchedule",
    "params":{
      "hours":12,
      "minutes":15,
      "paused":false,
      "recurring":true,
      "scheduleName":"MCASnapshot1",
      "scheduleType":"snapshot",
      "attributes":{
        "frequency":"Days Of Month"
      },
      "scheduleInfo":{
        "volumeID":"1"
      },
      "weekdays":[
      ],
      "monthdays":[
        1,
        10,
        15,
        30
      ],
      "startingDate":"2015-04-02T18:03:15Z"
    },
    "id":1
}
----


== 응답 예시 2

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Month"
      },
      "hasError": false,
      "hours": 12,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 15,
      "monthdays": [
        1,
        10,
        15,
        30
      ],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 5,
      "scheduleInfo": {
        "volumeID": "1"
      },
      "scheduleName": "MCASnapshot1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-04-02T18:03:15Z",
      "toBeDeleted": false,
      "weekdays": []
    },
      "scheduleID": 5
  }
}
----


== 요청 예시 3

다음 예시 일정에는 다음과 같은 매개변수가 있습니다.

* 2015년 4월 2일 예정된 시간 간격에서 5분 이내에 시작됩니다.
* 반복됩니다(매달 정해진 시간에 예약된 간격으로 실행됨).
* 시작일 이후 매월 2일, 3일, 4일에 진행됩니다.
* 이 행사는 매일 오후 2시 45분에 진행됩니다.
* 여기에는 여러 권의 권(권 = 1, 2)이 포함됩니다.


[listing]
----
{
  "method":"CreateSchedule",
  "params":{
    "hours":14,
    "minutes":45,
    "paused":false,
    "recurring":true,
    "scheduleName":"MCASnapUser1",
    "scheduleType":"snapshot",
    "attributes":{
      "frequency":"Days Of Month"
    },
    "scheduleInfo":{
      "volumes":[1,2]
    },
    "weekdays":[],
    "monthdays":[2,3,4],
    "startingDate":"2015-04-02T20:38:23Z"
  },
  "id":1
}
----


== 응답 예시 3

위의 요청은 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "schedule": {
      "attributes": {
        "frequency": "Days Of Month"
      },
      "hasError": false,
      "hours": 14,
      "lastRunStatus": "Success",
      "lastRunTimeStarted": null,
      "minutes": 45,
      "monthdays": [
        2,
        3,
        4
      ],
      "paused": false,
      "recurring": true,
      "runNextInterval": false,
      "scheduleID": 6,
      "scheduleInfo": {
        "volumes": [
          1,
          2
        ]
      },
      "scheduleName": "MCASnapUser1",
      "scheduleType": "Snapshot",
      "startingDate": "2015-04-02T20:38:23Z",
      "toBeDeleted": false,
      "weekdays": []
    },
    "scheduleID": 6
  }
}
----


== 버전 이후 새로운

9.6
