---
permalink: api/reference_element_api_modifygroupsnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,group,snapshot,modifygroupsnapshot 
summary: 'ModifyGroupSnapshot을 사용하면 스냅샷 그룹의 속성을 변경할 수 있습니다.  이 방법을 사용하면 읽기/쓰기 \(소스\) 볼륨에 생성된 스냅샷을 대상 스토리지 시스템에 원격으로 복제할 수도 있습니다.' 
---
= 그룹 스냅샷 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `ModifyGroupSnapshot` 스냅샷 그룹의 속성을 변경합니다.  이 방법을 사용하면 읽기/쓰기(소스) 볼륨에 생성된 스냅샷을 대상 스토리지 시스템에 원격으로 복제할 수도 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
enableRemoteReplication
 a| 
원격 클러스터에 복제할 스냅샷을 생성하는 데 사용됩니다. 가능한 값:

* `true`: 스냅샷은 원격 저장소에 복제됩니다.
* `false`: 스냅샷은 원격 저장소에 복제되지 않습니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
만료 시간
 a| 
스냅샷을 제거할 수 있는 시간을 지정합니다.  보존과 함께 사용할 수 없습니다.  expirationTime이나 원본 스냅샷의 retention이 지정되지 않으면 스냅샷은 만료되지 않습니다.  시간 형식은 시간 기반 만료를 위한 ISO 8601 날짜 문자열입니다. 그렇지 않으면 만료되지 않습니다.  의 값 `null` 스냅샷이 영구적으로 보관됩니다.  fifo 값을 지정하면 볼륨의 다른 FIFO 스냅샷과 비교하여 스냅샷이 FIFO(선입선출) 방식으로 보존됩니다.  FIFO 공간을 사용할 수 없으면 API가 실패합니다.
 a| 
ISO 8601 날짜 문자열
 a| 
None
 a| 
아니요



 a| 
이름
 a| 
그룹 스냅샷의 이름입니다.  이름을 입력하지 않으면 그룹 스냅샷이 촬영된 날짜와 시간이 사용됩니다.  허용되는 최대 이름 길이는 255자입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
그룹스냅샷ID
 a| 
스냅샷 그룹의 ID입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
스냅미러라벨
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트의 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
그룹스냅샷
 a| 
새로 수정된 그룹 스냅샷에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_groupsnapshot.adoc[그룹스냅샷]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "id": 695,
  "method": "ModifyGroupSnapshot",
  "params": {
    "groupSnapshotID": 3,
    "enableRemoteReplication": true,
    "expirationTime": "2016-04-08T22:46:25Z"
  }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 695,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:31:41Z",
      "groupSnapshotID": 3,
      "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:31:41Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2016-04-08T22:46:25Z",
          "groupID": 3,
          "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
          "name": "grpsnap1-2",
          "snapshotID": 2,
          "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "grpsnap1",
      "status": "done"
    }
  }
}
----


== 버전 이후 새로운

9.6
