---
permalink: api/reference_element_api_task_virtual_volumes.html 
sidebar: sidebar 
keywords: object,objects,task 
summary: 작업 개체에는 시스템에서 현재 실행 중이거나 완료된 가상 볼륨 작업에 대한 정보가 포함되어 있습니다.  ListVirtualVolumeTasks 메서드를 사용하면 모든 가상 볼륨 작업에 대한 정보를 검색할 수 있습니다. 
---
= 작업(가상 볼륨)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업 개체에는 시스템에서 현재 실행 중이거나 완료된 가상 볼륨 작업에 대한 정보가 포함되어 있습니다.  당신은 사용할 수 있습니다 `ListVirtualVolumeTasks` 모든 가상 볼륨 작업에 대한 정보를 검색하는 방법입니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
취소
 a| 
작업이 취소되었는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
cloneVirtualVolumeID
 a| 
복제되는 가상 볼륨의 고유한 가상 볼륨 ID(복제 작업용).
 a| 
UUID



 a| 
부모 메타데이터
 a| 
가상 볼륨의 스냅샷을 복제하거나 생성하는 작업에 대한 부모의 메타데이터가 포함된 개체입니다.
 a| 
JSON 객체



 a| 
부모 총 크기
 a| 
복제 또는 스냅샷 작업을 위해 부모에서 사용 가능한 총 공간(바이트)입니다.
 a| 
정수



 a| 
부모사용크기
 a| 
복제 또는 스냅샷 작업에 사용된 부모의 공간(바이트)입니다.
 a| 
정수



 a| 
작업
 a| 
작업이 수행하는 작업의 유형입니다. 가능한 값:

* 알 수 없음: 작업 동작을 알 수 없습니다.
* 준비: 작업은 가상 볼륨을 준비하는 것입니다.
* 스냅샷: 이 작업은 가상 볼륨의 스냅샷을 만드는 것입니다.
* 롤백: 이 작업은 가상 볼륨을 스냅샷으로 롤백하는 것입니다.
* 복제: 작업은 가상 볼륨의 복제본을 만드는 것입니다.
* fastClone: 이 작업은 가상 볼륨의 빠른 복제본을 만드는 것입니다.
* copyDiffs: 이 작업은 서로 다른 블록을 가상 볼륨에 복사하는 것입니다.

 a| 
끈



 a| 
상태
 a| 
가상 볼륨 작업의 현재 상태입니다. 가능한 값:

* 오류: 작업이 실패하여 오류가 반환되었습니다.
* 대기 중: 작업이 실행되기를 기다리고 있습니다.
* 실행 중: 작업이 현재 실행 중입니다.
* 성공: 작업이 성공적으로 완료되었습니다.

 a| 
끈



 a| 
가상볼륨호스트ID
 a| 
작업을 시작한 호스트의 고유 ID입니다.
 a| 
UUID



 a| 
가상볼륨ID
 a| 
새로운 고유 가상 볼륨 ID(새로운 가상 볼륨을 생성하는 작업의 경우)
 a| 
UUID



 a| 
가상볼륨작업ID
 a| 
작업의 고유 ID입니다.
 a| 
UUID

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listvirtualvolumetasks.adoc[가상 볼륨 작업 목록]
