---
permalink: api/reference_element_api_addidpclusteradmin.html 
sidebar: sidebar 
keywords: IdP,idp,cluster,admin,add,adding,addIdpclusteradmin 
summary: 'AddIpdClusterAdmin 메서드를 사용하면 타사 ID 공급자(IdP)가 인증한 클러스터 관리자 사용자를 추가할 수 있습니다.  IdP 클러스터 관리자 계정은 사용자와 관련된 IdP의 SAML 어설션에 제공된 SAML 속성-값 정보를 기반으로 구성됩니다.  사용자가 IdP에 성공적으로 인증하고 SAML 어설션 내에 여러 IdP 클러스터 관리자 계정과 일치하는 SAML 속성 문이 있는 경우, 사용자는 일치하는 IdP 클러스터 관리자 계정의 결합된 액세스 수준을 갖게 됩니다.' 
---
= AddIdpClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `AddIpdClusterAdmin` 타사 ID 공급자(IdP)가 인증한 클러스터 관리자 사용자를 추가하는 방법입니다.  IdP 클러스터 관리자 계정은 사용자와 관련된 IdP의 SAML 어설션에 제공된 SAML 속성-값 정보를 기반으로 구성됩니다.  사용자가 IdP에 성공적으로 인증하고 SAML 어설션 내에 여러 IdP 클러스터 관리자 계정과 일치하는 SAML 속성 문이 있는 경우, 사용자는 일치하는 IdP 클러스터 관리자 계정의 결합된 액세스 수준을 갖게 됩니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
입장
 a| 
이 IdP 클러스터 관리자가 사용할 수 있는 방법을 제어합니다.
 a| 
문자열 배열
 a| 
None
 a| 
예



 a| 
EULA 수락
 a| 
최종 사용자 라이선스 계약에 동의하세요.  시스템에 클러스터 관리자 계정을 추가하려면 true로 설정합니다.  생략하거나 false로 설정하면 메서드 호출이 실패합니다.
 a| 
부울
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
사용자 이름
 a| 
IdP 클러스터 관리자에 대한 SAML 속성-값 매핑(예: email=test@example.com).  이는 특정 SAML 주체를 사용하여 정의할 수 있습니다. `NameID` 또는 SAML 속성 문의 항목으로, 예: `eduPersonAffiliation` .
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
클러스터 관리자 ID
 a| 
새로 생성된 클러스터 관리자에 대한 고유 식별자입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
    "method": "AddIdpClusterAdmin",
    "params": {
        "username": "email=test@example.com",
        "acceptEula": true,
        "access": ["administrator"]
    }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
    "result": {
        "clusterAdminID": 13
    }
}
----


== 버전 이후 새로운

12.0
