---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: ModifySnapMirrorRelationship을 사용하면 예약된 스냅샷이 발생하는 간격을 변경할 수 있습니다.  이 방법을 사용하면 일정을 삭제하거나 일시 중지할 수도 있습니다. 
---
= 스냅미러 관계 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `ModifySnapMirrorRelationship` 예약된 스냅샷이 발생하는 간격을 변경합니다.  이 방법을 사용하면 일정을 삭제하거나 일시 중지할 수도 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
목적지볼륨
 a| 
SnapMirror 관계의 대상 볼륨입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[스냅미러볼륨정보]
 a| 
None
 a| 
예



 a| 
최대 전송률
 a| 
볼륨 간 최대 데이터 전송 속도를 초당 킬로바이트 단위로 지정합니다.  기본값인 0은 무제한이며 SnapMirror 관계가 사용 가능한 네트워크 대역폭을 최대한 활용할 수 있도록 허용합니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
정책 이름
 a| 
관계에 대한 ONTAP SnapMirror 정책의 이름을 지정합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
일정 이름
 a| 
ONTAP 시스템에서 SnapMirror 관계를 업데이트하는 데 사용되는 기존 cron 일정의 이름입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
스냅미러엔드포인트ID
 a| 
Element 스토리지 클러스터와 통신하는 원격 ONTAP 스토리지 시스템의 엔드포인트 ID입니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
스냅미러관계
 a| 
수정된 SnapMirror 관계 속성을 포함하는 개체입니다.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[스냅미러관계]

|===


== 버전 이후 새로운

10.1
