---
permalink: api/reference_element_api_clustercapacity.html 
sidebar: sidebar 
keywords: objects,object,clusterCapacity 
summary: clusterCapacity 객체에는 클러스터에 대한 고수준 용량 측정값이 포함되어 있습니다.  GetClusterCapacity API 메서드를 사용하면 클러스터 용량 정보를 얻을 수 있습니다.  객체 멤버의 공간 측정은 바이트 단위로 계산됩니다. 
---
= 클러스터 용량
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterCapacity 객체에는 클러스터에 대한 고수준 용량 측정값이 포함되어 있습니다.  GetClusterCapacity API 메서드를 사용하면 클러스터 용량 정보를 얻을 수 있습니다.  객체 멤버의 공간 측정은 바이트 단위로 계산됩니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
활성 블록 공간
 a| 
블록 드라이브의 공간 크기입니다.  여기에는 메타데이터 항목 및 정리할 수 있는 공간과 같은 추가 정보가 포함됩니다.
 a| 
정수



 a| 
활성 세션
 a| 
클러스터와 통신하는 활성 iSCSI 세션의 수입니다.
 a| 
정수



 a| 
평균 IOPS
 a| 
UTC(협정 세계시) 자정 이후 클러스터의 평균 IOPS입니다.
 a| 
정수



 a| 
클러스터최근IOSize
 a| 
클러스터의 모든 볼륨에 대한 IOPS의 평균 크기입니다.
 a| 
정수



 a| 
현재 IOPS
 a| 
지난 5초 동안 클러스터의 모든 볼륨에 대한 평균 IOPS입니다.
 a| 
정수



 a| 
최대 IOPS
 a| 
현재 클러스터의 예상 최대 IOPS 성능입니다.
 a| 
정수



 a| 
최대 프로비저닝 가능 공간
 a| 
제공 가능한 최대 공간입니다.  이는 계산된 값입니다.  현재 프로비저닝된 공간과 새 볼륨 크기를 합친 크기가 이 숫자를 초과하는 경우 새 볼륨을 생성할 수 없습니다.  값은 다음과 같이 계산됩니다. `maxOverProvisionableSpace = maxProvisionedSpace * maxMetadataOverProvisionFactor`
 a| 
정수



 a| 
최대 프로비저닝 공간
 a| 
모든 볼륨이 100% 채워진 경우(씬 프로비저닝된 메타데이터 없음) 프로비저닝 가능한 총 공간입니다.
 a| 
정수



 a| 
최대 사용 메타데이터 공간
 a| 
볼륨 드라이브에서 메타데이터를 저장하는 데 사용되는 바이트 수입니다.
 a| 
정수



 a| 
최대 사용 공간
 a| 
모든 활성 블록 드라이브의 총 공간 크기입니다.
 a| 
정수



 a| 
비제로블록
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 포함된 4KiB 블록의 총 수입니다.
 a| 
정수



 a| 
피크활성세션
 a| 
UTC 자정 이후 iSCSI 연결의 최대 수입니다.
 a| 
정수



 a| 
최대 IOPS
 a| 
UTC 자정 이후 currentIOPS의 가장 높은 값입니다.
 a| 
정수



 a| 
프로비저닝된 공간
 a| 
클러스터의 모든 볼륨에 프로비저닝된 총 공간입니다.
 a| 
정수



 a| 
타임스탬프
 a| 
이 클러스터 용량 샘플이 수집된 UTC+0 형식의 날짜와 시간입니다.
 a| 
ISO 8601 문자열



 a| 
총 작업
 a| 
클러스터의 수명 동안 수행된 총 I/O 작업 수입니다.
 a| 
정수



 a| 
유니크블록
 a| 
블록 드라이브에 저장된 블록의 총 수입니다.  값에는 복제된 블록이 포함됩니다.
 a| 
정수



 a| 
uniqueBlocksUsedSpace
 a| 
블록 드라이브에서 uniqueBlocks가 차지하는 총 데이터 양입니다.  이 숫자가 uniqueBlocks 값과 어떻게 관련되는지에 대한 자세한 내용은 GetclusterCapacity 메서드를 참조하세요.
 a| 
정수



 a| 
사용된 메타데이터 공간
 a| 
볼륨 드라이브에서 메타데이터를 저장하는 데 사용된 총 바이트 수입니다.
 a| 
정수



 a| 
스냅샷에 사용된 메타데이터 공간
 a| 
스냅샷에서 고유한 데이터를 저장하는 데 사용되는 볼륨 드라이브의 바이트 수입니다.  이 숫자는 시스템의 모든 스냅샷을 삭제하면 얼마나 많은 메타데이터 공간을 회복할 수 있는지에 대한 추정치를 제공합니다.
 a| 
정수



 a| 
사용된 공간
 a| 
시스템의 모든 블록 드라이브가 사용하는 총 공간입니다.
 a| 
정수



 a| 
제로블록스
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 없는 빈 4KiB 블록의 총 수입니다.
 a| 
정수

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_getclustercapacity.adoc[클러스터 용량 가져오기]
