---
permalink: api/reference_element_api_volume_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: volume,pairing,order,operations,volumes,pairing,pair,pairs 
summary: 볼륨을 페어링하려면 두 개의 해당 클러스터 간에 클러스터 쌍을 만들어야 합니다. 
---
= 볼륨 페어링 연산 순서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨을 페어링하려면 두 개의 해당 클러스터 간에 클러스터 쌍을 만들어야 합니다.

다음 API 메서드 세트를 사용하여 클러스터 연결을 설정합니다.

* xref:reference_element_api_startvolumepairing.adoc[볼륨 페어링 시작]:
+
이 API 메서드는 볼륨 쌍을 만드는 데 사용되는 볼륨 쌍 키를 생성하고 반환합니다.  키에는 볼륨 간 통신을 설정하는 데 사용되는 정보가 포함되어 있습니다.

* xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]:
+
이 방법은 생성된 페어링 키를 사용합니다.xref:reference_element_api_startvolumepairing.adoc[볼륨 페어링 시작] 볼륨 쌍을 생성하는 API 메서드입니다.  발행하다xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] 대상 볼륨에 대한 volumeID 및 volumePairingKey 매개변수를 사용하는 API 메서드입니다.



쌍을 이루는 볼륨 중 하나만 복제 대상 볼륨으로 식별될 수 있습니다.  사용하다xref:reference_element_api_modifyvolumepair.adoc[볼륨 쌍 수정] 볼륨이 대상인지 식별하여 볼륨의 데이터 복제 방향을 설정하는 API 방식입니다.  데이터는 소스 볼륨에서 대상 볼륨으로 복제됩니다.



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_startvolumepairing.adoc[볼륨 페어링 시작]
* xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
* xref:reference_element_api_modifyvolumepair.adoc[볼륨 쌍 수정]

