---
permalink: api/reference_element_api_removenodes.html 
sidebar: sidebar 
keywords: node,nodes,cluster,remove,removing,removenodes 
summary: RemoveNodes를 사용하면 더 이상 클러스터에 참여하지 않아야 하는 하나 이상의 노드를 제거할 수 있습니다. 
---
= 노드 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `RemoveNodes` 더 이상 클러스터에 참여하지 않아야 하는 하나 이상의 노드를 제거합니다.

노드를 제거하기 전에 다음을 사용하여 노드에 포함된 모든 드라이브를 제거해야 합니다. `RemoveDrives` 방법.  노드를 제거할 때까지는 다음을 수행할 수 없습니다. `RemoveDrives` 프로세스가 완료되었고 모든 데이터가 노드에서 다른 곳으로 마이그레이션되었습니다.  노드를 제거하면 해당 노드는 보류 노드로 등록됩니다.  노드를 다시 추가하거나 종료할 수 있습니다(노드를 종료하면 보류 중인 노드 목록에서 제거됩니다).



== 클러스터 마스터 노드 제거

당신이 사용하는 경우 `RemoveNodes` 클러스터 마스터 노드를 제거하려면 해당 메서드가 응답을 반환하기 전에 시간 초과가 발생할 수 있습니다.  메서드 호출로 노드를 제거하는 데 실패하면 메서드 호출을 다시 수행합니다.  다른 노드와 함께 클러스터 마스터 노드를 제거하는 경우 별도의 호출을 사용하여 클러스터 마스터 노드만 제거해야 합니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
앙상블 허용 오차 변경 무시
 a| 
노드를 제거할 때 앙상블의 노드 장애 허용 범위에 대한 변경 사항을 무시합니다.

스토리지 클러스터가 여러 노드 장애를 허용하는 데이터 보호 체계를 사용하고 노드를 제거하면 앙상블의 노드 장애 허용 범위가 감소하는 경우, 노드 제거는 일반적으로 오류와 함께 실패합니다.  이 매개변수를 true로 설정하면 앙상블 허용 오차 검사를 비활성화하여 노드 제거가 성공합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
노드
 a| 
제거할 노드의 NodeID 목록입니다.
 a| 
정수 배열
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "RemoveNodes",
   "params": {
     "nodes"  : [3,4,5]
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1
  "result" : {},
}
----


== 버전 이후 새로운

9.6
