---
permalink: api/reference_element_api_enablemaintenancemode.html 
sidebar: sidebar 
keywords: maintenance,enable,mode 
summary: EnableMaintenanceMode 메서드를 사용하면 유지 관리를 위해 스토리지 노드를 준비할 수 있습니다.  유지 관리 시나리오에는 노드의 전원을 끄거나 다시 시작해야 하는 모든 작업이 포함됩니다. 
---
= EnableMaintenanceMode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `EnableMaintenanceMode` 유지 관리를 위해 저장 노드를 준비하는 방법.  유지 관리 시나리오에는 노드의 전원을 끄거나 다시 시작해야 하는 모든 작업이 포함됩니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
해결되지 않은 오류로 강제 실행
 a| 
차단 클러스터 오류가 있는 경우에도 이 노드에 대해 강제로 유지 관리 모드를 활성화합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
노드
 a| 
유지 관리 모드로 전환할 노드 ID 목록입니다.  한 번에 하나의 노드만 지원됩니다.
 a| 
정수 배열
 a| 
None
 a| 
예



 a| 
분당 기본 스왑 한도
 a| 
1분당 교체할 기본 슬라이스 수입니다.  지정하지 않으면 모든 기본 슬라이스가 한 번에 교체됩니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
타임아웃
 a| 
유지 관리 모드가 자동으로 비활성화되기 전까지 얼마나 오랫동안 활성화 상태를 유지해야 하는지 지정합니다.  시간 문자열(예: HH:mm:ss)로 형식이 지정됩니다.  지정하지 않으면 유지 관리 모드는 명시적으로 비활성화될 때까지 활성화 상태로 유지됩니다.
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
GetAsyncResult 메서드를 사용하면 이 asyncHandle을 검색하고 유지 관리 모드 전환이 완료되는 시점을 확인할 수 있습니다.
 a| 
정수



 a| 
현재 모드
 a| 
노드의 현재 유지 관리 모드 상태입니다. 가능한 값:

* 비활성화: 유지 관리가 요청되지 않았습니다.
* FailedToRecover: 노드가 유지 관리 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지 관리 모드에서 복구 중입니다.
* 유지 관리 준비: 노드에 대한 유지 관리를 수행하기 위한 작업이 진행 중입니다.
* ReadyForMaintenance: 노드가 유지 관리를 수행할 준비가 되었습니다.

 a| 
MaintenanceMode(문자열)



 a| 
요청된 모드
 a| 
노드의 요청된 유지 관리 모드 상태입니다. 가능한 값:

* 비활성화: 유지 관리가 요청되지 않았습니다.
* FailedToRecover: 노드가 유지 관리 모드에서 복구되지 못했습니다.
* RecoveringFromMaintenance: 노드가 유지 관리 모드에서 복구 중입니다.
* 유지 관리 준비: 노드에 대한 유지 관리를 수행하기 위한 작업이 진행 중입니다.
* ReadyForMaintenance: 노드가 유지 관리를 수행할 준비가 되었습니다.

 a| 
MaintenanceMode(문자열)

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "EnableMaintenanceMode",
  "params": {
    "forceWithUnresolvedFaults": False,
    "nodes": [6],
    "perMinutePrimarySwapLimit" : 40,
    "timeout" : "01:00:05"
  },
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "ReadyForMaintenance",
        "asyncHandle": 1,
        "currentMode": "Disabled"
    }
}
----


== 버전 이후 새로운

12.2



== 더 많은 정보를 찾아보세요

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI 스토리지 유지 관리 모드 개념"^]
