---
permalink: api/reference_element_api_createclustersupportbundle.html 
sidebar: sidebar 
keywords: CreateClusterSupportBundle,create,cluster,support,bundle,creating 
summary: 관리 노드에서 CreateClusterSupportBundle을 사용하면 클러스터의 모든 노드에서 지원 번들을 수집할 수 있습니다.  번들이 생성되면 노드에 .tar.gz 파일로 저장됩니다.  이 방법은 관리 노드에서만 실행할 수 있으며, 스토리지 노드에서 실행하면 작동하지 않습니다. 
---
= 클러스터 지원 번들 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `CreateClusterSupportBundle` 클러스터의 모든 노드에서 지원 번들을 수집하려면 관리 노드를 사용합니다.  개별 노드 지원 번들은 tar.gz 파일로 압축됩니다.  클러스터 지원 번들은 노드 지원 번들을 포함하는 tar 파일입니다.  이 방법은 관리 노드에서만 실행할 수 있으며, 스토리지 노드에서 실행하면 작동하지 않습니다.



== 매개변수


NOTE: 이 메서드는 관리 노드에 대해 호출해야 합니다. 예를 들어:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
허용불완료
 a| 
하나 이상의 노드에서 번들을 수집할 수 없는 경우 스크립트가 계속 실행될 수 있도록 합니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
번들 이름
 a| 
생성된 각 지원 번들에 대한 고유한 이름입니다.  이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
엠비피
 a| 
클러스터의 MVIP.  번들은 클러스터의 모든 노드에서 수집됩니다.  nodes 매개변수가 지정되지 않은 경우 이 매개변수가 필요합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
노드
 a| 
번들을 수집할 노드의 IP 주소입니다.  번들을 수집할 노드를 지정하려면 nodes 또는 mvip 중 하나만 사용하세요. 둘 다 사용할 수는 없습니다.  mvip가 지정되지 않은 경우 이 매개변수가 필요합니다.
 a| 
문자열 배열
 a| 
None
 a| 
예



 a| 
비밀번호
 a| 
클러스터 관리자 비밀번호입니다.  *참고:* 이 비밀번호는 입력 시 텍스트로 표시됩니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
사용자 이름
 a| 
클러스터 관리자 사용자 이름입니다.
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
"method": "CreateClusterSupportBundle",
"params": {
          "bundlename": "clusterbundle",
          "mvip": "132.119.120.100"
     }
   },
 "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id":1,
  "result":{
   "details":{
      "bundleName":"clusterbundle",
      "extraArgs":"",
      "files":[
          "/tmp/supportbundles/clusterbundle.cl-4SD5.tar"
      ],
      "output":"timeout -s KILL 1790s /usr/local/bin/sfclustersupportbundle --quiet --name=\"clusterbundle\" --target-directory=\"/tmp/solidfire-dtemp.MM7f0m\" --user=\"admin\" --pass=\"admin\" --mvip=132.119.120.100"
       },
       "duration":"00:00:24.938127",
       "result":"Passed"
    }
}
----


== 버전 이후 새로운

9.6
