---
permalink: api/reference_element_api_createsupportbundle.html 
sidebar: sidebar 
keywords: create,creating,support,bundle,CreateSupportBundle 
summary: CreateSupportBundle을 사용하면 노드 디렉토리 아래에 지원 번들 파일을 만들 수 있습니다.  생성 후 번들은 tar.gz 파일로 노드에 저장됩니다. 
---
= CreateSupportBundle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `CreateSupportBundle` 노드 디렉토리 아래에 지원 번들 파일을 생성합니다.  번들은 생성 후 노드에 tar 파일로 저장됩니다(gz 압축 옵션은 extraArgs 매개변수를 통해 사용 가능).



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
번들 이름
 a| 
지원 번들에 대한 고유한 이름입니다.  이름이 제공되지 않으면 "supportbundle"과 노드 이름이 파일 이름으로 사용됩니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
추가 인수
 a| 
'--compress gz'를 사용하여 지원 번들을 tar.gz 파일로 생성합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
시간 초과 초
 a| 
지원 번들 스크립트가 실행되는 시간(초)입니다.
 a| 
정수
 a| 
1500
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
세부
 a| 
지원 번들의 세부 정보. 가능한 값:

* bundleName: CreateSupportBundleAPI 메서드에 지정된 이름입니다.  이름이 지정되지 않으면 "supportbundle"이 사용됩니다.
* extraArgs: 이 메서드와 함께 전달되는 인수입니다.
* 파일: 시스템이 생성한 지원 번들 파일 목록입니다.
* 출력: 지원 번들을 생성한 스크립트의 명령줄 출력입니다.
* timeoutSec: 지원 번들 스크립트가 중지되기 전에 실행되는 시간(초)입니다.
* url: 생성된 지원 번들에 대한 URL입니다.

 a| 
JSON 객체



 a| 
지속
 a| 
지원 번들을 만드는 데 사용된 시간은 HH:MM:SS.ssssss 형식입니다.
 a| 
끈



 a| 
결과
 a| 
지원 번들 운영의 성공 또는 실패.
 a| 
끈

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
 "method": "CreateSupportBundle",
"params": {
  "extraArgs": "--compress gz"
 },
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
"id": 1,
"result": {
  "details": {
    "bundleName": "supportbundle",
    "extraArgs": "--compress gz",
    "files": [
         "supportbundle.nodehostname.tar.gz"
     ],
     "output": "timeout -s KILL 1500s /sf/scripts/sfsupportbundle --quiet --compress gz /tmp/solidfire-dtemp.1L6bdX/supportbundle<br><br>Moved '/tmp/solidfire-dtemp.1L6bdX/supportbundle.nodehostname.tar.gz' to /tmp/supportbundles",
      "timeoutSec": 1500,
      "url": [
          "https://nodeIP:442/config/supportbundles/supportbundle.nodehostname.tar.gz"
      ]
    },
    "duration": "00:00:43.101627",
    "result": "Passed"
  }
}
----


== 버전 이후 새로운

9.6
