---
permalink: api/reference_element_api_keyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,keys 
summary: 'keyServerKmip 객체는 클러스터 기능(예: 휴면 상태 암호화)에 사용할 인증 키를 검색하는 위치인 키 관리 상호 운용성 프로토콜(KMIP) 키 서버를 설명합니다.' 
---
= 키서버Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
keyServerKmip 객체는 클러스터 기능(예: 휴면 상태 암호화)에 사용할 인증 키를 검색하는 위치인 KMIP(Key Management Interoperability Protocol) 키 서버를 설명합니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
키 제공자 ID
 a| 
이 KMIP 키 서버가 공급자에게 할당된 경우, 이 멤버에는 할당된 KMIP 키 공급자의 ID가 포함됩니다.  그렇지 않으면 이 멤버는 null입니다.
 a| 
정수



 a| 
키서버ID
 a| 
KMIP 키 서버의 ID입니다.  이는 키 서버 생성 중에 클러스터가 할당한 고유한 값입니다.  이 값은 변경할 수 없습니다.
 a| 
정수



 a| 
kmipAssignedProviderIsActive
 a| 
이 KMIP 키 서버가 공급자에게 할당된 경우(keyProviderID가 null이 아닌 경우), 이 멤버는 해당 공급자가 활성 상태(현재 사용 중인 키 제공)인지 여부를 나타냅니다.  그렇지 않으면 이 멤버는 null입니다.
 a| 
부울



 a| 
kmipCa증명서
 a| 
외부 키 서버의 루트 CA의 공개 키 인증서입니다.  이는 TLS 통신에서 외부 키 서버가 제시한 인증서를 검증하는 데 사용됩니다.  개별 서버가 서로 다른 CA를 사용하는 주요 서버 클러스터의 경우, 이 멤버에는 모든 CA의 루트 인증서가 연결된 문자열이 포함됩니다.
 a| 
끈



 a| 
kmip클라이언트 인증서
 a| 
Element 스토리지 KMIP 클라이언트에서 사용하는 PEM 형식의 Base64 인코딩된 PKCS#10 X.509 인증서입니다.
 a| 
끈



 a| 
kmipKeyServer호스트 이름
 a| 
이 KMIP 키 서버와 연결된 호스트 이름 또는 IP 주소입니다.
 a| 
문자열 배열



 a| 
kmipKeyServerName
 a| 
KMIP 키 서버의 이름입니다.  이 이름은 표시 목적으로만 사용되며 고유할 필요는 없습니다.
 a| 
끈



 a| 
kmipKeyServerPort
 a| 
이 KMIP 키 서버와 연결된 포트 번호(일반적으로 5696).
 a| 
정수

|===