---
permalink: api/reference_element_api_drive.html 
sidebar: sidebar 
keywords: objects,object,drive 
summary: 드라이브 개체에는 클러스터의 활성 노드에 있는 개별 드라이브에 대한 정보가 포함되어 있습니다.  이 개체에는 볼륨 메타데이터 또는 블록 드라이브로 추가된 드라이브에 대한 세부 정보와 아직 추가되지 않았지만 사용 가능한 드라이브에 대한 세부 정보가 포함되어 있습니다.  ListDrives API 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 운전하다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
드라이브 개체에는 클러스터의 활성 노드에 있는 개별 드라이브에 대한 정보가 포함되어 있습니다.  이 개체에는 볼륨 메타데이터 또는 블록 드라이브로 추가된 드라이브에 대한 세부 정보와 아직 추가되지 않았지만 사용 가능한 드라이브에 대한 세부 정보가 포함되어 있습니다.  이 정보는 다음을 사용하여 검색할 수 있습니다. `ListDrives` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.  이 객체는 항상 null이며 수정할 수 없습니다.
 a| 
JSON 객체



 a| 
capacity
 a| 
드라이브의 총 용량(바이트)입니다.
 a| 
정수



 a| 
섀시슬롯
 a| 
HCI 플랫폼의 경우 이 값은 드라이브가 있는 서버 섀시의 노드 문자와 슬롯 번호입니다.  저장 플랫폼의 경우 슬롯 번호는 "슬롯" 정수의 문자열 표현입니다.
 a| 
끈



 a| 
드라이브 실패 세부 정보
 a| 
드라이브 상태가 "실패"인 경우, 이 필드는 드라이브가 실패로 표시된 이유에 대한 자세한 정보를 제공합니다.
 a| 
끈



 a| 
드라이브ID
 a| 
이 드라이브의 ID입니다.
 a| 
정수



 a| 
드라이브 보안 오류 이유
 a| 
드라이브 보안을 활성화 또는 비활성화하는 데 실패한 경우, 실패한 이유를 설명합니다.  값이 "없음"이면 실패가 발생하지 않은 것입니다.
 a| 
끈



 a| 
키ID
 a| 
이 드라이브의 잠금을 해제하기 위한 인증 키를 얻기 위해 키 제공자가 사용하는 키ID입니다.
 a| 
UUID



 a| 
키 제공자 ID
 a| 
이 드라이브 잠금 해제를 위한 인증 키 제공자를 식별합니다.
 a| 
정수



 a| 
노드ID
 a| 
이 드라이브가 포함된 노드의 ID입니다.
 a| 
정수



 a| 
segmentFileSize
 a| 
드라이브의 세그먼트 파일 크기(바이트)입니다.
 a| 
정수



 a| 
연속물
 a| 
드라이브 일련번호.
 a| 
끈



 a| 
슬롯
 a| 
이 드라이브가 위치한 서버 섀시의 슬롯 번호이거나, 내부 메타데이터 드라이브에 SATADimm 장치가 사용되는 경우 -1입니다.
 a| 
정수



 a| 
상태
 a| 
드라이브의 상태. 가능한 값:

* 사용 가능: 사용 가능한 드라이브.
* 활성: 활성 드라이브.
* 지우기: 드라이브가 안전하게 지워지는 중입니다.  해당 드라이브의 모든 데이터는 영구적으로 제거됩니다.
* 실패: 실패한 드라이브.  이전에 드라이브에 있던 모든 데이터는 클러스터의 다른 드라이브로 마이그레이션되었습니다.
* 제거: 드라이브를 제거하는 중입니다.  이전에 드라이브에 있던 모든 데이터는 클러스터의 다른 드라이브로 마이그레이션됩니다.

 a| 
끈



 a| 
유형
 a| 
드라이브의 유형. 가능한 값:

* 볼륨: 볼륨 메타데이터를 저장합니다.
* 블록: 블록 데이터를 저장합니다.
* 알 수 없음: 드라이브 유형이 아직 활성화되지 않았으며 아직 결정되지 않았습니다.

 a| 
끈



 a| 
사용 가능 용량
 a| 
드라이브의 사용 가능한 용량(바이트)입니다.
 a| 
정수

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listdrives.adoc[드라이브 목록]
