---
permalink: api/reference_element_api_drivestats.html 
sidebar: sidebar 
keywords: object,objects,driveStats 
summary: driveStats 객체에는 단일 드라이브에 대한 높은 수준의 활동 측정값이 포함되어 있습니다.  API 메서드 GetDriveStats를 사용하여 측정 정보를 검색할 수 있습니다. 
---
= 드라이브 통계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
driveStats 객체에는 단일 드라이브에 대한 높은 수준의 활동 측정값이 포함되어 있습니다.  API 메소드를 사용하여 측정 정보를 검색할 수 있습니다. `GetDriveStats` .



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
활성 세션
 a| 
현재 이 드라이브를 사용 중인 iSCSI 세션 수(메타데이터 드라이브에만 표시됨).
 a| 
정수



 a| 
드라이브ID
 a| 
클러스터 내 드라이브의 고유 ID입니다.
 a| 
정수



 a| 
실패한 사망 횟수
 a| 
실패한 드라이브 하드웨어 요소의 수입니다.
 a| 
정수



 a| 
ios 진행 중
 a| 
이 드라이브에 진행 중인 I/O 수입니다.
 a| 
정수



 a| 
남은 수명퍼센트
 a| 
드라이브 미디어 마모 표시기.
 a| 
정수



 a| 
평생읽기바이트
 a| 
드라이브의 수명 동안 이 드라이브에서 읽은 총 바이트 수입니다.
 a| 
정수



 a| 
평생쓰기바이트
 a| 
드라이브의 수명 동안 이 드라이브에 기록된 총 바이트 수입니다.
 a| 
정수



 a| 
전원 켜짐 시간
 a| 
이 드라이브의 전원이 켜져 있던 시간입니다.
 a| 
정수



 a| 
읽다
 a| 
이 드라이브에 대한 초당 read() 호출 수입니다.
 a| 
정수



 a| 
바이트 읽기
 a| 
클라이언트 작업으로 인해 드라이브에서 읽은 총 바이트 수입니다.
 a| 
정수



 a| 
결합된 읽기
 a| 
더 큰 읽기 작업으로 결합될 수 있는 인접 섹터에 대한 read() 호출의 수입니다.
 a| 
정수



 a| 
읽기 밀리초
 a| 
읽는 데 소요된 시간(밀리초)입니다.
 a| 
정수



 a| 
읽기 작업
 a| 
클라이언트 작업으로 인해 드라이브에서 발생한 총 읽기 작업 수입니다.
 a| 
정수



 a| 
재할당된 섹터
 a| 
이 드라이브에서 교체된 불량 섹터의 수입니다.
 a| 
정수



 a| 
예비 용량 백분율
 a| 
드라이브의 사용 가능한 예비 용량입니다.
 a| 
정수



 a| 
타임스탬프
 a| 
UTC+0 형식의 현재 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
총 용량
 a| 
드라이브의 총 용량(바이트)입니다.
 a| 
정수



 a| 
수정할 수 없는 오류
 a| 
드라이브의 SMART(Self-Monitoring, Analysis and Reporting Technology) 모니터링 시스템에서 보고된 수정 불가능한 오류 값입니다.
 a| 
정수



 a| 
사용된 용량
 a| 
드라이브의 사용된 용량(바이트)입니다.
 a| 
정수



 a| 
사용된 메모리
 a| 
이 드라이브를 호스팅하는 노드에서 현재 사용 중인 메모리 양입니다.
 a| 
정수



 a| 
쓴다
 a| 
이 드라이브에 대한 초당 write() 호출 수입니다.
 a| 
정수



 a| 
쓰기바이트
 a| 
클라이언트 활동으로 인해 드라이브에 쓰여진 총 바이트 수입니다.
 a| 
정수



 a| 
결합된 쓰기
 a| 
더 큰 쓰기 작업으로 결합될 수 있는 인접 섹터에 대한 write() 호출의 수입니다.
 a| 
정수



 a| 
writeMsec
 a| 
쓰기에 소요된 시간(밀리초)입니다.
 a| 
정수



 a| 
writeOps
 a| 
클라이언트 활동으로 인해 드라이브에 발생한 총 쓰기 작업 수입니다.
 a| 
정수

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_getdrivestats.adoc[드라이브 통계 가져오기]
