---
permalink: api/reference_element_api_purgedeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,purge,purging,multiple,deleted,purgedeletedvolumes 
summary: PurgeDeletedVolumes 메서드를 사용하면 삭제된 볼륨을 즉시 영구적으로 제거할 수 있습니다. 이 메서드를 사용하면 한 번에 최대 500개의 볼륨을 제거할 수 있습니다. 
---
= 삭제된 볼륨 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `PurgeDeletedVolumes` 삭제된 볼륨을 즉시 영구적으로 제거하는 방법입니다. 이 방법을 사용하면 한 번에 최대 500개의 볼륨을 제거할 수 있습니다.

볼륨을 삭제하려면 다음을 사용해야 합니다. `DeleteVolumes` 제거되기 전에.  볼륨은 일정 시간이 지나면 자동으로 정리되므로 일반적으로 이 방법을 사용할 필요가 없습니다.


NOTE: 한 번에 많은 수의 볼륨을 정리하거나 정리하는 각 볼륨에 연관된 스냅샷이 많은 경우 해당 메서드가 실패하고 "xDBConnectionLoss" 오류가 반환될 수 있습니다.  이런 일이 발생하면 볼륨을 줄여서 메서드 호출을 다시 시도하세요.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


| 볼륨 ID | 시스템에서 제거할 볼륨의 볼륨 ID 목록입니다. | 정수 배열 | 아니요 | 아니요 


| 계정 ID | 계정 ID 목록입니다.  지정된 모든 계정의 모든 볼륨이 시스템에서 제거됩니다. | 정수 배열 | 아니요 | 아니요 


| 볼륨액세스그룹ID | volumeAccessGroupID 목록입니다.  지정된 모든 볼륨 액세스 그룹의 모든 볼륨이 시스템에서 제거됩니다. | 정수 배열 | 아니요 | 아니요 
|===
*참고:* 메서드 호출당 위 매개변수를 하나만 지정할 수 있습니다.  두 개 이상을 지정하거나 아무것도 지정하지 않으면 오류가 발생합니다.



== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "PurgeDeletedVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_deletevolumes.adoc[볼륨 삭제]
