---
permalink: api/reference_element_api_node.html 
sidebar: sidebar 
keywords: object,objects,node 
summary: 노드 객체에는 클러스터의 각 노드에 대한 정보가 포함되어 있습니다.  ListActiveNodes 및 ListAllNodes 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 마디
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드 객체에는 클러스터의 각 노드에 대한 정보가 포함되어 있습니다.  이 정보는 다음을 사용하여 검색할 수 있습니다. `ListActiveNodes` 그리고 `ListAllNodes` 행동 양식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
연관된FServiceID
 a| 
노드의 파이버 채널 서비스 ID입니다.  노드가 파이버 채널 노드가 아닌 경우 "0"입니다.
 a| 
정수



 a| 
연관된 마스터 서비스 ID
 a| 
노드의 마스터 서비스 ID입니다.
 a| 
정수



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체



 a| 
섀시 이름
 a| 
섀시를 고유하게 식별합니다. 단일 섀시의 모든 노드에 동일합니다.
 a| 
끈



 a| 
cip
 a| 
노드에 할당된 클러스터 IP 주소입니다.
 a| 
끈



 a| 
시피
 a| 
클러스터 통신에 사용되는 네트워크 인터페이스입니다.
 a| 
끈



 a| 
사용자 지정 보호 도메인 이름
 a| 
사용자 정의 보호 도메인을 고유하게 식별합니다.  이 이름은 지정된 사용자 지정 보호 도메인의 모든 섀시 내의 모든 스토리지 노드에서 동일합니다.
 a| 
끈



 a| 
fibreChannelTargetPortGroup
 a| 
이 노드와 연관된 대상 그룹입니다.  노드가 파이버 채널 노드가 아니면 "null"입니다.
 a| 
정수



 a| 
유지 관리 모드
 a| 
노드가 유지 관리를 위해 어떤 모드에 있는지 나타냅니다.
 a| 
해당 없음



 a| 
밉
 a| 
노드 관리에 사용되는 IP 주소입니다.
 a| 
끈



 a| 
미피
 a| 
노드 관리에 사용되는 네트워크 인터페이스입니다.
 a| 
끈



 a| 
이름
 a| 
노드의 호스트 이름입니다.
 a| 
끈



 a| 
노드ID
 a| 
이 노드의 NodeID입니다.
 a| 
정수



 a| 
노드슬롯
 a| 
HCI 플랫폼의 경우, 이 노드가 있는 섀시 슬롯에 해당하는 문자("A", "B", "C" 또는 "D")입니다.  저장 플랫폼의 경우 이 값은 null입니다.
 a| 
끈



 a| 
플랫폼 정보
 a| 
노드에 대한 하드웨어 정보입니다.  회원:

* chassisType: 노드의 하드웨어 플랫폼.
* cpuModel: 하드웨어 플랫폼의 CPU 모델입니다.
* nodeMemoryGB: 물리적 플랫폼에 설치된 메모리의 양(GB)입니다.
* nodeType: 노드 모델 이름.
* platformConfigVersion: 이 노드 하드웨어에 대해 구성된 소프트웨어 버전입니다.

 a| 
JSON 객체



 a| 
역할
 a| 
클러스터에서 노드의 역할. 가능한 값:

* 관리
* 스토리지
* 컴퓨팅
* 증인

 a| 



 a| 
한모금
 a| 
노드에 할당된 스토리지 IP 주소입니다.
 a| 
끈



 a| 
시피
 a| 
저장 트래픽에 사용되는 네트워크 인터페이스입니다.
 a| 
끈



 a| 
소프트웨어 버전
 a| 
노드에서 실행 중인 Element 소프트웨어의 현재 버전을 반환합니다.
 a| 
끈



 a| 
UUID
 a| 
이 노드와 연관된 범용 고유 식별자입니다.
 a| 
끈



 a| 
가상 네트워크
 a| 
가상 네트워크 IP 주소와 ID를 포함하는 객체입니다.
 a| 
xref:reference_element_api_virtualnetwork.adoc[가상 네트워크]정렬

|===


== 더 많은 정보를 찾아보세요

* xref:reference_element_api_listactivenodes.adoc[ListActiveNodes]
* xref:reference_element_api_listallnodes.adoc[모든 노드 나열]

