---
permalink: api/reference_element_api_hardwareinfo.html 
sidebar: sidebar 
keywords: object,objects,hardwareInfo 
summary: hardwareInfo 개체에는 클러스터의 각 노드의 하드웨어 및 상태에 대한 자세한 정보가 포함되어 있습니다.  GetHardwareInfo API 메서드를 사용하여 이 정보를 검색할 수 있습니다. 
---
= 하드웨어 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
hardwareInfo 개체에는 클러스터의 각 노드의 하드웨어 및 상태에 대한 자세한 정보가 포함되어 있습니다.  이 정보는 다음을 사용하여 검색할 수 있습니다. `GetHardwareInfo` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
보드시리얼
 a| 
DMI 보드 일련번호.
 a| 
끈



 a| 
버스
 a| 
마더보드 미디어 버스 정보.
 a| 
JSON 객체



 a| 
섀시직렬
 a| 
섀시의 일련번호.
 a| 
끈



 a| 
드라이브하드웨어
 a| 
노드의 각 드라이브에 대한 정보 목록입니다.
 a| 
JSON 객체 배열



 a| 
파이버채널포트
 a| 
노드의 파이버 채널 포트 목록입니다.
 a| 
정수 배열



 a| 
하드웨어 구성
 a| 
마더보드 주변 장치 구성 정보.
 a| 
JSON 객체



 a| 
커널 크래시덤프상태
 a| 
운영 체제 커널의 크래시 덤프 구성.
 a| 
끈



 a| 
메모리
 a| 
펌웨어 및 시스템 메모리 하드웨어 정보.
 a| 
JSON 객체



 a| 
회로망
 a| 
각 노드의 네트워크 인터페이스 하드웨어에 대한 설명입니다.
 a| 
JSON 객체



 a| 
네트워크 인터페이스
 a| 
노드의 네트워크 인터페이스 상태입니다.
 a| 
JSON 객체



 a| 
노드슬롯
 a| 
HCI 플랫폼의 경우, 이 노드가 있는 섀시 슬롯에 해당하는 문자("A", "B", "C" 또는 "D")입니다.  저장 플랫폼의 경우 이 값은 null입니다.
 a| 
끈



 a| 
엔브램
 a| 
노드의 NVRAM 통계.
 a| 
JSON 객체



 a| 
기원
 a| 
마더보드 공급업체.
 a| 
끈



 a| 
플랫폼
 a| 
섀시 플랫폼에 대한 설명입니다.
 a| 
JSON 객체



 a| 
연속물
 a| 
제품의 일련번호입니다.
 a| 
끈



 a| 
내부
 a| 
스토리지 컨트롤러 정보.
 a| 
JSON 객체



 a| 
시스템메모리
 a| 
운영 체제 메모리 사용량 및 성능 정보.
 a| 
JSON 객체



 a| 
체계
 a| 
노드 섀시의 유형입니다.
 a| 
JSON 객체



 a| 
UUID
 a| 
노드의 고유 ID입니다.
 a| 
UUID

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_gethardwareinfo.adoc[하드웨어 정보 받기]
