---
permalink: api/reference_element_api_createvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,groups,group,create,creating,CreateVolumeAccessGroup 
summary: CreateVolumeAccessGroup을 사용하여 새로운 볼륨 액세스 그룹을 만들 수 있습니다.  볼륨 액세스 그룹을 만들 때는 이름을 지정해야 하며, 선택적으로 시작자와 볼륨을 입력할 수 있습니다. 
---
= 볼륨 액세스 그룹 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `CreateVolumeAccessGroup` 새로운 볼륨 액세스 그룹을 생성합니다.  볼륨 액세스 그룹을 만들 때는 이름을 지정해야 하며, 선택적으로 시작자와 볼륨을 입력할 수 있습니다.

볼륨 액세스 그룹에 추가하는 모든 이니시에이터 IQN은 CHAP 인증 없이도 그룹의 모든 볼륨에 액세스할 수 있습니다.


NOTE: 복제된 볼륨은 소스 볼륨의 볼륨 액세스 그룹 멤버십을 상속하지 않습니다.

볼륨 액세스 그룹을 만들 때 다음 사항을 고려하세요.

* 볼륨 액세스 그룹에는 최대 64개의 개시자 IQN이 포함될 수 있습니다.
* 개시자는 하나의 볼륨 액세스 그룹에만 속할 수 있습니다.
* 볼륨 액세스 그룹에는 최대 2000개의 볼륨이 포함될 수 있습니다.
* 각 볼륨 액세스 그룹은 최대 4개의 볼륨 액세스 그룹에 속할 수 있습니다.




== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
개시자들
 a| 
볼륨 액세스 그룹에 포함할 개시자 ID 또는 이름(IQN 및 WWPN) 목록입니다.  개시자 이름 목록을 전달하면 개시자가 존재하지 않으면 생성됩니다.  개시자 ID 목록을 전달하는 경우, 해당 메서드는 개시자 중에 아직 존재하지 않는 것이 있으면 오류를 반환합니다.  개시자 이름을 전달하는 것은 더 이상 사용되지 않습니다. 가능한 경우 개시자 ID를 사용해야 합니다.
 a| 
정수 배열 또는 문자열 배열(더 이상 사용되지 않음)
 a| 
 a| 
아니요



 a| 
이름
 a| 
볼륨 액세스 그룹의 이름입니다.  고유할 필요는 없지만 권장됩니다.  길이는 1~64자여야 합니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
볼륨
 a| 
볼륨 액세스 그룹에 포함할 볼륨 ID 목록입니다.
 a| 
정수 배열
 a| 
 a| 
아니요



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
{}
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨액세스그룹
 a| 
새로 생성된 볼륨 액세스 그룹에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[볼륨액세스그룹]



 a| 
볼륨액세스그룹ID
 a| 
새로 생성된 볼륨 액세스 그룹의 ID입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "CreateVolumeAccessGroup",
   "params": {
      "name": "myaccessgroup",
      "initiators": ["iqn.1993-08.org.debian: 01: a31b1d799d5c"],
      "volumes": [327],
      "attributes": {}
   }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [],
      "initiatorIDs": [
        95
      ],
      "initiators": [
        "iqn.1993-08.org.debian: 01: a31b1d799d5c"
      ],
      "name": "myaccessgroup",
      "volumeAccessGroupID": 96,
      "volumes": [
        327
      ]
    },
    "volumeAccessGroupID": 96
  }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
* xref:reference_element_api_modifyvolume.adoc[볼륨 수정]

