---
permalink: api/reference_element_api_volumepair.html 
sidebar: sidebar 
keywords: object,objects,volumePair 
summary: volumePair 개체에는 다른 클러스터의 다른 볼륨과 쌍을 이루는 볼륨에 대한 정보가 포함되어 있습니다.  볼륨이 페어링되지 않은 경우 이 객체는 비어 있습니다.  ListActivePairedVolumes 및 ListActiveVolumes API 메서드를 사용하면 페어링된 볼륨에 대한 정보를 반환할 수 있습니다. 
---
= 볼륨페어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
volumePair 개체에는 다른 클러스터의 다른 볼륨과 쌍을 이루는 볼륨에 대한 정보가 포함되어 있습니다.  볼륨이 페어링되지 않은 경우 이 객체는 비어 있습니다.  당신은 사용할 수 있습니다 `ListActivePairedVolumes` 그리고 `ListActiveVolumes` 쌍으로 구성된 볼륨에 대한 정보를 반환하는 API 메서드입니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
클러스터페어ID
 a| 
볼륨이 페어링된 클러스터입니다.
 a| 
정수



 a| 
원격 복제
 a| 
볼륨 복제에 대한 세부 정보.  회원:

* 모드: (문자열) "비동기", "동기화" 또는 "스냅샷만" 중 하나입니다.
* pauseLimit: (정수) 내부적으로만 사용 가능.
* remoteServiceID: (정수) 원격 슬라이스 서비스 ID입니다.
* resumeDetails: (문자열) 나중에 사용하기 위해 예약되어 있습니다.
* snapshotReplication(JSON 객체)
+
** 상태: (문자열) 진행 중인 스냅샷 복제의 상태(진행 중인 경우)입니다.
** stateDetails: (문자열) 향후 사용을 위해 예약됨.


* 상태: (문자열) 볼륨 복제의 상태입니다.
* stateDetails: (문자열) 향후 사용을 위해 예약됨.

 a| 
JSON 객체



 a| 
원격 슬라이스 ID
 a| 
원격 클러스터의 클러스터 정의 슬라이스 ID입니다.
 a| 
정수



 a| 
원격 볼륨 ID
 a| 
로컬 볼륨이 페어링된 원격 클러스터의 볼륨 ID입니다.
 a| 
정수



 a| 
원격 볼륨 이름
 a| 
원격 볼륨의 이름입니다.
 a| 
끈



 a| 
볼륨페어UUID
 a| 
이 페어링에 대한 표준 형식의 범용적으로 고유한 클러스터 정의 식별자입니다.
 a| 
끈

|===


== 더 많은 정보를 찾아보세요

* xref:reference_element_api_listactivepairedvolumes.adoc[ListActivePairedVolumes]
* xref:reference_element_api_listactivevolumes.adoc[ListActiveVolumes]

