---
permalink: api/reference_element_api_copyvolume.html 
sidebar: sidebar 
keywords: volume,volumes,CopyVolume,overwrite,overwriting,data 
summary: 'CopyVolume 메서드를 사용하면 기존 볼륨의 데이터 내용을 다른 볼륨(또는 스냅샷)의 데이터 내용으로 덮어쓸 수 있습니다.  IQN, QoS 설정, 크기, 계정, 볼륨 액세스 그룹 멤버십과 같은 대상 볼륨의 속성은 변경되지 않습니다.  대상 볼륨은 이미 존재해야 하며 소스 볼륨과 크기가 같아야 합니다.' 
---
= 복사 볼륨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `CopyVolume` 기존 볼륨의 데이터 내용을 다른 볼륨(또는 스냅샷)의 데이터 내용으로 덮어쓰는 방법입니다.  IQN, QoS 설정, 크기, 계정, 볼륨 액세스 그룹 멤버십과 같은 대상 볼륨의 속성은 변경되지 않습니다.  대상 볼륨은 이미 존재해야 하며 소스 볼륨과 크기가 같아야 합니다.

작업이 시작되기 전에 클라이언트가 대상 볼륨을 마운트 해제하는 것이 가장 좋습니다.  작업 중에 대상 볼륨이 수정되면 변경 사항이 손실됩니다.  이 작업을 완료하는 데 걸리는 시간은 다양합니다.  당신은 사용할 수 있습니다xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기] 프로세스가 언제 완료되었는지 확인하는 방법xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] 복사 진행 상황을 확인하세요.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
dst볼륨ID
 a| 
덮어쓸 볼륨의 VolumeID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
볼륨ID
 a| 
읽을 볼륨의 VolumeID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
스냅샷ID
 a| 
복제본의 소스로 사용되는 스냅샷의 ID입니다.  ID가 제공되지 않으면 현재 활성 볼륨이 사용됩니다.
 a| 
정수
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
작업 결과를 얻는 데 사용되는 핸들 값입니다.
 a| 
정수



 a| 
클론ID
 a| 
새로 복제된 볼륨의 CloneID입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "CopyVolume",
   "params": {
      "volumeID" : 3,
      "dstVolumeID" : 2
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "asyncHandle": 9,
    "cloneID": 5
  }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]

