---
permalink: api/reference_element_api_disablemaintenancemode.html 
sidebar: sidebar 
keywords: disable,maintenance,mode 
summary: DisableMaintenanceMode 메서드를 사용하면 스토리지 노드를 유지 관리 모드에서 해제할 수 있습니다.  유지 관리를 완료하고 노드가 온라인 상태가 된 후에만 유지 관리 모드를 비활성화해야 합니다. 
---
= 유지 관리 모드 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `DisableMaintenanceMode` 저장 노드를 유지 관리 모드에서 해제하는 방법입니다.  유지 관리를 완료하고 노드가 온라인 상태가 된 후에만 유지 관리 모드를 비활성화해야 합니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
노드
 a| 
유지 관리 모드에서 해제할 스토리지 노드 ID 목록입니다.
 a| 
정수 배열
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
GetAsyncResult 메서드를 사용하면 이 asyncHandle을 검색하고 유지 관리 모드 전환이 완료되는 시점을 확인할 수 있습니다.
 a| 
정수



 a| 
현재 모드
 a| 
노드의 현재 유지 관리 모드 상태입니다. 가능한 값:

* 비활성화: 유지 관리가 요청되지 않았습니다.
* FailedToRecover: 노드가 유지 관리 모드에서 복구되지 못했습니다.
* 예상치 못한 오류: 노드가 오프라인 상태인 것으로 확인되었지만 비활성화 모드였습니다.
* RecoveringFromMaintenance: 노드가 유지 관리 모드에서 복구 중입니다.
* 유지 관리 준비: 노드에 대한 유지 관리를 수행하기 위한 작업이 진행 중입니다.
* ReadyForMaintenance: 노드가 유지 관리를 수행할 준비가 되었습니다.

 a| 
MaintenanceMode(문자열)



 a| 
요청된 모드
 a| 
노드의 요청된 유지 관리 모드 상태입니다. 가능한 값:

* 비활성화: 유지 관리가 요청되지 않았습니다.
* FailedToRecover: 노드가 유지 관리 모드에서 복구되지 못했습니다.
* 예상치 못한 오류: 노드가 오프라인 상태인 것으로 확인되었지만 비활성화 모드였습니다.
* RecoveringFromMaintenance: 노드가 유지 관리 모드에서 복구 중입니다.
* 유지 관리 준비: 노드에 대한 유지 관리를 수행하기 위한 작업이 진행 중입니다.
* ReadyForMaintenance: 노드가 유지 관리를 수행할 준비가 되었습니다.

 a| 
MaintenanceMode(문자열)

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "DisableMaintenanceMode",
  "params": {
    "nodes": [6]
  },
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "requestedMode": "Disabled",
        "asyncHandle": 1,
        "currentMode": "Enabled"
    }
}
----


== 버전 이후 새로운

12.2



== 더 많은 정보를 찾아보세요

http://docs.netapp.com/us-en/hci/docs/concept_hci_storage_maintenance_mode.html["NetApp HCI 스토리지 유지 관리 모드 개념"^]
