---
permalink: api/reference_element_api_setprotectiondomainlayout.html 
sidebar: sidebar 
keywords: layout,custom,protection domain,protection domains,setting protection domains 
summary: SetProtectionDomainLayout 메서드를 사용하면 사용자 지정 보호 도메인에 노드를 할당할 수 있습니다. 
---
= 보호 도메인 레이아웃 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `SetProtectionDomainLayout` 사용자 정의 보호 도메인에 노드를 할당하는 방법입니다.

클러스터의 모든 활성 노드에 대한 정보를 제공해야 하며 비활성 노드에 대한 정보는 제공할 수 없습니다.  주어진 섀시의 모든 노드는 동일한 사용자 정의 보호 도메인에 할당되어야 합니다.  모든 노드에 대해 동일한 protectionDomainType을 제공해야 합니다. 노드 및 섀시와 같이 사용자 정의되지 않은 protectionDomainType은 포함되어서는 안 됩니다.  이 중 하나라도 제공되면 사용자 지정 보호 도메인이 무시되고 해당 오류가 반환됩니다.


NOTE: 다음 구성에서는 사용자 지정 보호 도메인이 지원되지 않습니다.

* 공유 섀시를 포함하는 스토리지 클러스터
* 2노드 스토리지 클러스터


이러한 구성을 사용하는 스토리지 클러스터에서 해당 메서드를 사용하면 오류가 반환됩니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
보호 도메인 레이아웃
 a| 
각 노드에 대한 보호 도메인 정보입니다.
 a| 
JSON 목록link:reference_element_api_nodeprotectiondomains.html["노드 보호 도메인"] 사물.
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
보호 도메인 레이아웃
 a| 
각 노드와 연관된 보호 도메인의 목록입니다.
 a| 
JSON 목록link:reference_element_api_nodeprotectiondomains.html["노드 보호 도메인"] 사물.

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "id": 1,
  "method": "SetProtectionDomainLayout",
  "params": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----

{
  "id": 1,
  "result": {
    "protectionDomainLayout": [
      {
        "nodeID": 1,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR2914008D",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 2,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500EA",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-1",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 3,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291500C3",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      },
      {
        "nodeID": 4,
        "protectionDomains": [
          {
            "protectionDomainName": "QTFCR291400E6",
            "protectionDomainType": "chassis"
          },
          {
            "protectionDomainName": "Rack-2",
            "protectionDomainType": "custom"
          }
        ]
      }
    ]
  }
}
----


== 버전 이후 새로운

12.0
