---
permalink: api/reference_element_api_createsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,create,creating,CreateSnapMirrorRelationship 
summary: Element 웹 UI는 CreateSnapMirrorRelationship 메서드를 사용하여 소스 및 대상 엔드포인트 간에 SnapMirror 확장 데이터 보호 관계를 생성합니다. 
---
= CreateSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 웹 UI는 다음을 사용합니다. `CreateSnapMirrorRelationship` 소스 및 대상 엔드포인트 간에 SnapMirror 확장 데이터 보호 관계를 생성하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
스냅미러엔드포인트ID
 a| 
Element 스토리지 클러스터와 통신하는 원격 ONTAP 스토리지 시스템의 엔드포인트 ID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
소스볼륨
 a| 
관계의 소스 볼륨입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[스냅미러볼륨정보]
 a| 
None
 a| 
예



 a| 
목적지볼륨
 a| 
관계의 대상 볼륨입니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[스냅미러볼륨정보]
 a| 
None
 a| 
예



 a| 
관계 유형
 a| 
관계의 유형.  Element 소프트웨어를 실행하는 스토리지 시스템에서 이 값은 항상 "`extended_data_protection`"입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
정책 이름
 a| 
관계에 대한 ONTAP SnapMirror 정책의 이름을 지정합니다.  지정하지 않으면 기본 정책 이름은 MirrorLatest입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
일정 이름
 a| 
ONTAP 시스템에서 SnapMirror 관계를 업데이트하는 데 사용되는 기존 cron 일정의 이름입니다.  일정을 지정하지 않으면 snapMirror 업데이트가 예약되지 않으며 수동으로 업데이트해야 합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
최대 전송률
 a| 
볼륨 간 최대 데이터 전송 속도를 초당 킬로바이트 단위로 지정합니다.  기본값인 0은 무제한이며 SnapMirror 관계가 사용 가능한 네트워크 대역폭을 최대한 활용할 수 있도록 허용합니다.
 a| 
정수
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
스냅미러관계
 a| 
새로 생성된 SnapMirror 관계에 대한 정보입니다.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[스냅미러관계]

|===


== 버전 이후 새로운

10.1
