---
permalink: api/reference_element_api_getconfig.html 
sidebar: sidebar 
keywords: node,get,getting,info,config,configuration,getconfig 
summary: GetConfig API 메서드를 사용하면 노드에 대한 모든 구성 정보를 가져올 수 있습니다.  이 API 메서드에는 GetClusterConfig 및 GetNetworkConfig API 메서드에서 사용할 수 있는 동일한 정보가 포함되어 있습니다. 
---
= GetConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `GetConfig` 노드에 대한 모든 구성 정보를 가져오는 API 메서드입니다.  이 API 메서드에는 두 가지 모두에서 사용 가능한 동일한 정보가 포함됩니다. `GetClusterConfig` 그리고 `GetNetworkConfig` API 방법.



== 매개변수

이 방법에는 입력 매개변수가 없습니다.



== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
설정
 a| 
클러스터의 구성 세부 정보.  이 개체에는 다음이 포함되어 있습니다.

* xref:reference_element_api_cluster.adoc[무리]: 스토리지 노드가 연관된 스토리지 클러스터와 통신하는 방식을 식별하는 클러스터 정보입니다.
* xref:reference_element_api_network_all_interfaces.adoc[네트워크(모든 인터페이스)]: 노드의 각 네트워크 인터페이스에 대한 네트워크 연결 유형 및 현재 설정.

 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "GetConfig",
   "params": {},
   "id" : 1
}
----


== 응답 예시

이 응답 예시는 길이가 길기 때문에 보충 주제에 문서화되어 있습니다.



== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getclusterconfig.adoc[GetClusterConfig]
* xref:reference_element_api_getnetworkconfig.adoc[GetNetworkConfig]
* xref:reference_element_api_response_example_getconfig.adoc[GetConfig]

