---
permalink: api/reference_element_api_clusterinfo.html 
sidebar: sidebar 
keywords: element, api, object, objects, clusterInfo 
summary: clusterInfo 개체에는 노드가 클러스터와 통신하는 데 사용하는 정보가 포함되어 있습니다.  GetClusterInfo API 메서드를 사용하면 이 정보를 얻을 수 있습니다. 
---
= 클러스터정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterInfo 개체에는 노드가 클러스터와 통신하는 데 사용하는 정보가 포함되어 있습니다.  GetClusterInfo API 메서드를 사용하면 이 정보를 얻을 수 있습니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체



 a| 
기본 보호 계획
 a| 
보호 체계가 제공되지 않는 한 새 볼륨에 기본적으로 사용되는 보호 체계입니다.xref:reference_element_api_createvolume.adoc[볼륨 생성] 메서드 호출.  이 보호 체계는 항상 활성화된 보호 체계 세트에 있어야 합니다.
 a| 
끈



 a| 
활성화된 보호 계획
 a| 
이 스토리지 클러스터에서 활성화된 모든 보호 체계 목록입니다.
 a| 
문자열 배열



 a| 
암호화AtRestState
 a| 
휴면 상태 암호화 기능의 상태입니다. 가능한 값:

* 활성화: 저장 데이터 암호화가 활성화됩니다.
* 활성화됨: 저장 시 암호화가 활성화되었습니다.
* 비활성화: 저장 데이터 암호화가 비활성화됩니다.
* 비활성화됨: 저장 시 암호화가 비활성화되었습니다.

 a| 
끈



 a| 
앙상블
 a| 
클러스터에 참여하는 노드입니다.
 a| 
문자열 배열



 a| 
엠비피
 a| 
관리 네트워크의 클러스터에 대한 부동(가상) IP 주소입니다.
 a| 
끈



 a| 
mvip인터페이스
 a| 
MVIP 주소와 연결된 물리적 인터페이스입니다.
 a| 
끈



 a| 
mvip노드ID
 a| 
마스터 MVIP 주소를 보유한 노드입니다.
 a| 
정수



 a| 
mvipVlan태그
 a| 
MVIP 주소에 대한 VLAN 식별자입니다.
 a| 
끈



 a| 
이름
 a| 
고유한 클러스터 이름입니다.
 a| 
끈



 a| 
반복 횟수
 a| 
클러스터에 저장할 각 데이터의 복제본 수입니다.  유효한 값은 "2"입니다.
 a| 
정수



 a| 
소프트웨어 암호화 상태
 a| 
소프트웨어 기반 암호화 - 휴면 상태.
 a| 
끈



 a| 
지원되는 보호 계획
 a| 
이 스토리지 클러스터에서 지원되는 모든 보호 체계 목록입니다.
 a| 
문자열 배열



 a| 
svip
 a| 
스토리지(iSCSI) 네트워크의 클러스터에 대한 부동(가상) IP 주소입니다.
 a| 
끈



 a| 
svip인터페이스
 a| 
마스터 SVIP 주소와 연결된 물리적 인터페이스입니다.
 a| 
끈



 a| 
svip노드ID
 a| 
마스터 SVIP 주소를 보유한 노드입니다.
 a| 
정수



 a| 
svipVlan태그
 a| 
마스터 SVIP 주소에 대한 VLAN 식별자입니다.
 a| 
끈



 a| 
고유ID
 a| 
클러스터의 고유 ID입니다.
 a| 
끈



 a| 
UUID
 a| 
클러스터의 고유 식별자입니다.
 a| 
UUID



 a| 
볼륨 로드 밸런스 온 실제 Iops 상태
 a| 
실제 IOPS를 기준으로 슬라이스 밸런싱 상태가 최소 IOPS 기능으로 결정됩니다.  Element 12.8부터 사용 가능합니다.
 a| 
끈

|===
[discrete]
== 더 많은 정보를 찾아보세요

* link:reference_element_api_getclusterinfo.html["클러스터 정보 가져오기"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"^]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

