---
permalink: api/reference_element_api_removedrives.html 
sidebar: sidebar 
keywords: cluster,drive,drives,remove,removing,removedrives 
summary: RemoveDrives 메서드를 사용하면 클러스터에 속한 드라이브를 사전에 제거할 수 있습니다.  클러스터 용량을 줄이거나 드라이브의 수명이 다 되어가면서 교체할 준비를 할 때 이 방법을 사용할 수 있습니다.  드라이브가 클러스터에서 제거되기 전에 드라이브의 모든 데이터가 제거되고 클러스터의 다른 드라이브로 마이그레이션됩니다. 
---
= 드라이브 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `RemoveDrives` 클러스터에 속한 드라이브를 사전에 제거하는 방법입니다.  클러스터 용량을 줄이거나 드라이브의 수명이 다 되어가면서 교체할 준비를 할 때 이 방법을 사용할 수 있습니다. `RemoveDrives` 클러스터의 다른 노드에 블록 데이터의 세 번째 사본을 만들고 동기화가 완료될 때까지 기다린 후 드라이브를 "사용 가능" 목록으로 이동합니다.  "사용 가능" 목록에 있는 드라이브는 시스템에서 완전히 제거되었으며 실행 중인 서비스나 활성 데이터가 없습니다.

`RemoveDrives`비동기 방식입니다.  제거하는 드라이브의 총 용량에 따라 모든 데이터를 마이그레이션하는 데 몇 분이 걸릴 수 있습니다.

여러 드라이브를 제거할 때는 단일 드라이브를 사용하십시오. `RemoveDrives` 각각 하나의 드라이브가 있는 여러 개의 개별 메서드 대신 메서드 호출을 사용합니다.  이렇게 하면 클러스터의 저장 부하를 균등하게 안정화하기 위해 수행해야 하는 데이터 밸런싱 양이 줄어듭니다.

"실패" 상태의 드라이브를 제거할 수도 있습니다. `RemoveDrives` .  "실패" 상태의 드라이브를 제거하면 드라이브가 "사용 가능" 또는 "활성" 상태로 돌아가지 않습니다.  클러스터에서 드라이브를 사용할 수 없습니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
드라이브
 a| 
클러스터에서 제거할 드라이브ID 목록입니다.
 a| 
정수 배열
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
작업 결과를 얻는 데 사용되는 핸들 값입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "RemoveDrives",
   "params": {
      "drives"  : [3, 4, 5]
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result" : {
     "asyncHandle": 1
   }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기]
* xref:reference_element_api_listdrives.adoc[드라이브 목록]

