---
permalink: api/reference_element_api_startvolumepairing.html 
sidebar: sidebar 
keywords: volume,pair,pairing,start,starting,startvolumepairing 
summary: StartVolumePairing 메서드를 사용하면 볼륨에서 인코딩된 키를 생성하여 다른 볼륨과 페어링할 수 있습니다.  이 메서드에서 생성되는 키는 CompleteVolumePairing 메서드에서 볼륨 페어링을 설정하는 데 사용됩니다. 
---
= 볼륨 페어링 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `StartVolumePairing` 볼륨에서 인코딩된 키를 생성하여 다른 볼륨과 페어링하는 방법입니다.  이 방법이 생성하는 키는 다음에서 사용됩니다. `CompleteVolumePairing` 볼륨 페어링을 설정하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
방법
 a| 
페어링 과정을 시작할 볼륨 모드입니다.  볼륨이 소스 볼륨인 경우에만 모드를 설정할 수 있습니다. 가능한 값:

* `Async`: 쓰기는 로컬에서 완료되면 확인됩니다.  클러스터는 쓰기가 대상 클러스터에 복제될 때까지 기다리지 않습니다.  (모드 매개변수가 지정되지 않으면 기본값입니다.)
* `Sync`: 소스는 데이터가 로컬과 원격 클러스터에 저장될 때 쓰기를 확인합니다.
* `SnapshotsOnly`: 소스 클러스터에서 생성된 스냅샷만 복제됩니다.  소스 볼륨의 활성 쓰기는 복제되지 않습니다.

 a| 
끈
 a| 
None
 a| 
아니요



 a| 
볼륨ID
 a| 
페어링 프로세스를 시작할 볼륨의 ID입니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
볼륨페어링키
 a| 
에 의해 사용되는 문자열xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing] API 방식.
 a| 
끈

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "StartVolumePairing",
   "params": {
         "mode": "Async",
	 "volumeID" : 14
      },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result" : {
      "volumePairingKey" : "7b226d766970223a223139322e3136382e3133392e313232222c22766f6c756d654944223a312c22766f6c756d654e616d65223a2254657374222c22766f6c756d655061697255554944223a2236393632346663622d323032652d343332352d613536392d656339633635356337623561227d"
      }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_completevolumepairing.adoc[CompleteVolumePairing]
