---
permalink: api/reference_element_api_setsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,info,setting,set,setsnmpinfo 
summary: SetSnmpInfo 메서드를 사용하면 클러스터 노드에서 SNMP 버전 2 및 버전 3을 구성할 수 있습니다.  이 인터페이스를 사용하여 설정한 값은 클러스터의 모든 노드에 적용되며, 전달된 값은 SetSnmpInfo에 대한 이전 호출에서 설정된 모든 값을 대체합니다. 
---
= SetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `SetSnmpInfo` 클러스터 노드에서 SNMP 버전 2 및 버전 3을 구성하는 방법입니다.  이 인터페이스로 설정한 값은 클러스터의 모든 노드에 적용되며 전달된 값은 이전 호출에서 설정된 모든 값을 대체합니다. `SetSnmpInfo` .



== 매개변수


NOTE: SetSnmpInfo는 Element 버전 6.0 이상에서는 더 이상 사용되지 않습니다.  사용하다xref:reference_element_api_enablesnmp.adoc[EnableSnmp] 그리고xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 대신 방법을 사용하세요.

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
네트워크
 a| 
클러스터 노드에서 실행되는 SNMP 서버에 대한 네트워크 및 액세스 유형 목록입니다.  SNMP를 참조하세요xref:reference_element_api_network_snmp.adoc[회로망] 가능한 값에 대한 객체입니다.  이 매개변수는 SNMP v2에만 필요합니다.
 a| 
xref:reference_element_api_network_snmp.adoc[회로망]정렬
 a| 
None
 a| 
아니요



 a| 
활성화됨
 a| 
true로 설정하면 클러스터의 각 노드에서 SNMP가 활성화됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
snmpV3Enabled
 a| 
true로 설정하면 클러스터의 각 노드에서 SNMP v3가 활성화됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
usm사용자
 a| 
SNMP v3가 활성화된 경우 이 값을 네트워크 매개변수 대신 전달해야 합니다.  이 매개변수는 SNMP v3에만 필요합니다.
 a| 
xref:reference_element_api_usmuser.adoc[usm사용자]
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== SNMP v3가 활성화된 요청 예제

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":true,
    "usmUsers":[
      {
        "name":"user1",
        "access":"rouser",
        "secLevel":"auth",
        "password":"namex1",
        "passphrase":"yourpassphrase"
      }
    ]
  },
 "id":1
}
----


== SNMP v2가 활성화된 요청 예제

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
"method":"SetSnmpInfo",
"params":{
    "enabled":true,
    "snmpV3Enabled":false,
    "networks":[
      {
        "community":"public",
        "access":"ro",
        "network":"localhost",
      }
    ]
  },
  "id":1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1
  "result" :{
  }
}
----


== 버전 이후 새로운

9.6
