---
permalink: api/reference_element_api_schedule.html 
sidebar: sidebar 
keywords: object,objects,schedule 
summary: 일정 개체에는 볼륨의 스냅샷을 자율적으로 만들기 위해 생성된 일정에 대한 정보가 포함되어 있습니다.  ListSchedules API 메서드를 사용하면 모든 일정에 대한 일정 정보를 검색할 수 있습니다. 
---
= 일정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일정 개체에는 볼륨의 스냅샷을 자율적으로 만들기 위해 생성된 일정에 대한 정보가 포함되어 있습니다.  모든 일정에 대한 일정 정보를 검색할 수 있습니다. `ListSchedules` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
일정 발생 빈도를 나타냅니다. 가능한 값:

* 요일
* 월의 날짜
* 시간 간격

 a| 
JSON 객체



 a| 
오류가 있습니다
 a| 
일정에 오류가 있는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
시간
 a| 
다음 스냅샷이 생성되기까지 걸리는 시간을 표시합니다.  가능한 값은 0~24입니다.
 a| 
정수



 a| 
마지막 실행 상태
 a| 
마지막으로 예약된 스냅샷의 상태를 나타냅니다. 가능한 값:

* 성공
* 실패한

 a| 
끈



 a| 
마지막 실행 시간 시작
 a| 
일정이 시작된 마지막 시간을 나타냅니다.
 a| 
ISO 8601 날짜 문자열



 a| 
분
 a| 
다음 스냅샷이 생성되기까지 걸리는 시간(분)을 표시합니다.  가능한 값은 0~59입니다.
 a| 
정수



 a| 
월 일
 a| 
스냅샷을 찍을 날짜를 나타냅니다.
 a| 
정렬



 a| 
일시 정지
 a| 
일정이 일시 중지되었는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
반복되는
 a| 
일정이 반복되는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
다음 간격 실행
 a| 
스케줄러가 다음에 활성화될 때 스케줄을 실행할지 여부를 나타냅니다.  true인 경우 스케줄러가 다음에 활성화될 때 스케줄이 실행되고, 그런 다음 이 값은 다시 false로 설정됩니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
스케줄ID
 a| 
일정의 고유 ID입니다.
 a| 
정수



 a| 
일정 정보
 a| 
일정에 지정된 고유 이름, 생성된 스냅샷의 보존 기간, 스냅샷이 생성된 볼륨의 볼륨 ID가 포함됩니다.  유효한 값:

* `enableRemoteReplication`: 스냅샷을 원격 복제에 포함할지 여부를 나타냅니다.  (부울)
* `ensureSerialCreation`: 이전 스냅샷 복제가 진행 중인 경우 새 스냅샷 생성을 허용할지 여부를 지정합니다.  (부울)
* `name`: 사용할 스냅샷 이름입니다.  (끈)
* `retention`: 스냅샷이 보관되는 시간입니다.  시간에 따라 다음 형식 중 하나로 표시됩니다.
+
** `fifo`: 스냅샷은 FIFO(선입선출) 방식으로 보관됩니다.  비어 있으면 스냅샷은 영구적으로 보관됩니다.  (끈)
** 시:분:초


* `volumeID`: 스냅샷에 포함될 볼륨의 ID입니다.  (정수)
* `volumes`: 그룹 스냅샷에 포함될 볼륨 ID 목록입니다.  (정수 배열)

 a| 
JSON 객체



 a| 
일정 이름
 a| 
일정에 지정된 고유한 이름입니다.
 a| 
끈



 a| 
일정 유형
 a| 
현재는 일정 유형의 스냅샷만 지원됩니다.
 a| 
끈



 a| 
스냅미러라벨
 a| 
scheduleInfo에 포함된 생성된 스냅샷이나 그룹 스냅샷에 적용할 snapMirrorLabel입니다.  설정하지 않으면 이 값은 null입니다.
 a| 
끈



 a| 
시작일
 a| 
일정이 처음 시작되거나 시작될 날짜를 나타냅니다. UTC 시간 형식으로 표시됩니다.
 a| 
ISO 8601 날짜 문자열



 a| 
삭제 예정
 a| 
일정이 삭제되도록 표시되었는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
평일
 a| 
스냅샷을 찍을 요일을 나타냅니다.
 a| 
정렬

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listschedules.adoc[목록 일정]
