---
permalink: api/reference_element_api_getstoragecontainerefficiency.html 
sidebar: sidebar 
keywords: volume,virtual,container,volumes,get,getting,efficiency,vvol,GetStorageContainerEfficiency 
summary: GetStorageContainerEfficiency 메서드를 사용하면 가상 볼륨 스토리지 컨테이너에 대한 효율성 정보를 검색할 수 있습니다. 
---
= GetStorageContainerEfficiency
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `GetStorageContainerEfficiency` 가상 볼륨 저장 컨테이너에 대한 효율성 정보를 검색하는 방법입니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
스토리지컨테이너ID
 a| 
효율성 정보를 검색할 저장 컨테이너의 ID입니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
압축
 a| 
저장 컨테이너의 모든 가상 볼륨에 대한 데이터 압축을 통해 절약된 공간의 양입니다.  데이터가 압축되지 않고 저장되었음을 나타내는 비율로 표시되며, 값이 1이면 데이터가 압축되지 않은 상태로 저장되었음을 의미합니다.
 a| 
뜨다



 a| 
중복 제거
 a| 
스토리지 컨테이너의 모든 가상 볼륨에 대한 데이터를 복제하지 않음으로써 절약되는 공간의 양입니다.  비율로 표시됩니다.
 a| 
뜨다



 a| 
누락된 볼륨
 a| 
효율성 데이터를 쿼리할 수 없는 가상 볼륨입니다.  볼륨 누락은 가비지 수집(GC) 주기가 1시간 미만이거나, 네트워크 연결이 일시적으로 끊어졌거나, GC 주기 이후에 서비스가 다시 시작된 경우에 발생할 수 있습니다.
 a| 
정수 배열



 a| 
씬프로비저닝
 a| 
데이터를 저장하기 위해 할당된 공간의 양에 대한 사용된 공간의 비율입니다.  비율로 표시됩니다.
 a| 
뜨다



 a| 
타임스탬프
 a| 
GC 이후 효율성 데이터가 수집된 마지막 시간입니다.
 a| 
ISO 8601 데이터 문자열

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "GetStorageContainerEfficiency",
  "params": {
    "storageContainerID" : "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1"
  },
  "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "compression": 1,
    "deduplication": 1,
    "missingVolumes": [],
    "thinProvisioning": 1,
    "timestamp": "2016-04-12T15:39:49Z"
  }
}
----


== 버전 이후 새로운

9.6
