---
permalink: api/reference_element_api_getclusterversioninfo.html 
sidebar: sidebar 
keywords: cluster,version,info,get,getting,getclusterversioninfo 
summary: GetClusterVersionInfo 메서드를 사용하면 클러스터의 각 노드에서 실행 중인 Element 소프트웨어 버전에 대한 정보를 검색할 수 있습니다.  이 방법은 현재 소프트웨어를 업그레이드 중인 노드에 대한 정보도 반환합니다. 
---
= 클러스터 버전 정보 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `GetClusterVersionInfo` 클러스터의 각 노드에서 실행 중인 Element 소프트웨어 버전에 대한 정보를 검색하는 방법입니다.  이 방법은 현재 소프트웨어를 업그레이드 중인 노드에 대한 정보도 반환합니다.



== 클러스터 버전 정보 개체 멤버

이 메서드에는 다음과 같은 개체 멤버가 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
노드ID
 a| 
노드의 ID입니다.
 a| 
정수



 a| 
노드 내부 수정
 a| 
노드의 내부 소프트웨어 버전입니다.
 a| 
끈



 a| 
노드 버전
 a| 
노드의 소프트웨어 버전입니다.
 a| 
끈

|===


== 매개변수

이 방법에는 입력 매개변수가 없습니다.



== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
클러스터API버전
 a| 
클러스터의 현재 API 버전입니다.
 a| 
끈



 a| 
클러스터 버전
 a| 
현재 클러스터에서 실행 중인 Element 소프트웨어 버전입니다.
 a| 
끈



 a| 
클러스터 버전 정보
 a| 
각 노드의 버전 정보가 포함된 클러스터의 노드 목록입니다.
 a| 
JSON 객체 배열



 a| 
보류 중인 클러스터 버전
 a| 
이 버전이 있는 경우, 이는 클러스터 소프트웨어가 현재 업그레이드되거나 되돌려지고 있는 버전입니다.
 a| 
끈



 a| 
소프트웨어 버전 정보
 a| 
업그레이드 상태.  객체 멤버:

* 현재 버전:
+
노드의 현재 소프트웨어 버전입니다.

* nodeID: currentVersion에서 pendingVersion으로 업그레이드되는 노드의 ID입니다.  업그레이드가 진행 중이지 않으면 이 필드는 0(영)입니다.
* packageName: 설치되는 소프트웨어 패키지의 이름입니다.
* pendingVersion: 설치 중인 소프트웨어의 버전입니다.
* startTime: 설치가 시작된 날짜와 시간(UTC+0 형식)입니다.

 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "GetClusterVersionInfo",
   "params": {},
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
 "id": 1,
 "result": {
   "clusterAPIVersion": "6.0",
   "clusterVersion": "6.1382",
   "clusterVersionInfo": [
   {
      "nodeID": 1,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 2,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 3,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   },
   {
      "nodeID": 4,
      "nodeInternalRevision": "BuildType=Release Element=carbon Release=carbon ReleaseShort=carbon Version=6.1382 sfdev=6.28 Repository=dev Revision=061511b1e7fb BuildDate=2014-05-28T18:26:45MDT",
      "nodeVersion": "6.1382"
   }
 ],
   "softwareVersionInfo": {
      "currentVersion": "6.1382",
      "nodeID": 0,
      "packageName": "",
      "pendingVersion": "6.1382",
      "startTime": ""
    }
  }
}
----


== 버전 이후 새로운

9.6
