---
permalink: api/reference_element_api_volumestats.html 
sidebar: sidebar 
keywords: object,objects,volumeStats 
summary: volumeStats 개체에는 개별 볼륨에 대한 통계 데이터가 포함되어 있습니다. 
---
= 볼륨통계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
volumeStats 개체에는 개별 볼륨에 대한 통계 데이터가 포함되어 있습니다.



== 객체 멤버

다음 방법을 사용하면 일부 또는 모든 볼륨에 대한 volumeStats 객체를 가져올 수 있습니다.

* xref:reference_element_api_getvolumestats.adoc[볼륨 통계 가져오기]
* xref:reference_element_api_listvolumestatsbyaccount.adoc[계정별 볼륨 통계 목록]
* xref:reference_element_api_listvolumestatsbyvolume.adoc[볼륨별 통계 목록]
* xref:reference_element_api_listvolumestatsbyvolumeaccessgroup.adoc[목록볼륨통계별볼륨액세스그룹]


이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

[cols="20,50,15,15"]
|===
| 이름 | 설명 | 계산 | 유형 


 a| 
계정ID
 a| 
볼륨 소유자 계정의 ID입니다.
 a| 
해당 없음
 a| 
정수



 a| 
실제 IOPS
 a| 
지난 500밀리초 동안 볼륨에 대한 현재 실제 IOPS입니다.
 a| 
시점
 a| 
정수



 a| 
비동기 지연
 a| 
볼륨이 원격 클러스터와 마지막으로 동기화된 이후 경과된 시간입니다.  볼륨이 페어링되지 않은 경우 이는 null입니다.  *참고:* 활성 복제 상태의 대상 볼륨은 항상 asyncDelay가 0입니다.  대상 볼륨은 복제 중에 시스템을 인식하고 asyncDelay가 항상 정확하다고 가정합니다.
 a| 
해당 없음
 a| 
ISO 8601 기간 문자열 또는 null



 a| 
평균 IOPS 크기
 a| 
최근 500밀리초 동안 볼륨에 대한 최근 I/O의 평균 크기(바이트)입니다.
 a| 
시점
 a| 
정수



 a| 
버스트IOPS크레딧
 a| 
사용자가 사용할 수 있는 IOP 크레딧의 총 수입니다.  볼륨이 구성된 최대 IOPS를 사용하지 않으면 크레딧이 적립됩니다.
 a| 
해당 없음
 a| 
정수



 a| 
클라이언트 큐 깊이
 a| 
볼륨에 대한 미처리 읽기 및 쓰기 작업의 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
원하는 메타데이터 호스트
 a| 
볼륨 메타데이터가 메타데이터 서비스 간에 마이그레이션되는 경우 마이그레이션되는 메타데이터(슬라이스) 서비스입니다.  "null" 값은 볼륨이 마이그레이션되지 않음을 의미합니다.
 a| 
해당 없음
 a| 
JSON 객체



 a| 
대기 시간USec
 a| 
지난 500밀리초 동안 볼륨에 대한 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.  "0"(영) 값은 볼륨에 I/O가 없음을 의미합니다.
 a| 
시점
 a| 
정수



 a| 
메타데이터 호스트
 a| 
볼륨 메타데이터가 상주하는 메타데이터(슬라이스) 서비스입니다. 가능한 값:

* 기본: 볼륨을 호스팅하는 기본 메타데이터 서비스입니다.
* liveSecondaries: 현재 "라이브" 상태인 보조 메타데이터 서비스입니다.
* deadSecondaries: 죽은 상태의 보조 메타데이터 서비스입니다.

 a| 
해당 없음
 a| 
JSON 객체



 a| 
정규화된 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 평균 IOPS 수입니다.
 a| 
시점
 a| 
정수



 a| 
nonZeroBlocks
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 포함된 4KiB 블록의 총 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
바이트 읽기
 a| 
볼륨이 생성된 이후 볼륨에서 읽은 총 누적 바이트입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
readBytesLastSample
 a| 
마지막 샘플 기간 동안 볼륨에서 읽은 총 바이트 수입니다.
 a| 
시점
 a| 
정수



 a| 
readLatencyUSec
 a| 
지난 500밀리초 동안 볼륨에 대한 읽기 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.
 a| 
시점
 a| 
정수



 a| 
readLatencyUSecTotal
 a| 
볼륨에서 읽기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
읽기 작업
 a| 
볼륨이 생성된 이후 볼륨에 대한 총 읽기 작업 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
readOpsLastSample
 a| 
마지막 샘플 기간 동안의 총 읽기 작업 수입니다.
 a| 
시점
 a| 
정수



 a| 
샘플기간MSec
 a| 
샘플 기간의 길이(밀리초)입니다.
 a| 
해당 없음
 a| 
정수



 a| 
슬라이스IopsStats
 a| 
볼륨에 대한 I/O 사용 통계입니다.  Element 12.8부터 사용 가능합니다.  sliceIopsStats에 가능한 값:

* largeStatistics: 장기간(일반적으로 지난 24시간) 동안 측정된 볼륨의 I/O 통계입니다.
* smallStatistics: 짧은 기간(일반적으로 마지막 1시간) 동안 측정된 볼륨에 대한 I/O 통계입니다.


largeStatistics 및 smallStatistics에 가능한 값:

* averageReadIops: 볼륨의 평균 읽기 IOPS입니다.
* averageTotalIops: 볼륨의 평균 총 IOPS(읽기 + 쓰기)입니다.
* averageWriteIops: 볼륨의 평균 쓰기 IOPS입니다.
* nSamples: 통계 계산에 포함된 샘플 수.
* peakReadIops: 통계 간격 동안 관찰된 최대 읽기 IOPS.
* peakTotalIops: 통계 간격 동안 관찰된 최대 총 IOPS.
* peakWriteIops: 통계 간격 동안 관찰된 최대 쓰기 IOPS.
* sliceID: 볼륨 ID 또는 슬라이스 ID

 a| 
시점
 a| 
JSON 객체



 a| 
조절판
 a| 
데이터 재복제, 일시적인 오류, 스냅샷 촬영 등으로 인해 시스템이 클라이언트의 속도를 최대 IOPS 이하로 제한하는 정도를 나타내는 0과 1 사이의 부동 소수점 값입니다.
 a| 
해당 없음
 a| 
뜨다



 a| 
타임스탬프
 a| 
UTC+0 형식의 현재 시간입니다.
 a| 
해당 없음
 a| 
ISO 8601 날짜 문자열



 a| 
정렬되지 않은 읽기
 a| 
볼륨이 생성된 이후 볼륨에 대한 총 누적 정렬되지 않은 읽기 작업입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
정렬되지 않은 쓰기
 a| 
볼륨이 생성된 이후 볼륨에 대한 총 누적 정렬되지 않은 쓰기 작업입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
볼륨액세스그룹
 a| 
볼륨이 속한 볼륨 액세스 그룹의 ID 목록입니다.
 a| 
해당 없음
 a| 
정수 배열



 a| 
볼륨ID
 a| 
볼륨의 ID입니다.
 a| 
해당 없음
 a| 
정수



 a| 
볼륨크기
 a| 
총 프로비저닝된 용량(바이트)
 a| 
해당 없음
 a| 
정수



 a| 
볼륨활용도
 a| 
볼륨의 maxIOPS QoS 설정과 비교하여 클라이언트가 볼륨의 입력/출력 기능을 얼마나 최대한 활용하고 있는지를 설명하는 부동 소수점 값입니다. 가능한 값:

* 0: 클라이언트가 볼륨을 사용하지 않습니다.
* 0.01~0.99: 클라이언트가 볼륨의 IOPS 기능을 최대한 활용하지 못하고 있습니다.
* 1.00: 클라이언트는 maxIOPS 설정에서 정한 IOPS 한도까지 볼륨을 최대한 활용하고 있습니다.
* > 1.00: 클라이언트가 maxIOPS에서 설정한 한도보다 더 많은 것을 활용하고 있습니다.  이는 burstIOPS QoS 설정이 maxIOPS보다 높게 설정된 경우 가능합니다.  예를 들어, maxIOPS가 1000으로 설정되고 burstIOPS가 2000으로 설정된 경우 `volumeUtilization` 클라이언트가 볼륨을 최대한 활용하면 값은 2.00이 됩니다.

 a| 
해당 없음
 a| 
뜨다



 a| 
쓰기바이트
 a| 
볼륨이 생성된 이후 볼륨에 쓰여진 총 누적 바이트 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeBytesLastSample
 a| 
마지막 샘플 기간 동안 볼륨에 쓰여진 총 바이트 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeLatencyUSec
 a| 
지난 500밀리초 동안 볼륨에 대한 쓰기 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.
 a| 
시점
 a| 
정수



 a| 
writeLatencyUSecTotal
 a| 
볼륨에 쓰기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeOps
 a| 
볼륨이 생성된 이후 볼륨에 대한 총 누적 쓰기 작업입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeOps마지막 샘플
 a| 
마지막 샘플 기간 동안의 총 쓰기 작업 수입니다.
 a| 
시점
 a| 
정수



 a| 
제로블록스
 a| 
마지막 가비지 수집 작업이 완료된 후 데이터가 없는 빈 4KiB 블록의 총 수입니다.
 a| 
시점
 a| 
정수

|===