---
permalink: api/reference_element_api_listsnapmirrorrelationships.html 
sidebar: sidebar 
keywords: snapmirror,endpoints,endpoint,list,listing,listsnapmirrorrelationships 
summary: Element 소프트웨어 웹 UI는 ListSnapMirrorRelationships 메서드를 사용하여 Element 스토리지 클러스터의 하나 또는 모든 SnapMirror 관계를 나열합니다. 
---
= ListSnapMirror관계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 소프트웨어 웹 UI는 다음을 사용합니다. `ListSnapMirrorRelationships` Element 스토리지 클러스터에서 하나 또는 모든 SnapMirror 관계를 나열하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
스냅미러엔드포인트ID
 a| 
지정된 엔드포인트 ID와 연관된 관계만 나열합니다.  엔드포인트 ID가 제공되지 않으면 시스템은 알려진 모든 SnapMirror 엔드포인트의 관계를 나열합니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
목적지볼륨
 a| 
지정된 대상 볼륨과 관련된 관계를 나열합니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[스냅미러볼륨정보]
 a| 
None
 a| 
아니요



 a| 
소스볼륨
 a| 
지정된 소스 볼륨과 관련된 관계를 나열합니다.
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[스냅미러볼륨정보]
 a| 
None
 a| 
아니요



 a| 
v서버
 a| 
지정된 Vserver의 관계를 나열합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
관계ID
 a| 
지정된 관계 ID와 연관된 관계를 나열합니다.
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
스냅미러관계
 a| 
SnapMirror 관계에 대한 정보가 포함된 개체 목록입니다.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[스냅미러관계]정렬

|===


== 버전 이후 새로운

10.1
