---
permalink: api/reference_element_api_enableencryptionatrest.html 
sidebar: sidebar 
keywords: encryption,enable,enabling,EnableEncryptionAtRest 
summary: 'EnableEncryptionAtRest 메서드를 사용하면 클러스터에서 저장 시 고급 암호화 표준(AES) 256비트 암호화를 활성화하여 클러스터가 각 노드의 드라이브에 사용되는 암호화 키를 관리할 수 있습니다.  이 기능은 기본적으로 활성화되어 있지 않습니다.' 
---
= 휴지상태에서 암호화 활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `EnableEncryptionAtRest` 클러스터에서 각 노드의 드라이브에 사용되는 암호화 키를 관리할 수 있도록 클러스터에서 저장 시 AES(Advanced Encryption Standard) 256비트 암호화를 활성화하는 방법입니다.  이 기능은 기본적으로 활성화되어 있지 않습니다.


TIP: 클러스터에서 암호화의 현재 상태 및/또는 소프트웨어 암호화의 현재 상태를 보려면 다음을 사용하십시오.link:../api/reference_element_api_getclusterinfo["클러스터 정보 가져오기 방법"^] . 당신은 사용할 수 있습니다 `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo["클러스터가 저장 중인 데이터를 암호화하는 데 사용하는 정보를 얻는 방법"^].


NOTE: 이 방법을 사용하면 소프트웨어 암호화가 활성화되지 않습니다.  이것은 다음을 사용해서만 수행할 수 있습니다.link:../api/reference_element_api_createcluster.html["클러스터 생성 방법"^] ~와 함께 `enableSoftwareEncryptionAtRest` 로 설정 `true` .

저장 중 암호화를 활성화하면 클러스터는 클러스터의 각 노드에 있는 드라이브에 대한 암호화 키를 내부적으로 자동으로 관리합니다.

keyProviderID가 지정되면 키 공급자의 유형에 따라 비밀번호가 생성되고 검색됩니다.  이 작업은 일반적으로 KMIP 키 공급자의 경우 KMIP(Key Management Interoperability Protocol) 키 서버를 사용하여 수행됩니다.  이 작업 후 지정된 공급자는 활성 상태로 간주되며 암호화가 비활성화될 때까지 삭제할 수 없습니다. `DisableEncryptionAtRest` 방법.


NOTE: "-NE"로 끝나는 모델 번호가 있는 노드 유형이 있는 경우 `EnableEncryptionAtRest` 메서드 호출은 "암호화가 허용되지 않습니다."라는 응답과 함께 실패합니다.  클러스터에서 암호화할 수 없는 노드가 감지되었습니다.


NOTE: 클러스터가 실행 중이고 정상 상태일 때만 암호화를 활성화하거나 비활성화해야 합니다.  필요에 따라 원하는 대로 암호화를 활성화하거나 비활성화할 수 있습니다.


NOTE: 이 프로세스는 비동기적으로 진행되며 암호화가 활성화되기 전에 응답을 반환합니다.  당신은 사용할 수 있습니다 `GetClusterInfo` 프로세스가 완료되었는지 확인하기 위해 시스템을 폴링하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
키 제공자 ID
 a| 
사용할 KMIP 키 공급자의 ID입니다.
 a| 
정수
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "EnableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== 응답 예시

이 메서드는 EnableEncryptionAtRest 메서드의 다음 예와 유사한 응답을 반환합니다.  보고할 결과가 없습니다.

[listing]
----
{
   "id": 1,
   "result": {}
}
----
클러스터에서 휴지 상태 암호화가 활성화되는 동안 GetClusterInfo는 휴지 상태 암호화("encryptionAtRestState")의 상태를 "활성화"로 설명하는 결과를 반환합니다.  휴면 암호화가 완전히 활성화되면 반환된 상태가 "활성화됨"으로 변경됩니다.

[listing]
----
{
   "id": 1,
      "result": {
         "clusterInfo": {
            "attributes": { },
               "encryptionAtRestState": "enabling",
            "ensemble": [
               "10.10.5.94",
               "10.10.5.107",
               "10.10.5.108"
            ],
            "mvip": "192.168.138.209",
            "mvipNodeID": 1,
            "name": "Marshall",
            "repCount": 2,
            "svip": "10.10.7.209",
            "svipNodeID": 1,
            "uniqueID": "91dt"
      }
   }
}
----


== 버전 이후 새로운

9.6

[discrete]
== 더 많은 정보를 찾아보세요

* link:reference_element_api_secureerasedrives.html["보안 삭제 드라이브"]
* link:reference_element_api_getclusterinfo.html["클러스터 정보 가져오기"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

