---
permalink: api/reference_element_api_network_all_interfaces.html 
sidebar: sidebar 
keywords: object,objects,network 
summary: '네트워크 \(모든 인터페이스\) 개체는 스토리지 노드의 네트워크 인터페이스 구성에 대한 정보를 수집합니다.  GetConfig 및 GetNetworkConfig 메서드를 사용하면 스토리지 노드에 대한 이 정보를 얻을 수 있습니다.' 
---
= 네트워크(모든 인터페이스)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
네트워크(모든 인터페이스) 개체는 스토리지 노드의 네트워크 인터페이스 구성에 대한 정보를 수집합니다.  당신은 사용할 수 있습니다 `GetConfig` 그리고 `GetNetworkConfig` 저장 노드에 대한 정보를 얻는 방법.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===


| 이름 | 설명 | 유형 


 a| 
Bond10G
 a| 
Bond10G 본딩 인터페이스에 대한 구성 정보입니다.
 a| 
xref:reference_element_api_network_bonded_interfaces.adoc[네트워크(본딩된 인터페이스)]



 a| 
Bond1G
 a| 
Bond1G 본딩 인터페이스에 대한 구성 정보입니다.
 a| 
xref:reference_element_api_network_bonded_interfaces.adoc[네트워크(본딩된 인터페이스)]



 a| 
eth0-5
 a| 
저장 노드의 각 이더넷 인터페이스에 대한 하나의 개체로, 인터페이스에 대한 구성 정보를 설명합니다.  이러한 객체는 인터페이스 이름과 일치하도록 0~5까지 번호가 매겨집니다.
 a| 
xref:reference_element_api_network_ethernet_interfaces.adoc[네트워크(이더넷 인터페이스)]



 a| 
봐라
 a| 
루프백 인터페이스에 대한 구성 정보입니다.
 a| 
xref:reference_element_api_network_local_interfaces.adoc[네트워크(로컬 인터페이스)]

|===


== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getconfig.adoc[GetConfig]
* xref:reference_element_api_getnetworkconfig.adoc[GetNetworkConfig]

