---
permalink: api/reference_element_api_addvirtualnetwork.html 
sidebar: sidebar 
keywords: addvirtualnetwork,cluster,add,adding,virtual,network 
summary: AddVirtualNetwork 메서드를 사용하면 클러스터 구성에 새 가상 네트워크를 추가할 수 있습니다. 
---
= 가상 네트워크 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `AddVirtualNetwork` 클러스터 구성에 새로운 가상 네트워크를 추가하는 방법입니다.

가상 네트워크를 추가하면 각 노드에 대한 인터페이스가 생성되고 각 인터페이스에는 가상 네트워크 IP 주소가 필요합니다.  이 API 메서드의 매개변수로 지정하는 IP 주소의 수는 클러스터의 노드 수보다 크거나 같아야 합니다.  시스템은 가상 네트워크 주소를 대량으로 프로비저닝하고 이를 개별 노드에 자동으로 할당합니다.  노드에 가상 네트워크 주소를 수동으로 할당할 필요는 없습니다.


NOTE: AddVirtualNetwork 메서드는 새로운 가상 네트워크를 만드는 데만 사용됩니다.  기존 가상 네트워크를 변경하려면 다음을 사용하세요.xref:reference_element_api_modifyvirtualnetwork.adoc[가상 네트워크 수정] 방법.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
주소 블록
 a| 
가상 네트워크에 포함할 고유한 IP 주소 범위입니다.  객체에 필요한 멤버:

* 시작: IP 주소 범위의 시작입니다.  (끈)
* 크기: 블록에 포함할 IP 주소의 수입니다.  (정수)

 a| 
JSON 객체 배열
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
게이트웨이
 a| 
가상 네트워크 게이트웨이의 IP 주소입니다.  이 매개변수는 네임스페이스 매개변수가 true로 설정된 경우에만 유효합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
이름
 a| 
새 가상 네트워크에 대한 사용자 정의 이름입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
네임스페이스
 a| 
true로 설정하면 네임스페이스와 이에 포함된 가상 네트워크를 만들고 구성하여 라우팅 가능한 스토리지 VLAN 기능을 활성화합니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
넷마스크
 a| 
생성되는 가상 네트워크에 대한 고유한 네트워크 마스크입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
svip
 a| 
생성되는 가상 네트워크에 대한 고유한 스토리지 IP 주소입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
가상네트워크태그
 a| 
고유한 가상 네트워크(VLAN) 태그입니다.  지원되는 값은 1~4094입니다.
 a| 
정수
 a| 
None
 a| 
예

|===
*참고:* 네임스페이스를 false로 설정하면 가상 네트워크 매개변수는 각 가상 네트워크에서 고유해야 합니다.



== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
가상네트워크ID
 a| 
새 가상 네트워크의 가상 네트워크 ID입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "AddVirtualNetwork",
  "params": {
    "virtualNetworkTag": 2010,
    "name": "network1",
    "addressBlocks" : [
        { "start": "192.86.5.1", "size": 10 },
        { "start": "192.86.5.50", "size": 20 }
    ],
    "netmask" : "255.255.192.0",
    "gateway" : "10.0.1.254",
    "svip" : "192.86.5.200",
    "attributes" : {}
    "namespace" : true
  },
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id": 1,
   "result":
      {
        "virtualNetworkID": 5
   }
}
----


== 버전 이후 새로운

9.6
