---
permalink: api/reference_element_api_getnodehardwareinfo.html 
sidebar: sidebar 
keywords: node,hardware,info,get,getting,getnodehardwareinfo 
summary: GetNodeHardwareInfo 메서드를 사용하면 지정된 노드에 대한 모든 하드웨어 정보와 상태를 반환할 수 있습니다.  여기에는 일반적으로 제조업체, 공급업체, 버전 및 기타 관련 하드웨어 식별 정보가 포함됩니다. 
---
= 노드 하드웨어 정보 가져오기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `GetNodeHardwareInfo` 지정된 노드에 대한 모든 하드웨어 정보와 상태를 반환하는 메서드입니다.  여기에는 일반적으로 제조업체, 공급업체, 버전 및 기타 관련 하드웨어 식별 정보가 포함됩니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
노드ID
 a| 
하드웨어 정보를 요청하는 노드의 ID입니다.  파이버 채널 노드가 지정된 경우 파이버 채널 노드에 대한 정보가 반환됩니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
노드하드웨어정보
 a| 
지정된 노드ID에 대한 하드웨어 정보입니다.  이 출력의 각 객체에는 주어진 노드의 노드ID가 표시됩니다.
 a| 
xref:reference_element_api_hardwareinfo.adoc[하드웨어 정보]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "GetNodeHardwareInfo",
   "params": {
     "nodeID": 1
   },
"id" : 1
}
----


== 응답 예시

이 응답 예시는 길이가 길기 때문에 보충 주제에 문서화되어 있습니다.



== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_response_example_getnodehardwareinfo_fibre_channel.adoc[GetNodeHardwareInfo(Fibre Channel 노드에 대한 출력)]

xref:reference_element_api_response_example_getnodehardwareinfo.adoc[GetNodeHardwareInfo(iSCSI에 대한 출력)]
