---
permalink: api/reference_element_api_cluster_pairing_order_of_operations.html 
sidebar: sidebar 
keywords: cluster,pairing,pair,order,operations,clusters 
summary: 원격 복제를 사용하려면 Element 소프트웨어를 실행하는 두 개의 스토리지 클러스터 간에 연결을 설정해야 합니다. 
---
= 클러스터 페어링 작업 순서
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
원격 복제를 사용하려면 Element 소프트웨어를 실행하는 두 개의 스토리지 클러스터 간에 연결을 설정해야 합니다.

다음 API 메서드 세트를 사용하여 클러스터 연결을 설정합니다.

* xref:reference_element_api_startclusterpairing.adoc[클러스터 페어링 시작]:
+
이 API 메서드는 클러스터 쌍을 설정하는 데 사용되는 페어링 키를 생성하고 반환합니다.  키는 인코딩되어 있으며 클러스터 간 통신을 설정하는 데 사용되는 정보가 포함되어 있습니다.  하나의 클러스터는 최대 4개의 다른 클러스터와 쌍을 이룰 수 있습니다.  하지만 각 클러스터 페어링에 대해 새로운 키를 생성해야 합니다.  그만큼xref:reference_element_api_startclusterpairing.adoc[클러스터 페어링 시작] 이 메서드는 호출될 때마다 새로운 키를 생성합니다.  각각의 고유 키를 다음과 같이 사용하세요.xref:reference_element_api_completeclusterpairing.adoc[클러스터 페어링 완료] 각 추가 클러스터를 페어링하는 방법.

+

NOTE: 보안상의 이유로 페어링 키는 이메일을 통해 다른 사용자에게 전송되어서는 안 됩니다.  키에는 사용자 이름과 비밀번호가 포함되어 있습니다.

* xref:reference_element_api_completeclusterpairing.adoc[클러스터 페어링 완료]:
+
이 방법은 생성된 페어링 키를 사용합니다.xref:reference_element_api_startclusterpairing.adoc[클러스터 페어링 시작] 클러스터 쌍을 생성하는 API 메서드입니다.  발행하다xref:reference_element_api_completeclusterpairing.adoc[클러스터 페어링 완료] 목적지에 clusterPairingKey 매개변수를 포함하는 API 메서드입니다.  원본 클러스터는 키를 생성한 클러스터입니다.





== 더 많은 정보를 찾아보세요

* xref:reference_element_api_startclusterpairing.adoc[클러스터 페어링 시작]
* xref:reference_element_api_completeclusterpairing.adoc[클러스터 페어링 완료]

