---
permalink: api/reference_element_api_syncjob.html 
sidebar: sidebar 
keywords: object,objects,syncjob 
summary: syncJob 개체에는 클러스터에서 실행 중인 복제, 원격 복제 또는 슬라이스 동기화 작업에 대한 정보가 포함되어 있습니다. 
---
= 동기화 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
syncJob 개체에는 클러스터에서 실행 중인 복제, 원격 복제 또는 슬라이스 동기화 작업에 대한 정보가 포함되어 있습니다.

동기화 정보를 검색할 수 있습니다. `ListSyncJobs` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
초당 블록 수
 a| 
소스 클러스터에서 대상 클러스터로 초당 전송되는 데이터 블록 수입니다.  유형 멤버가 원격으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
지점 유형
 a| 
원격 복제 동기화 작업에만 반환됩니다. 가능한 값:

* 스냅 사진
* 용량

 a| 
끈



 a| 
초당 바이트
 a| 
복제본이 초당 처리하는 바이트 수입니다.  유형 멤버가 복제 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
뜨다



 a| 
클론ID
 a| 
진행 중인 복제 작업의 식별자입니다.  유형 멤버가 clone으로 설정된 경우에만 나타납니다.
 a| 
정수



 a| 
현재 바이트
 a| 
복제본이 소스 볼륨에서 처리한 바이트 수입니다.  유형 멤버가 복제 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
dst서비스ID
 a| 
볼륨의 기본 복제본을 호스팅하는 서비스 식별자입니다.  유형 멤버가 원격으로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
dst볼륨ID
 a| 
대상 볼륨 ID입니다.  유형 멤버가 clone 또는 remote로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
경과 시간
 a| 
동기화 작업이 시작된 이후 경과된 시간(초)입니다.
 a| 
동기화 작업 유형에 따라 float 또는 정수



 a| 
그룹클론ID
 a| 
진행 중인 그룹 복제 작업의 ID입니다.
 a| 
정수



 a| 
노드ID
 a| 
복제가 발생하는 노드를 지정합니다.  유형 멤버가 clone으로 설정된 경우에만 나타납니다.
 a| 
정수



 a| 
완료율
 a| 
동기화 작업 완료율입니다.
 a| 
동기화 작업 유형에 따라 float 또는 정수



 a| 
남은 시간
 a| 
작업을 완료하는 데 걸리는 예상 시간(초)입니다.
 a| 
뜨다



 a| 
슬라이스ID
 a| 
동기화되는 슬라이스 드라이브의 ID입니다.
 a| 
정수



 a| 
단계
 a| 
유형 멤버가 원격 또는 복제로 설정된 경우에만 표시됩니다. 가능한 값:

* 메타데이터: 복제는 원격 클러스터로 어떤 데이터를 전송해야 하는지 결정하는 과정입니다.  복제 프로세스의 이 단계에 대한 상태는 보고되지 않습니다.
* 데이터: 복제는 대량의 데이터를 원격 클러스터로 전송하는 과정입니다.
* 전체: 슬라이스 동기화 작업에 대한 슬라이스의 이전 버전과의 호환성을 나타냅니다.

 a| 
끈



 a| 
스냅샷ID
 a| 
복제본이 생성된 스냅샷의 ID입니다.  유형 멤버가 clone으로 설정된 경우에만 나타납니다.
 a| 
정수



 a| 
src서비스ID
 a| 
소스 서비스 ID입니다.
 a| 
정수



 a| 
src볼륨ID
 a| 
소스 볼륨 ID입니다.
 a| 
정수



 a| 
총 바이트
 a| 
복제본의 총 바이트 수입니다.  유형 멤버가 복제 또는 슬라이스로 설정된 경우에만 표시됩니다.
 a| 
정수



 a| 
유형
 a| 
동기화 작업의 유형입니다. 가능한 값:

* 클론
* 일부분
* 차단하다
* 원격

 a| 
끈

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
