---
permalink: api/reference_element_api_removeinitiatorsfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: initiators,initiator,volume,access,group,remove,removing,removeinitiatorsfromvolumeaccessgroup 
summary: RemoveInitiatorsFromVolumeAccessGroup 메서드를 사용하면 지정된 볼륨 액세스 그룹에서 이니시에이터를 제거할 수 있습니다. 
---
= 볼륨 액세스 그룹에서 이니시에이터 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `RemoveInitiatorsFromVolumeAccessGroup` 지정된 볼륨 액세스 그룹에서 개시자를 제거하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
볼륨액세스그룹ID
 a| 
이니시에이터가 제거되는 볼륨 액세스 그룹의 ID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
개시자들
 a| 
볼륨 액세스 그룹에 포함할 개시자 ID 또는 이름(IQN 및 WWPN) 목록입니다.  개시자 이름 목록을 전달하면 개시자가 존재하지 않으면 생성됩니다.  개시자 ID 목록을 전달하는 경우, 해당 메서드는 개시자 중에 아직 존재하지 않는 것이 있으면 오류를 반환합니다.  개시자 이름을 전달하는 것은 더 이상 사용되지 않습니다. 가능한 경우 개시자 ID를 사용해야 합니다.
 a| 
정수 배열(권장) 또는 문자열 배열(더 이상 사용되지 않음)
 a| 
None
 a| 
아니요



 a| 
deleteOrphanInitiators
 a| 
볼륨 액세스 그룹에서 제거된 후 개시자 객체를 삭제할지 여부를 지정합니다. 가능한 값:

* true: 볼륨 액세스 그룹에서 제거된 후 개시자 개체를 삭제합니다.
* false: 볼륨 액세스 그룹에서 제거된 후에는 개시자 객체를 삭제하지 마십시오. 이것이 기본값입니다.

 a| 
부울
 a| 
거짓
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
볼륨액세스그룹
 a| 
새로 수정된 볼륨 액세스 그룹에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[볼륨액세스그룹]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "id": 13171,
  "method": "RemoveInitiatorsFromVolumeAccessGroup",
  "params": {
    "initiators": [114,115],
    "volumeAccessGroupID": 96
  }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 13171,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [],
      "initiators": [],
      "name": "test",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== 버전 이후 새로운

9.6
