---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: ListEvents 메서드를 사용하면 클러스터에서 감지된 이벤트를 가장 오래된 것부터 가장 최근 것 순으로 정렬하여 나열할 수 있습니다. 
---
= 이벤트 목록
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ListEvents` 클러스터에서 감지된 이벤트를 가장 오래된 것부터 가장 최근 것 순으로 정렬하여 나열하는 방법입니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
드라이브ID
 a| 
이 드라이브 ID가 있는 이벤트만 반환되도록 지정합니다.
 a| 
정수
 a| 
0
 a| 
아니요



 a| 
종료이벤트ID
 a| 
반환할 이벤트 ID 범위의 끝을 식별합니다.
 a| 
정수
 a| 
(제한 없는)
 a| 
아니요



 a| 
게시 종료 시간
 a| 
이 시간 이전에 게시된 이벤트만 반환되도록 지정합니다.
 a| 
끈
 a| 
0
 a| 
아니요



 a| 
종료 보고 시간
 a| 
이 시간보다 일찍 보고된 이벤트만 반환되도록 지정합니다.
 a| 
끈
 a| 
0
 a| 
아니요



 a| 
이벤트 유형
 a| 
반환할 이벤트 유형을 지정합니다.  보다xref:reference_element_api_event.adoc[이벤트] 가능한 이벤트 유형에 대해.
 a| 
끈
 a| 
0
 a| 
아니요



 a| 
최대 이벤트
 a| 
반환할 이벤트의 최대 수를 지정합니다.
 a| 
정수
 a| 
(제한 없는)
 a| 
아니요



 a| 
노드ID
 a| 
이 노드 ID가 있는 이벤트만 반환되도록 지정합니다.
 a| 
정수
 a| 
 a| 



 a| 
서비스ID
 a| 
이 서비스 ID가 있는 이벤트만 반환되도록 지정합니다.
 a| 
 a| 
 a| 



 a| 
시작이벤트ID
 a| 
반환할 이벤트 범위의 시작을 식별합니다.
 a| 
정수
 a| 
0
 a| 
아니요



 a| 
시작게시시간
 a| 
이 시간 이후에 게시된 이벤트만 반환되도록 지정합니다.
 a| 
끈
 a| 
0
 a| 
아니요



 a| 
시작보고시간
 a| 
이 시간 이후에 보고된 이벤트만 반환되도록 지정합니다.
 a| 
끈
 a| 
0
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
이벤트
 a| 
이벤트 목록.
 a| 
xref:reference_element_api_event.adoc[이벤트]정렬

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== 버전 이후 새로운

9.6
