---
permalink: api/reference_element_api_pendingactivenode.html 
sidebar: sidebar 
keywords: object,objects,pendingActiveNode 
summary: pendingActiveNode 객체에는 현재 보류 중 활성 상태와 보류 중 활성 상태 사이에 있는 노드에 대한 정보가 포함되어 있습니다.  이는 현재 공장 소프트웨어 이미지로 반환되는 노드입니다.  ListPendingActiveNodes API 메서드를 사용하여 보류 중인 모든 Active 노드에 대한 정보 목록을 반환합니다. 
---
= 보류 중인 활성 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
pendingActiveNode 객체에는 현재 보류 중 활성 상태와 보류 중 활성 상태 사이에 있는 노드에 대한 정보가 포함되어 있습니다.  이는 현재 공장 소프트웨어 이미지로 반환되는 노드입니다.  사용하다 `ListPendingActiveNodes` 보류 중인 모든 활성 노드에 대한 정보 목록을 반환하는 API 메서드입니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
활성노드키
 a| 
소프트웨어를 성공적으로 설치한 후 노드가 자동으로 클러스터에 가입할 수 있게 해주는 고유 키입니다.
 a| 
끈



 a| 
할당된 노드 ID
 a| 
노드에 할당된 노드 ID입니다.
 a| 
끈



 a| 
비동기 핸들
 a| 
작업 상태를 쿼리하는 데 사용할 수 있는 비동기 메서드 핸들입니다.
 a| 
정수



 a| 
cip
 a| 
노드에 할당된 클러스터 IP 주소입니다.
 a| 
끈



 a| 
밉
 a| 
노드에 할당된 관리 IP 주소입니다.
 a| 
끈



 a| 
노드슬롯
 a| 
HCI 플랫폼의 경우, 이 노드가 있는 섀시 슬롯에 해당하는 문자("A", "B", "C" 또는 "D")입니다.  저장 플랫폼의 경우 이 값은 null입니다.
 a| 
끈



 a| 
보류 중인 활성 노드 ID
 a| 
노드의 보류 중인 노드 ID입니다.
 a| 
정수



 a| 
플랫폼 정보
 a| 
노드에 대한 하드웨어 정보입니다.  회원:

* chassisType: 노드의 하드웨어 플랫폼.
* cpuModel: 하드웨어 플랫폼의 CPU 모델입니다.
* nodeMemoryGB: 물리적 플랫폼에 설치된 메모리의 양(GB)입니다.
* nodeType: 노드 모델 이름.
* platformConfigVersion: 이 노드 하드웨어에 대해 구성된 소프트웨어 버전입니다.

 a| 
JSON 객체



 a| 
역할
 a| 
클러스터에서 노드의 역할. 가능한 값:

* 관리
* 스토리지
* 컴퓨팅
* 증인

 a| 



 a| 
한모금
 a| 
노드에 할당된 스토리지(iSCSI) IP 주소입니다.
 a| 
끈



 a| 
소프트웨어 버전
 a| 
노드에서 실행 중인 Element 소프트웨어의 현재 버전입니다.
 a| 
끈

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listpendingactivenodes.adoc[보류 중인 활성 노드 목록]
