---
permalink: api/reference_element_api_clusterstats.html 
sidebar: sidebar 
keywords: objects,clusterStats 
summary: clusterStats 개체에는 클러스터에 대한 통계 데이터가 포함되어 있습니다.  객체에 포함된 볼륨 관련 통계의 대부분은 클러스터의 모든 볼륨에 대해 평균화됩니다.  GetClusterStats 메서드를 사용하면 클러스터에 대한 이 정보를 검색할 수 있습니다. 
---
= 클러스터 통계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clusterStats 개체에는 클러스터에 대한 통계 데이터가 포함되어 있습니다.  객체에 포함된 볼륨 관련 통계의 대부분은 클러스터의 모든 볼륨에 대해 평균화됩니다.  GetClusterStats 메서드를 사용하면 클러스터에 대한 이 정보를 검색할 수 있습니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 계산 | 유형 


 a| 
실제 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 현재 실제 IOPS입니다.
 a| 
시점
 a| 
정수



 a| 
평균 IOPS 크기
 a| 
최근 500밀리초 동안 클러스터에 대한 최근 I/O의 평균 크기(바이트)입니다.
 a| 
시점
 a| 
정수



 a| 
클라이언트 큐 깊이
 a| 
클러스터에 대한 미처리 읽기 및 쓰기 작업의 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
클러스터 활용도
 a| 
현재 활용되고 있는 클러스터의 최대 IOPS 비율입니다.  이는 clusterUtilization = normalizedIOPS / maxIOPS(GetClusterCapacity에서)로 계산됩니다.
 a| 
해당 없음
 a| 
뜨다



 a| 
대기 시간USec
 a| 
지난 500밀리초 동안 클러스터에 대한 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.
 a| 
시점
 a| 
정수



 a| 
정규화된 IOPS
 a| 
지난 500밀리초 동안 전체 클러스터의 평균 IOPS 수입니다.
 a| 
시점
 a| 
정수



 a| 
바이트 읽기
 a| 
클러스터가 생성된 이후 클러스터에서 읽은 총 누적 바이트입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
readBytesLastSample
 a| 
마지막 샘플 기간 동안 클러스터에서 읽은 총 바이트 수입니다.
 a| 
시점
 a| 
정수



 a| 
readLatencyUSec
 a| 
지난 500밀리초 동안 클러스터에 대한 읽기 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.
 a| 
시점
 a| 
정수



 a| 
readLatencyUSecTotal
 a| 
클러스터 생성 이후 읽기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
읽기 작업
 a| 
클러스터 생성 이후 클러스터에 대한 총 누적 읽기 작업입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
readOpsLastSample
 a| 
마지막 샘플 기간 동안의 총 읽기 작업 수입니다.
 a| 
시점
 a| 
정수



 a| 
샘플기간MSec
 a| 
샘플 기간의 길이(밀리초)입니다.
 a| 
해당 없음
 a| 
정수



 a| 
서비스 개수
 a| 
클러스터에서 실행되는 서비스의 수입니다.  servicesTotal과 같으면 모든 노드에서 유효한 통계가 수집되었음을 나타냅니다.
 a| 
시점
 a| 
정수



 a| 
서비스총계
 a| 
클러스터에서 실행될 것으로 예상되는 서비스의 총 수입니다.
 a| 
해당 없음
 a| 
정수



 a| 
타임스탬프
 a| 
UTC+0 형식의 현재 시간입니다.
 a| 
해당 없음
 a| 
ISO 8601 날짜 문자열



 a| 
정렬되지 않은 읽기
 a| 
클러스터 생성 이후 클러스터에 대한 정렬되지 않은 총 누적 읽기 작업 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
정렬되지 않은 쓰기
 a| 
클러스터 생성 이후 클러스터에 대한 정렬되지 않은 총 누적 쓰기 작업 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
쓰기바이트
 a| 
클러스터가 생성된 이후 클러스터에 기록된 총 누적 바이트입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeBytesLastSample
 a| 
마지막 샘플 기간 동안 클러스터에 쓰여진 총 바이트 수입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeLatencyUSec
 a| 
지난 500밀리초 동안 클러스터에 대한 쓰기 작업을 완료하는 데 걸린 평균 시간(마이크로초)입니다.
 a| 
시점
 a| 
정수



 a| 
writeLatencyUSecTotal
 a| 
클러스터 생성 이후 쓰기 작업을 수행하는 데 소요된 총 시간입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeOps
 a| 
클러스터 생성 이후 클러스터에 대한 총 누적 쓰기 작업입니다.
 a| 
단조롭게 증가
 a| 
정수



 a| 
writeOps마지막 샘플
 a| 
마지막 샘플 기간 동안의 총 쓰기 작업 수입니다.
 a| 
시점
 a| 
정수

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_getclusterstats.adoc[클러스터 통계 가져오기]
