---
permalink: api/reference_element_api_addaccount.html 
sidebar: sidebar 
keywords: addaccount,add,adding,account,accounts 
summary: 'AddAccount를 사용하면 시스템에 새로운 계정을 추가할 수 있습니다.  계정이 생성됨에 따라 이 방법을 사용하여 새 계정으로 새 볼륨을 만들 수도 있습니다.  계정에 대해 지정한 CHAP(Challenge-Handshake 인증 프로토콜) 설정은 해당 계정이 소유한 모든 볼륨에 적용됩니다.' 
---
= 계정 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `AddAccount` 시스템에 새로운 계정을 추가합니다.  계정이 생성됨에 따라 이 방법을 사용하여 새 계정으로 새 볼륨을 만들 수도 있습니다.  계정에 대해 지정한 CHAP(Challenge-Handshake 인증 프로토콜) 설정은 해당 계정이 소유한 모든 볼륨에 적용됩니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
`attributes`
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
`enableChap`
 a| 
CHAP 계정 자격 증명을 초기자가 볼륨에 액세스하는 데 사용할 수 있는지 여부를 지정합니다.
 a| 
부울
 a| 
true
 a| 
아니요



 a| 
`initiatorSecret`
 a| 
개시자가 사용할 CHAP 비밀번호입니다.  이 비밀번호는 12~16자 길이여야 하며 해독이 불가능해야 합니다.  개시자 CHAP 비밀번호는 고유해야 하며 대상 CHAP 비밀번호와 같을 수 없습니다.  지정하지 않으면 무작위 비밀이 생성됩니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`targetSecret`
 a| 
대상에 사용할 CHAP 비밀번호(상호 CHAP 인증).  이 비밀번호는 12~16자 길이여야 하며 해독이 불가능해야 합니다.  대상 CHAP 비밀번호는 고유해야 하며 개시자 CHAP 비밀번호와 같을 수 없습니다.  지정하지 않으면 무작위 비밀이 생성됩니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`username`
 a| 
이 계정의 고유한 사용자 이름입니다.  (길이는 1~64자여야 합니다).
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
계정
 a| 
새로 생성된 계정에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_account.adoc[계정]



 a| 
계정ID
 a| 
새로 생성된 계정 개체의 ID입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
	"method": "AddAccount",
    "params": {
     "username"  : "bobsmith",
     "initiatorSecret" : "168[#5A757ru268)",
     "targetSecret" : "tlt&lt;,8TUYa7bC",
     "attributes" : {
       "billingcode" : 2345
     }
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "account": {
      "accountID": 90,
      "attributes": {
        "billingcode": 2345
      },
      "initiatorSecret": "168[#5A757ru268)",
      "status": "active",
      "storageContainerID": "00000000-0000-0000-0000-000000000000",
      "targetSecret": "tlt&lt;,8TUYa7bC",
      "username": "bobsmith",
      "volumes": [],
      "enableChap": true
    },
    "accountID": 90
  }
}
----


== 버전 이후 새로운

9.6
