---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: ModifyVirtualNetwork 메서드를 사용하면 기존 가상 네트워크의 속성을 변경할 수 있습니다. 
---
= 가상 네트워크 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ModifyVirtualNetwork` 기존 가상 네트워크의 속성을 변경하는 방법입니다.

이 방법을 사용하면 주소 블록을 추가하거나 제거하고, 넷마스크를 변경하거나, 가상 네트워크의 이름이나 설명을 수정할 수 있습니다.  이를 사용하여 네임스페이스를 활성화하거나 비활성화할 수 있으며, 가상 네트워크에서 네임스페이스가 활성화된 경우 게이트웨이를 추가하거나 제거할 수도 있습니다.


NOTE: 이 방법에는 매개변수로 virtualNetworkID 또는 virtualNetworkTag가 필요하지만 둘 다 필요하지는 않습니다.

주의:

네임스페이스 매개변수를 변경하여 기존 가상 네트워크에 대한 라우팅 가능 스토리지 VLAN 기능을 활성화하거나 비활성화하면 가상 네트워크에서 처리하는 모든 트래픽이 중단됩니다.  예약된 유지 관리 기간 동안 네임스페이스 매개변수를 변경하는 것이 가장 좋습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
가상네트워크ID
 a| 
수정할 가상 네트워크의 고유 식별자입니다.  이는 클러스터에서 할당한 가상 네트워크 ID입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
가상네트워크태그
 a| 
수정할 가상 네트워크를 식별하는 네트워크 태그입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
주소 블록
 a| 
이 가상 네트워크에 설정할 새 주소 블록입니다.  여기에는 기존 개체에 추가할 새 주소 블록이 포함될 수도 있고, 제거해야 할 사용되지 않는 주소 블록을 생략할 수도 있습니다.  혹은 기존 주소 블록의 크기를 확장하거나 줄일 수도 있습니다.  가상 네트워크 개체의 시작 주소 블록 크기는 늘릴 수만 있고 줄일 수는 없습니다.  이 개체에 필요한 멤버:

* 시작: IP 주소 범위의 시작입니다.  (끈)
* 크기: 블록에 포함할 IP 주소의 수입니다.  (정수)

 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
게이트웨이
 a| 
가상 네트워크 게이트웨이의 IP 주소입니다.  이 매개변수는 네임스페이스 매개변수가 true로 설정된 경우에만 유효합니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
이름
 a| 
가상 네트워크의 새로운 이름입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
네임스페이스
 a| 
true로 설정하면 가상 네트워크를 다시 만들고 이를 포함할 네임스페이스를 구성하여 라우팅 가능한 스토리지 VLAN 기능을 활성화합니다.  false로 설정하면 가상 네트워크에 대한 VRF 기능이 비활성화됩니다.  이 값을 변경하면 이 가상 네트워크를 통과하는 트래픽이 중단됩니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
넷마스크
 a| 
이 가상 네트워크에 대한 새로운 네트워크 마스크입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
svip
 a| 
이 가상 네트워크에 대한 저장소 가상 IP 주소입니다.  가상 네트워크의 SVIP는 변경할 수 없습니다.  다른 SVIP 주소를 사용하려면 새로운 가상 네트워크를 만들어야 합니다.
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 버전 이후 새로운

9.6
