---
permalink: api/reference_element_api_startbulkvolumeread.html 
sidebar: sidebar 
keywords: volume,read,session,start,starting,bulk,startbulkvolumeread 
summary: StartBulkVolumeRead 메서드를 사용하면 지정된 볼륨에서 대량 볼륨 읽기 세션을 시작할 수 있습니다. 
---
= 대량 볼륨 읽기 시작
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `StartBulkVolumeRead` 지정된 볼륨에서 대량 볼륨 읽기 세션을 시작하는 방법입니다.

볼륨에서 동시에 실행할 수 있는 대량 볼륨 프로세스는 두 개뿐입니다.  세션을 초기화하면 SolidFire 스토리지 볼륨에서 데이터를 읽어 외부 백업 소스에 저장합니다.  외부 데이터는 Element 스토리지 노드에서 실행되는 웹 서버를 통해 액세스됩니다.  외부 데이터 액세스를 위한 서버 상호작용 정보는 스토리지 시스템에서 실행되는 스크립트를 통해 전달됩니다.

대량 볼륨 읽기 작업이 시작되면 볼륨의 스냅샷이 만들어지고 읽기가 완료되면 스냅샷이 삭제됩니다.  스냅샷 ID를 매개변수로 입력하여 볼륨의 스냅샷을 읽을 수도 있습니다.  이전 스냅샷을 읽을 때 시스템은 볼륨의 새 스냅샷을 생성하지 않으며, 읽기가 완료되어도 이전 스냅샷을 삭제하지 않습니다.


NOTE: 기존 스냅샷의 ID가 제공되지 않으면 이 프로세스는 새 스냅샷을 생성합니다.  클러스터 충만도가 2단계 또는 3단계인 경우 스냅샷을 생성할 수 있습니다.  클러스터 충만도가 4단계 또는 5단계일 때는 스냅샷이 생성되지 않습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
체재
 a| 
볼륨 데이터의 형식입니다.  다음 중 하나일 수 있습니다.

* `uncompressed`: 볼륨의 모든 바이트는 압축 없이 반환됩니다.
* `native`: 불투명한 데이터는 더 작고 더 효율적으로 저장되어 후속 대량 볼륨 쓰기에 기록됩니다.

 a| 
끈
 a| 
None
 a| 
예



 a| 
볼륨ID
 a| 
읽을 볼륨의 ID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
스냅샷ID
 a| 
대량 볼륨 읽기에 사용되는 이전에 생성된 스냅샷의 ID입니다.  ID를 입력하지 않으면 현재 활성 볼륨 이미지의 스냅샷이 생성됩니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
스크립트
 a| 
실행 가능한 스크립트의 이름입니다.  스크립트 이름이 지정되지 않으면 Element 저장 노드에 액세스하려면 키와 URL이 필요합니다.  스크립트는 기본 노드에서 실행되고, 키와 URL은 스크립트로 반환되어 로컬 웹 서버에 접속할 수 있습니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
스크립트 매개 변수
 a| 
스크립트에 전달할 JSON 매개변수입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다. link:reference_element_api_attributes.html["자세히 알아보기"].
 a| 
JSON 객체
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
완료 여부를 확인할 비동기 프로세스의 ID입니다.
 a| 
정수



 a| 
열쇠
 a| 
세션을 고유하게 식별하는 불투명한 키입니다.
 a| 
끈



 a| 
URL
 a| 
노드의 웹 서버에 접근하기 위한 URL입니다.
 a| 
끈

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "StartBulkVolumeRead",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
      "snapshotID" : 2
   },
   "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
      "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== 버전 이후 새로운

9.6
