---
permalink: api/reference_element_api_breaksnapmirrorvolume.html 
sidebar: sidebar 
keywords: SnapMirror,volume,volumes,break,breaking,relationship,ONTAP,source,snapshot 
summary: Element 웹 UI는 BreakSnapMirrorVolume 메서드를 사용하여 ONTAP 소스 컨테이너와 Element 대상 볼륨 간의 SnapMirror 관계를 끊습니다.  Element SnapMirror 볼륨을 중단하는 기능은 Element 볼륨에 데이터를 복제하는 동안 ONTAP 시스템을 사용할 수 없게 되는 경우에 유용합니다.  이 기능을 사용하면 스토리지 관리자가 Element SnapMirror 볼륨을 제어하고 원격 ONTAP 시스템과의 관계를 끊고 볼륨을 이전 스냅샷으로 되돌릴 수 있습니다. 
---
= 브레이크스냅미러볼륨
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element 웹 UI는 다음을 사용합니다. `BreakSnapMirrorVolume` ONTAP 소스 컨테이너와 Element 대상 볼륨 간의 SnapMirror 관계를 끊는 방법입니다.  Element SnapMirror 볼륨을 중단하는 기능은 Element 볼륨에 데이터를 복제하는 동안 ONTAP 시스템을 사용할 수 없게 되는 경우에 유용합니다.  이 기능을 사용하면 스토리지 관리자가 Element SnapMirror 볼륨을 제어하고 원격 ONTAP 시스템과의 관계를 끊고 볼륨을 이전 스냅샷으로 되돌릴 수 있습니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
볼륨ID
 a| 
중단 작업을 수행할 볼륨입니다.  볼륨 액세스 모드는 snapMirrorTarget이어야 합니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
스냅샷ID
 a| 
이 ID로 식별된 스냅샷으로 볼륨을 롤백합니다.  기본 동작은 가장 최근의 스냅샷으로 롤백하는 것입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
보존하다
 a| 
snapshotID로 식별된 스냅샷보다 최신인 모든 스냅샷을 보존합니다. 가능한 값:

* true: snapshotID보다 최신인 스냅샷을 보존합니다.
* false: snapshotID보다 최신인 스냅샷을 보존하지 않습니다.


false인 경우 snapshotID보다 최신인 모든 스냅샷이 삭제됩니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
입장
 a| 
결과 볼륨 액세스 모드. 가능한 값:

* 읽기쓰기
* 읽기 전용
* 잠김

 a| 
끈
 a| 
읽기쓰기
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 버전 이후 새로운

10.0



== 더 많은 정보를 찾아보세요

xref:reference_element_api_breaksnapmirrorrelationship.adoc[BreakSnapMirror관계]
