---
permalink: api/reference_element_api_adddrives.html 
sidebar: sidebar 
keywords: drives,adding,cluster,drive,add,adddrives 
summary: AddDrives 메서드를 사용하면 클러스터에 사용 가능한 드라이브를 하나 이상 추가하여 해당 드라이브가 클러스터의 데이터 일부를 호스팅할 수 있습니다. 
---
= 드라이브 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `AddDrives` 클러스터에 하나 이상의 사용 가능한 드라이브를 추가하여 드라이브가 클러스터의 데이터 일부를 호스팅할 수 있도록 하는 방법입니다.

클러스터에 스토리지 노드를 추가하거나 기존 노드에 새 드라이브를 설치하면 새 드라이브는 사용 가능으로 표시되며, 활용하기 전에 AddDrives를 통해 추가해야 합니다.  사용하다xref:reference_element_api_listdrives.adoc[드라이브 목록] 추가할 수 있는 드라이브를 표시하는 방법입니다.  드라이브를 추가하면 시스템이 자동으로 드라이브 유형을 결정합니다.

이 방법은 비동기적이며 클러스터의 드라이브를 재조정하는 프로세스가 시작되자마자 반환됩니다.  그러나 새로 추가된 드라이브를 사용하여 클러스터의 데이터를 재조정하는 데 더 많은 시간이 걸릴 수 있습니다. AddDrives 메서드 호출이 완료된 후에도 재조정은 계속됩니다.  당신은 사용할 수 있습니다xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기] 메서드의 반환된 asyncHandle을 쿼리하는 메서드입니다.  AddDrives 메서드가 반환된 후에는 다음을 사용할 수 있습니다.xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] 새로운 드라이브로 데이터를 재조정하는 과정의 진행 상황을 확인하는 방법입니다.


NOTE: 여러 드라이브를 추가하는 경우, 각각 하나의 드라이브에 대한 여러 개의 개별 메서드를 호출하는 것보다 단일 AddDrives 메서드 호출로 드라이브를 추가하는 것이 더 효율적입니다.  이렇게 하면 클러스터의 저장 부하를 안정화하기 위해 수행해야 하는 데이터 밸런싱 양이 줄어듭니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
드라이브
 a| 
클러스터에 추가할 각 드라이브에 대한 정보입니다. 가능한 값:

* driveID: 추가할 드라이브의 ID(정수).
* 유형: 추가할 드라이브의 유형(문자열).  유효한 값은 "슬라이스", "블록" 또는 "볼륨"입니다.  생략하면 시스템이 올바른 유형을 할당합니다.

 a| 
JSON 객체 배열
 a| 
None
 a| 
예 (유형은 선택 사항입니다)

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
비동기 핸들
 a| 
작업 결과를 얻는 데 사용되는 핸들 값입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "id": 1,
  "method": "AddDrives",
  "params": {
    "drives": [
      {
        "driveID": 1,
        "type": "slice"
      },
      {
        "driveID": 2,
        "type": "block"
      },
      {
        "driveID": 3,
        "type": "block"
      }
    ]
  }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result" : {
    "asyncHandle": 1
  }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getasyncresult.adoc[비동기 결과 가져오기]
* xref:reference_element_api_listdrives.adoc[드라이브 목록]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]

