---
permalink: api/reference_element_api_ldapconfiguration.html 
sidebar: sidebar 
keywords: object,objects,ldapConfiguration 
summary: ldapConfiguration 개체에는 스토리지 시스템의 LDAP 구성에 대한 정보가 포함되어 있습니다.  GetLdapConfiguration API 메서드를 사용하여 LDAP 정보를 검색할 수 있습니다. 
---
= LDAP 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ldapConfiguration 개체에는 스토리지 시스템의 LDAP 구성에 대한 정보가 포함되어 있습니다.  LDAP 정보는 다음을 사용하여 검색할 수 있습니다. `GetLdapConfiguration` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
인증 유형
 a| 
사용할 사용자 인증 방법을 식별합니다. 가능한 값:

* 다이렉트바인드
* 검색 및 바인딩

 a| 
끈



 a| 
활성화됨
 a| 
시스템이 LDAP에 대해 구성되었는지 여부를 식별합니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
그룹검색기반DN
 a| 
그룹 검색을 시작할 트리의 기본 DN입니다(시스템은 여기에서 하위 트리 검색을 수행합니다).
 a| 
끈



 a| 
그룹검색커스텀필터
 a| 
사용자 정의 검색 필터가 사용되었습니다.
 a| 
끈



 a| 
그룹검색유형
 a| 
사용되는 기본 그룹 검색 필터를 제어합니다. 가능한 값:

* NoGroups: 그룹 지원이 없습니다.
* ActiveDirectory: 사용자의 모든 AD 그룹에 대한 중첩된 멤버십입니다.
* MemberDN: MemberDN 스타일 그룹(단일 레벨).

 a| 
끈



 a| 
검색BindDN
 a| 
사용자에 대한 LDAP 검색을 수행하기 위해 로그인하는 데 필요한 완전한 DN입니다(LDAP 디렉토리에 대한 읽기 액세스 권한이 필요함).
 a| 
끈



 a| 
서버 URI
 a| 
LDAP 서버 URI의 쉼표로 구분된 목록(예: `ldap://1.2.3.4` 그리고 `ldaps://1.2.3.4:123` .)
 a| 
끈



 a| 
사용자 DNTemplate
 a| 
완전히 적격한 사용자 DN을 형성하는 데 사용되는 문자열입니다.
 a| 
끈



 a| 
사용자 검색 기반 DN
 a| 
검색을 시작하는 데 사용되는 트리의 기본 DN입니다(여기서 하위 트리 검색을 수행합니다).
 a| 
끈



 a| 
사용자 검색 필터
 a| 
사용된 LDAP 필터입니다.
 a| 
끈

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_getldapconfiguration.adoc[GetLdapConfiguration]
