---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: DeleteAuthSessionsByUsername 메서드를 사용하면 지정된 사용자에 대한 모든 인증 세션을 삭제할 수 있습니다.  AccessGroup ClusterAdmins/Administrator에 속하지 않은 호출자는 자신의 세션만 삭제할 수 있습니다.  ClusterAdmins/Administrator 권한이 있는 호출자는 모든 사용자에게 속한 세션을 삭제할 수 있습니다.  삭제할 수 있는 세션 목록을 보려면 동일한 매개변수와 함께 ListAuthSessionsByUsername을 사용하세요.  삭제 가능한 세션 목록을 보려면 동일한 매개변수와 함께 ListAuthSessionsByUsername 메서드를 사용합니다. 
---
= 사용자 이름으로 인증 세션 삭제
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `DeleteAuthSessionsByUsername` 지정된 사용자에 대한 모든 인증 세션을 삭제하는 방법입니다.  AccessGroup ClusterAdmins/Administrator에 속하지 않은 호출자는 자신의 세션만 삭제할 수 있습니다.  ClusterAdmins/Administrator 권한이 있는 호출자는 모든 사용자에게 속한 세션을 삭제할 수 있습니다.  삭제할 수 있는 세션 목록을 보려면 다음을 사용하세요. `ListAuthSessionsByUsername` 동일한 매개변수를 사용하여.  삭제할 수 있는 세션 목록을 보려면 다음을 사용하세요. `ListAuthSessionsByUsername` 동일한 매개변수를 사용하는 메서드.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
인증 방법
 a| 
삭제할 사용자 세션의 인증 방법입니다.  ClusterAdmins/Administrator AccessGroup의 호출자만 이 매개변수를 제공할 수 있습니다.  가능한 값은 다음과 같습니다.

* *authMethod=Cluster*는 ClusterAdmin 사용자 이름을 지정합니다.
* *authMethod=Ldap*는 사용자의 LDAP DN을 지정합니다.
* *authMethod=Idp*는 사용자의 IdP UUID 또는 NameID를 지정합니다.  IdP가 두 옵션 중 하나를 반환하도록 구성되지 않은 경우 세션이 생성될 때 발급된 임의의 UUID가 지정됩니다.

 a| 
인증 방법
 a| 
None
 a| 
아니요



 a| 
사용자 이름
 a| 
사용자를 위한 고유 식별자입니다.
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
세션
 a| 
삭제된 인증 세션에 대한 세션 정보입니다.
 a| 
link:reference_element_api_authsessioninfo.html["인증 세션 정보"]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 버전 이후 새로운

12.0
