---
permalink: api/reference_element_api_session_iscsi.html 
sidebar: sidebar 
keywords: object,objects,session 
summary: '세션 \(iSCSI\) 개체에는 각 볼륨의 iSCSI 세션에 대한 자세한 정보가 포함되어 있습니다.  ListISCSISessions API 메서드를 사용하여 iSCSI 세션 정보를 검색할 수 있습니다.' 
---
= 세션(iSCSI)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
세션(iSCSI) 개체에는 각 볼륨의 iSCSI 세션에 대한 자세한 정보가 포함되어 있습니다.  iSCSI 세션 정보는 다음을 사용하여 검색할 수 있습니다. `ListISCSISessions` API 방식.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
계정ID
 a| 
CHAP 인증에 사용된 계정의 계정 ID(있는 경우)입니다.
 a| 
정수



 a| 
계정 이름
 a| 
CHAP 인증에 사용된 계정의 이름(있는 경우)입니다.
 a| 
끈



 a| 
입증
 a| 
이 iSCSI 세션에 대한 인증 정보입니다.
 a| 
xref:reference_element_api_iscsiauthentication.adoc[iSCSI 인증]



 a| 
생성시간
 a| 
UTC+0 형식의 iSCSI 세션 생성 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
드라이브ID
 a| 
세션을 호스팅하는 전송 서비스와 연관된 driveID입니다.
 a| 
정수



 a| 
드라이브 ID
 a| 
오류를 보고한 드라이브의 드라이브 ID 목록입니다.  해당 사항이 없으면 빈 목록입니다.
 a| 
정수 배열



 a| 
창시자
 a| 
이 iSCSI 세션의 서버 개시자에 대한 정보입니다.  회원:

* 별칭: 개시자에게 지정된 친근한 이름입니다.
* 속성: 이 개시자의 속성입니다.
* initiatorID: 이 개시자의 ID입니다.
* initiatorName: 이 개시자의 이름입니다.
* volumeAccessGroups: 이 개시자와 연관된 볼륨 액세스 그룹 목록입니다.

 a| 
JSON 객체



 a| 
개시자IP
 a| 
iSCSI 서버 초기자의 IP 주소와 포트 번호입니다.
 a| 
끈



 a| 
개시자 이름
 a| 
iSCSI 서버 이니시에이터의 iSCSI 정규화된 이름(IQN)입니다.
 a| 
끈



 a| 
개시자포트이름
 a| 
initiatorName은 initiatorSessionID와 결합되어 개시자 포트를 식별합니다.
 a| 
끈



 a| 
개시자 세션 ID
 a| 
iSCSI 세션이 해당 개시자에 속한다는 것을 식별하는 개시자가 제공한 48비트 ID입니다.
 a| 
정수



 a| 
msSinceLastIscsiPDU
 a| 
이 세션에서 마지막 iSCSI PDU를 수신한 이후 경과된 시간(밀리초)입니다.
 a| 
정수



 a| 
msSinceLastScsiCommand
 a| 
이 세션에서 마지막 SCSI 명령을 수신한 이후 경과된 시간(밀리초)입니다.
 a| 
정수



 a| 
노드ID
 a| 
세션을 호스팅하는 전송 서비스와 연관된 노드ID입니다.
 a| 
정수



 a| 
서비스ID
 a| 
세션을 호스팅하는 전송 서비스의 서비스 ID입니다.
 a| 
정수



 a| 
세션ID
 a| 
iSCSI 세션 ID입니다.
 a| 
정수



 a| 
대상 IP
 a| 
iSCSI 스토리지 대상의 IP 주소와 포트 번호입니다.
 a| 
끈



 a| 
대상 이름
 a| 
iSCSI 대상의 IQN입니다.
 a| 
끈



 a| 
대상포트이름
 a| 
targetName은 대상 포털 그룹 태그와 결합되어 대상 포트를 식별합니다.
 a| 
끈



 a| 
가상네트워크ID
 a| 
세션과 연결된 가상 네트워크 ID입니다.
 a| 
정수



 a| 
볼륨ID
 a| 
세션과 연관된 볼륨이 있는 경우 해당 볼륨의 볼륨 ID입니다.
 a| 
정수



 a| 
볼륨인스턴스
 a| 
iSCSI 세션과 연관된 볼륨 개체가 있는 경우 해당 개체를 식별합니다.
 a| 
정수

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listiscsisessions.adoc[ListISCSISessions]
