---
permalink: api/reference_element_api_getsnmpinfo.html 
sidebar: sidebar 
keywords: snmp,information,info,get,getting 
summary: 'GetSnmpInfo 메서드를 사용하면 현재의 단순 네트워크 관리 프로토콜(SNMP) 구성 정보를 가져올 수 있습니다.' 
---
= GetSnmpInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `GetSnmpInfo` 현재 단순 네트워크 관리 프로토콜(SNMP) 구성 정보를 가져오는 방법입니다.



== 매개변수


NOTE: GetSnmpInfo는 Element 버전 8.0 이후 버전에서는 더 이상 사용되지 않습니다.  그만큼xref:reference_element_api_getsnmpstate.adoc[GetSnmpState] 그리고xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL] 이 메서드는 GetSnmpInfo 메서드를 대체합니다.

이 방법에는 입력 매개변수가 없습니다.



== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
네트워크
 a| 
SNMP에 활성화된 네트워크 및 액세스 유형 목록입니다.  *참고:* 네트워크는 SNMP v3가 비활성화된 경우에만 표시됩니다.
 a| 
xref:reference_element_api_network_snmp.adoc[회로망]



 a| 
활성화됨
 a| 
클러스터의 노드가 SNMP에 대해 구성되었는지 여부를 나타냅니다. 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
snmpV3Enabled
 a| 
클러스터의 노드가 SNMP v3로 구성된 경우 가능한 값:

* true
* 거짓

 a| 
부울



 a| 
usm사용자
 a| 
SNMP v3가 활성화된 경우 SNMP에 대한 사용자 액세스 매개변수 목록이 클러스터에서 반환됩니다.  이는 네트워크 매개변수 대신 반환됩니다.
 a| 
xref:reference_element_api_usmuser.adoc[usm사용자]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "GetSnmpInfo",
   "params": {},
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
   "result" : {
      "enabled" : true,
      "networks" : [
         {
            "access" : "rosys",
            "cidr" : 0,
            "community" : "public",
            "network" : "localhost"
         }
      ]
   }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

* xref:reference_element_api_getsnmpstate.adoc[GetSnmpState]
* xref:reference_element_api_setsnmpacl.adoc[SetSnmpACL]

