---
permalink: api/reference_element_api_setsnmpacl.html 
sidebar: sidebar 
keywords: setsnmpACL,set,setting,snmp,acl,permissions,access,control,list 
summary: SetSnmpACL 메서드를 사용하여 클러스터 노드에서 SNMP 액세스 권한을 구성할 수 있습니다.  이 인터페이스를 사용하여 설정한 값은 클러스터의 모든 노드에 적용되며, 전달된 값은 SetSnmpACL에 대한 이전 호출에서 설정된 모든 값을 대체합니다.  또한 이 인터페이스로 설정된 값은 SetSnmpInfo로 설정된 모든 네트워크 또는 usmUsers 값을 대체합니다. 
---
= SetSnmpACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `SetSnmpACL` 클러스터 노드에서 SNMP 액세스 권한을 구성하는 방법입니다.  이 인터페이스로 설정한 값은 클러스터의 모든 노드에 적용되며 전달된 값은 이전 호출에서 설정된 모든 값을 대체합니다. `SetSnmpACL` .  또한 이 인터페이스로 설정된 값은 다음으로 설정된 모든 네트워크 또는 usmUsers 값을 대체합니다. `SetSnmpInfo` 방법.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
네트워크
 a| 
클러스터 노드에서 실행되는 SNMP 서버에 대한 네트워크 및 액세스 유형 목록입니다.  가능한 네트워크 값은 SNMP 네트워크 객체를 참조하세요.  SNMP v3가 비활성화된 경우 이 매개변수가 필요합니다.
 a| 
xref:reference_element_api_network_snmp.adoc[회로망]
 a| 
None
 a| 
아니요



 a| 
usm사용자
 a| 
클러스터 노드에서 실행되는 SNMP 서버에 대한 사용자 목록과 해당 사용자의 액세스 유형입니다.  SNMP v3가 활성화된 경우 이 매개변수가 필요합니다.
 a| 
xref:reference_element_api_usmuser.adoc[usm사용자]
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "SetSnmpACL",
  "params": {
    "usmUsers"  : [
      {
         "name": "jdoe",
         "access": "rouser",
         "secLevel": "priv",
         "password": "mypassword",
         "passphrase": "mypassphrase",
      }
    ]
  },
  "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_setsnmpinfo.adoc[SetSnmpInfo]
