---
permalink: api/reference_element_api_createcluster.html 
sidebar: sidebar 
keywords: CreateCluster,cluster,create,creating,initialize,initializing 
summary: 'CreateCluster 메서드를 사용하면 "mvip" 및 "svip" 주소의 소유권이 있는 클러스터의 노드를 초기화할 수 있습니다.  각각의 새로운 클러스터는 클러스터의 첫 번째 노드의 관리 IP(MIP)를 사용하여 초기화됩니다.  이 방법을 사용하면 구성 중인 모든 노드가 클러스터에 자동으로 추가됩니다.  새 클러스터가 초기화될 때마다 이 방법을 한 번만 사용하면 됩니다.' 
---
= 클러스터 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `CreateCluster` "mvip" 및 "svip" 주소의 소유권을 가진 클러스터의 노드를 초기화하는 방법입니다.  각각의 새로운 클러스터는 클러스터의 첫 번째 노드의 관리 IP(MIP)를 사용하여 초기화됩니다.  이 방법을 사용하면 구성 중인 모든 노드가 클러스터에 자동으로 추가됩니다.  새 클러스터가 초기화될 때마다 이 방법을 한 번만 사용하면 됩니다.


NOTE: 클러스터의 마스터 노드에 로그인하고 다음을 실행한 후xref:reference_element_api_getbootstrapconfig.adoc[부트스트랩 구성 가져오기] 클러스터에 포함하려는 나머지 노드의 IP 주소를 가져오는 방법으로는 클러스터의 마스터 노드에 대해 CreateCluster 메서드를 실행할 수 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
EULA 수락
 a| 
이 클러스터를 생성할 때 최종 사용자 라이선스 계약에 동의함을 나타내세요.  EULA를 수락하려면 이 매개변수를 true로 설정하세요.
 a| 
부울
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
휴지상태에서 소프트웨어 암호화 활성화
 a| 
이 매개변수를 활성화하면 소프트웨어 기반 암호화를 사용할 수 있습니다.  모든 클러스터에서 기본값은 false입니다.  휴면 상태의 소프트웨어 암호화가 활성화되면 클러스터에서 비활성화할 수 없습니다.
 a| 
부울
 a| 
true
 a| 
아니요



 a| 
엠비피
 a| 
관리 네트워크의 클러스터에 대한 부동(가상) IP 주소입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
노드
 a| 
클러스터를 구성하는 초기 노드 세트의 CIP/SIP 주소입니다.  이 노드의 IP는 목록에 있어야 합니다.
 a| 
문자열 배열
 a| 
None
 a| 
예



 a| 
주문번호
 a| 
영숫자 판매 주문 번호.  소프트웨어 기반 플랫폼에 필요합니다.
 a| 
끈
 a| 
None
 a| 
아니요(하드웨어 기반 플랫폼)

예(소프트웨어 기반 플랫폼)



 a| 
비밀번호
 a| 
클러스터 관리자 계정의 초기 비밀번호입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
일련번호
 a| 
9자리 영숫자 일련 번호.  소프트웨어 기반 플랫폼에서는 필요할 수 있습니다.
 a| 
끈
 a| 
None
 a| 
아니요(하드웨어 기반 플랫폼)

예(소프트웨어 기반 플랫폼)



 a| 
svip
 a| 
스토리지(iSCSI) 네트워크의 클러스터에 대한 부동(가상) IP 주소입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
사용자 이름
 a| 
클러스터 관리자의 사용자 이름입니다.
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "CreateCluster",
  "params": {
    "acceptEula": true,
    "mvip": "10.0.3.1",
    "svip": "10.0.4.1",
    "username": "Admin1",
    "password": "9R7ka4rEPa2uREtE",
    "attributes": {
      "clusteraccountnumber": "axdf323456"
    },
    "nodes": [
      "10.0.2.1",
      "10.0.2.2",
      "10.0.2.3",
      "10.0.2.4"
    ]
  },
  "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
"id" : 1,
"result" : {}
}
----


== 버전 이후 새로운

9.6

[discrete]
== 더 많은 정보를 찾아보세요

* link:reference_element_api_getbootstrapconfig.html["부트스트랩 구성 가져오기"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

