---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: ListVolumes 메서드를 사용하면 클러스터에 있는 볼륨 목록을 가져올 수 있습니다.  사용 가능한 매개변수를 사용하여 목록에 반환하려는 볼륨을 지정할 수 있습니다. 
---
= 볼륨 목록
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ListVolumes` 클러스터에 있는 볼륨 목록을 가져오는 방법입니다.  사용 가능한 매개변수를 사용하여 목록에 반환하려는 볼륨을 지정할 수 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
계정
 a| 
여기에 지정한 계정이 소유한 볼륨만 반환됩니다.  volumeIDs 매개변수와 상호 배타적입니다.
 a| 
정수 배열
 a| 
None
 a| 
아니요



 a| 
가상 볼륨 포함
 a| 
가상 볼륨은 기본적으로 응답에 포함됩니다.  가상 볼륨을 제외하려면 false로 설정합니다.
 a| 
부울
 a| 
true
 a| 
아니요



 a| 
페어링됨
 a| 
페어링된 볼륨이나 페어링되지 않은 볼륨을 반환합니다. 가능한 값:

* true: 모든 쌍을 반환합니다.
* false: 페어링되지 않은 모든 볼륨을 반환합니다.

 a| 
부울
 a| 
None
 a| 
아니요



 a| 
한계
 a| 
반환되는 볼륨 결과의 최대 수를 설정할 수 있습니다.  volumeIDs 매개변수와 상호 배타적입니다.
 a| 
정수
 a| 
10000
 a| 
아니요



 a| 
시작 볼륨 ID
 a| 
이 값보다 크거나 같은 ID를 가진 볼륨만 반환됩니다.  volumeIDs 매개변수와 상호 배타적입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
볼륨 ID
 a| 
볼륨 ID 목록입니다.  이 매개변수를 지정하면 다른 매개변수는 이 볼륨 세트에서만 작동합니다.  계정, startVolumeID 및 limit 매개변수와 상호 배타적입니다.
 a| 
정수 배열
 a| 
아니요
 a| 
아니요



 a| 
볼륨 이름
 a| 
볼륨 이름과 일치하는 볼륨 개체 정보만 반환됩니다.
 a| 
끈
 a| 
아니요
 a| 
아니요



 a| 
볼륨상태
 a| 
상태 값과 동일한 상태를 가진 볼륨만 반환됩니다. 가능한 값:

* 창조하다
* 스냅샷팅
* 활동적인
* 삭제됨

 a| 
끈
 a| 
아니요
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨
 a| 
권의 목록.
 a| 
xref:reference_element_api_volume.adoc[용량]정렬

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== 버전 이후 새로운

9.6
