---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: ModifyVolumes 방법을 사용하면 한 번에 최대 500개의 기존 볼륨을 구성할 수 있습니다.  변화는 즉시 일어납니다.  ModifyVolumes가 지정된 볼륨을 수정하지 못하면 지정된 볼륨은 변경되지 않습니다. 
---
= 볼륨 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ModifyVolumes` 한 번에 최대 500개의 기존 볼륨을 구성하는 방법입니다.  변화는 즉시 일어납니다.  만약에 `ModifyVolumes` 지정된 볼륨을 수정하지 못하면 지정된 볼륨이 변경되지 않습니다.

볼륨을 수정할 때 QoS 값을 지정하지 않으면 각 볼륨의 QoS 값은 변경되지 않습니다.  새로 생성된 볼륨에 대한 기본 QoS 값을 검색하려면 다음을 실행하세요. `GetDefaultQoS` 방법.

복제되는 볼륨 크기를 늘려야 하는 경우 복제 오류를 방지하기 위해 다음 순서에 따라 늘리세요.

. 복제대상 액세스를 통해 볼륨의 크기를 늘립니다.
. 읽기/쓰기 접근 권한으로 소스 또는 볼륨의 크기를 늘립니다.


대상 볼륨과 소스 볼륨의 크기가 동일한지 확인하세요.


NOTE: 액세스 상태를 잠금 또는 복제 대상으로 변경하면 기존의 모든 iSCSI 연결이 종료됩니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
입장
 a| 
볼륨에 대한 접근이 허용되었습니다. 가능한 값:

* `readOnly`: 읽기 작업만 허용됩니다.
* `readWrite`: 읽기와 쓰기가 허용됩니다.
* `locked`: 읽기나 쓰기가 허용되지 않습니다.  지정하지 않으면 액세스 값은 변경되지 않습니다.
* `replicationTarget`: 볼륨 쌍에 대한 대상 볼륨을 식별합니다.  볼륨이 페어링되지 않으면 액세스 상태가 잠금됩니다.  값이 지정되지 않으면 액세스 값은 변경되지 않습니다.

 a| 
끈
 a| 
None
 a| 
아니요



 a| 
계정ID
 a| 
볼륨이 재할당되는 accountID입니다.  아무것도 지정하지 않으면 이전 계정 이름이 사용됩니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
QoSPolicy와 연관
 a| 
볼륨을 지정된 QoS 정책과 연결합니다. 가능한 값:

* `true`: QoSPolicyID 매개변수에 지정된 QoS 정책과 볼륨을 연결합니다.
* `false`: QoSPolicyID 매개변수에 지정된 QoS 정책과 볼륨을 연관시키지 마세요.  거짓인 경우 QoSPolicy 매개변수에서 QoS 정책을 지정했는지 여부에 관계없이 기존 정책 연결이 모두 제거됩니다.

 a| 
부울
 a| 
None
 a| 
아니요



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
생성시간
 a| 
새로운 볼륨 생성 날짜로 설정할 ISO 8601 날짜 문자열입니다.  setCreateTime이 true로 설정된 경우 필요합니다.
 a| 
ISO 8601 문자열
 a| 
None
 a| 
아니요



 a| 
dontMoveforIopsRebalance
 a| 
실제 IOPS로 부하를 분산할 때 볼륨이 이동하지 않도록 방지합니다.  이 설정은 Element 12.8부터 사용할 수 있으며 다음 경우에만 유효합니다.link:reference_element_api_enablefeature.html["실제 IOPS에 대한 볼륨 로드 밸런스"] 활성화되어 있습니다. 가능한 값:

* `true`: 볼륨은 실제 IOPS를 기준으로 부하를 분산하지 않습니다.
* `false`: 볼륨은 실제 IOPS를 기준으로 부하를 분산합니다.


*참고*: 고가용성(노드 장애)을 위한 밸런싱은 다음보다 우선합니다. `VolumeLoadBalanceOnActualIOPS` 그리고 `dontMoveforIopsRebalance` .
| 부울 | 거짓 | 아니요 


 a| 
enableSnapMirrorReplication
 a| 
SnapMirror 엔드포인트를 사용하여 볼륨을 복제하는 데 사용할 수 있는지 여부를 결정합니다. 가능한 값:

* `true`
* `false`

 a| 
부울
 a| 
거짓
 a| 
아니요



| fifoSize | 볼륨에서 지원하는 FIFO(선입선출) 스냅샷의 최대 수를 지정합니다.  FIFO 및 비 FIFO 스냅샷은 모두 볼륨에서 사용 가능한 스냅샷 슬롯의 동일한 풀을 사용합니다.  이 옵션을 사용하면 사용 가능한 스냅샷 슬롯의 FIFO 스냅샷 소비를 제한할 수 있습니다.  이 값을 현재 FIFO 스냅샷 수보다 작게 수정할 수 없습니다. | 정수 | None | 아니요 


| 최소FifoSize | FIFO(선입선출) 스냅샷에만 예약된 스냅샷 슬롯 수를 지정합니다.  FIFO 및 비 FIFO 스냅샷은 동일한 풀을 공유하므로 minFifoSize 매개변수는 가능한 비 FIFO 스냅샷의 총 수를 같은 양만큼 줄입니다.  현재 비 FIFO 스냅샷 수와 충돌하도록 이 값을 수정할 수 없습니다. | 정수 | None | 아니요 


 a| 
방법
 a| 
볼륨 복제 모드. 가능한 값:

* `asynch`: 타겟에 쓰기 전에 시스템이 소스에 데이터가 저장되었음을 인식할 때까지 기다립니다.
* `sync`: 소스에서 데이터 전송 확인을 기다리지 않고 대상에 데이터 쓰기를 시작합니다.

 a| 
끈
 a| 
None
 a| 
아니요



 a| 
qos
 a| 
볼륨에 대한 새로운 서비스 품질 설정입니다.  지정하지 않으면 QoS 설정은 변경되지 않습니다. 가능한 값:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[서비스 품질]
 a| 
None
 a| 
아니요



 a| 
qos정책ID
 a| 
지정된 볼륨에 QoS 설정을 적용해야 하는 정책의 ID입니다.  이 매개변수는 qos 매개변수와 상호 배타적입니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
생성 시간 설정
 a| 
볼륨 생성의 기록된 날짜를 변경하려면 true로 설정합니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
총 크기
 a| 
볼륨의 새로운 크기(바이트)입니다.  1000000000은 1GB와 같습니다.  크기는 가장 가까운 메가바이트 단위로 반올림됩니다.  이 매개변수는 볼륨의 크기를 늘리는 데만 사용할 수 있습니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
볼륨 ID
 a| 
수정할 볼륨의 볼륨 ID 목록입니다.
 a| 
정수 배열
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===
| 이름 | 설명 | 유형 


 a| 
용량
 a| 
새로 수정된 각 볼륨에 대한 정보를 담고 있는 객체의 배열입니다.
 a| 
xref:reference_element_api_volume.adoc[용량]정렬

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [319,22],
    "access": "readWrite",
    "dontMoveForIopsRebalance": false
  },
  "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "volumes":
      {
        "access":  "readWrite,
        "accountID": 22,
        "attributes": {},
        "blockSize": 4096,
        "createTime": "2024-04-01T19:39:40Z",
        "currentProtectionScheme": "doubleHelix",
        "deleteTime": "",
        "dontMoveForIopsRebalance": false,
        "enable512e": false,
        "enableSnapMirrorReplication": false,
        "fifoSize": 24,
        "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
        "lastAccessTime": "2024-04-02T12:41:34Z",
        "lastAccessTimeIO": "2024-04-01T20:41:19Z",
        "minFifoSize": 0,
        "name": "suite40",
        "previousProtectionScheme": null,
        "purgeTime": "",
        "qos": {
          "burstIOPS": 27000,
          "burstTime": 60,
          "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
          },
          "maxIOPS": 27000,
          "minIOPS": 500
        },
        "qosPolicyID": null,
        "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
        "scsiNAADeviceID": "6f47acc100000000336565750000013f",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000000716800,
        "virtualVolumeID": null,
        "volumeAccessGroups": [
        22
        ],
        "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
        "volumeID": 319,
        "volumePairs": [],
        "
      }
  }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_getdefaultqos.adoc[기본 QoS 가져오기]
