---
permalink: api/reference_element_api_checkpingonvlan.html 
sidebar: sidebar 
keywords: VLAN,pre-deployment,network,validation,validate,validating,check,checking,CheckPingOnVlan 
summary: 배포 전 네트워크 유효성 검사를 수행할 때 CheckPingOnVlan 메서드를 사용하여 임시 VLAN에서 네트워크 연결을 테스트할 수 있습니다.  CheckPingOnVlan은 임시 VLAN 인터페이스를 생성하고, VLAN 인터페이스를 사용하여 스토리지 클러스터의 모든 노드에 ICMP 패킷을 보낸 다음, 인터페이스를 제거합니다. 
---
= CheckPingOnVlan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `CheckPingOnVlan` 배포 전 네트워크 검증을 수행할 때 임시 VLAN에서 네트워크 연결을 테스트하는 방법입니다. `CheckPingOnVlan` 임시 VLAN 인터페이스를 생성하고, VLAN 인터페이스를 사용하여 스토리지 클러스터의 모든 노드에 ICMP 패킷을 보낸 다음, 인터페이스를 제거합니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
시도
 a| 
시스템이 테스트 ping을 반복해야 하는 횟수를 지정합니다.
 a| 
정수
 a| 
5
 a| 
아니요



 a| 
호스트
 a| 
ping을 실행할 장치의 주소 또는 호스트 이름을 쉼표로 구분하여 지정합니다.
 a| 
끈
 a| 
클러스터의 노드
 a| 
아니요



 a| 
인터페이스
 a| 
ping을 보내야 하는 기존(기본) 인터페이스입니다. 가능한 값:

* Bond10G: Bond10G 인터페이스에서 ping을 보냅니다.
* Bond1G: Bond1G 인터페이스에서 ping을 보냅니다.

 a| 
끈
 a| 
None
 a| 
예



 a| 
패킷 크기
 a| 
각 IP로 전송되는 ICMP 패킷에 보낼 바이트 수를 지정합니다.  바이트 수는 네트워크 구성에 지정된 최대 MTU보다 작아야 합니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
pingTimeoutMsec
 a| 
각 개별 ping 응답을 기다리는 시간(밀리초)을 지정합니다.
 a| 
정수
 a| 
500ms
 a| 
아니요



 a| 
조각화 금지
 a| 
ICMP 패킷에 대해 DF(분할 금지) 플래그를 활성화합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
sourceAddressV4
 a| 
ICMP ping 패킷에 사용할 소스 IPv4 주소입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
sourceAddressV6
 a| 
ICMP ping 패킷에 사용할 소스 IPv6 주소입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
총 시간 초과 초
 a| 
다음 ping 시도를 하거나 프로세스를 종료하기 전에 ping이 시스템 응답을 기다려야 하는 시간(초)을 지정합니다.
 a| 
정수
 a| 
5
 a| 
아니요



 a| 
가상네트워크태그
 a| 
ping 패킷을 보낼 때 사용할 VLAN ID입니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
결과
 a| 
노드가 통신할 수 있었던 각 IP 목록과 ping 응답 통계입니다.
 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
    "method": "CheckPingOnVlan",
    "params": {
        "interface": "Bond10G",
        "virtualNetworkTag": 4001,
        "sourceAddressV4": "192.168.41.4",
        "hosts": "192.168.41.2"
},
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "192.168.41.2": {
      "individualResponseCodes": [
        "Success",
        "Success",
        "Success",
        "Success",
        "Success"
      ],
      "individualResponseTimes": [
        "00:00:00.000373",
        "00:00:00.000098",
        "00:00:00.000097",
        "00:00:00.000074",
        "00:00:00.000075"
      ],
      "individualStatus": [
        true,
        true,
        true,
        true,
        true
      ],
      "interface": "Bond10G",
      "responseTime": "00:00:00.000143",
      "sourceAddressV4": "192.168.41.4",
      "successful": true,
      "virtualNetworkTag": 4001
    }
  }
}
----


== 버전 이후 새로운

11.1
