---
permalink: api/reference_element_api_listvirtualvolumes.html 
sidebar: sidebar 
keywords: virtual,volume,volumes,vvol,list,listing,listvirtualvolumes 
summary: ListVirtualVolumes 메서드를 사용하면 현재 시스템에 있는 가상 볼륨을 나열할 수 있습니다.  이 방법을 사용하면 모든 가상 볼륨을 나열하거나 하위 집합만 나열할 수 있습니다. 
---
= 가상 볼륨 나열
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ListVirtualVolumes` 현재 시스템에 있는 가상 볼륨을 나열하는 방법입니다.  이 방법을 사용하면 모든 가상 볼륨을 나열하거나 하위 집합만 나열할 수 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
세부
 a| 
응답의 세부 수준. 가능한 값:

* true: 응답에 각 VVol에 대한 자세한 내용을 포함합니다.
* false: 응답에 각 VVol에 대한 표준 수준의 세부 정보를 포함합니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
한계
 a| 
나열할 가상 볼륨의 최대 개수입니다.
 a| 
정수
 a| 
10000
 a| 
아니요



 a| 
재귀적
 a| 
응답에 각 VVol의 자식에 대한 정보를 포함할지 여부를 지정합니다. 가능한 값:

* true: 응답에 각 VVol의 자식에 대한 정보를 포함합니다.
* false: 응답에 각 VVol의 자식에 대한 정보를 포함하지 않습니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
시작가상볼륨ID
 a| 
응답에서 목록을 시작할 가상 볼륨의 ID입니다.
 a| 
UUID 유형
 a| 
None
 a| 
아니요



 a| 
가상 볼륨 ID
 a| 
정보를 검색할 가상 볼륨 ID 목록입니다.  이 매개변수를 생략하면 해당 메서드는 해당 가상 볼륨에 대한 정보만 반환합니다.
 a| 
virtualVolumeID UUID 배열
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
다음 가상 볼륨 ID
 a| 
목록에 있는 다음 가상 볼륨의 ID입니다.
 a| 
UUID



 a| 
가상 볼륨
 a| 
현재 시스템에 있는 가상 볼륨을 설명하는 개체 목록입니다.
 a| 
xref:reference_element_api_virtualvolume.adoc[가상 볼륨]정렬

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "ListVirtualVolumes",
    "params": {
    },
    "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "nextVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
    "virtualVolumes": [
      {
        "bindings": [
          177
        ],
        "children": [],
        "metadata": {
          "SFProfileId": "f4e5bade-15a2-4805-bf8e-52318c4ce443",
          "SFgenerationId": "0",
          "VMW_ContainerId": "abaab415-bedc-44cd-98b8-f37495884db0",
          "VMW_VVolName": "asdf",
          "VMW_VVolType": "Config",
          "VMW_VmID": "502e0676-e510-ccdd-394c-667f6867fcdf",
          "VMW_VvolProfile": "f4e5bade-15a2-4805-bf8e-52318c4ce443:0"
        },
        "parentVirtualVolumeID": "00000000-0000-0000-0000-000000000000",
        "snapshotID": 0,
        "snapshotInfo": null,
        "status": "done",
        "storageContainer": {
          "accountID": 1,
          "initiatorSecret": "B5)D1y10K)8IDN58",
          "name": "test",
          "protocolEndpointType": "SCSI",
          "status": "active",
          "storageContainerID": "abaab415-bedc-44cd-98b8-f37495884db0",
          "targetSecret": "qgae@{o{~8\"2U)U^"
        },
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeType": "config",
        "volumeID": 166,
        "volumeInfo": null
      }
    ]
  }
}
----


== 버전 이후 새로운

9.6
