---
permalink: api/reference_element_api_testping.html 
sidebar: sidebar 
keywords: ping,test,TestPing 
summary: TestPing 방법을 사용하면 ICMP 패킷을 사용하여 1G 및 10G 인터페이스에서 클러스터의 모든 노드에 대한 네트워크 연결을 테스트할 수 있습니다.  테스트에서는 네트워크 구성의 MTU 설정에 따라 각 패킷에 적절한 MTU 크기를 사용합니다.  TestPing은 임시 VLAN 인터페이스를 생성하지 않습니다. 
---
= 테스트핑
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `TestPing` ICMP 패킷을 사용하여 1G 및 10G 인터페이스 모두에서 클러스터의 모든 노드에 대한 네트워크 연결을 테스트하는 방법입니다.  테스트에서는 네트워크 구성의 MTU 설정에 따라 각 패킷에 적절한 MTU 크기를 사용합니다. `TestPing` 임시 VLAN 인터페이스를 생성하지 않습니다.



== 매개변수

이 메서드에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
시도
 a| 
시스템이 테스트 ping을 반복해야 하는 횟수를 지정합니다.
 a| 
정수
 a| 
5
 a| 
아니요



 a| 
호스트
 a| 
ping을 실행할 장치의 주소 또는 호스트 이름을 쉼표로 구분하여 지정합니다.  호스트가 지정되지 않으면 이 메서드는 스토리지 클러스터의 호스트에 ping을 보냅니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
인터페이스
 a| 
ping을 보내야 하는 기존(기본) 인터페이스입니다. 가능한 값:

* `Bond10G`: Bond10G 인터페이스에서 ping을 보냅니다.
* `Bond1G`: Bond1G 인터페이스에서 ping을 보냅니다.

 a| 
끈
 a| 
None
 a| 
아니요



 a| 
패킷 크기
 a| 
각 IP로 전송되는 ICMP 패킷에 보낼 바이트 수를 지정합니다.  바이트 수는 네트워크 구성에 지정된 최대 MTU보다 작아야 합니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
pingTimeoutMsec
 a| 
각 개별 ping 응답을 기다리는 시간(밀리초)을 지정합니다.
 a| 
정수
 a| 
500밀리초
 a| 
아니요



 a| 
조각화 금지
 a| 
ICMP 패킷에 대해 DF(분할 금지) 플래그를 활성화합니다.
 a| 
부울
 a| 
거짓
 a| 
아니요



 a| 
sourceAddressV4
 a| 
ICMP ping 패킷에 사용할 소스 IPv4 주소입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
sourceAddressV6
 a| 
ICMP ping 패킷에 사용할 소스 IPv6 주소입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
총 시간 초과 초
 a| 
다음 ping 시도를 하거나 프로세스를 종료하기 전에 ping이 시스템 응답을 기다려야 하는 시간(초)을 지정합니다.
 a| 
정수
 a| 
5
 a| 
아니요



 a| 
가상네트워크태그
 a| 
ping 패킷을 보낼 때 사용할 VLAN ID입니다.
 a| 
정수
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
세부
 a| 
노드가 통신할 수 있었던 각 IP 목록과 ping 응답 통계입니다.
 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
    "method": "TestPing",
    "params": {
        "interface": "Bond1G",
        "hosts": "192.168.0.1"
    },
    "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "192.168.0.1": {
        "individualResponseCodes": [
          "Success",
          "Success",
          "Success",
          "Success",
          "Success"
        ],
        "individualResponseTimes": [
          "00:00:00.000304",
          "00:00:00.000123",
          "00:00:00.000116",
          "00:00:00.000113",
          "00:00:00.000111"
        ],
        "individualStatus": [
          true,
          true,
          true,
          true,
          true
        ],
        "interface": "Bond1G",
        "responseTime": "00:00:00.000154",
        "sourceAddressV4": "192.168.0.5",
        "successful": true
      }
    },
    "duration": "00:00:00.001747",
    "result": "Passed"
  }
}
----


== 버전 이후 새로운

5.0
