---
permalink: api/reference_element_api_groupsnapshot.html 
sidebar: sidebar 
keywords: object,objects,groupSnapshot 
summary: groupSnapshot 개체에는 볼륨 그룹의 스냅샷에 대한 정보가 포함되어 있습니다.  ListGroupSnapshots API 메서드를 사용하여 그룹 스냅샷 정보를 검색할 수 있습니다. 
---
= 그룹스냅샷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
groupSnapshot 개체에는 볼륨 그룹의 스냅샷에 대한 정보가 포함되어 있습니다.  당신은 사용할 수 있습니다 `ListGroupSnapshots` 그룹 스냅샷 정보를 검색하는 API 메서드입니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체



 a| 
생성시간
 a| 
그룹 스냅샷이 생성된 UTC+0 형식의 날짜와 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
enableRemoteReplication
 a| 
스냅샷이 원격 복제에 활성화되어 있는지 여부를 식별합니다.
 a| 
부울



 a| 
그룹스냅샷ID
 a| 
그룹 스냅샷의 고유 ID입니다.
 a| 
정수



 a| 
그룹 스냅샷 UUID
 a| 
그룹 스냅샷의 UUID입니다.
 a| 
끈



 a| 
회원들
 a| 
그룹 스냅샷의 각 멤버에 대한 정보를 담고 있는 객체의 배열입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅 사진]정렬



 a| 
이름
 a| 
그룹 스냅샷의 이름이거나, 아무것도 지정되지 않은 경우 스냅샷이 생성된 UTC 형식의 날짜와 시간입니다.
 a| 
문자열 또는 ISO 8601 날짜 문자열



 a| 
원격 상태
 a| 
소스 클러스터에서 볼 때 대상 클러스터의 각 원격 스냅샷의 범용 식별자와 복제 상태를 포함하는 배열입니다.
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[원격 클러스터 스냅샷 상태]정렬



 a| 
상태
 a| 
스냅샷의 현재 상태입니다. 가능한 값:

* 알 수 없음: 스냅샷 상태를 가져오는 중 오류가 발생했습니다.
* 준비 중: 이 스냅샷은 사용을 위해 준비 중이며 아직 쓸 수 없습니다.
* 원격 동기화: 이 스냅샷은 원격 클러스터에서 복제되고 있습니다.
* 완료: 이 스냅샷은 준비 또는 복제가 완료되어 이제 사용할 수 있습니다.
* 활성: 이 스냅샷은 활성 브랜치입니다.
* 복제: 이 스냅샷은 CopyVolume 작업과 관련이 있습니다.

 a| 
끈

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listgroupsnapshots.adoc[ListGroupSnapshots]
