---
permalink: api/reference_element_api_modifyaccount.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,accounts,settings,modifyaccount 
summary: ModifyAccount 메서드를 사용하면 기존 계정을 수정할 수 있습니다. 
---
= 계정 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ModifyAccount` 기존 계정을 수정하는 방법.

계정을 잠그면 해당 계정의 기존 연결이 즉시 종료됩니다.  계정의 CHAP 설정을 변경하면 기존 연결은 활성 상태로 유지되고, 새 CHAP 설정은 후속 연결이나 재연결에 사용됩니다.  계정의 속성을 지우려면 속성 매개변수에 {}를 지정합니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
계정ID
 a| 
수정할 계정의 AccountID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
enableChap
 a| 
CHAP 계정 자격 증명을 초기자가 볼륨에 액세스하는 데 사용할 수 있는지 여부를 지정합니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
개시자 비밀
 a| 
개시자가 사용할 CHAP 비밀번호입니다.  이 비밀번호는 12~16자 길이여야 하며 해독이 불가능해야 합니다.  개시자 CHAP 비밀번호는 고유해야 하며 대상 CHAP 비밀번호와 같을 수 없습니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
상태
 a| 
계정 상태. 가능한 값:

* 활성: 계정이 활성화되어 있으며 연결이 허용됩니다.
* 잠김: 계정이 잠기고 연결이 거부되었습니다.

 a| 
끈
 a| 
None
 a| 
아니요



 a| 
대상 비밀
 a| 
대상에 사용할 CHAP 비밀번호(상호 CHAP 인증).  이 비밀번호는 12~16자 길이여야 하며 해독이 불가능해야 합니다.  대상 CHAP 비밀번호는 고유해야 하며 개시자 CHAP 비밀번호와 같을 수 없습니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
사용자 이름
 a| 
계정과 연결된 사용자 이름을 변경하는 데 사용됩니다.  (길이는 1~64자여야 합니다).
 a| 
끈
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
계정
 a| 
수정된 계정에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_account.adoc[계정]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.  이 예에서 속성은 {}를 지정하여 지워집니다.

[listing]
----
{
   "method": "ModifyAccount",
   "params": {
     "accountID"  : 25,
     "status"   : "locked",
     "attributes" : {}
   },
   "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
    "account": {
        "storageContainerID": "abcdef01-1234-5678-90ab-cdef01234567",
        "username": "user1",
        "accountID": 1,
        "volumes": [
        ],
        "enableChap": true,
        "initiatorSecret": "txz123456q890",
        "attributes": {
        },
        "status": active",
        "targetSecret": "rxe123b567890"
    }
}
----


== 버전 이후 새로운

9.6
