---
permalink: api/reference_element_api_listkeyserverskmip.html 
sidebar: sidebar 
keywords: KMIP,key server,key,server,listing,list,listkeyserverskmip 
summary: 'ListKeyServersKmip 메서드를 사용하면 생성된 모든 Key Management Interoperability Protocol (KMIP) 키 서버를 나열할 수 있습니다.  추가 매개변수를 지정하여 결과를 필터링할 수 있습니다.' 
---
= ListKeyServersKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ListKeyServersKmip` 생성된 모든 키 관리 상호 운용성 프로토콜(KMIP) 키 서버를 나열하는 방법입니다.  추가 매개변수를 지정하여 결과를 필터링할 수 있습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
키 제공자 ID
 a| 
이 옵션을 지정하면 해당 메서드는 지정된 KMIP 키 공급자에 할당된 KMIP 키 서버만 반환합니다.  생략하면 반환된 KMIP 키 서버는 지정된 KMIP 키 공급자에 할당되었는지 여부에 따라 필터링되지 않습니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
kmipAssignedProviderIsActive
 a| 
필터는 활성화 여부에 따라 KMIP 키 서버 객체를 반환했습니다. 가능한 값:

* true: 활성화된 KMIP 키 서버만 반환합니다(현재 사용 중인 키 제공).
* false: 비활성 상태(키를 제공하지 않고 삭제 가능)인 KMIP 키 서버만 반환합니다.


생략하면 반환된 KMIP 키 서버는 활성화 여부에 따라 필터링되지 않습니다.
 a| 
부울
 a| 
None
 a| 
아니요



 a| 
kmipHasProviderAssigned
 a| 
필터는 KMIP 키 공급자가 할당되었는지 여부에 따라 KMIP 키 서버를 반환했습니다. 가능한 값:

* true: KMIP 키 공급자가 할당된 KMIP 키 서버만 반환합니다.
* false: KMIP 키 공급자가 할당되지 않은 KMIP 키 서버만 반환합니다.


생략하면 반환된 KMIP 키 서버는 KMIP 키 공급자가 할당되었는지 여부에 따라 필터링되지 않습니다.
 a| 
부울
 a| 
None
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
kmipKeyServers
 a| 
생성된 KMIP 키 서버의 전체 목록입니다.
 a| 
link:reference_element_api_keyserverkmip.html["키서버Kmip"]정렬

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "ListKeyServersKmip",
  "params": {},
"id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
    "kmipKeyServers": [
        {
            "kmipKeyServerName": "keyserverName",
            "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "keyServerID": 15,
            "kmipAssignedProviderIsActive": true,
            "kmipKeyServerPort": 5696,
            "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames": [
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID": 1
        }
    ]
}
----


== 버전 이후 새로운

11.7
