---
permalink: api/reference_element_api_rollbacktosnapshot.html 
sidebar: sidebar 
keywords: rollbacktosnapshot,snapshot,creating,create,roll,back,rollback,roll back,existing 
summary: RollbackToSnapshot 메서드를 사용하면 활성 볼륨 이미지의 기존 스냅샷을 만들 수 있습니다.  이 방법은 기존 스냅샷에서 새로운 스냅샷을 만듭니다. 
---
= 스냅샷으로 롤백
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `RollbackToSnapshot` 활성 볼륨 이미지의 기존 스냅샷을 만드는 방법입니다.  이 방법은 기존 스냅샷에서 새로운 스냅샷을 만듭니다.

새로운 스냅샷이 활성화되고 기존 스냅샷은 수동으로 삭제할 때까지 보존됩니다.  saveCurrentState 매개변수를 true로 설정하지 않으면 이전에 활성화된 스냅샷이 삭제됩니다.

*클러스터 충만도*

[NOTE]
====
* 클러스터 충만도가 1, 2 또는 3단계에 있는 경우 스냅샷을 만들 수 있습니다.  클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.
* 슬라이스 동기화가 진행 중일 때는 볼륨을 스냅샷으로 롤백하는 작업이 실패할 수 있습니다.  다시 해 보다 `RollbackToSnapshot` 동기화가 완료된 후.


====


== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
볼륨ID
 a| 
볼륨의 VolumeID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 속성
 a| 
None
 a| 
아니요



 a| 
이름
 a| 
스냅샷의 이름입니다.  이름이 지정되지 않으면 롤백되는 스냅샷의 이름이 사용되며, 이름 끝에 "- copy"가 추가됩니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
스냅샷ID
 a| 
주어진 볼륨에서 이전에 생성된 스냅샷의 ID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
현재 상태 저장
 a| 
이전 활성 볼륨 이미지를 저장할지 여부를 지정합니다.  유효한 값:

* true: 이전 활성 볼륨 이미지가 유지됩니다.
* false: 이전 활성 볼륨 이미지가 삭제됩니다.

 a| 
부울
 a| 
거짓
 a| 
아니요

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
체크섬
 a| 
저장된 스냅샷의 데이터를 나타내는 작은 문자열입니다.
 a| 
끈



 a| 
스냅샷ID
 a| 
saveCurrentState가 false로 설정된 경우 이 값은 null입니다.

saveCurrentState가 true로 설정된 경우 새로 생성된 스냅샷의 고유 ID입니다.
 a| 
정수



 a| 
스냅 사진
 a| 
saveCurrentState가 false로 설정된 경우 이 값은 null입니다.

saveCurrentState가 true로 설정된 경우 새로 생성된 스냅샷에 대한 정보가 포함된 객체입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅 사진]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
 "method": "RollbackToSnapshot",
 "params": {
    "volumeID": 1,
    "snapshotID": 3114,
    "saveCurrentState": true
  },
  "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
    "snapshot": {
      "attributes": {},
      "checksum": "0x0",
      "createTime": "2016-04-04T17:27:32Z",
      "enableRemoteReplication": false,
      "expirationReason": "None",
      "expirationTime": null,
      "groupID": 0,
      "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
      "name": "test1-copy",
      "snapshotID": 1,
      "snapshotUUID": "30d7e3fe-0570-4d94-a8d5-3cc8097a6bfb",
      "status": "done",
      "totalSize": 5000658944,
      "virtualVolumeID": null,
      "volumeID": 1
    },
    "snapshotID": 1
  }
}
----


== 버전 이후 새로운

9.6
