---
permalink: api/reference_element_api_modifyvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volumes,volume,defining,define,modify,modifying,edit,editing,change,changing,modifyvolumeaccessgrouplunassignments,access,group,lun,assignment 
summary: ModifyVolumeAccessGroupLunAssignments 메서드를 사용하면 특정 볼륨에 대한 사용자 정의 LUN 할당을 정의할 수 있습니다. 
---
= 볼륨 액세스 그룹 LUN 할당 수정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `ModifyVolumeAccessGroupLunAssignments` 특정 볼륨에 대한 사용자 정의 LUN 할당을 정의하는 방법입니다.

이 방법은 볼륨 액세스 그룹의 lunAssignments 매개변수에 설정된 LUN 값만 변경합니다.  다른 모든 LUN 할당은 변경되지 않습니다.

LUN 할당 값은 볼륨 액세스 그룹의 볼륨에 대해 고유해야 합니다.  볼륨 액세스 그룹 내에서 중복된 LUN 값을 정의할 수 없습니다.  하지만 다른 볼륨 액세스 그룹에서도 동일한 LUN 값을 다시 사용할 수 있습니다.


NOTE: 유효한 LUN 값은 0~16383입니다.  이 범위를 벗어나는 LUN 값을 전달하면 시스템에서 예외가 발생합니다.  예외가 발생하면 지정된 LUN 할당은 수정되지 않습니다.

주의:

활성 I/O가 있는 볼륨의 LUN 할당을 변경하면 I/O가 중단될 수 있습니다.  볼륨 LUN 할당을 변경하기 전에 서버 구성을 변경해야 합니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===


| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
볼륨액세스그룹ID
 a| 
LUN 할당이 수정될 고유한 볼륨 액세스 그룹 ID입니다.
 a| 
정수
 a| 
None
 a| 
예



 a| 
lunAssignments
 a| 
새로 할당된 LUN 값이 있는 볼륨 ID입니다.
 a| 
정수 배열
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
볼륨 액세스 그룹 LUN 할당
 a| 
수정된 볼륨 액세스 그룹 LUN 할당에 대한 세부 정보가 포함된 개체입니다.
 a| 
JSON 객체

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "ModifyVolumeAccessGroupLunAssignments",
   "params": {
       "volumeAccessGroupID" : 218,
       "lunAssignments" : [
           {"volumeID" : 832, "lun" : 0},
           {"volumeID" : 834, "lun" : 1}
        ]
    },
    "id" : 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroupLunAssignments": {
      "deletedLunAssignments": [],
      "lunAssignments": [
        {
          "lun": 0,
          "volumeID": 832
        },
        {
          "lun": 1,
          "volumeID": 834
        }
      ],
      "volumeAccessGroupID": 218
    }
  }
}
----


== 버전 이후 새로운

9.6
