---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: DisableEncryptionAtRest 메서드를 사용하면 EnableEncryptionAtRest 메서드를 사용하여 이전에 클러스터에 적용된 암호화를 제거할 수 있습니다.  이 비활성화 방법은 비동기적이며 암호화가 비활성화되기 전에 응답을 반환합니다.  GetClusterInfo 메서드를 사용하면 시스템을 폴링하여 프로세스가 완료되었는지 확인할 수 있습니다. 
---
= 휴지상태에서 암호화 비활성화
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `DisableEncryptionAtRest` 클러스터에 이전에 적용된 암호화를 제거하는 방법 `EnableEncryptionAtRest` 방법.  이 비활성화 방법은 비동기적이며 암호화가 비활성화되기 전에 응답을 반환합니다.  당신은 사용할 수 있습니다 `GetClusterInfo` 프로세스가 완료되었는지 확인하기 위해 시스템을 폴링하는 방법입니다.


TIP: 클러스터에서 암호화의 현재 상태 및/또는 소프트웨어 암호화의 현재 상태를 보려면 다음을 사용하십시오.link:api/reference_element_api_getclusterinfo.html["클러스터 정보 가져오기 방법"] . 당신은 사용할 수 있습니다 `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["클러스터가 저장 중인 데이터를 암호화하는 데 사용하는 정보를 얻는 방법"].


NOTE: 이 방법을 사용하면 휴면 상태의 소프트웨어 암호화를 비활성화할 수 없습니다.  휴면 상태에서 소프트웨어 암호화를 비활성화하려면 다음이 필요합니다.link:reference_element_api_createcluster.html["새로운 클러스터를 생성하다"] 휴면 상태에서 소프트웨어 암호화가 비활성화된 상태입니다.



== 매개변수

이 방법에는 입력 매개변수가 없습니다.



== 반환 값

이 메서드에는 반환 값이 없습니다.



== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== 버전 이후 새로운

9.6

[discrete]
== 더 많은 정보를 찾아보세요

* link:api/reference_element_api_getclusterinfo.html["클러스터 정보 가져오기"]
* https://docs.netapp.com/us-en/element-software/index.html["SolidFire 및 Element 소프트웨어 문서"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["NetApp SolidFire 및 Element 제품의 이전 버전에 대한 설명서"^]

