---
permalink: api/reference_element_api_createsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,create,creating,snapshot,snapshots,CreateSnapshot 
summary: CreateSnapshot을 사용하면 볼륨의 특정 시점 복사본을 만들 수 있습니다.  모든 볼륨이나 기존 스냅샷에서 스냅샷을 만들 수 있습니다. 
---
= 스냅샷 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용할 수 있습니다 `CreateSnapshot` 볼륨의 특정 시점 복사본을 생성합니다.  모든 볼륨이나 기존 스냅샷에서 스냅샷을 만들 수 있습니다.

이 API 메서드로 SnapshotID를 제공하지 않으면 볼륨의 활성 분기에서 스냅샷이 생성됩니다.  스냅샷이 생성된 볼륨이 원격 클러스터로 복제되는 경우, 스냅샷도 동일한 대상으로 복제될 수 있습니다.  enableRemoteReplication 매개변수를 사용하여 스냅샷 복제를 활성화합니다.


NOTE: 클러스터 충만도가 1, 2 또는 3단계에 있는 경우 스냅샷을 만들 수 있습니다.  클러스터 충만도가 4단계 또는 5단계에 도달하면 스냅샷을 생성할 수 없습니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
`attributes`
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
`enableRemoteReplication`
 a| 
스냅샷을 원격 저장소에 복제할지 여부를 지정합니다. 가능한 값:

* `true`: 스냅샷은 원격 저장소에 복제됩니다.
* `false`: 스냅샷은 원격 저장소에 복제되지 않습니다.

 a| 
부울
 a| 
거짓
 a| 
아니요



| `ensureSerialCreation`  a| 
이전 스냅샷 복제가 진행 중인 경우 스냅샷을 생성하지 않도록 지정합니다.  가능한 값은 다음과 같습니다.

* `true`: 이렇게 하면 한 번에 하나의 스냅샷만 복제됩니다.  이전 스냅샷 복제가 진행 중이면 새 스냅샷을 만드는 데 실패합니다.
* `false`: 기본.  다른 스냅샷 복제가 진행 중인 경우에도 이 스냅샷 생성이 허용됩니다.

| 부울 | `false` | 아니요 


| 만료 시간  a| 
스냅샷을 제거할 수 있는 시간을 지정합니다.  와 함께 사용할 수 없습니다 `retention` .  expirationTime이나 retention이 지정되지 않으면 스냅샷은 만료되지 않습니다.  시간 형식은 시간 기반 만료를 위한 ISO 8601 날짜 문자열입니다. 그렇지 않으면 만료되지 않습니다.  의 값 `null` 스냅샷이 영구적으로 보관됩니다.  의 값 `fifo` 볼륨의 다른 FIFO 스냅샷과 관련하여 스냅샷이 선입선출 방식으로 보존됩니다.  FIFO 공간을 사용할 수 없으면 API가 실패합니다.
| 끈 | None | 아니요 


 a| 
`name`
 a| 
스냅샷의 이름입니다.  이름을 입력하지 않으면 스냅샷이 촬영된 날짜와 시간이 사용됩니다.  허용되는 최대 이름 길이는 255자입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`retention`
 a| 
이 매개변수는 다음과 같습니다. `expirationTime` 매개변수는 시간 형식이 HH:mm:ss인 것을 제외합니다.  둘 다 아닌 경우 `expirationTime` ...도 아니다 `retention` 지정된 경우 스냅샷은 만료되지 않습니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`snapMirrorLabel`
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트의 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.
 a| 
끈
 a| 
None
 a| 
아니요



 a| 
`snapshotID`
 a| 
새 스냅샷이 만들어진 스냅샷의 고유 ID입니다.  전달된 snapshotID는 해당 볼륨의 스냅샷이어야 합니다.
 a| 
정수
 a| 
None
 a| 
아니요



 a| 
`volumeID`
 a| 
복사할 볼륨 이미지의 고유 ID입니다.
 a| 
정수
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
체크섬
 a| 
저장된 스냅샷에서 올바른 숫자를 나타내는 문자열입니다.  이 체크섬은 나중에 다른 스냅샷을 비교하여 데이터의 오류를 감지하는 데 사용할 수 있습니다.
 a| 
끈



 a| 
스냅샷ID
 a| 
새로운 스냅샷의 고유 ID입니다.
 a| 
스냅샷 ID



 a| 
스냅 사진
 a| 
새로 생성된 스냅샷에 대한 정보를 담고 있는 객체입니다.
 a| 
xref:reference_element_api_snapshot.adoc[스냅 사진]

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
   "method": "CreateSnapshot",
   "params": {
      "volumeID": 1
   },
   "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
  "id": 1,
  "result": {
    "checksum": "0x0",
      "snapshot": {
        "attributes": {},
        "checksum": "0x0",
        "createTime": "2016-04-04T17:14:03Z",
        "enableRemoteReplication": false,
        "expirationReason": "None",
        "expirationTime": null,
        "groupID": 0,
        "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
        "name": "2016-04-04T17:14:03Z",
        "snapshotID": 3110,
        "snapshotUUID": "6f773939-c239-44ca-9415-1567eae79646",
        "status": "done",
        "totalSize": 5000658944,
        "virtualVolumeID": null,
        "volumeID": 1
      },
        "snapshotID": 3110
  }
}
----


== 예외

xNotPrimary 예외는 다음과 같은 경우 표시됩니다. `CreateSnapshot` API가 호출되었지만 스냅샷을 생성하는 데 실패했습니다. 이는 예상되는 동작입니다.  다시 시도하세요 `CreateSnapshot` API 호출.



== 버전 이후 새로운

9.6
