---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: AddClusterAdmin 메서드를 사용하여 새로운 클러스터 관리자 계정을 추가할 수 있습니다.  클러스터 관리자는 API와 관리 도구를 통해 클러스터를 관리할 수 있습니다.  클러스터 관리자는 표준 테넌트 계정과 완전히 별개이며 관련이 없습니다. 
---
= 클러스터 관리자 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
당신은 사용할 수 있습니다 `AddClusterAdmin` 새로운 클러스터 관리자 계정을 추가하는 방법입니다.  클러스터 관리자는 API와 관리 도구를 통해 클러스터를 관리할 수 있습니다.  클러스터 관리자는 표준 테넌트 계정과 완전히 별개이며 관련이 없습니다.

각 클러스터 관리자는 API 하위 집합으로 제한될 수 있습니다.  다양한 사용자와 애플리케이션에 대해 여러 개의 클러스터 관리자 계정을 사용해야 합니다.  모범 사례로, 각 클러스터 관리자에게 필요한 최소한의 권한을 부여하세요. 이렇게 하면 자격 증명이 손상될 경우 잠재적인 영향이 줄어듭니다.



== 매개변수

이 방법에는 다음과 같은 입력 매개변수가 있습니다.

|===
| 이름 | 설명 | 유형 | 기본값 | 필수의 


 a| 
입장
 a| 
클러스터 관리자가 사용할 수 있는 방법을 제어합니다.
 a| 
문자열 배열
 a| 
None
 a| 
예



 a| 
EULA 수락
 a| 
최종 사용자 라이선스 계약에 동의하세요.  시스템에 클러스터 관리자 계정을 추가하려면 true로 설정합니다.  생략하거나 false로 설정하면 메서드 호출이 실패합니다.
 a| 
부울
 a| 
None
 a| 
예



 a| 
속성
 a| 
JSON 객체 형식의 이름/값 쌍 목록입니다.
 a| 
JSON 객체
 a| 
None
 a| 
아니요



 a| 
비밀번호
 a| 
이 클러스터 관리자를 인증하는 데 사용되는 비밀번호입니다.
 a| 
끈
 a| 
None
 a| 
예



 a| 
사용자 이름
 a| 
이 클러스터 관리자의 고유한 사용자 이름입니다.  길이는 1~1024자여야 합니다.
 a| 
끈
 a| 
None
 a| 
예

|===


== 반환 값

이 메서드는 다음과 같은 반환 값을 갖습니다.

|===


| 이름 | 설명 | 유형 


 a| 
클러스터 관리자 ID
 a| 
새로 생성된 클러스터 관리자의 ClusterAdminID입니다.
 a| 
정수

|===


== 요청 예시

이 방법에 대한 요청은 다음 예와 유사합니다.

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== 응답 예시

이 메서드는 다음 예와 유사한 응답을 반환합니다.

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== 버전 이후 새로운

9.6



== 더 많은 정보를 찾아보세요

xref:reference_element_api_app_b_access_control.adoc[접근 제어]
