---
permalink: api/reference_element_api_snapshot.html 
sidebar: sidebar 
keywords: object,objects,snapshot 
summary: 스냅샷 개체에는 볼륨에 대해 만들어진 스냅샷에 대한 정보가 포함되어 있습니다.  ListSnapshots API 메서드를 사용하면 볼륨 또는 모든 볼륨에 대한 스냅샷 정보 목록을 검색할 수 있습니다.  해당 개체에는 활성 스냅샷에 대한 정보와 볼륨에 대해 생성된 각 스냅샷에 대한 정보가 포함됩니다. 
---
= 스냅 사진
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스냅샷 개체에는 볼륨에 대해 만들어진 스냅샷에 대한 정보가 포함되어 있습니다.  당신은 사용할 수 있습니다 `ListSnapshots` 볼륨 또는 모든 볼륨에 대한 스냅샷 정보 목록을 검색하는 API 메서드입니다.  해당 개체에는 활성 스냅샷에 대한 정보와 볼륨에 대해 생성된 각 스냅샷에 대한 정보가 포함됩니다.



== 객체 멤버

이 개체에는 다음과 같은 멤버가 포함되어 있습니다.

|===
| 이름 | 설명 | 유형 


 a| 
속성
 a| 
JSON 객체 형식의 이름-값 쌍 목록입니다.
 a| 
JSON 객체



 a| 
체크섬
 a| 
저장된 스냅샷의 데이터에 대한 작은 문자열 표현입니다.  이 체크섬은 나중에 다른 스냅샷을 비교하여 데이터의 오류를 감지하는 데 사용할 수 있습니다.
 a| 
끈



 a| 
생성시간
 a| 
스냅샷이 생성된 UTC+0 형식 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
enableRemoteReplication
 a| 
원격 복제에 대해 스냅샷이 활성화되어 있는지 식별합니다.
 a| 
부울



 a| 
만료 사유
 a| 
스냅샷 만료일이 어떻게 설정되는지 나타냅니다. 가능한 값:

* Api: 만료 시간은 API를 사용하여 설정됩니다.
* 없음: 만료 시간이 설정되지 않았습니다.
* 테스트: 테스트를 위해 만료 시간을 설정합니다.
* fifo: 만료는 선입선출 방식으로 발생합니다.

 a| 
끈



 a| 
만료 시간
 a| 
이 스냅샷이 만료되어 클러스터에서 삭제되는 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
그룹ID
 a| 
스냅샷이 그룹 스냅샷의 멤버인 경우 그룹 ID입니다.
 a| 
정수



 a| 
그룹 스냅샷 UUID
 a| 
그룹의 각 스냅샷에 대한 정보를 포함합니다.  각 멤버는 스냅샷의 UUID에 대한 UUID 매개변수를 갖습니다.
 a| 
끈



 a| 
인스턴스 생성 시간
 a| 
로컬 클러스터에서 스냅샷이 생성된 시간입니다.
 a| 
ISO 8601 날짜 문자열



 a| 
인스턴스 스냅샷 UUID
 a| 
로컬 클러스터의 스냅샷에 대한 범용적으로 고유한 ID입니다.  이 ID는 다른 클러스터에 복제되지 않습니다.
 a| 
끈



 a| 
이름
 a| 
스냅샷에 할당된 고유한 이름입니다.  이름이 지정되지 않으면 이름은 스냅샷이 생성된 시점의 UTC+0 형식 타임스탬프가 됩니다.
 a| 
끈



 a| 
원격 상태
 a| 
소스 클러스터에서 볼 때 대상 클러스터의 각 원격 스냅샷의 범용 식별자와 복제 상태를 포함하는 배열입니다.
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[원격 클러스터 스냅샷 상태]정렬



 a| 
스냅미러라벨
 a| 
SnapMirror 소프트웨어에서 SnapMirror 엔드포인트의 스냅샷 보존 정책을 지정하는 데 사용되는 레이블입니다.  설정하지 않으면 이 값은 null입니다.
 a| 
끈



 a| 
스냅샷ID
 a| 
기존 스냅샷의 고유 ID입니다.
 a| 
끈



 a| 
스냅샷UUID
 a| 
기존 스냅샷의 범용 고유 ID입니다.  스냅샷이 여러 클러스터에 복제되면 이 ID도 함께 복제되고 클러스터 전체에서 스냅샷을 식별하는 데 사용됩니다.
 a| 
끈



 a| 
상태
 a| 
스냅샷의 현재 상태입니다. 가능한 값:

* 알 수 없음: 스냅샷 상태를 가져오는 중 오류가 발생했습니다.
* 준비 중: 이 스냅샷은 사용을 위해 준비 중이며 아직 쓸 수 없습니다.
* 원격 동기화: 이 스냅샷은 원격 클러스터에서 복제되고 있습니다.
* 완료: 이 스냅샷은 준비 또는 복제가 완료되어 이제 사용할 수 있습니다.
* 활성: 이 스냅샷은 활성 브랜치입니다.
* 복제: 이 스냅샷은 CopyVolume 작업과 관련이 있습니다.

 a| 
끈



 a| 
총 크기
 a| 
스냅샷의 총 크기(바이트)입니다.
 a| 
정수



 a| 
가상볼륨ID
 a| 
이 스냅샷과 연결된 가상 볼륨의 ID입니다.
 a| 
UUID



 a| 
볼륨ID
 a| 
스냅샷이 생성된 볼륨의 ID입니다.
 a| 
정수



 a| 
볼륨 이름
 a| 
스냅샷이 생성될 당시의 볼륨 이름입니다.
 a| 
끈

|===


== 더 많은 정보를 찾아보세요

xref:reference_element_api_listsnapshots.adoc[리스트스냅샷]
